### ISSUE TITLE
Unable to compile contracts in firefox.

### ISSUE THREAD

**Issue by pranavburnwal** [ethereum/remix-project#102]
Hi,

I have the same problem as 
https://github.com/ethereum/remix-ide/issues/1644

<img width="1440" alt="image" src="https://user-images.githubusercontent.com/15976005/71730815-26353680-2e7e-11ea-9558-b19ed6c28031.png">

Please help thanks!

**Comment by LianaHus** [comment]
this issue should be fixed by now.  @pranavburnwal  @step21  could you please confirm this?

**Comment by step21** [comment]
I couldn't reproduce it anymore, so it seems like it is fixed.

**Comment by pranavburnwal** [comment]
> 
> 
> this issue should be fixed by now. @pranavburnwal @step21 could you please confirm this?

I will try!

**Comment by pranavburnwal** [comment]
Closing this for now.  Thanks, @step21 @LianaHus 
If it doesn't work will report!
