### ISSUE TITLE
handle error on file/folder creation in internal/external plugins

### ISSUE THREAD

**Issue by LianaHus** [ethereum/remix-project#1028]
Currently, when internal/external plugins are trying to write/read in File Explorer, when no workspace available, the FileManager is not creating the file/folder but throwing an error.
Our plugins are not handling this error but either doing nothing or printing an error in the console. No feedback to the user.
I see 3 options:

1. handle that it FileManager - simply create a workspace on demand
2. handle that it FileManager - FilManager is auto-creating a new workspace when the last one is deleted
3. update all internal/external plugins that writing a file/folder in File Manager and handle the error case by case

**Comment by Aniket-Engg** [comment]
Handle it in File Manager

**Comment by yann300** [comment]
4 - handle that it FileManager - throw an exception to the plugin and display a toaster from remix UIR
