### ISSUE TITLE
regarding to installation

### ISSUE THREAD

**Issue by saifullah27** [ethereum/remix-project#103]
hi i m trying to install remix-ide in windows10 with nodev10.16.0 and npmv4.6 but its throwing me error
![remix error](https://user-images.githubusercontent.com/6271581/71645103-c7908100-2cf4-11ea-9bc1-605c1830095d.png)
can u please help me? i m stuck. spend whole day but no success... :(

**Comment by Aniket-Engg** [comment]
This should have been fixed. Feel free to reopen incase issue persists.
