### ISSUE TITLE
add address button is not clickable

### ISSUE THREAD

**Issue by huahuayu** [ethereum/remix-project#1076]
hi, the add address button is not clickable (for retrieving the deployed contract). 

I found it last week, and the problem is still there, my colleague also can't click it from his computer.

![image](https://user-images.githubusercontent.com/1725060/113541193-538a0a80-9614-11eb-9a49-8e1e3dc2873e.png)

**Comment by huahuayu** [comment]
@yann300

**Comment by ryestew** [comment]
@huahuayu - Do you have a compiled version of the source code ( with the same compilation settings as the deployed version) as the active tab in the editor?  This is necessary to use **AtAddress**.  

I will be updating the docs to make this more clear. 

Or are you using the ABI?  I do believe there is a problem accessing contracts with the ABI.

**Comment by gperezalba** [comment]
Hi, I was having the same problem and while searching for the solution in the issues found https://github.com/ethereum/remix-project/issues/826. They are checking address checksum and if it's invalid button At Address disables. So I you use https://ethsum.netlify.app/ for example you can get the address with the correct checksum (notice the capital letters in the new address) the button works. 

I think the pop-up in the button must reference something related to that or people wont find the solution. Thanks guys
