### ISSUE TITLE
Cannot deploy contract AtAddress button disabled

### ISSUE THREAD

**Issue by VexyCats** [ethereum/remix-project#1099]
Cannot click on the deploy contract At Address button as its disabled. 

I'm using the same code and same compiler from the verified contract on etherscan. I've compiled the code and it works fine to deploy normally on VM but not when connected to mainnet. 

Man, since these latest updates remix has literally become unusable. Can't migrate old files, cannot create workspaces, cannot deploy contracts at the address they are currently deployed at.

**Comment by gperezalba** [comment]
Hi, I was having the same problem and while searching for the solution in the issues found https://github.com/ethereum/remix-project/issues/826. They are checking address checksum and if it's invalid button At Address disables. So I you use https://ethsum.netlify.app/ for example you can get the address with the correct checksum (notice the capital letters in the new address) the button works. 

I think the pop-up in the button must reference something related to that or people wont find the solution. Thanks guys

**Comment by Loque18** [comment]
I'm having the same issue, did you find a solution?

**Comment by sdakansu** [comment]
You should compile the contract before using the "at address" button. A detailed explanation can be found here:

https://ethereum.stackexchange.com/questions/49376/how-to-load-contract-from-address-remix/49377

**Comment by taimoor954** [comment]
Your button might have been disabled due to check sum error. This can cause probably because you include spaces during the copy pasting process. verify your address here _https://ethsum.netlify.app/_ .

**Comment by PalakSDarji** [comment]
> You should compile the contract before using the "at address" button. A detailed explanation can be found here:
> 
> https://ethereum.stackexchange.com/questions/49376/how-to-load-contract-from-address-remix/49377

Worked for me! Thanks @sdakansu

**Comment by sunny-mittal** [comment]
Hope this helps someone though the issue is closed. I deleted the hex prefix (0x) and readded it and it enabled the button. Seemed like something to do with copy/paste caused the misbehavior.
