### ISSUE TITLE
Contract that reverts with Solidity Custom Error fails to deploy to Javascript VM

### ISSUE THREAD

**Issue by dwardu** [ethereum/remix-project#1138]
Using the contract from the [Custom Errors explainer blog post](https://blog.soliditylang.org/2021/04/21/custom-errors/):

```solidity
// SPDX-License-Identifier: GPL-3.0
pragma solidity ^0.8.4;

error Unauthorized();

contract VendingMachine {
    address payable owner = payable(msg.sender);

    function withdraw() public {
        if (msg.sender != owner)
            revert Unauthorized();

        owner.transfer(address(this).balance);
    }
    // ...
}
```

The contract compiles correctly in Remix IDE, and ABI is created correctly:

```json
{
    "inputs": [],
    "name": "Unauthorized",
    "type": "error"
}
```

But deployment _to Javascript VM_ fails with following error:

```
creation of VendingMachine pending...

creation of VendingMachine errored: invalid fragment object (argument="value", value={"inputs":[],"name":"Unauthorized","type":"error"}, code=INVALID_ARGUMENT, version=abi/5.0.7)
```

On the other hand, deployment to Rinkeby succeeds.

**Comment by dwardu** [comment]
I guess this issue will be closed when ethers-io/ethers.js#1498 is closed and merged into this project.

**Comment by LianaHus** [comment]
this should be fixed in remix.ethereum.org in an hour. Alpha is already updated

**Comment by dwardu** [comment]
@LianaHus Cool. Thanks.

TBH I was waiting for ethers-io/ethers.js#1498 fix to be announced, and was intending to create a PR with the dependency upgrade :blush: Was it fixed in a different way?

**Comment by LianaHus** [comment]
ethers.js (5.1.4) was published I think yesterday. thanks anyway :)

**Comment by LianaHus** [comment]
https://github.com/ethers-io/ethers.js/releases/tag/v5.1.4

**Comment by dwardu** [comment]
Ok! Thanks.
