### ISSUE TITLE
Support decoding custom errors

### ISSUE THREAD

**Issue by chriseth** [ethereum/remix-project#1152]
Example contract:
```
// SPDX-License-Identifier: GPL-3.0

pragma solidity ^0.8.4;

error E(uint a);
contract C {
    function f() public pure {
        revert E(2);
    }
    function g() public {
        revert E(2);
    }
}
```

If I compile this contract, deploy it and execute the two functions, the following is displayed in the console:

![image](https://user-images.githubusercontent.com/9073706/116673408-a3ee5100-a9a3-11eb-8041-96dd4ea88ab7.png)

It would be nice to display for both functions that they failed (currently, it is only displayed for the "view" function f).

The next step would be to display the error string in hex.

And finally, remix should try to decode the hex string as follows:
 - iterate through the errors in the ABI json to see if the first four bytes match any of the selectors (computed in the same way as function selectors)
 - ABI-decode the data starting from the fourth byte
 - display it together with the natspec "notice" string corresponding to the error

**Comment by yann300** [comment]
some point still need to be dealt with:
 - [ ] integration with the natspec
 - [ ] display the parameter names
