### ISSUE TITLE
Debugger: Memory display should use teletype font

### ISSUE THREAD

**Issue by chriseth** [ethereum/remix-project#1154]
The memory display in the debugger is hard to read because it uses a font whose characters have a different width:
![image](https://user-images.githubusercontent.com/9073706/116674862-74404880-a9a5-11eb-869b-8c5786e2650d.png)

(the same is true maybe for `calldata`

**Comment by mickys** [comment]
This is an absolute must for anyone doing their own memory management.
Same thing needs to be done to the Stack, call Stack, Call Data
