### ISSUE TITLE
Remix doesn't save my file

### ISSUE THREAD

**Issue by ygboucherk** [ethereum/remix-project#1158]
Hello,

I tried compiling a solidity file, but I got `warning: source file doesn't specify required compiler version`. I tried refreshing the page and got an empty file.
What's going wrong ?

Thanks for any response

**Comment by ygboucherk** [comment]
ah I'm using `chrome 90.0.4430.93`

**Comment by ygboucherk** [comment]
Ah I found it was owed to corrupted cookies (I guess it stores files in cookies)

**Comment by kgh6378** [comment]
me too i always have to delete cookies regularly
