### ISSUE TITLE
Issues in switching to and from localhost workspace

### ISSUE THREAD

**Issue by Aniket-Engg** [ethereum/remix-project#1183]
- [ ] If current workspace is `xyz` and I click on `connect to localhost` then on `cancel` in modal, workspace is automatically switched to `default_workspace`
- [ ] If current workspace is `xyz` and I click on `connect to localhost`, click on `connect` in modal but remixd is not running, workspace is automatically switched to `default_workspace`
- [ ] If current workspace is `localhost` and I switch to workspace `xyz`, workspace is automatically switched to `default_workspace`

I analysed 3rd point locally and I see that even after automatically switching to `default_workspace`, file manager mode is `localhost`

**Comment by Aniket-Engg** [comment]
Reopening it as an old way-around was not satisfactory

**Comment by ryestew** [comment]
link https://github.com/ethereum/remix-project/issues/1377

**Comment by ryestew** [comment]
This should be fixed after issue 1377 is fixed

**Comment by LianaHus** [comment]
@Aniket-Engg  please recheck and close this if it is fixed

**Comment by Aniket-Engg** [comment]
I checked this on remix-alpha. This is fixed now.
