### ISSUE TITLE
Blockhash causes VM to revert

### ISSUE THREAD

**Issue by fulldecent** [ethereum/remix-project#1203]
# Test case

```solidity
// SPDX-License-Identifier: MIT

pragma solidity 0.8.4;

contract BH {
    event Hash(bytes32);
    constructor() {
        emit Hash(blockhash(1));
    }
}
```

# Expected

Can deploy this contract successfully

# Actual

> creation of BH errored: transaction execution failed

All gas is used. For any amount of gas.

# Notes

Running `blockhash(0)` and `blockhash(i)` for some other values of `i` does not cause this problem.

**Comment by yann300** [comment]
were you using JavaScript VM?

**Comment by fulldecent** [comment]
Yes

**Comment by yann300** [comment]
I am a bit confused because I don't see the error message.. have you been using https://remix.ethereum.org ?

**Comment by fulldecent** [comment]
Sorry.

Confirmed. Cannot reproduce any longer.
