### ISSUE TITLE
Solidity Static Analysis Plugin UI improvements

### ISSUE THREAD

**Issue by Aniket-Engg** [ethereum/remix-project#1247]
- [x] Sometimes shows warning in browser console:
```
Warning: Each child in a list should have a unique "key" prop.

Check the render method of `RemixUiStaticAnalyser`. See https://fb.me/react-warning-keys for more information.
in div (created by RemixUiStaticAnalyser)
in RemixUiStaticAnalyser
```

- [x] If analysis result is being shown and I click on `Select all`, results are hidden instantly
- [x] If I have each checkbox unchecked, click on `Run`, no results are displayed. Now if `auto run` is checked and I check the `Select <category name>`, results related to that category are displayed instantly. Auto run is something which should run the analysis just after compilation

**Comment by tizah** [comment]
Hello @Aniket-Engg I was able to fix the issues on this PR [Static Analysis Improvements](https://github.com/ethereum/remix-project/pull/1251)
