### ISSUE TITLE
fix vertical scroll of ide

### ISSUE THREAD

**Issue by LianaHus** [ethereum/remix-project#1292]
scroll down to the issue or see the photo below

**Comment by LianaHus** [comment]
![Screenshot from 2021-06-16 12-00-41](https://user-images.githubusercontent.com/9685356/122199713-a137b480-ce9a-11eb-85c4-c138252d92d3.png)

**Comment by Rishabhraghwendra18** [comment]
Hi . First timer this side . May I work on this ?

**Comment by LianaHus** [comment]
Can't reproduce anymore. Probably was fix with settings tab move to react
