### ISSUE TITLE
Going from OZ Wizard to Remix opens in default_workspace and not code-sample

### ISSUE THREAD

**Issue by ryestew** [ethereum/remix-project#1295]
It used to open in code-sample.  Now it opens default_workspace.  

(BTW - it would be slightly better if we had standardized the use of - or _ for names)(this is another issue or guideline).

**Comment by Aniket-Engg** [comment]
Just to add more to the analysis, if remix is opened first time with `code=` parameter in URL, it is opened in `code-sample` workspace and `default_workspace` is not created.

**Comment by yann300** [comment]
>  if remix is opened first time with code= parameter in URL, it is opened in code-sample workspace and default_workspace is not created.

would you require the default workspace to be created in that case ?
