### ISSUE TITLE
File Explorers Workspaces - copying and pasting between workspaces is not possible 

### ISSUE THREAD

**Issue by ryestew** [ethereum/remix-project#1317]
Currently you cannot cut and pasted between workspaces.  You can copy the contents of a file and make a new file on a workspace and paste in the content.  Maybe that is enough.  But if you are on OZ Wizard and generate a file that gets opened in the sample-code workspace - it would be good to be able to copy this file into another workspace.

**Comment by yann300** [comment]
it's already possible to copy the content, copying file doesnt't add much value...
we'll have copying workpaces though soon.
