### ISSUE TITLE
Move vertical icon bar to Reactjs

### ISSUE THREAD

**Issue by ioedeveloper** [ethereum/remix-project#1333]
Vertical icon bar should have a scroll if needed

**Comment by ryestew** [comment]
I don't see the arrows and I'm not sure why the top border is thicker than the bottom one.  And I think the problem is the thickness of the top border and not the bottom border...

Here it is in the dark theme:
<img width="52" alt="image" src="https://user-images.githubusercontent.com/6050001/137566033-f7e76ebd-de81-4db4-a556-e8f1a951ece1.png">

**Comment by ryestew** [comment]
In the dark theme (at least on IPFS) the settings gear is alway in black -which does not seem correct.

**Comment by ryestew** [comment]
The other thing is that when there are not too many plugins I see the thick border line under the plugin manager and it is not clear why the boder is there.

oh wait - I just tried to deactive all the plugins and I get this:
<img width="394" alt="image" src="https://user-images.githubusercontent.com/6050001/137566204-7515a09e-5275-4966-8bbf-934445fe3ef8.png">

**Comment by ryestew** [comment]
I"ll try this later not on IPFS.

**Comment by ryestew** [comment]
I reloaded and the plugins that I had deactivated are not in the icon panel - but the thick line is there
<img width="68" alt="image" src="https://user-images.githubusercontent.com/6050001/137566333-29a9c45e-3c9c-4edd-81ba-168d23dcf4ec.png">

**Comment by ryestew** [comment]
The border lines probably should not be there unless the scroll is happening - because they don't serve any purpose except to show the scrolling area.

**Comment by joeizang** [comment]
yeah I fixed those issues and would ask that you take a look.

**Comment by vermouth22** [comment]
<img width="169" alt="Screen Shot 2022-01-19 at 1 54 09 PM" src="https://user-images.githubusercontent.com/35277634/150216568-4d396181-1b31-447f-ba1a-5e2bd23ca07d.png">
<img width="185" alt="Screen Shot 2022-01-19 at 1 55 09 PM" src="https://user-images.githubusercontent.com/35277634/150216573-9581ca6f-8811-4c40-98f2-f51d3e802aeb.png">
Rollover glow shadow (at Cairo Compiler) looks very subtle on a 13 inch Macbook Pro.
