### ISSUE TITLE
URL parameter for importing code from Github

### ISSUE THREAD

**Issue by dmitrydao** [ethereum/remix-project#1338]
## Overview
This is a feature request. 
Add extra parameter to the URL when importing code from Github.

## Issue

Remix allows importing Solidity code from Github but it doesn't add an extra parameter to the URL after importing. This makes it impossible to create a link that people can use to open a code sample in Remix.

Our team currently uses gists for that but it doesn't scale well when you have a large team. What happens is that multiple people own different gists and it makes it hard to have a centralized way to update different code snippets. Also, sometimes you need to update the code fast but the owner of a particular gist might be unavailable, on vacation, or even no longer working in the company. We need to fix that.

## Solution

Implement the same logic for importing Github code as gists by adding an additional parameter, such as`&github=https://github.com/documentation_repo/example.sol`. 

The end result should look the following way: `https://remix.ethereum.org/#optimize=false&runs=200&evmVersion=null&version=soljson-v0.8.4+commit.c7e474f2.js&github=https://github.com/documentation_repo/example.sol`

## Use cases
The best use case for this is the developer portal. Our team wants to update code samples once and make developers open them in Remix and load that code in our dev portal. In this case, we have to maintain only one version of the code which will be in the documentation repository.

**Comment by yann300** [comment]
ok we'll have a look to it.
in the meantime, what do you think of https://remix-ide.readthedocs.io/en/latest/locations.html?highlight=code%20sample#load-an-encoded-base64-string-into-a-sol-file
is that answering your need?

**Comment by dmitrydao** [comment]
Appreciate you pick it up. I think your solution will require encoding all of the code samples, which is not exactly what we're looking for and is not a scalable way for the long term. 

It will actually require more work from us, like encoding each time after the code samples have been changed and replacing that value with a new one after each update. 

But thanks for the suggestion anyway. I do hope you can figure out the way I outlined in the original issue.
