### ISSUE TITLE
Metamask compatibility completely broken

### ISSUE THREAD

**Issue by kzaher** [ethereum/remix-project#134]
When picking `Injected Web3` provider, and that is the latest version of Metamask (e.g. 6.6.1) sending transactions fails with 

**Gas estimation failed**

**Gas estimation errored with the following message (see below). The transaction execution will likely fail. Do you want to force sending? 
gas required exceeds allowance (7006834) or always failing transaction**

Filling in gas value manually in the UI doesn't help.

**Comment by MysticRyuujin** [comment]
Is this still a problem? Does MetaMask work, especially if you're using a custom RPC provider?
