### ISSUE TITLE
invalid member of stdlib

### ISSUE THREAD

**Issue by akashde93** [ethereum/remix-project#135]
![screenshot 34](https://user-images.githubusercontent.com/37961895/50541869-d79eed80-0bd4-11e9-85fb-bbc51b37e033.png)
![screenshot 35](https://user-images.githubusercontent.com/37961895/50541870-d79eed80-0bd4-11e9-82c3-cc4cb24b7e88.png)
when i am trying to run 'node compile.js' it its showing "  (node:10152) V8: C:\Users\Akash\chat\node_modules\solc\soljson.js:3 Invalid asm.js: Invalid member of stdlib  " and even when i run ' npm run test ' its showing an error " PS C:\Users\Akash\chat> node compile.js
(node:10152) V8: C:\Users\Akash\chat\node_modules\solc\soljson.js:3 Invalid asm.js: Invalid member of stdlib
PS C:\Users\Akash\chat> npm run  test

> chat@1.0.0 test C:\Users\Akash\chat
> mocha

(node:1432) V8: C:\Users\Akash\chat\node_modules\solc\soljson.js:3 Invalid asm.js: Invalid member of stdlib
  inbox
    1) "before each" hook for "deploys a contract"

  0 passing (115ms)
  1 failing

  1) "before each" hook for "deploys a contract":
     TypeError: (intermediate value).deploy(...).sent is not a function
      at Context.beforeEach (test\inbox.test.js:17:4)

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! chat@1.0.0 test: `mocha`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the chat@1.0.0 test script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Akash\AppData\Roaming\npm-cache\_logs\2018-12-29T20_20_39_579Z-debug.log
PS C:\Users\Akash\chat> "  
Can anyone give me a solution?

**Comment by timbilt** [comment]
install specific version 12 helped me:
sudo pacman -Sy "nodejs=12.18.3"

**Comment by ierosvin** [comment]
I have this issue just now. I hope a definite solution is coming soon. It's already 2021. 🙏 Thank you guys for all your hard work!

**Comment by ar4sdoteth** [comment]
> I have this issue just now. I hope a definite solution is coming soon. It's already 2021. 🙏 Thank you guys for all your hard work!

Just install node 12.18.3, worked for me.

**Comment by waseeld** [comment]
> > I have this issue just now. I hope a definite solution is coming soon. It's already 2021. pray Thank you guys for all your hard work!
> 
> Just install node 12.18.3, worked for me.

i have node v14.15.4 but i still have the same error

**Comment by royce777** [comment]
I've got node v14.16 and get this error : 
Compilation failed. See above.
(node:18916) V8: C:\Users\r0yce\.config\truffle\compilers\node_modules\soljson-v0.4.15+commit.bbb8e64f.js:3 Invalid asm.js: Invalid member of stdlib, so frustrating =(

**Comment by ArnoSlabbinck** [comment]
I got the same error when I tried to migrate my contracts but what worked for me was to change the port number in truffle.js to the port number of the ganache workspace. I don't know if this helps but  hope it can help somebody

**Comment by beingOptimusP** [comment]
same issue guys, is changing the node version the only solution?
if yes, could anyone get me the installable node version 12 file link

**Comment by mando-dev** [comment]
man< i have tried so many things. Nothing seems to work. I have tried, changing node versions, checking the pragma syntax, installing nvm, If anyone has any suggestions please help!!!!!

**Comment by mando-dev** [comment]
HEY guys I was able to figure out the issue for myself. Basically use node version 10.0.0     If this doesnt work then you prolly have a typo.     But to use an old version of node , i first installed NVM-node version manager. Once you download that, on your terminal you can run "nvm use 10".    Just like that, that means you are trying to use node version 10. nvm should notify you that you are veriosn 10, after that u r good. if you get into trouble, message me at my webstie mandodev.com

**Comment by Eloneron** [comment]
Hey guys, 
for me changing the solidity compiler version solved the issue.
I arbitrarily picked:
npm install solc@0.4.26

**Comment by wfs** [comment]
> Hey guys, for me changing the solidity compiler version solved the issue. I arbitrarily picked: npm install solc@0.4.26

Thanks @Eloneron ! Works now for me as well. 

Don't forget to update truffle-config.js in your truffle project. FYI, I'm running node 16.3.0,

**Comment by MAbbasRaza** [comment]
> Hey guys, for me changing the solidity compiler version solved the issue. I arbitrarily picked: npm install solc@0.4.26

works for me as well cause of this

**Comment by G-TipSolutions** [comment]
Sweeeet found it. and did it!!! thanks Crew/fam

**Comment by Kali-Decoder** [comment]
Thanks Elonron Great

**Comment by cameel** [comment]
Just FYI, we don't have a real solution to this problem yet but it seems that only the asm.js builds are affected. If you use the [wasm builds](https://github.com/ethereum/solc-bin/tree/gh-pages/emscripten-wasm32), you should not run into it. We have rebuilt older versions for wasm so these binaries are available in solc-bin even as far back as 0.3.6. On top of that they're also significantly faster. There's basically no reason to still use the asm.js builds at this point.

**Comment by ShirleyRex** [comment]
> Hey guys, for me changing the solidity compiler version solved the issue. I arbitrarily picked: npm install solc@0.4.26

This worked for me
Thanks @Eloneron

**Comment by Maxhaufe17** [comment]
I have download the extension NVM in VS code, then the problem was solved.

Thanks

**Comment by usamaiqball** [comment]
> > Hey guys, for me changing the solidity compiler version solved the issue. I arbitrarily picked: npm install solc@0.4.26
> 
> Thanks @Eloneron ! Works now for me as well.
> 
> Don't forget to update truffle-config.js in your truffle project. FYI, I'm running node 16.3.0,

worked for me.

**Comment by Aniket-Engg** [comment]
Looks like this is working fine now, so closing this.
