### ISSUE TITLE
Custum transaction context not updating balance of test contract instance

### ISSUE THREAD

**Issue by Reliec** [ethereum/remix-project#1351]
![grafik](https://user-images.githubusercontent.com/58212023/124316419-dd933200-db75-11eb-9733-a768a8ad0508.png)
![grafik](https://user-images.githubusercontent.com/58212023/124316490-f26fc580-db75-11eb-8472-2b25001e7040.png)
Im currently trying to write tests for a custom transaction context. If the transaction goes through, so should the balance of the testContract be updated.  At least thats how i grasp it.

I currently can't find any information about this besides the official documentation and I'm unsure if this is a bug or just me missunderstanding the concept.

**Comment by Aniket-Engg** [comment]
Hello @Reliec , a transaction should be performed to transfer the value to contract. You can find some examples here: https://remix-ide.readthedocs.io/en/latest/unittesting_examples.html

**Comment by Reliec** [comment]
Ah ok, so the transaction context really only instantiates the values but doest't transfer anything yet, right @Aniket-Engg ? I will try that out and close this issue if my problem is solved.

**Comment by Aniket-Engg** [comment]
Closing it. Please reopen if issue persists.
