### ISSUE TITLE
JSON parsing error in Yul metadata field in Compilation Details

### ISSUE THREAD

**Issue by cameel** [ethereum/remix-project#1431]
Somewhat related to #122.

When I compile a Yul snippet and click `Compilation Details`, I see the following error message in the `METADATA` section:

```
Unable to display "$metadata": $JSON.parse: unexpected character at line 1 column 1 of the JSON data
```

Other fields representing missing compilation artifacts are empty and this one should be too.

I tried it specifically with the code from #122 and Solidity 0.8.6 but I've seen this behavior with other code/versions too.

By the way, the work on making it possible to output all the same information in Yul mode is currently ongoing and in the near future it will be possible to store all the extra info in the IR and get the same output as for Solidity (https://github.com/ethereum/solidity/issues/11494).

**Comment by LianaHus** [comment]
https://github.com/ethereum/remix-project/issues/122
