### ISSUE TITLE
Hometab import from GITHUB & from HTTPS don't work

### ISSUE THREAD

**Issue by ryestew** [ethereum/remix-project#1433]
Take a file like the examples in the modal or like this file - for github import:
https://github.com/OpenZeppelin/openzeppelin-contracts/blob/master/contracts/finance/PaymentSplitter.sol

or like the example in https and it doesn't work

**Comment by ioedeveloper** [comment]
@ajsarun Your issue raised in the gitter channel is being tracked here. https://github.com/ethereum/remix-project/issues/1433

**Comment by Aniket-Engg** [comment]
A similar one: https://files.gitter.im/578fa63cc2f0db084a23e12f/z9sd/image.png
