### ISSUE TITLE
Use existing plugins to improve UX

### ISSUE THREAD

**Issue by LianaHus** [ethereum/remix-project#1443]
- add some items in context menu
**Done. We are planing to add more** see https://github.com/ethereum/remix-project/issues/1631
- discuss how can plugins be used
**Done** see https://github.com/ethereum/remix-project/issues/1632 https://github.com/ethereum/remix-project/issues/1633

more context from Roadmap 2021:
```
Integration of external plugin to the native UI - @liana @filip
- Q2 Storage plugin ( decentralized git )
- Gas Profiler
- Q1 Deploy & Run
- Q2 Solidity Unit Testing
```
**DGIT** _is implemented, improvements coming_
**Gas Profiler** _NEED AN UPDATE_
**Deploy & Run**  _nothing to add_
**SUT** _Debugger is already used in SUT, Test dir path is added to context menu, https://github.com/ethereum/remix-project/issues/1631 is planned_

**Comment by ryestew** [comment]
So far DGIT unit testing has been done.  FYI - this is about Context menu & Rt Click

**Comment by ryestew** [comment]
@bunsenstraat & @LianaHus should discuss this issue to figure out the next step.
