### ISSUE TITLE
Gas limit is ignored.

### ISSUE THREAD

**Issue by MicahZoltu** [ethereum/remix-project#147]
In the run tab of remix I am prompted to set the gas limit for my transactions.  However, setting it doesn't appear to actually work and instead estimated gas is used.  This is problematic when gas estimation doesn't work.  For example, I have a transaction that has variable gas costs based on when it is mined, so I need to explicitly specify gas and not use estimates.

Gas limit setting:
![image](https://user-images.githubusercontent.com/886059/41139908-42e83366-6b1d-11e8-966d-b36ad6dec982.png)

Actual gas provided:
![image](https://user-images.githubusercontent.com/886059/41139921-4be240f6-6b1d-11e8-9323-12687be0db4f.png)

This is when using `Web3 Provider`.

**Comment by caoyifeng007** [comment]
Does anybody know how to specify a fixed number of gas in an `address(addr).call` when debug in remix?

**Comment by Aniket-Engg** [comment]
This should be fixed
