### ISSUE TITLE
Generate Solidity input json

### ISSUE THREAD

**Issue by karalabe** [ethereum/remix-project#1472]
I'm unsure if this is something I missed or is genuinely not there (maybe for a reason).

Yesterday I've tried to verify a contract on Etherscan, and unless it's a flat file (unlikely if you make anything remotely complex) you need to upload some insane amount of metadata. Something called the `Solidity input json`. It would be nice if Remix would dump this out too among the various resources it generates.

I did see that there's an Etherscan Remix verification plugin that does generate it, but my key was rejected, so the only way I could verify is to hook into the HTTP traffic between the plugin and etherscan and extract the solidity-json-input from the browser request and submit it manually. I'm guessing there has to be an easier way.

**Comment by cameel** [comment]
This is also something that would be very helpful as a way to reproduce problems reported by users directly with the compiler.
