### ISSUE TITLE
Upload to IPFS - JS error on Compiler

### ISSUE THREAD

**Issue by ryestew** [ethereum/remix-project#1473]
On the solidity compiler, with the js console open - hit the publish to IPFS and in the console I get:
<img width="555" alt="image" src="https://user-images.githubusercontent.com/6050001/129333555-ea82fbef-27e6-415d-958d-0ed91dfcefc6.png">

**Comment by yann300** [comment]
I think we try also to push ipfs content to the default local not if it exists. Can you check if the content is pushed in our remote node?

**Comment by bunsenstraat** [comment]
this is normal behaviour as the export loops over all available ipfs nodes

https://github.com/ethereum/remix-project/blob/d041cfa759c187f093f5ebb335c6a040ffe34594/libs/remix-ui/publish-to-storage/src/lib/publishToIPFS.tsx#L6

**Comment by ryestew** [comment]
Is it possible to catch the error and not print it?

**Comment by bunsenstraat** [comment]
This error cannot be caught, ERR_CONNECTION_REFUSED. closing the issue.
