### ISSUE TITLE
Remix-SyntaxError & Compiler issues

### ISSUE THREAD

**Issue by DecoratedWings** [ethereum/remix-project#1566]
Hi, 

I am facing the following error: 
Cannot load compiler version list. It might have been blocked by an advertisement blocker. Please try deactivating any of them from this page and reload. Error: SyntaxError: JSON.parse: unexpected end of data at line 1 column 1 of the JSON data

No ad blockers are enabled and I have tried on both chrome and safari. 

Additionally I see the following error on the compile tab: 
Worker error: undefined

My remix was working just fine last week, not sure what caused this change.

Thanks for your time.

**Comment by djdenny56** [comment]
I am having the same issue and warnings, also no ad blockers, and I have allowed all permissions in Chrome.

**Comment by DecoratedWings** [comment]
@djdenny56 actually thanks to their gitter chat: https://gitter.im/ethereum/remix?at=5dec986bd64a052fb6d6d4fe a few members explained a good workaround to import the compiler. 
What they suggested worked for me so let me share and then close this issue so others may benefit :) 

**To summarize:** 

1) Go here for a list of their custom compiler versions: https://github.com/ethereum/solc-bin/tree/gh-pages/emscripten-wasm32 

2) Then paste the version you need after this url: https://binaries.soliditylang.org/ into remix

3) So for example for version 0.7.4 this would be the URL: https://binaries.soliditylang.org/emscripten-wasm32/solc-emscripten-wasm32-v0.7.4+commit.3f05b770.js

4) Then in remix go to the compiler tab, select (+) button above compiler and paste in the entire URL. 
It will import that version compiler

Credits to:  @PostMan56 & @zlex7 from Gitter chat for their solution

**Comment by cameel** [comment]
CORS issue at binaries.soliditylang.org has been fixed so things should be back to normal.

**Comment by DecoratedWings** [comment]
@cameel Thanks so much, it is working as before now :) 

I will close this issue.
