### ISSUE TITLE
Can't load compiler list in Chrome

### ISSUE THREAD

**Issue by kevinengel** [ethereum/remix-project#1568]
See this error in the console:

Access to XMLHttpRequest at 'https://binaries.soliditylang.org/bin/list.json' from origin 'https://remix.ethereum.org' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.

Works fine on Firefox for some reason. I tried clearing the site data, but made no difference.

**Comment by kevinengel** [comment]
Works again now!

**Comment by cameel** [comment]
This is still the issue from yesterday: #1566. Turns out that the problem comes back each time CloudFront cache at`solc-bin` is invalidated.

Here's the summary of the problem from #remix channel:

> The problem is in the way [simple CORS requests](https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS#simple_requests) affect caching.
>
> CloudFront has It has two separate policies that affect caching:
> - _cache policy_, which determines if your request can be served from the cache or if it has to forward the request to S3 and cache the result.
> - _origin request policy_, which determines how the request to S3 looks like (which headers are forwarded, etc) when it has to be made.
>
> This works fine with normal CORS requests where we have a pre-flight `OPTIONS` request followed by the actual request. Only the pre-flight request needs the `Origin` header and the response to the actual request does not have CORS headers (no matter whether the client uses CORS or not).
> But when a browser performs a simple CORS request, it just sends a `GET` that includes the `Origin` header and expects CORS headers on the response. The problem is that you can also make a `GET` request without `Origin` and the response will not have CORS headers (which makes sense - without `Origin` the server can't apply the CORS policy).
> With our current cache policy, CloudFront ignores the `Origin` header on `GET` requests. If it did not, caching would be much less effective because this header changes depending on the host. The origin request policy though makes CloudFront pass that header to S3 if present. The response from S3 is cached and served to everyone, regardless of whether they provide `Origin` on their request or not. This means that the cached response may or may not have CORS headers, depending on whether the client that asked for the file first provided the `Origin` header.

> I'm going to disable caching for `bin/list.json`. This will revert us to the situation where it's slow for people in regions outside EU but I think it's still better than this breakage
> Then I'll ask the devops team for help in finding a long-term solution.
