### ISSUE TITLE
nx serve "Module not found"

### ISSUE THREAD

**Issue by LANGLANG-CHAN** [ethereum/remix-project#1604]
Trying using "nx serve" then got below error

D:\remixproject\remix-project>nx serve

> nx run remix-ide:serve
**
Web Development Server is listening at http://localhost:8080/
**
Starting type checking service...
Using 2 workers with 2048MB memory limit
i ｢wds｣: Project is running at http://localhost:8080/
i ｢wds｣: webpack output is served from /
i ｢wds｣: 404s will fallback to //webpack.index.html
Type checking in progress...
Hash: c8de2b0e038fc9e0ce1c
Built at: 2021/09/16 上午1:21:06
Entrypoint main = runtime.js runtime.js.map vendor.js vendor.js.map main.js main
.js.map
Entrypoint polyfills = runtime.js runtime.js.map polyfills.js polyfills.js.map
chunk {main} main.js, main.js.map (main) 2.2 MiB ={runtime}= ={vendor}= [initial
] [rendered]
chunk {polyfills} polyfills.js, polyfills.js.map (polyfills) 769 KiB ={runtime}=
 [initial] [rendered]
chunk {runtime} runtime.js, runtime.js.map (runtime) 0 bytes ={main}= ={polyfill
s}= ={vendor}= [entry] [rendered]
chunk {vendor} vendor.js, vendor.js.map (vendor) 13.2 MiB ={main}= ={runtime}= [
initial] [rendered] split chunk (cache group: vendor) (name: vendor)

ERROR in D:/remixproject/remix-project/libs/remix-ui/static-analyser/src/lib/rem
ix-ui-static-analyser.tsx
Module not found: Error: Can't resolve '@remix-project/remix-analyzer' in 'D:\re
mixproject\remix-project\libs\remix-ui\static-analyser\src\lib'

ERROR in ./app/editor/contextualListener.js
Module not found: Error: Can't resolve '@remix-project/remix-astwalker' in 'D:\r
emixproject\remix-project\apps\remix-ide\src\app\editor'

ERROR in D:/remixproject/remix-project/dist/libs/remix-debug/src/solidity-decode
r/internalCallTree.js
Module not found: Error: Can't resolve '@remix-project/remix-astwalker' in 'D:\r
emixproject\remix-project\dist\libs\remix-debug\src\solidity-decoder'

ERROR in D:/remixproject/remix-project/dist/libs/remix-debug/src/solidity-decode
r/astHelper.js
Module not found: Error: Can't resolve '@remix-project/remix-astwalker' in 'D:\r
emixproject\remix-project\dist\libs\remix-debug\src\solidity-decoder'

ERROR in D:/remixproject/remix-project/dist/libs/remix-debug/src/source/sourceMa
ppingDecoder.js
Module not found: Error: Can't resolve '@remix-project/remix-astwalker' in 'D:\r
emixproject\remix-project\dist\libs\remix-debug\src\source'

ERROR in ./app/tabs/test-tab.js
Module not found: Error: Can't resolve '@remix-project/remix-solidity' in 'D:\re
mixproject\remix-project\apps\remix-ide\src\app\tabs'

ERROR in ./app/tabs/runTab/model/dropdownlogic.js
Module not found: Error: Can't resolve '@remix-project/remix-solidity' in 'D:\re
mixproject\remix-project\apps\remix-ide\src\app\tabs\runTab\model'

ERROR in D:/remixproject/remix-project/apps/solidity-compiler/src/app/compiler-a
pi.ts
Module not found: Error: Can't resolve '@remix-project/remix-solidity' in 'D:\re
mixproject\remix-project\apps\solidity-compiler\src\app'

ERROR in D:/remixproject/remix-project/dist/libs/remix-tests/src/compiler.js
Module not found: Error: Can't resolve '@remix-project/remix-solidity' in 'D:\re
mixproject\remix-project\dist\libs\remix-tests\src'

ERROR in D:/remixproject/remix-project/libs/remix-core-plugin/src/lib/compiler-a
rtefacts.ts
Module not found: Error: Can't resolve '@remix-project/remix-solidity' in 'D:\re
mixproject\remix-project\libs\remix-core-plugin\src\lib'

ERROR in D:/remixproject/remix-project/libs/remix-core-plugin/src/lib/compiler-m
etadata.ts
Module not found: Error: Can't resolve '@remix-project/remix-solidity' in 'D:\re
mixproject\remix-project\libs\remix-core-plugin\src\lib'

ERROR in D:/remixproject/remix-project/libs/remix-core-plugin/src/lib/compiler-f
etch-and-compile.ts
Module not found: Error: Can't resolve '@remix-project/remix-solidity' in 'D:\re
mixproject\remix-project\libs\remix-core-plugin\src\lib'

ERROR in D:/remixproject/remix-project/libs/remix-ui/solidity-compiler/src/lib/c
ompiler-container.tsx
Module not found: Error: Can't resolve '@remix-project/remix-solidity' in 'D:\re
mixproject\remix-project\libs\remix-ui\solidity-compiler\src\lib'

ERROR in D:/remixproject/remix-project/libs/remix-ui/solidity-compiler/src/lib/l
ogic/compileTabLogic.ts
Module not found: Error: Can't resolve '@remix-project/remix-solidity' in 'D:\re
mixproject\remix-project\libs\remix-ui\solidity-compiler\src\lib\logic'

ERROR in D:/remixproject/remix-project/libs/remix-core-plugin/src/lib/compiler-c
ontent-imports.ts
Module not found: Error: Can't resolve '@remix-project/remix-url-resolver' in 'D
:\remixproject\remix-project\libs\remix-core-plugin\src\lib'
i ｢wdm｣: Failed to compile.
Error from chokidar (D:\): Error: EBUSY: resource busy or locked, lstat 'D:\page
file.sys'
ERROR in D:/remixproject/remix-project/apps/solidity-compiler/src/app/compiler-a
pi.ts(1,25):
TS2307: Cannot find module '@remix-project/remix-solidity'.
ERROR in D:/remixproject/remix-project/libs/remix-core-plugin/src/lib/compiler-a
rtefacts.ts(3,34):
TS2307: Cannot find module '@remix-project/remix-solidity'.
ERROR in D:/remixproject/remix-project/libs/remix-core-plugin/src/lib/compiler-c
ontent-imports.ts(3,34):
TS2307: Cannot find module '@remix-project/remix-url-resolver'.
ERROR in D:/remixproject/remix-project/libs/remix-core-plugin/src/lib/compiler-f
etch-and-compile.ts(3,25):
TS2307: Cannot find module '@remix-project/remix-solidity'.
ERROR in D:/remixproject/remix-project/libs/remix-core-plugin/src/lib/compiler-m
etadata.ts(3,34):
TS2307: Cannot find module '@remix-project/remix-solidity'.
ERROR in D:/remixproject/remix-project/libs/remix-ui/solidity-compiler/src/lib/c
ompiler-container.tsx(6,99):
TS2307: Cannot find module '@remix-project/remix-solidity'.
Version: typescript 3.8.3
Time: 29691ms

**Comment by j5465** [comment]
怎么解决的呀？
