### ISSUE TITLE
Run&Deploy: Auto-select contract list with contract that was compiled

### ISSUE THREAD

**Issue by pappas999** [ethereum/remix-project#1651]
Whenever you compile a contract that imports and uses other contracts, when you go to the Deploy and Run Transactions tab, the contract dropdown contains a list of all contracts compiled, and the one selected by default is usually a library contract, causing the user to have to change the contract to the main one they just compiled before they go to deploy. 

Can the IDE please be updated to auto-fill the dropdown with the main contract that was just compiled, and not one of the associated libraries? This would save developers time and hassle having to always change the value. Developers would be wanting to deploy the contract they just compiled in 99% of use cases, and not some other library or contract that is imported

**Comment by LianaHus** [comment]
we can autoselect the contract but libs should stay in the list, as it is possible to deploy a library

**Comment by pappas999** [comment]
thanks @LianaHus , what you suggested makes perfect sense.
