### ISSUE TITLE
Whole code shifts horizontally when scrolling through 

### ISSUE THREAD

**Issue by greenlucid** [ethereum/remix-project#1679]
When scrolling past line 100, the container of the code suddenly shifts to the right.
When scrolling back up, it shifts to the left.
This is because the column that displays the line numbers becomes larger when there are more digits, to accommodate.
The effect may be more obvious if you hit the zoom button a few times.
This is super annoying, particularly when you notice

**Comment by LianaHus** [comment]
@yann300  any update here?
