### ISSUE TITLE
Gas estimation error

### ISSUE THREAD

**Issue by inix** [ethereum/remix-project#1716]
Hi:
When I deployed, I encounted following error messages:
Gas estimation errored with the following message:

<img width="477" alt="remix err" src="https://user-images.githubusercontent.com/2264291/139466134-0b4a9823-46ea-418b-8049-2260632d136d.png">

**Comment by markusbug** [comment]
After you deployed a contract, or did you try to create a smart contract in this transaction?

What Provider were you using in Remix?

**Comment by inix** [comment]
> After you deployed a contract, or did you try to create a smart contract in this transaction?
> 
> What Provider were you using in Remix?

I try to deploy the contract,it can be compiled successfully.
I deploy to Binance Testnet.

**Comment by markusbug** [comment]
The Internal JSON-RPC error is most likely a problem with Metamask.
Are you sure you correctly added the Binance testnet?

Can you try to deploy it on another Testnet? (Goerli for example)

**Comment by inix** [comment]
> The Internal JSON-RPC error is most likely a problem with Metamask. Are you sure you correctly added the Binance testnet?
> 
> Can you try to deploy it on another Testnet? (Goerli for example)

I can sure my wallet had connected to BSC testnet successfully.
I had deployed two test smart contract successfully.
But this error also happened when I try to deploy with hardhat and truffle.
I am not sure what is the problem.

**Comment by markusbug** [comment]
> > The Internal JSON-RPC error is most likely a problem with Metamask. Are you sure you correctly added the Binance testnet?
> > Can you try to deploy it on another Testnet? (Goerli for example)
> 
> I can sure my wallet had connected to BSC testnet successfully. I had deployed two test smart contract successfully. But this error also happened when I try to deploy with hardhat and truffle. I am not sure what is the problem.

As you just said, this is not a Problem with the Remix IDE, I suggest you look for assistance on Metamask.

**Comment by inix** [comment]
> > > The Internal JSON-RPC error is most likely a problem with Metamask. Are you sure you correctly added the Binance testnet?
> > > Can you try to deploy it on another Testnet? (Goerli for example)
> > 
> > 
> > I can sure my wallet had connected to BSC testnet successfully. I had deployed two test smart contract successfully. But this error also happened when I try to deploy with hardhat and truffle. I am not sure what is the problem.
> 
> As you just said, this is not a Problem with the Remix IDE, I suggest you look for assistance on Metamask.

OK. Thank you
