### ISSUE TITLE
compiler warning in Red

### ISSUE THREAD

**Issue by Aniket-Engg** [ethereum/remix-project#1732]
- If there is an error in a contract on first compilation and warning in second compilation, warning comes in red
- If there is an warning in a contract on first compilation and error in second compilation, error comes in yellow

It kind of persists colours from previous compilation

<img width="1020" alt="Screenshot 2021-11-08 at 12 39 47 PM" src="https://user-images.githubusercontent.com/30843294/140698844-58a955cb-f563-43b2-8b93-10a1104b684b.png">

**Comment by LianaHus** [comment]
i think this is a duplicate of https://github.com/ethereum/remix-project/issues/1452

**Comment by yann300** [comment]
this should be already fixed, please reopen it if not
