### ISSUE TITLE
bug when replacing upload that is opened in editor

### ISSUE THREAD

**Issue by bunsenstraat** [ethereum/remix-project#1737]
- upload a file
- change the content of the file but leave it open in editor
- upload it again and say ok to overwrite
- result file in editor is still the changed file
- if file is not in editor when uploading & replacing it's fine

**Comment by FAvE01** [comment]
![Uploading D9A0B9D8-1FF0-4123-A3A9-C40C960C4049.jpeg…]()

**Comment by FAvE01** [comment]
👍🤝
