### ISSUE TITLE
Unable to connect remix IDE to hardhat local blockchain

### ISSUE THREAD

**Issue by LucianoTrujillo** [ethereum/remix-project#1763]
I've followed both https://remix-ide.readthedocs.io/en/latest/remixd.html and https://remix-ide.readthedocs.io/en/latest/hardhat.html step by step, but when trying to choose hardhat environment, this error appears:

"Not possible to connect to the Web3 provider. Make sure the provider is running, a connection is open (via IPC or RPC) or that the provider plugin is properly configured."

but, I can deploy locally using hardhat, so blockchain is running and listening. Also, I have default configuration.

MacOS, latest Chrome

**Comment by Aniket-Engg** [comment]
@LucianoTrujillo Can you please add some screenshots to understand the issue? I can connect with hardhat local Blockchain normally

**Comment by nilsbunger** [comment]
@LucianoTrujillo I had the same issue on Brave browser, but turning off shields for remix fixed it. Check if you have something similar going on in your browser?

@Aniket-Engg a warning about browser blockers might be helpful to add in the docs.

**Comment by Aniket-Engg** [comment]
@LucianoTrujillo Is it worked for you?

**Comment by Aniket-Engg** [comment]
Closing it. Please feel free to reopen if issue persists

**Comment by phongdc168** [comment]
> @LucianoTrujillo I had the same issue on Brave browser, but turning off shields for remix fixed it. Check if you have something similar going on in your browser?
> 
> @Aniket-Engg a warning about browser blockers might be helpful to add in the docs.

thanks for your solution, it works for me

**Comment by parthavpovil** [comment]
> @LucianoTrujillo I had the same issue on Brave browser, but turning off shields for remix fixed it. Check if you have something similar going on in your browser?
> 
> @Aniket-Engg a warning about browser blockers might be helpful to add in the docs.


yo thanks man 🤝
