### ISSUE TITLE
Gas estimation error why???

### ISSUE THREAD

**Issue by xteriumboy** [ethereum/remix-project#1764]
Hi:
When I deployed, I encounted following error messages:
Gas estimation errored with the following message:

**Comment by xteriumboy** [comment]
<img width="477" alt="error" src="https://user-images.githubusercontent.com/17035127/141985230-46ed4e18-54f1-4d18-a7de-9d1e268844e2.png">

**Comment by LianaHus** [comment]
I can't say without seeing your contract. you most likely have not enough gas or tokens...  Please check your contract again.

**Comment by xteriumboy** [comment]
I TRY to deploy in VM to test this contract
![image](https://user-images.githubusercontent.com/17035127/143521290-a815bd7f-7d44-4a58-b36d-c67fdd8db065.png)

https://bscscan.com/address/0xcd85f338788c67e3037b7698c5126df72cc5d0c1#code
