### ISSUE TITLE
Debugger not working on Ropsten

### ISSUE THREAD

**Issue by taiyangc** [ethereum/remix-project#1775]
When trying to run debugger, the following errors showed up in console log:

<img width="889" alt="Screen Shot 2021-11-20 at 3 20 36 AM" src="https://user-images.githubusercontent.com/1467354/142724434-00baf894-e64d-434b-a489-10ad1bb08eb6.png">

The "Start debugging" button does nothing. Any clue why?

**Comment by LianaHus** [comment]
Hi @taiyangc,
thanks for the report. the debugger node we use seems down, our DevOps team will fix it ASAP.
For now, you can still use debugger with your own node if you can run one.
