### ISSUE TITLE
A global install issue with new version of remixd on window 10

### ISSUE THREAD

**Issue by D-One0914** [ethereum/remix-project#1786]
Hello, 
I am using window 10
node: 16.13  
npm : 8.1.0

I did "npm install -g @remix-project/remixd" before latest update, 
remixd -v was totally fine. 

However, After the update,  I downloaded again @remix-project/remixd globally with this keyworkds "npm install -g @remix-project/remixd". 
remixd -v  seems not working saying remixd  is not recognized as an internal or external command. 

and, npm install -g @remix-project/remixd@0.5.2 is totally fine 

Please let me know how to solve it 

thank you in advance !

**Comment by kgamecarter** [comment]
same issues on win11

**Comment by chinh-trieutien** [comment]
the path suppose to be 
`node_modules\@remixproject\remixd\bin\remixd.js`
but the install script look up for 
`node_modules\@remix-project\remixd\bin\remixd.js`

**Comment by ddarville** [comment]
Hi,

Im experiencing the same issue. I have followed instructions from https://remix-ide.readthedocs.io/en/latest/remixd.html
But keeps dropping the same message after installation -> remixd is not recognized as an internal or external command

Any workaround to call the remixd.js with its absolute path?

**Comment by ddarville** [comment]
> Hi,
> 
> Im experiencing the same issue. I have followed instructions from https://remix-ide.readthedocs.io/en/latest/remixd.html But keeps dropping the same message after installation -> remixd is not recognized as an internal or external command
> 
> Any workaround to call the remixd.js with its absolute path?

I found a temp solution for windows.

1. Install remixd in your project directory without the '-g' flag.
2. Navegate to node_modules and find the folder name @remix-project/remixd 
3. Navegate to the /src/bin folder and open a terminal and type node remixd.js + argument.

Hope this can help somebody out there.

**Comment by yurycooliq** [comment]
Solved. `npm install -g @remix-project/remixd@0.5.1`

**Comment by milekdo** [comment]
> Solved. `npm install -g @remix-project/remixd@0.5.1`

Dude don't spam - going back two versions is NOT solving the problem AT ALL...

**Comment by zidanegimiga** [comment]
Hey, I also tried installing the package within the project's scope but the `remixd` command still doesn't work

**Comment by Raxort** [comment]
Try to install the Remixd from an Administrator's account. This solved the problem for me.

1. Remove previously installed Remixd: `npm uninstall @remix-project/remixd`
2. Log in as **Administrator**
3. `npm install -g @remix-project/remixd`
4. Reboot your PC and you will be happy :)
