### ISSUE TITLE
replace all toasters for copy update to tooltips

### ISSUE THREAD

**Issue by LianaHus** [ethereum/remix-project#1800]

**Comment by JayDub19** [comment]
Some people (autism) are unable to tolerate displays that move too much. Thank you for removing the toast (slides in and out for "you copied into clipboard" message).

**Comment by Aniket-Engg** [comment]
We need to check if this is done for all copy to clipboard toasters and issue can be closed.

**Comment by Aniket-Engg** [comment]
@joeizang Please check if it is still not fixed
