### ISSUE TITLE
doesn't open any files

### ISSUE THREAD

**Issue by shevcovsfd** [ethereum/remix-project#1805]
**Remix Desktop version:** 1.3.2  
**remixd version:** 0.5.2  
**OS:** Windows 11  

Remix doesn't open any folders and solidity files. Does not depend on the number of clicks.  
![](https://sun9-75.userapi.com/impg/dXqOHEmput1CQQlj1ynsQczB2pnzt6oV6ovhTQ/w0nTVoyek48.jpg?size=1920x1020&quality=96&sign=4f0a64b757a9422a2c54f2a542166d15&type=album)

**Comment by mkbrv** [comment]
Same here. Just installed the latest version. I open a file and it hangs in Loading. Any file, or new files, new workspace, default one.
v14.15.4
Win10.

**Comment by jambola441** [comment]
> Same here. Just installed the latest version. I open a file and it hangs in Loading. Any file, or new files, new workspace, default one. node v14.15.4 Win10.

+1
Ubuntu 18.04.1 LTS
Chrome

![image](https://user-images.githubusercontent.com/92416078/143786069-6027e4b1-8de1-467a-ba9f-4f6b24db0dd7.png)

**Comment by magna-nz** [comment]
Same here Windows 11.

**Comment by jambola441** [comment]
> > Same here. Just installed the latest version. I open a file and it hangs in Loading. Any file, or new files, new workspace, default one. node v14.15.4 Win10.
> 
> +1 Ubuntu 18.04.1 LTS Chrome
> 
> ![image](https://user-images.githubusercontent.com/92416078/143786069-6027e4b1-8de1-467a-ba9f-4f6b24db0dd7.png)

Fixed as of today

**Comment by shevcovsfd** [comment]
yes, fixed
