### ISSUE TITLE
A global install issue with new version of remixd on Ubuntu 20

### ISSUE THREAD

**Issue by yurycooliq** [ethereum/remix-project#1806]
Hello,
I am using Ubuntu 20.04
node: 14.18.1 (16.13.1 have the same issue)
npm : 8.1.4

I did `npm install -g @remix-project/remixd`.

If I execute the `remixd -v` command, a message appears that the remixd command was not found. I tried to run other global packages, they are executing well, so the problem is not in npm.

Please let me know how to solve it

thank you in advance!

**Comment by xiangjianmeng** [comment]
me too

**Comment by CodeShredder726b** [comment]
me three. on arch.

**Comment by yurycooliq** [comment]
Solved. `npm install -g @remix-project/remixd@0.5.1`

**Comment by yurycooliq** [comment]
This is only a problem with the latest release. On Windows the same thing.

**Comment by jeriale** [comment]
Solution from @yurycooliq worked for me. I also had the same issue.

**Comment by limhyesook** [comment]
Same here. 0.5.2 seem to work but it forces read-only mode

**Comment by YUANYUAN-DeepGo** [comment]
@yurycooliq saved my ass, thx
