### ISSUE TITLE
npm install issue / missing remixd cmd

### ISSUE THREAD

**Issue by 26A0D355-AA5F-4621-8975-9184E8DF8C23** [ethereum/remix-project#1809]
After upgrading to 0.5.3, `remixd` cmd no longer works - the build output appears to be incorrect.

To reproduce:
Uninstall @remix-project/remixd then reinstall.

Possibly Related:
https://github.com/ethereum/remix-project/commit/d6f9c64324ec4e9a54ce2b2de87e005f12d5b64c#diff-a185b6361a56b0812c01914d7e86806c84ef1d3c1a04bff7c3a9edd03dd86fc7

Comparison of directory structures:

@remix-project/remixd@0.5.2
![image](https://user-images.githubusercontent.com/84586206/143777717-02a6f91c-8a80-4885-9f30-7d5c074025bb.png)

@remix-project/remixd@0.5.3
![image](https://user-images.githubusercontent.com/84586206/143777760-344830a0-cb1c-4991-9dfa-008b3a3addc2.png)

**Comment by 26A0D355-AA5F-4621-8975-9184E8DF8C23** [comment]
Temporary workaround:

Modify @remix-project/remixd/package.json fields then `npm link`:

```
  "bin": {
    "remixd": "./src/bin/remixd.js"
  },
```

**Comment by evanjmg** [comment]
ridiculous that the first time I install this I get this - need some checks there

**Comment by 26A0D355-AA5F-4621-8975-9184E8DF8C23** [comment]
> ridiculous that the first time I install this I get this - need some checks there

I'm sure it was an honest mistake - there are a lot of higher priority issues to be sure.  If the workaround doesn't suffice, you can always `npm i @remix-project/remixd@0.5.2`.

**Comment by jovijovi** [comment]
> > ridiculous that the first time I install this I get this - need some checks there
> 
> I'm sure it was an honest mistake - there are a lot of higher priority issues to be sure. If the workaround doesn't suffice, you can always `npm i @remix-project/remixd@0.5.2`.

I also encountered this problem. The 0.5.3 version cannot find the `remixd`.
`npm i @remix-project/remixd@0.5.2` It works.
Thx @26A0D355-AA5F-4621-8975-9184E8DF8C23

**Comment by tpkeeper** [comment]
have missed 6 hours for this, thx

**Comment by dotwilbert** [comment]
For me correcting permissions and creating the link worked.

```bash
<your path to install>/node_modules/.bin$ chmod 775 ../@remix-project/remixd/src/bin/remixd.js
<your path to install>/node_modules/.bin$ ln -s ../@remix-project/remixd/src/bin/remixd.js remixd
```

**Comment by nocibambi** [comment]
Had the same issue as of today on Ubuntu 22.04. @dotwilbert's workaround works.
