### ISSUE TITLE
remix.help() is not a function ?

### ISSUE THREAD

**Issue by kylebakerio** [ethereum/remix-project#1811]
The following libraries are accessible:
web3 version 1.5.2
ethers.js 
remix (run remix.help() for more info)

yet calling `remix.help()` just returns "remix.help() is not a function". `remix.help` and `remix` are also not `help`ful. ¯\_(ツ)_/¯

**Comment by LianaHus** [comment]
![Screenshot from 2021-12-06 12-15-39](https://user-images.githubusercontent.com/9685356/144837015-09c8154a-66c6-4552-be08-94e3a12ad040.png)
are those the only available functions we have now? @tizah @ryestew @yann300

**Comment by LianaHus** [comment]
https://github.com/ethereum/remix-project/blob/master/libs/remix-ui/terminal/src/lib/commands.ts here is a list of available commands

**Comment by LianaHus** [comment]
another issue: scroll is not working in pop up list. type '.' to see it

**Comment by LianaHus** [comment]
- [ ] another issue. command line should be always visible when terminal is open.
- [ ] sometimes when we close the terminal the title bar disappears .

**Comment by LianaHus** [comment]
@tizah
