### ISSUE TITLE
remixd 0.5.3 executable file not found

### ISSUE THREAD

**Issue by SinaTadayon** [ethereum/remix-project#1818]
Hi 
I install latest version of the remixd with npm intall -g @remix-project/remixd but after install remixd binary file not found.
thx

**Comment by DuanLu-Lin** [comment]
me too, it works normally when I roll back to 0.5.2, my environment is macOS 12.0.1.

**Comment by NadozirnySvyatoslav** [comment]
me too, windows 10

**Comment by tgarm** [comment]
me too. Ubuntu 20.04

**Comment by milekdo** [comment]
seems fixed in 0.5.5
