### ISSUE TITLE
console.log `DeclarationError: Undeclared identifier.`

### ISSUE THREAD

**Issue by dadaphl** [ethereum/remix-project#1833]
Following contract can not be compiled
```
// SPDX-License-Identifier: GPL-3.0

pragma solidity >=0.7.0 <0.9.0;

import "hardhat/console.sol";
contract Example {
    function logSomething() external view {
        console.log("inside getOwner");
    }
}
```
Error:
```
from solidity:
DeclarationError: Undeclared identifier.
 --> contracts/c1.sol:8:9:
  |
8 |         console.log("inside getOwner");
  |         ^^^^^^^
```
![Screenshot from 2021-12-08 20-01-26](https://user-images.githubusercontent.com/415536/145268235-a1385add-d4c9-494b-9507-33560b7e9da5.png)

Versions:
```
 - Welcome to Remix 0.20.3 - 
 soljson-v0.8.7+commit.e28d00a7.js
Javascrip VM (London)
```

**Comment by Aniket-Engg** [comment]
@dadaphl It seems working for me

![issueScreen](https://user-images.githubusercontent.com/30843294/145986784-f3957b68-4555-4cbf-aa42-86ca5dfc83e7.png)

Please check if it works fine for you now.

**Comment by dadaphl** [comment]
In chrome it works as expected. It seems to be an issue with my browser (latest firefox). I had several glitches recently, that come up randomly, even after resetting the cache, storage and cookies. Content from files disappears for no obvious reason when I click in the source code. When I inspected the .deps folder, console.sol was empty. I will continue to investigate and close this issue for now as it doesn't seem to be specific to console.sol
