### ISSUE TITLE
High  gas fee

### ISSUE THREAD

**Issue by CatalinTa** [ethereum/remix-project#1838]
On meta mask the gas fee is very high (200 USD) and this message appear;
_**This gas fee has been suggested by https://remix.ethereum.org. Overriding this may cause a problem with your transaction. Please reach out to https://remix.ethereum.org if you have questions.**_
Pls help!

**Comment by yann300** [comment]
I think you can  anyway edit the gas fee in metamask. is that working? (closing this issue, please reopen if needed).
