### ISSUE TITLE
Remix IDE not allowing tPLS or PLS or Pulse or pulse as a method of payment

### ISSUE THREAD

**Issue by 01fbk** [ethereum/remix-project#1842]
Hello,

When creating a smart contract on the pulse test chain using Remix IDE, tPLS or PLS or pulse or Pulse is not available as a method of payment. 
I have the following: 

`require(msg.value >= 0.1 tPLS, "Error: The price is 0.1 tPLS.");`

and also the following line: 

`if(msg.value > 0.1 tPLS) msg.sender.transfer(msg.value-0.1 tPLS);`

If I use ether instead of tPLS or PLS or pulse or Pulse, the compiler does not give an error anymore, but is still not finishing the transaction on PulseChain Testnet, it just hangs forever in the Creating state.

The error received is: 

`ParseError: Expected ',' but got identifier.`

Using Injected Web 3 option to deploy as per below.

![image](https://user-images.githubusercontent.com/35327838/146274485-b2f6cf4c-cdca-4243-a094-94f60c8a4e07.png)

Thank you,
Cristian

**Comment by 01fbk** [comment]
Fixed, apparently a long wait time for a moment in the system.

**Comment by yann300** [comment]
I think you need to have a specific compiler (I m pretty sure the classic compiler doesn't recoginze `tPLS` token).
Does the PulseChain requires a specific compiler?
