### ISSUE TITLE
Issue with errors tooltip pop up in code

### ISSUE THREAD

**Issue by chark3n** [ethereum/remix-project#1845]
Hello, 

I am experiencing an issue with the tooltip error pop up when I hover over an '!' on a line of code it gets cut off. It seems to only happen when the error is a certain length, smaller lined errors appear normally. I'm not sure what I did to cause it. 

Image of the cut off error 
![image](https://user-images.githubusercontent.com/95053260/146330025-50a10ab5-37a3-4821-b57b-3213a19f78fe.png)

Image of a shorter normal error message popup
![image](https://user-images.githubusercontent.com/95053260/146330138-69e51471-8086-4dcb-b653-59036c52c974.png)

Thanks in advance

**Comment by aj3423** [comment]
+1, same problem here. 
Linux + Brave browser
