### ISSUE TITLE
Debugger is not working for several chains

### ISSUE THREAD

**Issue by LianaHus** [ethereum/remix-project#1878]
Checking with 1_Storage.sol on goerli and Ropsten

sol v0.8.6: ChainID is not defined (goerli)
sol v0.8.11 - error: "Cannot read properties of undefined (reading 'memory')" (goerly, ropsten)

**Comment by Aniket-Engg** [comment]
As per initial analysis, there is an error in browser console as `cannot encode arguments` when we deploy a contract even with VM. This may be related to above issue. I am looking into this.
