### ISSUE TITLE
Only one compiler available 

### ISSUE THREAD

**Issue by v3gabond** [ethereum/remix-project#1881]
![Adsız](https://user-images.githubusercontent.com/97173096/148227094-bb87eb5c-a84c-48b4-aeb8-127aeaef8630.png)

**Comment by CrapFX** [comment]
Same issue please help

**Comment by cameel** [comment]
Duplicate of #1882. If you're still experiencing this, see https://github.com/ethereum/remix-project/issues/1882#issuecomment-1005995788 for a workaround.
