### ISSUE TITLE
Cannot see solidity Compilers

### ISSUE THREAD

**Issue by Atharva-Vijay-Khade** [ethereum/remix-project#1884]
![image](https://user-images.githubusercontent.com/58695354/148261898-8cd0b5da-6146-42b9-8298-186114970e17.png)

**Comment by cameel** [comment]
Duplicate of #1882. If you're still experiencing this, see https://github.com/ethereum/remix-project/issues/1882#issuecomment-1005995788 for a workaround.

**Comment by Atharva-Vijay-Khade** [comment]
Thank you @cameel , now the compilers are visible.
