### ISSUE TITLE
Medium articles window of hometab

### ISSUE THREAD

**Issue by ioedeveloper** [ethereum/remix-project#1928]
Here are bugs found in the medium articles window in hometab.
- The last thumbnail in the medium articles list doesn't show article snippet.
- Clicking on the article content closes the medium article window without loading content.

**Comment by faysal247** [comment]
> Here are bugs found in the medium articles window in hometab.
> 
> * The last thumbnail in the medium articles list doesn't show article snippet.
> * Clicking on the article content closes the medium article window without loading content.

Commit
