### ISSUE TITLE
Remix url parameter bugs

### ISSUE THREAD

**Issue by ryestew** [ethereum/remix-project#1932]
- [ ]  Activating defiexplorer doesn't work unless the solidity module is also activated. This url does not work as expected: https://remix.ethereum.org/?#activate=solidityUnitTesting,defiexplorer
- [ ]  Loading a file in the editor does not seem to be working:  A file will be loaded into the FE but not into the editor with this URL: https://remix.ethereum.org/#url=https://github.com/ethereum/remix-project/blob/master/apps/remix-ide/contracts/app/solidity/mode.so
- [ ] But if there is not that file in the current workspace - how will it load that file with a URL like this? 
https://remix.ethereum.org/?#activate=udapp,solidity&call=fileManager//open//3_Ballot.sol
So this is a bad example for the docs...
- [ ] The following URL doesn't switch the theme - but does load the list of plugins
https://remix.ethereum.org/?#activate=solidity,solidityUnitTesting,LearnEth,udapp&theme=dark

**Comment by yann300** [comment]
> Loading a file in the editor does not seem to be working: A file will be loaded into the FE but not into the editor with this

can you try https://remix.ethereum.org/#url=https://github.com/ethereum/remix-project/blob/master/apps/remix-ide/contracts/app/solidity/mode.sol

**Comment by yann300** [comment]
> But if there is not that file in the current workspace - how will it load that file with a URL like this?

yes indeed, we should probably add a `switchWorkspaceAndOpenFile` function, not sure if that should be done now.
what do you think @ioedeveloper ?

**Comment by yann300** [comment]
> Activating defiexplorer doesn't work unless the solidity module is also activated. This url does not work as expected:

can you show me, defi_explorer would open ok for me.. @ryestew

**Comment by ioedeveloper** [comment]
> > But if there is not that file in the current workspace - how will it load that file with a URL like this?
> 
> yes indeed, we should probably add a `switchWorkspaceAndOpenFile` function, not sure if that should be done now. what do you think @ioedeveloper ?

Yes, this can implemented as a feature in the future.
