### ISSUE TITLE
Add pop up to warn inexperienced users about malicious copy/paste code scams

### ISSUE THREAD

**Issue by iggy18** [ethereum/remix-project#1951]
There is a campaign on YouTube right now promoting a scam where people copy and paste code for a "front running bot" that supposedly yields 15x BNB what you put in after 15 minutes of waiting. Almost all of the code is commented out and they are just importing a wallet address from another file stored on ghostbin.

This scam is obvious to anyone who can read the code, but it is geared at inexperienced users. 

Remix removes the the normal barriers one must navigate In order to get started writing smart contracts. This is great, but it provides a new route for scammers to trick people. remix is the pinch point for this scam. Without remix the scammers would need to instruct victims to set up a local dev environment, which would severely limit the success rate of the scam.

Scams lose their effectiveness when the victim is educated about the scam. This is why scammers usually instruct their victims not to talk to anyone.

I'm adding this issue in the hopes that remix will implement a noticeable brightly colored pop up upon page load to inform people not to copy paste code they do not understand because it is a common fraud tactic. This simple popup with help to reduce fraud in the crypto community.

**Comment by ryestew** [comment]
Scam Alert: Beware of Youtube videos promoting "liquidity front runner bots" saying to paste contract code into Remix IDE.  Learn more here.

**Comment by vermouth22** [comment]
Here is the Medium article to link to for the warning above: https://medium.com/remix-ide/remix-in-youtube-crypto-scams-71c338da32d?source=friends_link&sk=bb6efbbf88bc3e496611943d282ad797

**Comment by metaman0x** [comment]
0x60ad80ee17854d2c0d6e567f045d6a11199e4c3c571063c7

**Comment by metaman0x** [comment]
I don't watch youtube. And I take back everything I said. It takes a massive piece of absolute s*** to from someone's crypto down to nothing within 20 mins of the most breakthrough moment since this nightmare started. Clearly there is no winning this rigged game. So enjoy that time you stole from me. It's more precious than you think

**Comment by iggy18** [comment]
> Here is the Medium article to link to for the warning above: https://medium.com/remix-ide/remix-in-youtube-crypto-scams-71c338da32d?source=friends_link&sk=bb6efbbf88bc3e496611943d282ad797

That's awesome. This pop-up will prevent a ton of people from losing money. well done ya'll. thank you!

**Comment by ryestew** [comment]
The home tab now  has a warning and a link to the medium article.

**Comment by mbogokennedy** [comment]
Currently, there is this address that is scamming on Ethereum: 0xB2931F1608598C6620B3096AF0d7844F57aE3154. Luckily, I tested using Sepolia Testnet and it drained all my test Ethereum.

Youtube Video: https://www.youtube.com/watch?v=QzQoG0Q25zQ&t=46s

Be careful, stay safe

**Comment by technicallykind** [comment]
How can we disable this warning?

**Comment by 1S33dp1sk** [comment]
whoever added this feature needs to reconsider any career in UIUX
