### ISSUE TITLE
remix-handler issue in `connect to Localhost`

### ISSUE THREAD

**Issue by Aniket-Engg** [ethereum/remix-project#1967]
- [x] It doesn't show modal on first time load. Tried it with Chrome, Brave browser's incognito window with remix-beta cc: @LianaHus 
- [x] Remove `$` from content in modal
<img width="529" alt="Screenshot 2022-01-19 at 12 51 47 PM" src="https://user-images.githubusercontent.com/30843294/150088509-e9a5cbfb-b55b-4006-9a9a-27f2365b20d5.png">

- [x] On remixd disconnection, localhost workspace files are not removed from editor
- [ ] If a folder A is expanded in remix IDE and a file is created inside folder A from local device, It doesn't appear on remix IDE unless folder A is collapsed and expanded again. Thus folders created at root directory don't appear on remix IDE as workspace can not be collapsed.

**Comment by Velewele** [comment]
Resubmit

**Comment by bunsenstraat** [comment]
"If a folder A is expanded in remix IDE and a file is created inside folder A from local device, It doesn't appear on remix IDE unless folder A is collapsed and expanded again. Thus folders created at root directory don't appear on remix IDE as workspace can not be collapsed."

As far as I know we don't monitor local file changes in remixd. so even if you add a file locally it won't appear in Remix unless you disconnect and connect again or collapse/uncollapse. @Aniket-Engg
