### ISSUE TITLE
remixd modal

### ISSUE THREAD

**Issue by ryestew** [ethereum/remix-project#1982]
There seems to be a $ sign in the remixd modal:
**Before using, make sure remixd version is latest i.e. $0.5.5**
<img width="499" alt="image" src="https://user-images.githubusercontent.com/6050001/150261306-4cd77872-903e-4ebe-ac93-940b35171277.png">

**Comment by ryestew** [comment]
previously reported in: https://github.com/ethereum/remix-project/issues/1967

**Comment by LianaHus** [comment]
I'll remove it
