### ISSUE TITLE
Canot create files in desktop safari 15.1

### ISSUE THREAD

**Issue by silviosisa** [ethereum/remix-project#1992]
![Captura de Pantalla 2022-01-22 a la(s) 11 14 01](https://user-images.githubusercontent.com/8923873/150642175-e3e39747-0cb7-4eb2-9fe0-5795a47dd0e8.png)
![Captura de Pantalla 2022-01-22 a la(s) 11 13 50](https://user-images.githubusercontent.com/8923873/150642202-c236247c-8d9f-4ae0-ae96-da97188c67b0.png)
you cannot write after that

**Comment by Aniket-Engg** [comment]
I can reproduce this.

**Comment by ryestew** [comment]
We don't support the Safari browser.  Please use Firefox, Chrome or Brave.  We will update our docs so it is clear about the list of the browsers Remix supports.
