### ISSUE TITLE
remix.ethereum.org not working

### ISSUE THREAD

**Issue by matheusqro** [ethereum/remix-project#2008]
Code is not compiling in remix.ethereum.org

![error](https://user-images.githubusercontent.com/39939428/151692085-6774db5b-3339-4dc9-85cf-37c8814a3861.png)

The error occurs in Microsoft Edge v=97.0.1072.55
In Chrome v=97.0.4692.99 worked normally.

**Comment by Aniket-Engg** [comment]
@matheusqro Remix loads compiler using worker and this error can sometimes appear for slow internet or on quick compiler version update. Can you please confirm you see it regularly and there are some steps to reproduce ?

**Comment by ryestew** [comment]
MS Edge is not a supported browser.  We will be updating our list of supported browsers.  But thanks for letting us know.
