### ISSUE TITLE
Remix debugger throwing TypeError

### ISSUE THREAD

**Issue by akornato** [ethereum/remix-project#2009]
Remix debugger is throwing `TypeError: Cannot read properties of undefined (reading 'memory')` for various transactions, e.g. for https://rinkeby.etherscan.io/tx/0xf4153f4e2cc7cf421f6689d2c0c509003bbc110f7e4cddfc5da59324596c64c1

<img width="512" alt="Screenshot 2022-01-30 at 15 33 55" src="https://user-images.githubusercontent.com/14935179/151704077-9d5f98e5-a86e-41bf-bb71-79edba1f7449.png">

**Comment by Aniket-Engg** [comment]
Hello @akornato , can you please check if it is fixed now?

**Comment by Aniket-Engg** [comment]
This should be fixed in our latest release. Please feel free to reopen in case issue persists.
