### ISSUE TITLE
In Candy Theme it Creates Visual Pollution

### ISSUE THREAD

**Issue by berkingurcan** [ethereum/remix-project#2010]
In candy theme, although my mouse cursor does not there or without any relevant move some line or lines getting dark.

<img width="733" alt="Screen Shot 2022-01-31 at 08 57 13" src="https://user-images.githubusercontent.com/70534820/151745819-13f4d2e4-fdad-4103-b996-cef19f94405f.png">

**Comment by berkingurcan** [comment]
<img width="828" alt="Screen Shot 2022-01-31 at 09 06 23" src="https://user-images.githubusercontent.com/70534820/151746625-d0f70af7-137e-446d-90fd-e9133bb15490.png">

**Comment by LianaHus** [comment]
hi. are you sure this is Candy theme?
I have this in Candy:
![Screenshot from 2022-02-16 10-31-47](https://user-images.githubusercontent.com/9685356/154236061-db3b564f-27dd-455e-8776-3cecfa324eec.png)

Maybe the bug has been fixed with last release. Can you please confirm this @berkingurcan ?
