### ISSUE TITLE
Encode Constructor Argument Copy Button Now Broken (< 24 hours old)

### ISSUE THREAD

**Issue by ryanjsfx2424** [ethereum/remix-project#2022]
Hello! Next to the "transact" button before deploying a smart contract on remix I click the "copy" button to encode the constructor arguments (so I can verify the smart contract on polygonscan later).

That copy button worked fine last night but isn't working today. Tried on Brave and Firefox on OSX 11.6.1. Also broken on Brave on OSX 11.6. Also broken on firefox on Linux (don't remember flavor of my work desktop).

Also broken according to hashlips discord member.

I guess remix underwent an update in the past 24 hours??

**Comment by licitrasimone** [comment]
I looked good remix too and I confirm the words of the colleague @ryanjsfx2424. 
Broken on firefox and chrome on Linux.

**Comment by CustomSocks** [comment]
I too have just started having this issue.

**Comment by ioedeveloper** [comment]
Fixed by https://github.com/ethereum/remix-project/pull/2023

**Comment by ioedeveloper** [comment]
You can use the work with the fix here before patch release https://remix-alpha.ethereum.org/
