### ISSUE TITLE
Switching file tab clears code in solidity code on previous file tab: observed on Chrome

### ISSUE THREAD

**Issue by KennyDxsale** [ethereum/remix-project#2024]

**Comment by ioedeveloper** [comment]
I can't reproduce this. Can you include a description of how to reproduce this?

**Comment by KennyDxsale** [comment]
To reproduce the issue, I suggest you add in lots of scripts to the IDE.
After certain number of scripts added, the next ones will not save the the solidity script content, which disappears after switching tabs.
