### ISSUE TITLE
Can't connect to existing contract wth ABI

### ISSUE THREAD

**Issue by Lumyo** [ethereum/remix-project#2028]
It is impossible to connect to an existing contract with an `.abi` file with v0.21.0.
It works fine with v0.20.3.

Process :
- Save abi in a file with `.abi` extension in Remix, and have it as active file in Remix
- Go in Deploy & run transactions tab
- Select Injected web 3
- Enter contract address and click `At address` button

I get the error `No compiled contracts found.` in latest version, but it works fine in v0.20.3

**Comment by Pangssu** [comment]
Same here
