### ISSUE TITLE
Bug: Invalid parameters: must provide an Ethereum address.

### ISSUE THREAD

**Issue by DoctorWhoFR** [ethereum/remix-project#2034]
hello, since a few days, I have a bug during the contract testing, when I use the provider inject the first account that is injected works perfectly, but then when I change account from metamask I get each time an error for all other transactions

`"Invalid parameters: must provide an Ethereum address."
`
It's only append for Injected, there is not bug with the virtual VM.
- Only the others accounts bugs, the first account work perfectly.
- It's not important who is the first account, just the other dont work with error "must provide"
- The Transactions replays dont take the new address.

**Comment by DoctorWhoFR** [comment]
I just saw that when i currently copy the second account its always return the first injected account, but diplay the other account in the list.

**Comment by laurenamy** [comment]
Experiencing this as well, only the first account in metamask works for function calls

**Comment by viraj124** [comment]
Guys, I am also facing this issue

**Comment by viraj124** [comment]
@bunsenstraat  can you or the team please look at this?
