### ISSUE TITLE
Error encoding arguments: Error: types/values length mismatch when passing in 2 args but require 4 and 2 empty

### ISSUE THREAD

**Issue by CryptoBeginner** [ethereum/remix-project#2047]
Error encoding arguments: Error: types/values length mismatch (count={"types":2,"values":4}, value={"types":["address","address"],"values":["0xd8b934580fcE35a11B58C6D73aDeE468a2833fa8","0xd9145CCE52D386f254917e481eB44e9943F39138","",""]}, code=INVALID_ARGUMENT, version=abi/5.5.0)

tested on truffle works but not here.

```
// SPDX-License-Identifier: MIT
pragma solidity 0.8.9;

import "@openzeppelin/contracts/token/ERC721/IERC721.sol";
import "./meatToken.sol";

contract MeatFarm {

    uint256[] public tokenIndex;
    mapping(address => uint256[]) public stakingBalance;
    mapping(address => bool) public isStaking;
    mapping(address => uint256) public startTime;
    mapping(address => uint256) public meatBalance;

    string public name = "MeatFarm";

    IERC721 public cdnoNFT;
    MeatToken public meatToken;

    event Stake(address indexed from, uint256 amount);
    event Unstake(address indexed from, uint256 amount);
    event YieldWithdraw(address indexed to, uint256 amount);

    constructor(
        IERC721 _cdnoNFT,        <----------- when put contract address it went error
        MeatToken _meatToken <----------- when put contract address it went error
        ) { 
            cdnoNFT = _cdnoNFT;
            meatToken = _meatToken;
        }
        ```

**Comment by ameerak7** [comment]
im getting the same error on remix- does it work anywhere else?

**Comment by Aniket-Engg** [comment]
@CryptoBeginner This deploys smoothly for me with params: `0xd8b934580fcE35a11B58C6D73aDeE468a2833fa8,0xd9145CCE52D386f254917e481eB44e9943F39138` . Please add what constructor parameter you are providing or If I am missing something here.

**Comment by bizop** [comment]
Running into the same issue, just recently started on a known working contract.

**Comment by ameerak7** [comment]
@Aniket-Engg Can I share my project's gist with you and can you see if it works? Thanks

**Comment by CryptoBeginner** [comment]
![help](https://user-images.githubusercontent.com/37536675/152887333-70c258ec-765c-4776-a10f-ca971c642f53.png)

**Comment by ameerak7** [comment]
some other ppl in the remix ide gitter have the same problem

**Comment by ameerak7** [comment]
Oh yeah @ryestew was talking about it

**Comment by ameerak7** [comment]
@ryestew thanks

**Comment by ameerak7** [comment]
https://gist.github.com/ameerak7/b0865bd78ef326aa264ec90e4db9dd18

Deploy issuer.sol first which should work, then try security. Thats when you get the error.

**Comment by yann300** [comment]
is security https://gist.github.com/ameerak7/b0865bd78ef326aa264ec90e4db9dd18#file-deps-github-ncirocco-ldgr-contracts-ldgrsecurity-sol-L18 ?

**Comment by ameerak7** [comment]
yes

**Comment by yann300** [comment]
could you create a backup (from the home page "Download backup") and send it over.
Thanks

**Comment by ameerak7** [comment]
@yann300 elaborate what you need backed up and how to do it?

**Comment by ameerak7** [comment]
@yann300 https://github.com/ncirocco/ldgr try this

**Comment by ryestew** [comment]
This looks like an error in your code and not in the error that Remix gives.

**Comment by ameerak7** [comment]
this worked fine a week ago- i ran like 30 transactions?

**Comment by ameerak7** [comment]
@ryestew How is the code at fault?

**Comment by yann300** [comment]
@ameerak7 we 'll push a fix in remix-alpha.ethereum.org with the next 30 min, so you can verify if the issue is fixed

**Comment by ameerak7** [comment]
@yann300 Sounds good. I’ve seen some other people on reddit with the same problem so I don’t think it’s a code issue.

**Comment by ameerak7** [comment]
This one is mine but a comment had the same issue. https://www.reddit.com/r/ethdev/comments/smetv1/mismatch_error_in_remix_ide/?utm_source=share&utm_medium=ios_app&utm_name=iossmf

**Comment by yann300** [comment]
could you please check in https://remix-alpha.ethereum.org (please clear the cache) if the issue is fixed, and let me know.
many thanks!

**Comment by StefanKnezevic1** [comment]
Hey I was having the same problem in Remix and I pasted my code in the Remix-Alpha provided and it works great! Thanks so much. When do you think this change will be seen in the regular Remix version?

> u

**Comment by StefanKnezevic1** [comment]
Hey I was having the same problem in Remix and I pasted my code in the Remix-Alpha provided and it works great! Thanks so much. When do you think this change will be seen in the regular Remix version?

**Comment by yann300** [comment]
it should already be live

**Comment by ameerak7** [comment]
@ryestew @yann300 The issue is not actually completely fixed. You can deploy and run on javascript vm, but when it comes to injected web3 it doesn't work in the case of rinkeby.
