### ISSUE TITLE
Hardhat console.log()s don't print with a contract deployed in an Injected Web3 environment

### ISSUE THREAD

**Issue by ZeusExMachina** [ethereum/remix-project#2087]
Hi, I am new to working with solidity and Web3, but I am currently creating an NFT marketplace smart contract. To debug it, I've opted to use the console.log() function imported from "hardhat/console.sol".

However, the console.log() function seems to not print anything with a contract deployed with an InjectedWeb3 environment. On the contrary, the console.log() function does print to the console when the environment is a JavaScript VM.

I'm wondering if this behaviour is intentional. And if it is intentional, would there be any way I can print to the console when using the Injected Web3 environment in a similar fashion to console.log()?

Images of what I'm seeing are shown below:

![6](https://user-images.githubusercontent.com/50428456/154823692-69f99b5d-fa35-491f-a472-7c07cc300d27.PNG)
Console.log() not working with Injected Web3 environment

![5](https://user-images.githubusercontent.com/50428456/154823705-8262955f-bbff-4189-b9a7-764040fd036e.PNG)
Console.log() working with JavaScriptVM environment

**Comment by Aniket-Engg** [comment]
It depends on the Environment to support logging them. Remix detects and decodes the input data to the logging calls, and writes it to the terminal.

**Comment by Aniket-Engg** [comment]
Closing it.
