### ISSUE TITLE
Add support for foundry-style imports

### ISSUE THREAD

**Issue by ImRajdeepB** [ethereum/remix-project#2096]
Is it possible to support foundry-style imports, using custom remappings?
Refer https://onbjerg.github.io/foundry-book/forge/dependencies.html#remapping-dependencies

**Comment by Aniket-Engg** [comment]
Do you mean import for github submodules?

**Comment by ImRajdeepB** [comment]
Yeah

**Comment by Aniket-Engg** [comment]
@ImRajdeepB With recent release, Remix provides a way to define the compiler configuration using a json file. Supporting foundry imports on Remix is more about remappings. You can update the compiler settings in `compiler_config` with these remappings to support standard imports in foundry contract:
```
"remappings":  [
			"ds-test/=lib/forge-std/lib/ds-test/src/",
			"forge-std/=lib/forge-std/src/"
		],
```

**Comment by Aniket-Engg** [comment]
We will try to add those remapping to compiler config if there is a foundry project in workspace
