### ISSUE TITLE
MultiSelect in FE turned on without me knowing it

### ISSUE THREAD

**Issue by ryestew** [ethereum/remix-project#2107]
I was creating a new file and it did not put it in the contracts folder and then as I clicked around the FE, I realized that multiselect was on - but I don't think i had done anyting to turn it on.
<img width="349" alt="image" src="https://user-images.githubusercontent.com/6050001/155746429-3efe1c33-8efd-4049-9eaa-57d46d0ff3a8.png">

**Comment by ryestew** [comment]
when I hit the command key - the multi-select turned off.

**Comment by ioedeveloper** [comment]
I can't reproduce this.

Can you provide steps to reproduce this?

**Comment by Aniket-Engg** [comment]
This happens randomly with me too
