### ISSUE TITLE
Importing ABI files using GitHub or HTTPS results in null characters. Gists work fine.

### ISSUE THREAD

**Issue by dwightjl** [ethereum/remix-project#2135]
I'm trying to generate URLs to easily load ABI examples into Remix. Loading from a Gist seems to work, but for some reason loading ABI files using `#url=` imports a long string of  � characters. Is there a better way to do this or is this a Remix bug?

Gist: https://remix.ethereum.org/#gist=f0ba3fb0bdbfd1589387c05ac904a050

GitHub (github.com): https://remix.ethereum.org/#url=https://github.com/smartcontractkit/documentation/blob/db7fb63efb1fcaf2854a0ac13fb1fcd995369a18/_includes/samples/Keepers/CronUpkeep.abi

GitHub (raw.githubusercontent.com): https://remix.ethereum.org/#url=https://raw.githubusercontent.com/smartcontractkit/documentation/db7fb63efb1fcaf2854a0ac13fb1fcd995369a18/_includes/samples/Keepers/CronUpkeep.abi

HTTPS: https://remix.ethereum.org/#url=https://documentation-git-fork-ritika-b-keepers-cron-chainlinklabs.vercel.app/samples/Keepers/CronUpkeep.abi

I tried some other ABI files from GitHub and they experience the same issue, so I'm pretty sure this isn't an issue with the ABI file itself.

**Comment by Aniket-Engg** [comment]
fixed by https://github.com/ethereum/remix-project/pull/2138
