### ISSUE TITLE
Local storage of the browser is full even though it indicates "0%"

### ISSUE THREAD

**Issue by cjxe** [ethereum/remix-project#2139]
I populated the local storage with a `.exe` file of 90mb and random `.json` files.

![image](https://user-images.githubusercontent.com/35844899/156831145-826a13f5-7387-4f52-beb8-e8d63e236aef.png)

dGit indicates 0% of the storage is used, thus I created a new workspace to clone [some repo](https://github.com/cjxe/solidity-data-structures). Received the following error:

![image](https://user-images.githubusercontent.com/35844899/156831231-d3df0ab4-d410-47b2-ae12-5109ffa0b92c.png)

So I went and deleted the workspace: 

![image](https://user-images.githubusercontent.com/35844899/156831659-d635fbb1-74fc-4a41-99b9-d67221f59e05.png)

and I still can't clone any repo, I receive the same error.

**Browser:** Chrome Version 98.0.4758.102 (Official Build) (64-bit)

That's why I switched to another browser called Brave (Version 1.36.109 Chromium: 99.0.4844.51 (Official Build) (64-bit)). I successfully cloned the repo.

**Comment by bunsenstraat** [comment]
can you check again please? see if the issue is fixed for you.

**Comment by cjxe** [comment]
The issue is fixed in Remix v0.22.1
