### ISSUE TITLE
Optimism deployment improvement.

### ISSUE THREAD

**Issue by ioedeveloper** [ethereum/remix-project#2145]
- [ ] Show better transaction details for optimism deployment. E.g L1 & L2 gas fees.
- [x] Provide "view on etherscan" link.
- [x] use chainlist - update: we should add this link from the homepage with probably a blog post explaining how to use it @LianaHus @ryestew

**Comment by yann300** [comment]
the former would be easy to do. for the former did you intend to show the actual transaction cost (in eth)?
