### ISSUE TITLE
Notify users about new feature 

### ISSUE THREAD

**Issue by Aniket-Engg** [ethereum/remix-project#215]
Every time a new release of Remix IDE come and it has features which affect users, we should show a one time dialog in centre at the time of loading with a list of new features and link of a medium blog explaining them. Afterwards, list can reside in the blue section of Remix IDE Home.

**Comment by LianaHus** [comment]
We have the following options:
On the first load after each release
- to open a ta with information about new features/ release notes.
- to pop up a modal dialog with new features description
or
to create a new badge on home tab which will always show the last release description and will be expanded on first load after release.
