### ISSUE TITLE
the code URL param auto loads & puts focus on the solidity compiler - less useful for starknet

### ISSUE THREAD

**Issue by ryestew** [ethereum/remix-project#2152]
It would be nice that this URL has the starknet plugin active in the side panel and not the solidity compiler:
https://remix.ethereum.org/?#activate=starkNet_compiler&code=IyBEZWNsYXJlIHRoaXMgZmlsZSBhcyBhIFN0YXJrTmV0IGNvbnRyYWN0LgolbGFuZyBzdGFya25ldAoKZnJvbSBzdGFya3dhcmUuY2Fpcm8uY29tbW9uLmNhaXJvX2J1aWx0aW5zIGltcG9ydCBIYXNoQnVpbHRpbgoKIyBEZWZpbmUgYSBzdG9yYWdlIHZhcmlhYmxlLgpAc3RvcmFnZV92YXIKZnVuYyBiYWxhbmNlKCkgLT4gKHJlcyA6IGZlbHQpOgplbmQKCiMgSW5jcmVhc2VzIHRoZSBiYWxhbmNlIGJ5IHRoZSBnaXZlbiBhbW91bnQuCkBleHRlcm5hbApmdW5jIGluY3JlYXNlX2JhbGFuY2V7CiAgICAgICAgc3lzY2FsbF9wdHIgOiBmZWx0KiwgcGVkZXJzZW5fcHRyIDogSGFzaEJ1aWx0aW4qLAogICAgICAgIHJhbmdlX2NoZWNrX3B0cn0oYW1vdW50IDogZmVsdCk6CiAgICBsZXQgKHJlcykgPSBiYWxhbmNlLnJlYWQoKQogICAgYmFsYW5jZS53cml0ZShyZXMgKyBhbW91bnQpCiAgICByZXR1cm4gKCkKZW5kCgojIFJldHVybnMgdGhlIGN1cnJlbnQgYmFsYW5jZS4KQHZpZXcKZnVuYyBnZXRfYmFsYW5jZXsKICAgICAgICBzeXNjYWxsX3B0ciA6IGZlbHQqLCBwZWRlcnNlbl9wdHIgOiBIYXNoQnVpbHRpbiosCiAgICAgICAgcmFuZ2VfY2hlY2tfcHRyfSgpIC0+IChyZXMgOiBmZWx0KToKICAgIGxldCAocmVzKSA9IGJhbGFuY2UucmVhZCgpCiAgICByZXR1cm4gKHJlcykKZW5k&optimize=false&runs=200&evmVersion=null&version=soljson-v0.8.7+commit.e28d00a7.js

**Comment by yann300** [comment]
&& we should not display any modal and the guided tour.

**Comment by bunsenstraat** [comment]
it does this when code is loaded. so that needs changing. 

```
            if (params.code) {
              // if code is given in url we focus on solidity plugin
              this.menuicons.select('solidity')
            } else {
```
