### ISSUE TITLE
Search plugin and highlight

### ISSUE THREAD

**Issue by LianaHus** [ethereum/remix-project#2155]
The Plugin is awsome! I'm happy we have this now.

I have some feedback though
- [x] The plugin has no documentation and meaningful tooltip
- [x] #2248
- [x] "too many results to display. Please narrow your search." looks a problem to me. we can show only half and load rest later or show with scroll.. 
- [x] selection color is very bad.  https://github.com/ethereum/remix-project/pull/2164
![Screenshot from 2022-03-09 12-16-16](https://user-images.githubusercontent.com/9685356/157447621-1001b9fd-eb7c-47f2-9525-23e67f9f60f4.png)

- [x]  I search for "contract" it says too many results. I search for "contract " it shows me the result of "contract"
- [x]  when I click on result it is not scrolling to it when the line is longer than editor's width
- [x]  sometimes it highlights the word and the next one for example "contract" first then "contract Name". EDIT: @LianaHus this is an issue with the highlighting API => https://github.com/ethereum/remix-project/issues/2345

**Comment by bunsenstraat** [comment]
@LianaHus: sometimes it highlights the word and the next one for example "contract" first then "contract Name"
this is always the case when the auto highlighting kicks in.
