### ISSUE TITLE
Gas estimation failed

### ISSUE THREAD

**Issue by CLKJL** [ethereum/remix-project#2157]
I tried to mint 2000 nfts but it shows me this...

Gas estimation failed
Close
Gas estimation errored with the following message (see below). The transaction execution will likely fail. Do you want to force sending?
execution reverted

I did mint 20nfts but seems like it can mint no more than 20nft..??

**Comment by yann300** [comment]
This means that the transaction will revert, and that you should probably not broadcast it.
closing this, please reopen if needed.
