### ISSUE TITLE
Got an error when executed "remixd -s ./exercise/ -u http://localhost:8080"

### ISSUE THREAD

**Issue by rocqina** [ethereum/remix-project#2161]
![image](https://user-images.githubusercontent.com/15166591/157631505-f5a7659c-8ad4-4e91-bc3a-174794fb6afe.png)

**Comment by yann300** [comment]
could you reinstall remixd, we've updated the versioin.

**Comment by Aniket-Engg** [comment]
is it fixed for you @rocqina ?

**Comment by bunsenstraat** [comment]
closing until reopened
