### ISSUE TITLE
debugging 

### ISSUE THREAD

**Issue by ryestew** [ethereum/remix-project#2172]
Try debugging this txn on mainnet: 0x5191d0053c670cd53eafff4c92dcc095823a7dae3238344be72daea2c4b935fa

Click the step over forward button 45 times until you get to step 0128 JUMP - if you click step over forward again - nothing happens and if you click any other type of step button, nothing happens. You can use the slider. But this is not an issue of clicking too fast.  I clicked slowly enough to see the opcodes change and I didn't click again until they changed.

Clearing this problem is easy - just by dragging the slider to the beginning.

If I use the step into button 45x to get to step 0128 JUMP - I can go to the next step and I can go backwards and when I get to the next step I can then use the step over forward button.

**Comment by bunsenstraat** [comment]
not reproducable
