### ISSUE TITLE
DGit Storage calculation

### ISSUE THREAD

**Issue by Aniket-Engg** [ethereum/remix-project#2175]
<img width="812" alt="Screenshot 2022-03-14 at 11 37 56 AM" src="https://user-images.githubusercontent.com/30843294/158115992-e0f0b1a4-066b-4ea5-8cbd-b10b3a19b929.png">

- [ ] It will be great to show realtime storage size in terminal
- [ ] If maximum possible storage is 2GB as shown in terminal, percentage calculation in DGit plugin seems incorrect

**Comment by bunsenstraat** [comment]
fixed
