### ISSUE TITLE
DGit storage issue

### ISSUE THREAD

**Issue by Aniket-Engg** [ethereum/remix-project#2178]
Dgit cannot load more that 1GB
- [ ]  It shows error afterwards
<img width="310" alt="Screenshot 2022-03-14 at 12 16 43 PM" src="https://user-images.githubusercontent.com/30843294/158143924-782454a0-41ba-4370-8fb5-aa6565232656.png">

- [ ] After that it doesn't show files for any workspace

<img width="310" alt="Screenshot 2022-03-14 at 12 16 43 PM" src="https://files.gitter.im/5e451c02d73408ce4fd98526/TBrN/Screenshot-2022-03-14-at-12.45.19-PM.png">

- [ ] Even after refreshing Remix IDE, default workspace is blank and old workspaces are not appearing in the list
<img width="567" alt="Screenshot 2022-03-14 at 2 58 07 PM" src="https://user-images.githubusercontent.com/30843294/158144291-5b019151-4eae-48bb-bf75-d0572f031b3d.png">

**Comment by bunsenstraat** [comment]
seems to me also localstorage was also full probably

**Comment by bunsenstraat** [comment]
closing this for now ok?
