### ISSUE TITLE
Injected Web3 does not use the parameter "Gas limit"

### ISSUE THREAD

**Issue by zhek** [ethereum/remix-project#221]
You need to do that when choosing "Injected Web3" you need to make the parameter "Gas limit" not active.  For example, I sent a contract to the network with the parameter "Gas limit" 3,000,000, but in reality 3,164,646 were used.

Now this parameter is misleading.

**Comment by Aniket-Engg** [comment]
Now there is option to choose between estimated gas or defining custom gas
