### ISSUE TITLE
Tabs: there is some confusion between tabs

### ISSUE THREAD

**Issue by ryestew** [ethereum/remix-project#2212]
Somehow I have this set of tabs:
<img width="719" alt="image" src="https://user-images.githubusercontent.com/6050001/158925520-b8d20708-70c1-4ad7-93ca-bd169c237958.png">

scripts/mocha-scripts.js & mocha-scripts.js
If I try to close scripts/mocha-scripts.js then mocha-scripts.js closes but the tab I clicked on does not close. 
But then I don't know how I got 2 tabs open for what seems like the same file.

In the FE - there is no file called mocha-scripts.js in the root.  It is only in the scripts folder.
Also I cannot close both files.

I'm having trouble replicating this problem.

**Comment by yann300** [comment]
tagging @ioedeveloper as David did some changes in it recently.

**Comment by yann300** [comment]
@ioedeveloper If you have any idea what can cause this..
@ryestew this wasn't existing before? how did  you come to this situation?

**Comment by ioedeveloper** [comment]
I fixed this behaviour in this PR https://github.com/ethereum/remix-project/pull/2193 . Can you reproduce this with latest changes?

**Comment by yann300** [comment]
@ryestew could you try it again please?

**Comment by ryestew** [comment]
I am not getting this anymore - so I assume this was fixed.
