### ISSUE TITLE
File Explorer: horizontal scroll

### ISSUE THREAD

**Issue by LianaHus** [ethereum/remix-project#2216]
after several nested folders, one can't see folders anymore

![Screenshot from 2022-03-21 10-40-49](https://user-images.githubusercontent.com/9685356/159236671-f58ec017-6dd7-41e9-8b15-6213c2a5b57c.png)
.

**Comment by Astilen** [comment]
Yea, to be more precise, the folders were always there, the problem occurs because they automatically open. In addition, writing code that alters these files somehow switches focus from writing code to the explorer window. Thanks!
