### ISSUE TITLE
search results without a page in docs

### ISSUE THREAD

**Issue by Sunghee2** [ethereum/remix-project#222]
When I search 'current' and click on the first one in docs, I get results without [a page](https://remix-ide.readthedocs.io/en/stable/best-practices.html).
I think this problem is caused by searching the markdown file outside the docs folder.
Because `meeting.md`, `release-process.md` file etc. are searched.

**Comment by ryestew** [comment]
Please add more details.  We will close this for now - but will re-open it if this is still an issue.
