### ISSUE TITLE
Loading a contract at an address from ABI was broken in a recent update

### ISSUE THREAD

**Issue by froggiedev** [ethereum/remix-project#2220]
Saving an ABI file with extension .abi now gives the error:

```
ParserError: Expected pragma, import directive or contract/interface/library/struct/enum/constant/function definition.
--> abis/ProxyManager.abi:1:1:
|
1 | [
| ^
```

when it used to correctly compile.

**Comment by Aniket-Engg** [comment]
<img width="813" alt="Screenshot 2022-03-22 at 11 38 13 AM" src="https://user-images.githubusercontent.com/30843294/159418462-7d93d1cf-e4fc-4b5e-af74-81929f54d373.png">

@froggiedev This works fine for me. Can you add exact steps to reproduce?

**Comment by kylebakerio** [comment]
When I paste something into "At Address" box, nothing happens, and I don't get any button to 'deploy' it, when connected to e.g. rinkeby. not sure if related? unclear if the UI should do something, if some button should pop up, or what, but I just paste a contract address, and nothing...

**Comment by Aniket-Engg** [comment]
After pasting the address in box, you need to click on `At Address` to load the deployed contract UI
