### ISSUE TITLE
Help Please for running remix locally!

### ISSUE THREAD

**Issue by rayeaster** [ethereum/remix-project#2222]
I run an old version of remix locally from https://www.npmjs.com/package/remix-ide and it worked well until recently. Seems some resource is missing when loading the page

![image](https://user-images.githubusercontent.com/1487283/159410491-b3a15cbe-7a8c-4933-a200-6b766e449f15.png)

May I ask how to fix this issue?

**Comment by Aniket-Engg** [comment]
Remix is no more released as NPM module. You can use the Remix Desktop application: https://github.com/ethereum/remix-desktop/releases
To setup it locally see: https://github.com/ethereum/remix-project#setup
