### ISSUE TITLE
Hardhat config not picked up if TypeScript (hardhat.config.ts) 

### ISSUE THREAD

**Issue by kenvogg** [ethereum/remix-project#2237]
If you set up Remixd + Hardhat, it only works properly if a file is found in your shared folder called `hardhat.config.js`. In many of the hardhat projects, the config is using TypeScript, which will be `hardhat.config.ts`. 

To reproduce, simply have the `.ts` verison isntead, and when doing `remixd -s ./ -u https://remix.ethereum.org` you will not see `hardhat is listening on 127.0.0.1:65522` appear.

**Comment by Aniket-Engg** [comment]
This has been implement by https://github.com/ethereum/remix-project/pull/2213 and will be out in our next release. Till then you can use it with remix-alpha.ethereum.org

**Comment by Aniket-Engg** [comment]
fixed by https://github.com/ethereum/remix-project/pull/2213
