### ISSUE TITLE
Remix-ide defaults to wrong environment when connected to injected web3 and a reload is initiated.

### ISSUE THREAD

**Issue by ioedeveloper** [ethereum/remix-project#2250]
<img width="296" alt="Screen Shot 2022-03-29 at 11 47 37" src="https://user-images.githubusercontent.com/23282059/160595134-0a9e112e-9fbe-41e9-a1c9-1149d9e9f6ed.png">

**Comment by yann300** [comment]
fixed by https://github.com/ethereum/remix-project/pull/2292
