### ISSUE TITLE
Hardhat: cannot send transaction that fails

### ISSUE THREAD

**Issue by yzhou61** [ethereum/remix-project#2254]
Using the hardhat plugin, I used to be able to send a transaction that fails on chain. The gas estimate would tell me that the transaction is likely to fail, ask me to confirm, and then proceed to the transaction sending page.

Starting with v0.21.0, I can no longer do that. When the gas estimation fails, the provider automatically jumps back to javascript, causing the subsequent transaction send to fail with "invalid address".

**Comment by Aniket-Engg** [comment]
@yzhou61 Can you please add steps to reproduce and related screenshot to understand the issue?

**Comment by yzhou61** [comment]
@Aniket-Engg sure thing. Steps to repro:

```
git checkout v0.22.2
npm install
# current: { node: 'v16.14.2', npm: '8.5.0' }
npm run build
npm run serve
```
Then in Remix:
- Enable hardhat provider plugin
- Launch a local hardhat node
- Switch the Remix environment to hardhat and connect to the node
- Deploy a contract
- Send a tx that fails

Here's what I see. The following 3 images are from the same screenshot.
![image](https://user-images.githubusercontent.com/1254973/162587250-ad60f131-e766-49cc-be40-864bcaccf367.png)
![image](https://user-images.githubusercontent.com/1254973/162587541-29773a36-3099-4441-bbfe-69f4afa64ec0.png)
![image](https://user-images.githubusercontent.com/1254973/162587271-cb99d9e1-6015-46aa-829e-1ab4fa46b7a9.png)

As you can see, as soon as the "gas estimation failed" dialog pops up, the environment switches back to JS.

Now if I hit the "Send Transaction" button, the console shows the following:
```
transact to Test.(fallback) errored: Invalid account selected
```

In v0.20.3, when the gas estimation fails, the environment doesn't automatically switch back the JS, allowing me to send the tx even if it's going to fail.

Thanks for looking into this.
