### ISSUE TITLE
FE add a display name option for ipfs/swarm file

### ISSUE THREAD

**Issue by LianaHus** [ethereum/remix-project#226]
when yuou have >1 files imported from ipfs or swarm you see the list of hashes. would be nie to be able to name them locally
![afterparty](https://user-images.githubusercontent.com/9685356/65411308-d231a500-ddec-11e9-84d2-8d7581b04727.png)

**Comment by joeizang** [comment]
Can there be a little more explanation about this nice to have feature?

**Comment by Aniket-Engg** [comment]
> Can there be a little more explanation about this nice to have feature?

cc: @LianaHus
