### ISSUE TITLE
Remix-Desktop no longer working after Remix-Project release v0.23

### ISSUE THREAD

**Issue by screencredits** [ethereum/remix-project#2309]
Desktop Remix IDE (https://github.com/ethereum/remix-desktop) will no longer launch - or more specifically, launches a white screen - since the release of v0.23. Console errors are:

![fetch](https://user-images.githubusercontent.com/103757720/163581789-84045b89-7359-4b0f-ad41-91d1d11d0a73.png)

Possible breaking changes: #2274

**Comment by yann300** [comment]
this is fiexed now, thanks for the report.
