### ISSUE TITLE
pop() or delete error: "The transaction ran out of gas"

### ISSUE THREAD

**Issue by Ilario17** [ethereum/remix-project#2310]
The pop and delete methods always give "VM error: out of gas.", 

The code is very very simple, it's just a test:

```
contract Arrays {
    uint [] public myArray;

   function pushToArray(uint number) public {
        myArray.push(number);
    }

    function popArray() public {
        myArray.pop();
    }
}
```

I tried to increase the gas limit, but nothing changes.

The Remix version is **0.23.0**

**Comment by bytrislasis** [comment]
I get the same error with very simple operations

**Comment by Charitha2588** [comment]
did you find any fix for this?
