### ISSUE TITLE
Can not run a script using metamask.

### ISSUE THREAD

**Issue by Skyge** [ethereum/remix-project#2328]
Just trying to run scripts in the default workspace to deploy contracts, but nothing happened, and the error like following:

<img width="1393" alt="image" src="https://user-images.githubusercontent.com/27282380/165052033-20f9b202-7a95-40cc-9b8c-4013ca43e07d.png">

**Comment by Aniket-Engg** [comment]
Hello @Skyge , with the new fix, it takes some time to get the transaction minted before showing the deployed instance in the `Deploy & Run Transactions`. It seems like you have run the script again before first run is completed.

Can you please reload the IDE and try it again?

**Comment by Aniket-Engg** [comment]
Ah i checked. It seems an issue with IPFS node. I am looking on it.

**Comment by athamefinance** [comment]
Any update on a fix for this?

**Comment by athamefinance** [comment]
after a hard refresh then trying to run a script I receive 
![image](https://user-images.githubusercontent.com/102305702/165139092-25ad83fa-a256-43c7-9d75-2ed49d771724.png)
2nd try
![image](https://user-images.githubusercontent.com/102305702/165139182-50f68891-1fc8-4955-a918-115b7886f350.png)

**Comment by Aniket-Engg** [comment]
Fix is still in progress. We will update here once done.

**Comment by Skyge** [comment]
Okay, let me have a check now.

**Comment by Skyge** [comment]
@Aniket-Engg  It works now, although there is some errors when refresh the whole page like following:

<img width="790" alt="image" src="https://user-images.githubusercontent.com/27282380/165304610-7af157ed-8bb9-429b-8650-99646daea0f2.png">

**Comment by Aniket-Engg** [comment]
Yes, they can be ignored for now. We will look into them sometime soon.
