### ISSUE TITLE
Plugin FLATTENER: 502 Bad Gateway

### ISSUE THREAD

**Issue by kordenv** [ethereum/remix-project#2329]
Can't add FLATTENER plugin
gives an error message:
502 Bad Gateway
The server returned an invalid or incomplete response.

**Comment by Aniket-Engg** [comment]
Hello @kordenv , Thanks for raising this. I can reproduce this. There should be something wrong on the IPFS side. We will look into this.

**Comment by Aniket-Engg** [comment]
@kordenv Can you check it now? It should be working fine.

**Comment by kordenv** [comment]
> @kordenv Can you check it now? It should be working fine.

Everything worked :) Thank you so much
