### ISSUE TITLE
Matomo modal closing by itself

### ISSUE THREAD

**Issue by ryestew** [ethereum/remix-project#2348]
The matomo modal closes by itself in less than 1 second.  Check this on an incognito window.

**Comment by bunsenstraat** [comment]
https://github.com/ethereum/remix-project/blob/f40b80927f49c78e30ea52957d7e096dcd313bde/libs/remix-ui/workspace/src/lib/components/file-explorer.tsx#L81

It focuses on something in the FE
which triggers a blur action on modals
so hides them
