### ISSUE TITLE
Add an option for `via-ir` for compiling solidity using the new codegen

### ISSUE THREAD

**Issue by hrkrshnn** [ethereum/remix-project#2350]
From https://blog.soliditylang.org/2022/03/16/solidity-0.8.13-release-announcement/#yul-ir-pipeline-production-ready

> You can enable the new pipeline using the --via-ir commandline switch or by setting settings.viaIR to true in Standard JSON input (i.e. at the same level where you would have the optimizer key).

**Comment by paulrberg** [comment]
Note that this can currently be done by passing a configuration file (basically, by using standard-json):

```json
{
  "viaIR": true
}
```

<img width="301" alt="Screenshot 2022-12-27 at 3 55 05 PM" src="https://user-images.githubusercontent.com/8782666/209676781-a33fd86f-70d6-429c-b150-24964cf4fa01.png">
