### ISSUE TITLE
Injected web3 provider, say MetaMask if it's MetaMask

### ISSUE THREAD

**Issue by fulldecent** [ethereum/remix-project#2393]
_(This is from the our Remix user study today.)_

In the deploy pane, if the injected web3 provide is MetaMask (and often it is), you can detect this. Remix can show this as

> MetaMask (web browser provider)

or otherwise use the more generic:

> Web browser provider (EIP-1193)

---

This UI wording in Remix can be aligned to match the actual specification that is used, specifically https://eips.ethereum.org/EIPS/eip-1193

<img width="1334" alt="Screen Shot 2022-05-12 at 16 24 32" src="https://user-images.githubusercontent.com/382183/168162571-f6291de4-0172-4a24-83e3-1493eb02afe5.png">

**Comment by Aniket-Engg** [comment]
closed by #2549
