### ISSUE TITLE
Environment section of Deploy & Run

### ISSUE THREAD

**Issue by ryestew** [ethereum/remix-project#2431]
JSVM) => Local VM 
Injected Web3 => Injected provider - metamask  - get the metamask from the window object (window.injectedweb3 )
Web3 provider - its officially is JSON RPC -  how about calling it External Provider

If this dropdown is not a browser native dropdown, but a custom one - then we could put icons in there - so it would be easy to identify if its the one with Metamask.  This would require a good bit of work.  In the right scenario, it could be worth it.

**Comment by LianaHus** [comment]
Use suggestion from [#2394](https://github.com/ethereum/remix-project/issues/2394)
