### ISSUE TITLE
update remixd to uppercase

### ISSUE THREAD

**Issue by ryestew** [ethereum/remix-project#2454]
liana: y
andrew: y
rob: y
Aniket: ?
David: y
Filip: u
Yann: N

**Comment by Aniket-Engg** [comment]
I would like to go with `RemixD` or `Remixd`.

> Access your local file system from Remix IDE using [Remixd NPM package](https://www.npmjs.com/package/@remix-project/remixd).

I think we should define remixd as 'access your project from local device to browser' rather than using the word file system

**Comment by Draxgee** [comment]
Am sorry how can I do it
