### ISSUE TITLE
Unable to select compiler

### ISSUE THREAD

**Issue by fulldecent** [ethereum/remix-project#2485]
Clicking COMPILE resets the selected compiler.

Tested on current Safari and Edge browsers to same effect.
![out](https://user-images.githubusercontent.com/382183/171917904-85cded7b-f941-4509-a93c-9006d8cfe07e.gif)

**Comment by Aniket-Engg** [comment]
Hi @fulldecent , It happens because Remix sets the compiler version to the best suited version according to the pragma from file to be compiled

**Comment by fulldecent** [comment]
Got it, thank you.

That is good to switch. But confusing.

I'll leave it up to the UI team if this situation deserves some popup warning.

**Comment by Aniket-Engg** [comment]
cc: @LianaHus

**Comment by ryestew** [comment]
So the user manually sets a compiler version that does not match the pragma.  When Remix automatically selects a compiler that fits the pragma, should Remix put out a warning to the user that it is overriding their choice?

**Comment by Aniket-Engg** [comment]
It can be an info

**Comment by cameel** [comment]
I just ran into this and came here to report it as a bug. I have to say that this is really confusing and without any indication in the UI looks like a weird bug. From the bot messages here and the fact that this is closed I assume that it's already fixed and just not yet deployed?

**Comment by Aniket-Engg** [comment]
thanks for your report @cameel
