### ISSUE TITLE
Cannot edit in read-only editor

### ISSUE THREAD

**Issue by ricothagod** [ethereum/remix-project#2486]
Hi, I have Remix IDE hosted on a server and when I try to edit any file, it says:

**Cannot edit in read-only editor**

![Cannot-edit](https://user-images.githubusercontent.com/106879016/172013318-7a1b7732-a646-4969-85bc-e38edd89f67b.png)

Any help would be much appreciated

**Comment by Aniket-Engg** [comment]
Hello @ricothagod , Can you pull the latest code and try again?

**Comment by Aniket-Engg** [comment]
@ricothagod is it working fine for you now?

**Comment by talha-rafique** [comment]
try to close the file and then re-open it. 
will fix your issue Definately.

**Comment by Aniket-Engg** [comment]
okay, thanks.

**Comment by kostia-lev** [comment]
Please fix it! I created new file and could not figure out why it is in read only mode on remix website
