### ISSUE TITLE
remix-tests JavaScript heap out of memory. And remix web client often crash.

### ISSUE THREAD

**Issue by iranran** [ethereum/remix-project#2500]
When I run remix-tests , out of memory happens, I have set "NODE_OPTIONS=--max_old_space_size=10240"

And in remix web client often crash too. My contract a little complicated, code more than 1200 lines 

remix-tests -c 0.6.9 -v 5 tests/unit/A_test.sol

	👁	:: Running remix-tests - Unit testing for solidity ::	👁

[14:33:32] info: verbosity level set to silly
[14:33:32] info: Compiler version set to 0.6.9. Latest version is 0.8.14
Loading remote solc version v0.6.9+commit.3e3065ac ...
'creation of library remix_tests.sol:Assert pending...'

	◼  A_test
	✓  Check input add
	✓  Check input add2
	✓  Check input add3

<--- Last few GCs --->

[92306:0x130008000]    58188 ms: Scavenge 10063.7 (10254.2) -> 10062.8 (10275.2) MB, 26.7 / 0.0 ms  (average mu = 0.643, current mu = 0.496) allocation failure
[92306:0x130008000]    63108 ms: Mark-sweep 10077.1 (10275.2) -> 10071.8 (10290.7) MB, 4915.4 / 0.0 ms  (average mu = 0.395, current mu = 0.029) allocation failure scavenge might not succeed

<--- JS stacktrace --->

FATAL ERROR: Reached heap limit Allocation failed - JavaScript heap out of memory
 1: 0x1004082dc node::Abort() [/Users/wxlo/.nvm/versions/node/v16.15.1/bin/node]
 2: 0x100408464 node::errors::TryCatchScope::~TryCatchScope() [/Users/wxlo/.nvm/versions/node/v16.15.1/bin/node]
 3: 0x100557b90 v8::Utils::ReportOOMFailure(v8::internal::Isolate*, char const*, bool) [/Users/wxlo/.nvm/versions/node/v16.15.1/bin/node]
 4: 0x100557b24 v8::internal::V8::FatalProcessOutOfMemory(v8::internal::Isolate*, char const*, bool) [/Users/wxlo/.nvm/versions/node/v16.15.1/bin/node]
 5: 0x1006db23c v8::internal::Heap::GarbageCollectionReasonToString(v8::internal::GarbageCollectionReason) [/Users/wxlo/.nvm/versions/node/v16.15.1/bin/node]
 6: 0x1006d9d5c v8::internal::Heap::CollectGarbage(v8::internal::AllocationSpace, v8::internal::GarbageCollectionReason, v8::GCCallbackFlags) [/Users/wxlo/.nvm/versions/node/v16.15.1/bin/node]
 7: 0x1006e50a4 v8::internal::Heap::AllocateRawWithLightRetrySlowPath(int, v8::internal::AllocationType, v8::internal::AllocationOrigin, v8::internal::AllocationAlignment) [/Users/wxlo/.nvm/versions/node/v16.15.1/bin/node]
 8: 0x1006e5138 v8::internal::Heap::AllocateRawWithRetryOrFailSlowPath(int, v8::internal::AllocationType, v8::internal::AllocationOrigin, v8::internal::AllocationAlignment) [/Users/wxlo/.nvm/versions/node/v16.15.1/bin/node]
 9: 0x1006b7fcc v8::internal::Factory::NewFillerObject(int, bool, v8::internal::AllocationType, v8::internal::AllocationOrigin) [/Users/wxlo/.nvm/versions/node/v16.15.1/bin/node]
10: 0x1009f00d0 v8::internal::Runtime_AllocateInYoungGeneration(int, unsigned long*, v8::internal::Isolate*) [/Users/wxlo/.nvm/versions/node/v16.15.1/bin/node]
11: 0x100d0474c Builtins_CEntry_Return1_DontSaveFPRegs_ArgvOnStack_NoBuiltinExit [/Users/wxlo/.nvm/versions/node/v16.15.1/bin/node]
12: 0x100d057b8 Builtins_StringAdd_CheckNone [/Users/wxlo/.nvm/versions/node/v16.15.1/bin/node]

**Comment by ryestew** [comment]
could be related to: https://github.com/ethereum/remix-project/issues/2378

**Comment by Aniket-Engg** [comment]
@iranran Have you got it fixed?
