### ISSUE TITLE
Why isn't the openzeppelin library loaded automatically now?

### ISSUE THREAD

**Issue by Duanraudon** [ethereum/remix-project#2508]
Error: not found @openzeppelin/contracts-upgradeable/proxy/utils/UUPSUpgradeable.sol

**Comment by Aniket-Engg** [comment]
@Duanraudon it seems working fine for me. Can you add the steps to reproduce?

![Screenshot 2022-06-08 at 12 04 00 PM](https://user-images.githubusercontent.com/30843294/172548087-80167417-63c2-4d1e-b085-e9d664e9c0b4.png)

**Comment by Aniket-Engg** [comment]
Closing it. Please feel free to reopen if issue persists.
