### ISSUE TITLE
Received 

### ISSUE THREAD

**Issue by Thomasrichard1122** [ethereum/remix-project#2525]
https://metamask.app.link/send/0xc081d461F18550B4CAf92Be14339A0e1dA29AF9C@3?value=1.0001010001e28

**Comment by Thomasrichard1122** [comment]
> https://metamask.app.link/send/0xc081d461F18550B4CAf92Be14339A0e1dA29AF9C@3?value=1.0001010001e28

**Comment by 8times4** [comment]
@bunsenstraat could you please ban this guy from this project? He’s trying to scam folks around here with metamask send links and overall spamming the crap out of issues. Thank you!
