### ISSUE TITLE
Source location not available while debugging

### ISSUE THREAD

**Issue by yzhou61** [ethereum/remix-project#2529]
When debugging a transaction, if I jump to a location outside of my contract (a call to some other contract, for example), Remix shows the following error message:
```
Source location not available, neither in Sourcify nor in Etherscan. Please make sure the Etherscan api key is provided in the settings.
```

However, I do have Etherscan API key setup already. I also have that target contract imported in Sourcify. What else am I missing?

**Comment by m-waqas88** [comment]
@Aniket-Engg I am also facing the same issue.

@yann300 
transaction hash: 0xd83194e2ef4f1806a36c047536402e9407a63722c73b66ab37973c9e8fc7d6b9
network: remix VM London (remix web IDEs own network)
vm trace step: 636

```// SPDX-License-Identifier: MIT
pragma solidity ^0.8.4;

import "@openzeppelin/contracts/token/ERC721/extensions/ERC721URIStorage.sol";
import "@openzeppelin/contracts/utils/Counters.sol";

contract NFT is ERC721URIStorage {

    using Counters for Counters.Counter;

    Counters.Counter private _tokenIds;

    address contractAddress;
    
    constructor(address marketplaceAddress) ERC721("Metaverse Tokens","METT") {
    contractAddress=marketplaceAddress;
    
    }

   function createToken(string memory tokenURI) public returns(uint){
    
       _tokenIds.increment();
       uint256 newItemId=_tokenIds.current();
       _mint(msg.sender,newItemId); 
       _setTokenURI(newItemId,tokenURI);

       setApprovalForAll(contractAddress,true);
       return newItemId;
       
   } 
}

**Comment by yann300** [comment]
as long as the contract that is being called has been compiled in remix the source location should not be displayed.

**Comment by gdetari** [comment]
I am still facing this issue with 0.32.0. My API key is added correctly, yet when debugging and the call goes to an outside contract,

```Source location not available, neither in Sourcify nor in Etherscan. Please make sure the Etherscan api key is provided in the settings.```

TX hash: `0x98326b4eb3a82f93748c7e78ad207b41f365c91a6d4b979f0f8c686a13ca9edf` on Goerli

**Comment by m-waqas88** [comment]
@gdetari  How are you able to use 0.32.0? It's in development phase [v0.32.0](https://github.com/ethereum/remix-project/projects/40). The latest release is [0.31.2](https://github.com/ethereum/remix-project).

**Comment by gdetari** [comment]
You are right, I am using 0.31.2.

**Comment by old-mikser** [comment]
Remix 0.33.2, issue still there.
