### ISSUE TITLE
Can't move a file to another folder???

### ISSUE THREAD

**Issue by php4fan** [ethereum/remix-project#2533]
In Remix, in the File Explorer, I accidentally created a file in the wrong folder, so I wanted to move it.

I tried dragging and dropping and that doesn't work (when you click and try to drag, it doesn't drag it).

I right-clicked and there's no "move" option in the context menu.

The only way I could find was to copy it, which is ridiculous, because you need to:
- right-click, Copy
- right-click Paste into a different folder. This creates a copy with a different name than the original (with "Copy of" prepended or "copy" appended, I forget)
- right-click Rename it to restore the original name
- right-click delete the original file.

Four actions to do what one would normally do with a single drag-n-drop operation on a normal file explorer.

**Comment by vasuvanka** [comment]
i too faced same issue

**Comment by 6str** [comment]
yes. pls add the ability to move files. basic file reorganisation and housekeeping is too painful without it
