### ISSUE TITLE
Deploy & Run: x icon to the right of blank contract select box has no use

### ISSUE THREAD

**Issue by ryestew** [ethereum/remix-project#2543]
When no compiled contract -the contract select box is not needed and should be removed
<img width="302" alt="image" src="https://user-images.githubusercontent.com/6050001/174137615-26cebb60-5145-42ab-bc8c-418fe0c4f402.png">

**Comment by LianaHus** [comment]
this one duplicates https://github.com/ethereum/remix-project/issues/2544

**Comment by Aniket-Engg** [comment]
@ioedeveloper suggested that this should be taken care once [Proxy PR](https://github.com/ethereum/remix-project/pull/2260) is merged
