### ISSUE TITLE
Compiler tab: show "compilation details" in a tab

### ISSUE THREAD

**Issue by LianaHus** [ethereum/remix-project#259]
remove empty lines to make vertical scroll less

**Comment by joeizang** [comment]
![image](https://github.com/ethereum/remix-project/assets/4255962/69c25811-265a-46b3-8671-57ff9cd30a63)

I am thinking of grouping these into tab headings @LianaHus @ryestew @vermouth22. Can I have suggestions of what the groupings should be?

**Comment by joeizang** [comment]
![compilerui redesign-smaller](https://github.com/ethereum/remix-project/assets/4255962/cedab3c1-4d4c-4b2a-bfea-bf62031fe7a3)

I did some thinking about the ui on excalidraw. Please your feedback is highly valued. @ryestew @vermouth22 @LianaHus

**Comment by ryestew** [comment]
Suggestion: make the modal a main panel plugin - so the compilation details appear in a main panel tab.  Lots of real estate to use.

**Comment by Aniket-Engg** [comment]
fixed by #4153
