### ISSUE TITLE
Support Goerli contract verification

### ISSUE THREAD

**Issue by fulldecent** [ethereum/remix-project#2610]
Goerli is the only test network which Ethereum has committed to maintaining long term. Source: https://ethereum.org/en/developers/docs/networks/

I'm hoping for first-class support of publishing contract source code and verifying on Etherscan. If this is an issue from Etherscan's end, please email them using your Ethereum.org email address and tell them to fix it and keep this issue open as a tracker.

<img width="1624" alt="Screen Shot 2022-07-11 at 23 55 55" src="https://user-images.githubusercontent.com/382183/178405477-92e23e68-4b9a-421a-a4b0-e4dac673359b.png">

**Comment by yann300** [comment]
Could you try again please, this should work. probably the etherscan api was unreachable at that moment..

**Comment by Aniket-Engg** [comment]
https://github.com/ethereum/remix-project/issues/2674 too seems related

**Comment by fulldecent** [comment]
Thank you, updated issue at https://github.com/ethereum/remix-project/issues/2674 to only fix the error wording

**Comment by ashvds** [comment]
@fulldecent  @yann300 , After the Goerli merge, it seems like cloned contracts are no longer being recognised as contracts AT ALL by etherscan, is that part of this?
