### ISSUE TITLE
Plugin info issues

### ISSUE THREAD

**Issue by Aniket-Engg** [ethereum/remix-project#2611]
- [x] Info bar is expanded for all plugins if expanded for one plugin
- [x] documentation appears at two places: one plugin right-top and inside plugin info
- [x] There is UI difference in UDApp plugin
![Screenshot 2022-07-12 at 12 57 29 PM](https://user-images.githubusercontent.com/30843294/178434528-339ab936-e6cb-4672-9b43-87d3fb7cf338.png)

- [ ] There is no info for search plugin. In such case, we should show: `No plugin info available.`
![Screenshot 2022-07-12 at 12 59 38 PM](https://user-images.githubusercontent.com/30843294/178434723-650ecfcd-b8e7-492e-9e20-7e6668ac439e.png)

- [x] Add description for all plugins managed by Remix
- [x] Show verified green icon for all plugins managed by Remix

**Comment by LianaHus** [comment]
No plugin info available"
