### ISSUE TITLE
Upgrade with Proxy error reporting

### ISSUE THREAD

**Issue by ryestew** [ethereum/remix-project#2616]
When using
<img width="297" alt="image" src="https://user-images.githubusercontent.com/6050001/178507295-d431282c-483e-413d-b3d1-fe86cb4fcbe5.png">

or
<img width="293" alt="image" src="https://user-images.githubusercontent.com/6050001/178507342-63389179-e456-4546-aaef-d85accad1b9e.png">

and the address is not that of the proxy 1967 contract, there is no error reported in Remix.

**Comment by Aniket-Engg** [comment]
@ioedeveloper do you think this can be done?
