### ISSUE TITLE
Expanding method view on Udapp add quotes for integer

### ISSUE THREAD

**Issue by Aniket-Engg** [ethereum/remix-project#2617]
![Screenshot 2022-07-12 at 7 45 58 PM](https://user-images.githubusercontent.com/30843294/178511539-361ebadb-043b-4458-878b-7774fdef1aeb.png)

![Screenshot 2022-07-12 at 7 46 06 PM](https://user-images.githubusercontent.com/30843294/178511578-b6113f02-8a66-4f6f-9265-2862af07bdff.png)

**Comment by Marenz** [comment]
Adding an other example that shows that it only partially adds a quote:
![image](https://user-images.githubusercontent.com/424752/178511931-00beebce-a791-406b-a2f5-6f458a37e2d3.png)
![image](https://user-images.githubusercontent.com/424752/178511942-10b82f8a-922a-4a59-90c3-92c60e242ff1.png)

**Comment by yann300** [comment]
We need to add double quotes cause we don't know if the number will be supported by js runtime.
I fixed the bug by adding double quoted to all the numbers
