### ISSUE TITLE
Clone error message

### ISSUE THREAD

**Issue by ryestew** [ethereum/remix-project#2623]
Currently variations on this:  (remove low level error messages)
Title Clone Git Repository
Body:An error occured: UrlParseError: Cannot parse remote URL: "github.com/ryestew"

It should be (2 Rs in occurred)
Body: An error occurred: Please check that you have the correct URL for the repo.  If the repo is private, you need to add your github credentials (with the valid token permissions) in Settings plugin. 

If @ioedeveloper can provide us with the full list of errors types, then we can get more specific.  Or we can put more precise advice for 404 & 401 errors and the rest or the error types get a general error message.

**Comment by Aniket-Engg** [comment]
Error message updated in #2626
