### ISSUE TITLE
[remixd] Crash with no message when other program is already using port 65522

### ISSUE THREAD

**Issue by ss22219** [ethereum/remix-project#2655]
TypeError: Cannot read properties of null (reading 'setWebSocket')
    at /Users/gool/.config/yarn/global/node_modules/@remix-project/remixd/src/bin/remixd.js:106:36
    at Server.<anonymous> (/Users/gool/.config/yarn/global/node_modules/@remix-project/remixd/src/websocket.js:29:17)
    at Server.emit (node:events:539:35)
    at emitErrorNT (node:net:1407:8)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)

https://github.com/ethereum/remix-project/blob/a03b35efec210f1190bfabed6aabee29d6f8e6b0/libs/remixd/src/bin/remixd.ts#L109

**Comment by Aniket-Engg** [comment]
To me, it shows proper error:

![Screenshot 2022-08-16 at 5 59 22 PM](https://user-images.githubusercontent.com/30843294/184879831-e6cdcfbb-c592-4e6f-a6e9-fdc7ee77b1f3.png)

Can you add the remixd version and command you are using?

**Comment by Aniket-Engg** [comment]
Closing it. Please feel free to reopen if issue persists.
