### ISSUE TITLE
Encode input arguments does not encode input arguments

### ISSUE THREAD

**Issue by fulldecent** [ethereum/remix-project#2673]
When deploying a contract there is a button to copy encoded input arguments.

However when using this button, it does not give you the encoded inputs, it gives you the entire contract deployment.

https://user-images.githubusercontent.com/382183/180284390-1c9b5881-30de-4196-ae12-95d47a629458.mov

FYI, you need to be able to get the encoded input arguments in order to use the verify on Etherscan module in Remix.

**Comment by Aniket-Engg** [comment]
Yes, for now, it gives bytecode appended with encoded constructor arguments. We can still discuss it.

**Comment by fulldecent** [comment]
Cool, thank you
