### ISSUE TITLE
Cannot validate contracts on Rinkeby

### ISSUE THREAD

**Issue by fulldecent** [ethereum/remix-project#2674]
<img width="482" alt="Screen Shot 2022-07-21 at 14 23 49" src="https://user-images.githubusercontent.com/382183/180286455-20a67baa-e911-4c2d-8b41-c1ce61af9c15.png">

Please make this work on ALL test networks. And please open source this plugin.

Also, please update the error message to more clearly explain the situation (is the network unavailable? which specific call to which API failed?)

**Comment by fulldecent** [comment]
@Aniket-Engg Still is not working for me with Goerl.

It is stuck pending in queue for 5+ hours so far.

I can't rule out that this problem may be from Etherscan.



![Screen Shot 2022-08-08 at 23 29 25](https://user-images.githubusercontent.com/382183/183557908-e9fe1c7d-053a-4c73-9072-0cbb81932526.png)
i

**Comment by Aniket-Engg** [comment]
@yann300 Can you please investigate into this?

**Comment by Aniket-Engg** [comment]
Hello @fulldecent Can you check it now with Remix 0.33.0 ? Things should be improved. Feel free to share your feedback

**Comment by Aniket-Engg** [comment]
Closing it. Please feel free to open if issue persists
