### ISSUE TITLE
Yul-compiled contract does not show up in Contracts since v0.25.0

### ISSUE THREAD

**Issue by pokrovskyy** [ethereum/remix-project#2684]
This urgent bug prevents using [remix.ethereum.org](https://remix.ethereum.org/) for Yul contracts. Starting v0.25.0, the compiled Yul contract will not appear in "Contracts" dropdown on "Deploy & Run transactions" panel, making it impossible to deploy and interact with it. 

Version: 0.25.0
Language: Yul
Compiler: any

**Comment by pokrovskyy** [comment]
![CleanShot 2022-07-25 at 10 33 11@2x](https://user-images.githubusercontent.com/1635058/180839187-554f2893-6087-4cac-a6f4-6fa6089bb589.png)

**Comment by Aniket-Engg** [comment]
@pokrovskyy This is fixed and released. Please check now.

**Comment by pokrovskyy** [comment]
Confirmed it works now in v0.25.1 - much appreciated! 👏
