### ISSUE TITLE
Don't show anything

### ISSUE THREAD

**Issue by roushanyyzz** [ethereum/remix-project#2685]
![image](https://user-images.githubusercontent.com/50560167/180932199-e7614627-f270-4933-b07e-672eeb6b2300.png)
Don't show anything

**Comment by Aniket-Engg** [comment]
@roushanyyzz  You should download and install the latest version of Remix Desktop from https://github.com/ethereum/remix-desktop/releases
... then hit "Clear the cache and restart Remix" button. It will take some time to reload, but you will be up to date!
