### ISSUE TITLE
In permissions modal, reset should be underlined on hover.

### ISSUE THREAD

**Issue by ryestew** [ethereum/remix-project#2690]
<img width="328" alt="image" src="https://user-images.githubusercontent.com/6050001/180954695-b589c2de-78ad-47be-a84b-e7027100513c.png">

**Comment by LianaHus** [comment]
![Screenshot from 2023-02-22 17-31-36](https://user-images.githubusercontent.com/9685356/220693264-9da9d547-cb19-45e6-9721-3f61bff09506.png)
