### ISSUE TITLE
issues with vyper plugin

### ISSUE THREAD

**Issue by Aniket-Engg** [ethereum/remix-project#2720]
- [ ] Documentation and `Make an issue` link in plugin info and link on GitHub icon on top still refers to old repo i.e. https://github.com/GrandSchtroumpf/vyper-remix
- [x] When there is no file opened in editor, it shows issue in browser console
```
Error: Error from IDE : Error: No such file or directory No file selected
    at l.<anonymous> (index.js:345)
    at Object.<anonymous> (index.js:561)
    at l.emit (index.js:634)
    at index.js:1099
    at index.js:1011
    at Object.next (index.js:959)
    at i (index.js:912)
```

- [x]  This text `The url to your local compiler` seems unnecessary
- [x] When tried compiling a contract using `Remote compiler`, it shows no message on UI. On icon panel, it shows warning icon and in browser console error is:
```
compiler.tsx:46 POST https://vyper.live/compile 400 (Bad Request)
CompilerButton.tsx:64 Error: Vyper compilation failed: Bad Request
    at compiler.tsx:56
    at s (runtime.js:45)
    at Generator._invoke (runtime.js:264)
    at Generator.e.<computed> [as next] (runtime.js:98)
    at r (asyncToGenerator.js:3)
    at l (asyncToGenerator.js:25)
```

**Comment by PatrickAlphaC** [comment]
Is this plugin supported by [this repo](https://github.com/GrandSchtroumpf/vyper-remix)? All the links are pointing to there, but it looks like this repo supports the vyper plugin?

**Comment by PatrickAlphaC** [comment]
Thanks for this issue, I was just playing around with that repo trying to get stuff to work and then I found that this repo hosts all the code!

**Comment by PatrickAlphaC** [comment]
Additionally, the plugin doesn't support 0.3^ editions of vyper, and the syntax highlighting is off. 


<img width="827" alt="Screen Shot 2022-08-16 at 8 19 36 AM" src="https://user-images.githubusercontent.com/54278053/184877973-b12fcdab-ba04-490d-8041-f4bccc99b0cc.png">

**Comment by Aniket-Engg** [comment]
cc: @yann300

**Comment by PatrickAlphaC** [comment]
Would love to see how we can help with this, it'll be really helpful for making vyper courses.
