### ISSUE TITLE
Spacelab theme hide names and variables

### ISSUE THREAD

**Issue by ismaelbej** [ethereum/remix-project#2742]
I tested Firefox 103.0.1, Brave 1.42.88, and Chrome 104.0.5112.79. Remix was tested at v0.25.1 .

<img width="1280" alt="Screen Shot 2022-08-08 at 23 40 01" src="https://user-images.githubusercontent.com/79440/183552499-71b5eb59-2a3c-4ee5-8aa1-458ecc5dd22d.png">

**Comment by joeizang** [comment]
Fixed by #2747

**Comment by Aniket-Engg** [comment]
fixed by https://github.com/ethereum/remix-project/pull/2747
