### ISSUE TITLE
wordwrap in errors in vyper

### ISSUE THREAD

**Issue by ryestew** [ethereum/remix-project#2803]
Errors in the Vyper plugin need to be horizontally scrolled to see them.  Its not a huge inconvenience - but maybe there can be a way to turn on word wrap.
<img width="437" alt="image" src="https://user-images.githubusercontent.com/6050001/186455047-ea0bb692-0e9d-42ad-ad55-f5e02110a687.png">

**Comment by LianaHus** [comment]
@ryestew @joeizang  is this still relevant ? If not please close it

**Comment by joeizang** [comment]
This has since been fixed in the vyper refactor
