### ISSUE TITLE
vyper compilation probs

### ISSUE THREAD

**Issue by ryestew** [ethereum/remix-project#2804]
When I try to compile a vyper file I get an error concerning "Unexpected end of JSON input"

<img width="813" alt="image" src="https://user-images.githubusercontent.com/6050001/186495792-b771978f-23b5-476b-bd4a-0486b6f58f19.png">

**Comment by yann300** [comment]
We should display a warning, saying that this plugin only works with vyper 0.2.16, you could too put the issue link: https://github.com/vyperlang/vyper/issues/3075

**Comment by joeizang** [comment]
This has since been fixed with the new vyper compiler that is supports version 0.3.10 and is backwards compatible also.
