### ISSUE TITLE
Debugger UI may not be wide enough

### ISSUE THREAD

**Issue by ryestew** [ethereum/remix-project#2806]
When the stack panel is fully populated the full storage changes & call data panel are just visible.

<img width="603" alt="image" src="https://user-images.githubusercontent.com/6050001/186501144-336138dc-39c7-4ffd-a180-c93fc8e895ff.png">

I'm not sure there is much we can do about this - or we could open the panel to be a bit wider.  But these panels are visible.  It is not the perfect UI solution right now.

**Comment by LianaHus** [comment]
also the scrollbar shouldn't be visible when debugging is not started
