### ISSUE TITLE
How many smart contract problems solidity static analysis can be detected?

### ISSUE THREAD

**Issue by xf97** [ethereum/remix-project#282]
Hello, I would like to ask how many kinds of smart contract problems can Remix-ide's solidity static  analysis function detect? If there are relevant documents, please tell me, I will read the relevant materials myself. I am sorry to disturb you because I am conducting a survey in related fields. I look forward to your reply.

**Comment by yann300** [comment]
@Aniket-Engg

**Comment by Aniket-Engg** [comment]
I think our static analysis modules are well listed here: https://remix-ide.readthedocs.io/en/latest/static_analysis.html

**Comment by xf97** [comment]
Thanks, I saw this document, it helped me a lot.
