### ISSUE TITLE
Etherscan contract verification extension Activation fails

### ISSUE THREAD

**Issue by zaryab2000** [ethereum/remix-project#2869]
- The extension gets stuck when trying to activate
- I get this response when I try to click on the extension
<img width="258" alt="image" src="https://user-images.githubusercontent.com/42082608/188305960-de49eea0-a69b-43fb-b580-ea3b80053b43.png">

Need some help with this, please. thanks

**Comment by Aniket-Engg** [comment]
![Screenshot 2022-09-05 at 12 10 22 PM](https://user-images.githubusercontent.com/30843294/188381104-15e8cf64-31d2-4b9e-a3c0-d52e899055a2.png)

@zaryab2000 It loads fine for me. Do you still see the issue?

**Comment by Aniket-Engg** [comment]
Closing it. Please feel free to reopen if issue persists.

**Comment by zaryab2000** [comment]
yeah seems to work fine - Sorry forgot to update here @Aniket-Engg . Thanks
