### ISSUE TITLE
editor freezes on large files

### ISSUE THREAD

**Issue by bunsenstraat** [ethereum/remix-project#2870]
Parsing larger files, not compiling, but parsing the current file can take long and block the editor while typing. 
Need to put that in a worker.

**Comment by iamsethsamuel** [comment]
I think this is an issue with Chrome

**Comment by bunsenstraat** [comment]
> I think this is an issue with Chrome

No it's the internal parser which blocks the browser. It can be turned off by turning off autocomplete/show gas/display errors in the settings of Remix. An update will be available soon to fix the issue.
