### ISSUE TITLE
Imported Files errors not turning off when another file is being compiled

### ISSUE THREAD

**Issue by ryestew** [ethereum/remix-project#2938]
When I tested I imported some files.  The files had compiler version errors.  Then I erased the import lines recompiled but the files are still red in the .deps folder.  Its seems distracting that these errors don't turn off when the files are not being imported.

<img width="1109" alt="image" src="https://user-images.githubusercontent.com/6050001/191878525-18bc4abb-9207-45cd-857a-02c781a40c11.png">

**Comment by bunsenstraat** [comment]
this is as intended. the files have errors in them. removing them from an import statement should not make the errors go away.
