### ISSUE TITLE
[Feature] Enable contract interaction with only contract ABI

### ISSUE THREAD

**Issue by nonseodion** [ethereum/remix-project#2939]
## Background
Currently, the Remix IDE requires that you have the contract code it then compiles it and gives you the option to deploy and start interacting with your contract or supply an address instead. 
It'll be great if we could use just the ABI instead to interact with the contract. Remix can verify the contract ABI and then allow an address to be supplied before interaction.

## Rationale
Allows frontend developers to interact with the contracts, and know possible inputs, outputs and errors before writing code.

I'd love to get your feedback if this is a viable feature and also work on it.

**Comment by Aniket-Engg** [comment]
Hello @nonseodion , This is already a feature. You can save abi in a file with `.abi` and can use it to interact with a contract. See: https://remix-ide.readthedocs.io/en/latest/run.html#using-the-abi-with-ataddress

**Comment by nonseodion** [comment]
Thanks totally missed that.
