### ISSUE TITLE
trying to interact with rinkeby contract

### ISSUE THREAD

**Issue by maikelmclauflin** [ethereum/remix-project#295]
added a contract [`0x5Dd2321058b4CC9de197D53A8d1C332457a52bB8`](https://rinkeby.etherscan.io/address/0x5Dd2321058b4CC9de197D53A8d1C332457a52bB8) but i do not seem to be able to load it on https://remix.ethereum.org/

whenever i click the at address button i get this error
```
app.js:286155 Uncaught TypeError: Cannot read property 'getAttribute' of undefined
    at ContractDropdownUI.getSelectedContract (app.js:286155)
    at app.js:286245
    at DropdownLogic.loadContractFromAddress (app.js:286349)
    at ContractDropdownUI.loadFromAddress (app.js:286234)
```
metamask is on rinkeby and my address shows up in the dropdown

**Comment by JoyCood** [comment]
@Aniket-Engg when i update the chrome to latest version, the same error happend to me, but the lower version of chome work fine.
my latest version of chrome is :  87.0.4280.66.

**Comment by rplusq** [comment]
Getting the same error, I'm using Stephen Grider's Blockchain Development course to learn. Seems like @jlawson5463 was doing so too.
