### ISSUE TITLE
Double Nav in DGit

### ISSUE THREAD

**Issue by ryestew** [ethereum/remix-project#2980]
Its back!
<img width="411" alt="image" src="https://user-images.githubusercontent.com/6050001/193716040-27d85ee9-c65f-49fd-baf5-fcc32579ce98.png">

**Comment by drafish** [comment]
It's not just DGit, and not just side panel. Every external plugin load through iframe will got a redundant vertical scrollbar. 

I found the same issue on stackoverflow. Check this out.

https://stackoverflow.com/questions/36974514/why-is-there-a-vertical-scroll-bar-if-parent-and-child-have-the-same-height

The question is already be answered with a detailed explanation and properly solution. I tested and it worked.

**Comment by drafish** [comment]
![image](https://user-images.githubusercontent.com/18543527/197429317-71df4973-5efc-4358-8ee3-d33d5050bd75.png)
![image](https://user-images.githubusercontent.com/18543527/197429362-de5f080a-2b58-43ed-b9a8-13bf4e91d36d.png)
I think you mentioned this issue by mistake. The number of PR that mentioned in commit message happen to be the same with the number of this issue. @internetbuilder

**Comment by Aniket-Engg** [comment]
fixed by #3026
