### ISSUE TITLE
Integrate the ability of running provider plugins.

### ISSUE THREAD

**Issue by yann300** [ethereum/remix-project#30]
A first naive implementation:
 - appManager listen on plugin activated
 - If it is of `provider` plugin, appManager call runtab.addProvider for adding it to the env list.
 - when it's deactivated, entry is removed.

**Comment by LianaHus** [comment]
is there a 'provider' type for plugins?

**Comment by yann300** [comment]
in the branch  I was working yes but it's not quite ready for review (but soon)
