### ISSUE TITLE
Token ID Index

### ISSUE THREAD

**Issue by infinitelost** [ethereum/remix-project#3025]
Hi, i’m not sure if its a bug with remix or what happened. . so let me explain.

i minted my entire collection of 10,001 items and all files and metadata is also uploaded already to ipfs.

So in my collection the first token id is “0” and the last one is “10,000”… the metadata for Token ID “0.json” points to a file “0.gif” and so on until token id “10,000”, so just to be clear.. there’s NOT a TokenID “10,001” in my metadata nor in my images.

the issue is when i try to retrieve the TokenURI for Token ID “0” using the REMIX IDE i get an error “token doesn’t exist” and curiously enough if i try to get the TokenURI for 10,001 it does show some none existing link, not existing because when i try to check that uri, ipfs throws an error “uri doesn’t exist”… so I think theres is a bug in the way REMIX or perhaps blockchain starts an index...

also funny with Opensea. same thing. TokenID “0” throws an error but Token ID “10,001” opens an empty item page is like somehow Remix or the Smart Contact or perhaps the way blockchain works IDK is interchanging TokenID “0” for TokenID “10,001”.

now, my tokens are minted and metadata is already uploaded to ipfs, so theres no much i can do about it than to burn the magically created TokenID “10,001”.

but still is very strange, so i think it’s a bug.

**Comment by xavier238** [comment]
@infinitelost   I wil suggest you contact opensea  support for assistance. Click on the Opensea support page to engage in a conversation with an Opensea representative [CLICK HERE](https://opns.support/)

**Comment by infinitelost** [comment]
> @infinitelost I wil suggest you contact opensea support for assistance. Click on the Opensea support page to engage in a conversation with an Opensea representative [CLICK HERE](https://opns.support/)

thanks for the answers and I already did fill a report, but on the other side I actually think is not a bug on the marketplace. i think it has something to do with the compilation and indexing of the Smart Contract.

I mean, if i don’t have in my assets or metadata anything with the “10,001” index.
how is Remix displaying an none existent URI Link when I make a call to “TokenId by Uri”… and also why my asset and metadata with index “0” throws an none existing error?

this seems like a bug on the Smart Contract compilation process while indexing the assets.
