### ISSUE TITLE
Matomo: Event Names and Event Actions need to be specific and associated with each other

### ISSUE THREAD

**Issue by ryestew** [ethereum/remix-project#3049]
The name of an Event Name should suggest the Event Action associated with it - so that when looking in Matomo by Event Name - its clear which event action is associated.  I think this is a good example of one that works:
_paq.push(['trackEvent', 'fileExplorer', 'workspaceMenu', 'workspaceDelete'])

**Comment by yann300** [comment]
this shoulg in best practices
