### ISSUE TITLE
Allow rename "browser" folder to anything and use relative path

### ISSUE THREAD

**Issue by 3esmit** [ethereum/remix-project#305]
The path changes the resulting bytecode due path being included in the hash that goes into end of contract deployed. 

When using remix, it always marks at start with "browser/<contractname>.sol", while when I work with solc in my PC it starts with "<relativepath>/"<contractname.sol>", usually being "./contracts/MyContract.sol" opposed to in remix "browser/MyContract.sol".

I would like that I am able to set this name folder to anything, and that it started with "./" as any relative path.

Duplicate of: ethereum/remix-project#293 ethereum/remix#1361

**Comment by Aniket-Engg** [comment]
browser folder is not more there. So closing it.
