### ISSUE TITLE
Environment Name not properly centered in its div

### ISSUE THREAD

**Issue by muneeb-i-khan** [ethereum/remix-project#3055]

**Comment by Aniket-Engg** [comment]
Hello @muneeb-i-khan , Can you please share a screenshot or add more details in the support of the issue

**Comment by muneeb-i-khan** [comment]
![Remix_bug](https://user-images.githubusercontent.com/96231592/199000158-0dfada01-ec52-41e6-a011-9b5b69032a3e.png)

**Comment by muneeb-i-khan** [comment]
This happens while resizing the side pannel

**Comment by muneeb-i-khan** [comment]
It happens when one resizes side pannel to a smaller size

**Comment by LianaHus** [comment]
![Screenshot from 2022-11-14 12-37-07](https://user-images.githubusercontent.com/9685356/201650569-cc59b2ee-0c7b-45ce-9978-b737142bf619.png)
another issue
