### ISSUE TITLE
Tooltips to review

### ISSUE THREAD

**Issue by ryestew** [ethereum/remix-project#3082]
**Below are tooltips that need updating**

## Icon Panel
- [x] the icon panel has the native tooltips not the the custom ones.

## File Explorer
- [x] **GitHub GIST** 1. Needs to be better positioned
<img width="208" alt="image" src="https://user-images.githubusercontent.com/6050001/199806539-82cb852f-08c2-4c96-b28f-6a44a84bddbf.png">

## Deploy & Run

- [x] **tooltip on disabled Contract selectbox** 
       Sometimes the tooltip doesn't go away.  
<img width="929" alt="image" src="https://user-images.githubusercontent.com/6050001/199803725-229f19ef-04b7-466d-8df2-a548ecc44a1d.png">

- [x] **tooltip on Contract selectbox**  edit:
Maybe it is too long and needs a br tag. Edit: 2. Maybe it is too long and needs a br tag. 
When there is a compiled .sol file, choose the contract to deploy or to use with AtAddress.

- [x] **atAddress** 1. needs a br tag - its too long.
<img width="911" alt="image" src="https://user-images.githubusercontent.com/6050001/199804188-a95d3a36-0d8b-44c0-b2ab-b29414d1b947.png">

- [x] **Environment i** 1. slight adjustment in placement of the tooltip arrow
<img width="320" alt="image" src="https://user-images.githubusercontent.com/6050001/199811095-a1d61612-8659-4448-96af-427880fbf51c.png">

- [x] **Environment Plug** 1. text update: "you want to interact with."   And consider replacing Provider: here is the entire edit: Open chainlist.org and get the connection specs of the chain you want to interact with.
<img width="688" alt="image" src="https://user-images.githubusercontent.com/6050001/199807073-622969b4-e8a3-4329-919c-3ef55b44ffbd.png">

- [x] **Gas Limit** 1. badly positioned text.
<img width="441" alt="image" src="https://user-images.githubusercontent.com/6050001/199808276-0999d7a5-8696-4d2a-86e1-b96e9ea6c452.png">

- [x] **Proxy Contracts** 1. Needs the custom tooltip.
<img width="390" alt="image" src="https://user-images.githubusercontent.com/6050001/199804679-f7ea8788-fe07-4197-9340-b62e334b12e6.png">

- [x] **Function title** 1. Somehow I got a native tooltip on a function's name - but I didn't try to get it to appear.
<img width="485" alt="image" src="https://user-images.githubusercontent.com/6050001/199808859-679e08fe-b3a9-44c7-b17e-eb27a480ef36.png">

- [x] **Fallback / low level** 1. Update text: Click for docs about using 'receive'/'fallback'  
<img width="298" alt="image" src="https://user-images.githubusercontent.com/6050001/199809089-0ec70f93-654a-4ff8-b303-a764591a7eb4.png">

## Solidity Compiler
- [x] **Compile & Run monster sized tooltip** 1. The tooltip pointer should be over the **i**. 2. Text change: "Click the i icon to learn more" 
<img width="946" alt="image" src="https://user-images.githubusercontent.com/6050001/199805719-a57d5c56-8801-413b-9198-dd87add0713b.png">

## Static Analysis
- [x] **Blank tooltip (only an arrow) over titles of subjects
<img width="308" alt="image" src="https://user-images.githubusercontent.com/6050001/199813221-30d24367-cd74-45d2-9b77-92fe47ea299c.png">

- [x] **Run button** 1. Badly placed arrow
<img width="186" alt="image" src="https://user-images.githubusercontent.com/6050001/199813681-30bc2105-5ef3-4686-ba6e-c14d8b22c832.png">

**Comment by joeizang** [comment]
@ryestew I could not replicate item 10 under the Run and Deploy section
