### ISSUE TITLE
Question: how remix send jsonrpc request when used with Injected Provider Metamask

### ISSUE THREAD

**Issue by gzliudan** [ethereum/remix-project#3085]
When remix is working with Injected Provider Metamask, does remix dispatch all JsonRpc request to MetaMask? Some api need not permission, such as eth_getBlockByNumber. Does remix dispatch these calls to RPC node directly? And how remix send jsonrpc request to metamask, such as protocol, end point address ?

**Comment by yann300** [comment]
> does remix dispatch all JsonRpc request to MetaMask?

yes

metamask inject the object `ethereum` to the page. This is a provider that can be used along side web3.js and ethers.js. all the calls are made to metamask, then metamask disptach tne call to their nodes. Remix doesn't know the final endpoint address.
Hope that helps, let me know if you have more question.

**Comment by gzliudan** [comment]
Thanks. How does remix fetch jsonrpc response from metamask?
