### ISSUE TITLE
Workspace hamburger got eaten

### ISSUE THREAD

**Issue by ryestew** [ethereum/remix-project#3101]
The workspace icons are back and the hamburger is gone - this must be part of the rollback - but put it back in
<img width="394" alt="image" src="https://user-images.githubusercontent.com/6050001/200960761-c64b2634-47e4-416a-85cf-b846f36f7459.png">

**Comment by yann300** [comment]
did you run the latest version? please try clearing th cache too. I close, please reopen if necessary
