### ISSUE TITLE
Change "null" workspace to "local or localstorage, or browserstorage"

### ISSUE THREAD

**Issue by molecula451** [ethereum/remix-project#3144]
Currently the "null" workspaces is showing all the data that is storaged in the browser, it would be an improve if it's set to a better name

**Comment by Aniket-Engg** [comment]
Hello @molecula451 , if you see a `null` workspace in workspace dropdown, it may be there because of an old bug which is fixed now. You can delete that and it should not appear again.

**Comment by molecula451** [comment]
closing this for now, as I have lot of files on localstorage, would look at it later
