### ISSUE TITLE
navigation carets in slider on home tab

### ISSUE THREAD

**Issue by Aniket-Engg** [ethereum/remix-project#3151]
![Screenshot 2022-11-21 at 7 18 27 PM](https://user-images.githubusercontent.com/30843294/203074820-7b116571-40d0-4529-8548-d527cba999f4.png)

The carets appear if you leave IDE for some time and come back to home tab.

They disappear only when another image comes after sliding

cc: @bunsenstraat

**Comment by LianaHus** [comment]
hmm. can't reproduce this. any details to reproduce? zoom level, browser etc

**Comment by Aniket-Engg** [comment]
It used to appear when we leave Remix as it is for some time and come back to it. I haven't seen it recently, so closing the issue.
