### ISSUE TITLE
Compiling contract with 0 runs defaults to 200

### ISSUE THREAD

**Issue by JoshuaAlvarez06** [ethereum/remix-project#3153]
Hello. I have run into an issue when deploying contracts using Remix. I came across this issue when I tried to verify a contract that I had (thought) I compiled with `optimization` enabled and `0` runs and was not able to verify it on Etherscan using `0` runs. I then tried to verify it with `200` runs and it worked.

This leads me to believe that there may be a bug when checking the value we input in to the `runs` input in https://remix.ethereum.org. Maybe it's just checking for `!runs` and defaults it to `200` when it is `0`.

This is causing issues because I can only compile and deploy my contract with 0 runs.

**Comment by Aniket-Engg** [comment]
I can reproduce it

**Comment by JoshuaAlvarez06** [comment]
> @JoshuaAlvarez06 That just calculates code size and modal will appear if size is greater than the limit. You can configure runs to manage the size while optimization. 
> 
> Now you can compile with 0 runs and you can confirm that in `Compilation Details` of the compiled contract

I understand. The compilation and deployment both work. The modal does not come up with 1 runs though, and it does with 0, though. Meaning, it's obviously still a bug that it comes up with 0. The modal shouldn't come up anymore
