### ISSUE TITLE
Unable to Access  Local Filesystem

### ISSUE THREAD

**Issue by ketan-sol** [ethereum/remix-project#3170]
Getting an error while trying to connect to local files.
"Cannot connect to the remixd daemon. Please make sure you have the remixd running in the background."
Remixd is already installed and running in background.
Tried with installing both locally and globally. Was working fine before 0.6.8 update

**Comment by Marrmee** [comment]
same problem here...

**Comment by kelvinink** [comment]
same problem

**Comment by Aniket-Engg** [comment]
@ketan-sol Are you trying to share a hardhat project?

**Comment by Aniket-Engg** [comment]
@ketan-sol  Can you check if it is fixed with remixd v0.6.10 ?

**Comment by Genysys** [comment]
same problem here

**Comment by ketan-sol** [comment]
@Aniket-Engg  Still facing the same issue.

**Comment by Aniket-Engg** [comment]
@ketan-sol Can you add more details like OS and browser you are using?

Are you using any framework project?

**Comment by Aniket-Engg** [comment]
Is it with hardhat project too with remixd v0.6.10? For foundry, there is a fix in progress.

**Comment by Genysys** [comment]
@Aniket-Engg yes. But i am just running `remixd` and not specifying a src file. shouldnt it still read it ?

**Comment by Aniket-Engg** [comment]
If you just run `remixd` , it shares your current working directory with remix IDE

**Comment by ketan-sol** [comment]
@Aniket-Engg  brave on m1 mac. Simple hardhat project

**Comment by Aniket-Engg** [comment]
okay, thanks for the info @ketan-sol . We are working on another fix. will let you know once it is released

**Comment by ketan-sol** [comment]
@Aniket-Engg  still facing same issue. Remixd was successfully installed and running but got a deprecation warning -

"(node:2054) [DEP0128] DeprecationWarning: Invalid 'main' field in '/usr/local/lib/node_modules/@remix-project/remixd/node_modules/@remixproject/plugin-utils/package.json' of 'src/index.js'. Please either fix that or report it to the module author"

**Comment by Aniket-Engg** [comment]
@ketan-sol This seems a warning only. Are you able to connect Remixd successfully with Remix IDE?

**Comment by ketan-sol** [comment]
@Aniket-Engg no. Still facing the same error

"Cannot connect to the remixd daemon. Please make sure you have the remixd running in the background."
Remixd is already installed and running in background.

**Comment by Aniket-Engg** [comment]
cc: @bunsenstraat

**Comment by bunsenstraat** [comment]
@ketan-sol we should connect on a call if you can. Sort this out.

**Comment by 0xkakashixyz** [comment]
same here
remixd -v 0.6.11
Mac Air M2 OS: ventura 13.1
tried installing remix locally and globally. It returns the alert
```Cannot connect to the remixd daemon. Please make sure you have the remixd running in the background."
Remixd is already installed and running in background```

**Comment by ketan-sol** [comment]
@bunsenstraat sure let me know

**Comment by bunsenstraat** [comment]
> @bunsenstraat sure let me know

Let's schedule a call. I am in Europe time zone.

**Comment by huaigu** [comment]
any update?
got same issue with latest version 0.6.12

**Comment by RohanShrothrium** [comment]
Same issue with mac m1 and brave

**Comment by cfranchella** [comment]
was having the same issue, tried putting shields down and worked

**Comment by bunsenstraat** [comment]
@RohanShrothrium can you confirm the shields fix works?

**Comment by Uttam-Singhh** [comment]
**Working sol:** If you are on brave at the search tab click on lion symbol and turn off shields!

<img width="391" alt="img 2023-03-26 at 1 07 42 AM" src="https://user-images.githubusercontent.com/63050765/227737941-bb89bb61-dfc8-41e4-bf93-163a9a6c02b9.png">

**Comment by ketan-sol** [comment]
version 0.6.13 still having same issue.
Tried with shields off. Still facing same issue. 

<img width="1132" alt="Screenshot 2023-04-06 at 5 45 47 PM" src="https://user-images.githubusercontent.com/89595019/230376708-17e79112-e848-4548-962f-b87409e33372.png">

**Comment by bunsenstraat** [comment]
@ketan-sol You're specifying http in the -u, while remix runs on https

**Comment by bunsenstraat** [comment]
> **Working sol:** If you are on brave, go to the search tab above and click on lion symbol and turn off shields!
> 
> <img alt="img 2023-03-26 at 1 07 42 AM" width="391" src="https://user-images.githubusercontent.com/63050765/227737941-bb89bb61-dfc8-41e4-bf93-163a9a6c02b9.png">

exactly that should work fine. can everyone confirm?
