### ISSUE TITLE
console.log DeclarationError: Undeclared identifier in Solidity

### ISSUE THREAD

**Issue by SaikrishnaReddy1919** [ethereum/remix-project#3194]
Issue: `console.log` is throwing an error in remix.
<img width="308" alt="Screenshot 2022-12-06 at 9 38 34 PM" src="https://user-images.githubusercontent.com/29354571/205963068-193a707f-a543-4785-a2b8-ab4c7675088d.png">

Code : 
```javascript
contract LoanFactory {
    Loan[] loans;

    constructor() {}

    function createLoan() external {
        Loan loan = new Loan(100);
        loans.push(loan);
        console.log(loan);
        address(loan); 
    }
}
```
Error : 

<img width="264" alt="Screenshot 2022-12-06 at 9 36 44 PM" src="https://user-images.githubusercontent.com/29354571/205962685-4e6cbed0-6327-48c4-bb3c-ce7fef11133d.png">

**Comment by Kerry1207** [comment]
For using console.log([parameters]) you must include the following import statement outside your smart contract:
`import "hardhat/console.sol";`

In this case, your smart contract must be modified as follows:
```
 pragma solidity ^0.8.0;

import "hardhat/console.sol";

contract LoanFactory {
    Loan[] loans;

    constructor() {}

    function createLoan() external {
        Loan loan = new Loan(100);
        loans.push(loan);
        console.log(loan);
        address(loan); 
    }
}
```

**Comment by Aniket-Engg** [comment]
@SaikrishnaReddy1919 seems `loan` is a `struct` variable, that can be reason of error. You can try to log individual property.

**Comment by SaikrishnaReddy1919** [comment]
It's working that way. But is there any way to print structs and other complex types?

**Comment by Aniket-Engg** [comment]
As of now, there is no support for complex data types
