### ISSUE TITLE
Problem with carousel buttons on Remix-project website

### ISSUE THREAD

**Issue by muneeb-i-khan** [ethereum/remix-project#3204]
The carousel buttons on Remix-project website are not properly placed. You can see that in the below screenshot.

![Screenshot 2022-12-11 233224](https://user-images.githubusercontent.com/96231592/206920613-6231461f-9266-42ad-b381-3ff0544b340b.png)

**Comment by LianaHus** [comment]
I'm closing this here. We will handle it website's repo. Thanks
