### ISSUE TITLE
Improving Static Analysis

### ISSUE THREAD

**Issue by LianaHus** [ethereum/remix-project#3208]
We agreed to 
- Remove Categories (still show them on the warning item)
- **Disable** Slither and not **hide** it. Add a tooltip.
- Add Solhint to SSA.
- Add a warning alert in Solidity plugin to show statistics from SSA. Clicking on this should switch to SSA plugin

please add mockups or share any suggestions you have

We will have following items on SSA plugin:
- **Run** button
- **Autorun** checkbox
- **Remix StaticAnalysis** checkbox
- **Slither** checkbox
- **Solhint** checkbox

**Comment by ryestew** [comment]
![static-analysis-v1](https://user-images.githubusercontent.com/6050001/235688725-ca9ef757-4949-4b1b-89b1-a1b5d1362134.png)
![static-analysis-v2](https://user-images.githubusercontent.com/6050001/235688731-7934edcc-71d8-4dc8-becd-01de5860d285.png)

**Comment by ryestew** [comment]
![static-analysis-v5](https://github.com/ethereum/remix-project/assets/6050001/02b47c6b-a387-4b55-81d0-1240919cfb06)

**Comment by ryestew** [comment]
same but real size:
![static-analysis-v5-72dpi](https://github.com/ethereum/remix-project/assets/6050001/c5b63da6-a8de-4362-8e2e-a144aa1eb702)

**Comment by ryestew** [comment]
Should the Static Analysis plugin always be on?

**Comment by LianaHus** [comment]
i think we should avoid extra i icons instead, all 3 labels should have a proper tooltips.

**Comment by LianaHus** [comment]
I think I'll prefer V1

**Comment by yann300** [comment]
@ryestew instead of `General` it should be `Basic` or something equivalent.

**Comment by yann300** [comment]
@ryestew @joeizang  slither should be the last one.

**Comment by yann300** [comment]
@ryestew @joeizang tooltip on hover the analyzer with more description

**Comment by ryestew** [comment]
Here's a version that we worked on today - I have since added the lines for the tabs.  I think there is too much functionality in the tab titles - its odd to have a the checkbox in the titles.

![static-analysis-v6a](https://github.com/ethereum/remix-project/assets/6050001/6907b5a8-6a56-41fa-86ae-32c6be36c6d6)

**Comment by joeizang** [comment]
I tend to agree with what @ryestew said. The checkboxes as part of the label for the tabs isn't really a good fit having written the code. I will make modifications based of this and see how it pans out.

**Comment by LianaHus** [comment]
@ryestew can you add here the wireframe we created in the call with Joe?

**Comment by joeizang** [comment]
Here are the results of our discussion during standup 6-6-23: 
![image](https://github.com/ethereum/remix-project/assets/4255962/37cf22f4-469d-487d-8e67-543b4e5bad58)
