### ISSUE TITLE
Home Tab Sliders

### ISSUE THREAD

**Issue by ryestew** [ethereum/remix-project#3220]
When the browser screen is a bit narrow, the slider looks like this:
<img width="622" alt="image" src="https://user-images.githubusercontent.com/6050001/207627826-ef3abc61-7744-452f-84b6-3233729c1e47.png">

1. The bottom of the button should not be cut off.
2. The 170 x 170 image should be clickable.

**Comment by LianaHus** [comment]
why it should be clickable?
