### ISSUE TITLE
Hometab Features Module Images

### ISSUE THREAD

**Issue by vermouth22** [ethereum/remix-project#3221]
"Remixer" image was outdated and too large to load efficiently. We should consider future modules as they load from Twitter tags, ensuring they do not interrupt loadtime of the IDE itself.

Here is a replacement image for now:
https://drive.google.com/file/d/17_qeGCHDBsgnbSagOXa-FgnPqHvjcvst/view?usp=sharing
![Remixer_small](https://user-images.githubusercontent.com/35277634/207699258-66672340-d787-4f6d-8b6b-e4c618cc1553.png)

**Comment by bunsenstraat** [comment]
fixed in https://github.com/ethereum/remix-project/pull/3223
