### ISSUE TITLE
The remix screen goes blank when I try to use the debug button... please fix

### ISSUE THREAD

**Issue by mattjaf** [ethereum/remix-project#3235]
![image](https://user-images.githubusercontent.com/5776918/208185941-378a1d25-2275-4797-89a1-7092d2593063.png)

![image](https://user-images.githubusercontent.com/5776918/208185892-1f07372d-aebe-4e47-aed6-3c3e7cf841bf.png)

**Comment by mattjaf** [comment]
it worked fine on local (london) and goerli, it might be a mumbai issue?

**Comment by mattjaf** [comment]
Submitted a ticket on polygon developers:

https://developersupport.polygon.technology/support/tickets/877

**Comment by chichke** [comment]
Same here 😭

**Comment by LianaHus** [comment]
Is this still relevant?

**Comment by mattjaf** [comment]
seems to be an error handling bug, when  `debug_traceTransaction` is undefined

could possibly use a try catch with an alert or something
