### ISSUE TITLE
move Sol2Uml to remix-project repo

### ISSUE THREAD

**Issue by yann300** [ethereum/remix-project#3238]
Move sol2Uml plugin to the remix-project.
This plugin convert a compilation result to an UML representation of the compiled contracts.
This will require importing new dependecies: 
See the code in the plugin https://github.com/aquiladev/remix-sol2uml/blob/main/src/App.js#L33

We could put a new action in the solidity compiler tab or a right/click, this need anyway to be easily usable and visible.

**Comment by yann300** [comment]
Here's some code which will help flattening a file: https://github.com/bunsenstraat/flattener/blob/master/src/Client.ts#L79

**Comment by joeizang** [comment]
Next part will be to generate pdf of the uml diagram and save it in file explorer so it can be downloaded at anytime.

This might require the following:
- [ ] adding packages that support generating pdf from svg
- [ ] any package cannot have the native node fs library being used in it.
- [ ] folder name for artifacts like pdfs or jpg images from the svg generated images can be resources. This is subject to discussion and change.
