### ISSUE TITLE
tooltip design: needs an outline to separate from the page beneath it.

### ISSUE THREAD

**Issue by ryestew** [ethereum/remix-project#3240]
This is especially a problem with long tooltips:
<img width="507" alt="image" src="https://user-images.githubusercontent.com/6050001/208510344-147c467d-4bfa-4cf4-bc85-977f61b82257.png">

or

<img width="895" alt="image" src="https://user-images.githubusercontent.com/6050001/208510567-de41970b-2b59-4fb3-92f9-981b4b028878.png">

If they had a border, they should be easier to read.

**Comment by LianaHus** [comment]
included in https://github.com/ethereum/remix-project/issues/3241
