### ISSUE TITLE
tooltips don't always come in aligned to the arrow

### ISSUE THREAD

**Issue by ryestew** [ethereum/remix-project#3241]
Go to the hamburger icon on the FE
Check the tooltips for each item.

The first is vertically aligned with the arrow:
<img width="416" alt="image" src="https://user-images.githubusercontent.com/6050001/208511219-fe07a1da-396c-4cbf-bcf5-39ba99feff23.png">

The rest are below the arrow:
<img width="895" alt="image" src="https://user-images.githubusercontent.com/6050001/208510567-de41970b-2b59-4fb3-92f9-981b4b028878.png">

**Comment by LianaHus** [comment]
There is room for improvement
1. I would suggest to have borders
2. Long text should be avoided or split to 2 lines
3. triangle arrow should be vertically in the center of the tooltip field
