### ISSUE TITLE
Remixd keep crashing when connect to localhost

### ISSUE THREAD

**Issue by iam-Truong** [ethereum/remix-project#3258]
I use the last version Remixd(0.6.9). When i connect to remixd with local host method, it keep crashing so many time in 5 minute. I just deploy 1 smart contract and didnt execute any transaction (in previous version , remixed crash just only when i deploy many contract and do more transaction, im ok with this).

**Comment by iam-Truong** [comment]
It crash so much that Vscode pop up this error : "The Solidity Language Server server crashed 5 times in the last 3 minutes. The server will not be restarted"

**Comment by Aniket-Engg** [comment]
Can you please add more details to reproduce it? 
So you connect remixd with remix.ethereum.org, right? 
Why there is a popup for this in VSCode?

**Comment by iam-Truong** [comment]
yes i connect remixd with remix.ethereum.org. Its okay with creating connection
But when i start deploying SC, it just keeping crashing ("Page crashed")
And some contract take a long time to compile(compile very fast when not connect to localhost).

**Comment by Aniket-Engg** [comment]
@iam-Truong  Can you check if it is fixed with remixd v0.6.10 ?

**Comment by iam-Truong** [comment]
Nothing change @Aniket-Engg . Still crashing with v0.6.10. When i got too many err, its break connection betwen localhost and remix. (Assertion failed: (0), function uv_close, file ../deps/uv/src/unix/core.c, line 178.
[1]    8268 abort      remixd -s . --remix-ide https://remix.ethereum.org)

**Comment by iam-Truong** [comment]
- Terminal on VSCode (1) 
- Remix IDE (2)
Step 1: I cd to my working folder and start connect to remixd with this command : remixd -s . --remix-ide https://remix.ethereum.org/ on (1)
Step 2: I connect to localhost on (2) —> if it success, it will log this message “setup notifications for .” On (1) ( in this case it definitely success)
Step 3: I deploy a smart contract(success), not even execute a single transaction, just stand there for few second —> Remix Page Crashed Error  on (2) 
Step 4: Redo Step 2,3 and it keep crashing over and over again. After like 5 times connect and break, this error will log on (1) 
“
setup notifications for .
setup notifications for .
setup notifications for .
setup notifications for .
setup notifications for .
(Assertion failed: (0), function uv_close, file ../deps/uv/src/unix/core.c, line 178.
[1] 8268 abort remixd -s . --remix-ide https://remix.ethereum.org/)
“

One more thing is if I connect to localhost, remixd take so long time to compile a smart contract and execute a simple transaction( it only hanppen when a smart contract or transaction comprise so many heavy logic, I know this base on my personal	experience long-time work on remix).    If I not connect localhost, just way more easy and fast to compile and execute that transaction. 

Before all this error happened, localhost works very well. But since all this come to me, when I works I have to copy all my code to remix , and when I finish, I copy my code back to remix which is very exhausted. 	 

I use MacBook Pro M1 model

Hope this clear to help u guys.

**Comment by iam-Truong** [comment]
![Screenshot 2023-01-10 at 00 18 38](https://user-images.githubusercontent.com/89788386/211368235-208dbf3c-73fc-4fb3-9705-c5bd7e099e5e.png)
![Screenshot 2023-01-09 at 23 51 50](https://user-images.githubusercontent.com/89788386/211368274-9829622e-12e9-4eef-b72a-d3092e865379.png)
![321611294_3013711475602425_6802669871314337345_n](https://user-images.githubusercontent.com/89788386/211368642-0ce2007c-649a-43f7-becb-eec0663e2baf.png)

**Comment by LianaHus** [comment]
hi @iam-Truong . Do you have this issue with specific contract or every time the code complicated?

**Comment by iam-Truong** [comment]
I got this issue just only connect with my specific solidity project folder. Others still work fine. 
I dont know why this happen? Is it because of having to much smart contract on folder? cause i have like more than 40 smart contract linked together on that folder

**Comment by Aniket-Engg** [comment]
@iam-Truong Please try once more with remixd v0.6.11 and check if it is fixed?

**Comment by iam-Truong** [comment]
@Aniket-Engg  still get it with remixd v0.6.11

**Comment by bunsenstraat** [comment]
> @Aniket-Engg still get it with remixd v0.6.11
@iam-Truong we need to connect and debug

**Comment by bunsenstraat** [comment]
@iam-Truong I was thinking, as the solidity language server is also crashing on VsCode, are you sure you don't have any circular dependencies going on by any chance?

**Comment by iam-Truong** [comment]
> 

I sent you an email @bunsenstraat

**Comment by iam-Truong** [comment]
> @iam-Truong I was thinking, as the solidity language server is also crashing on VsCode, are you sure you don't have any circular dependencies going on by any chance?

Hmm maybe, Does gitlab SSH involve in this ? Cause i use the same SSH key with Gitlab and Remixd

**Comment by iam-Truong** [comment]
The bug is gone with remixd 0.6.14, thanks everyone very much really appreciate this.
