### ISSUE TITLE
The etherscan verification plugin can't be truly activated

### ISSUE THREAD

**Issue by lurengeng** [ethereum/remix-project#3276]
I tried with TWO different PC and different network, it doesn't work
Win10    Chrome 106.   Thanks
![image](https://user-images.githubusercontent.com/61215384/210288911-6ea052b4-ea70-4cbf-a3f0-b9f84070af3d.png)

![image](https://user-images.githubusercontent.com/61215384/210288925-7a731a2b-0da7-42bb-9455-f98a5b64088c.png)

**Comment by lurengeng** [comment]
It works .
Thx

**Comment by ntop001** [comment]
Not works on arbscan. always "Pending".
