### ISSUE TITLE
Error from IDE: Failed to fetch

### ISSUE THREAD

**Issue by ninjadynamics** [ethereum/remix-project#3288]
I've removed the old token and created a new one. Uninstalled DGIT and installed it again. Nothing works. I cannot fetch, push or pull.

**Comment by Aniket-Engg** [comment]
@bunsenstraat can you please look into this?

**Comment by bunsenstraat** [comment]
@ninjadynamics we had some maintenance issues, can you check again please?

**Comment by LianaHus** [comment]
@ninjadynamics

**Comment by ninjadynamics** [comment]
It works now! Thanks!! 😀
