### ISSUE TITLE
Cann't load compiler !!

### ISSUE THREAD

**Issue by FirstAsAlways** [ethereum/remix-project#3289]
Cannot load compiler version list. It might have been blocked by an advertisement blocker. Please try deactivating any of them from this page and reload. Error: SyntaxError: Unexpected end of JSON input

**Comment by Aniket-Engg** [comment]
Hello @probadre , compiler list is loading fine for me. Can you reload the Remix and try it again?

**Comment by LianaHus** [comment]
Do you intentionally use the latest local version? Can you please try to load another version?

**Comment by LianaHus** [comment]
You are using the local version in all your screenshots. Can you try to use the v0.8.16?

**Comment by Aniket-Engg** [comment]
@probadre is it fixed for you?

**Comment by rickbeeloo** [comment]
How did you get this fixed @FirstAsAlways ?
