### ISSUE TITLE
Remix IDE's screen hangs when using "While loop" 

### ISSUE THREAD

**Issue by fahad-sajid** [ethereum/remix-project#3313]
When I am deploying a **basic while loop smart contract** on remix IDE, after calling the loop function after deployment, the browser window's screen gets stuck and after couple of seconds the window page get unresponsive call and the window is crashed. (screenshots attached). The smart contract code I am running is also attached for the ref. May be this is some kind of glitch as I tried the **for loop** and it is working perfectly fine.

Note: I am a beginner in programming hence this basic level query as I couldn't find any solution on internet.

```
`// SPDX-License-Identifier: GPL-3.0
pragma solidity >= 0.5.0 < 0.9.0;

contract loops {
    uint [5] public Arr; // defining an array of 5 integers
    uint public count ;

    function Loop() public {
        while (count < Arr.length)
        Arr[count] =count;
        count++;
    }
}`
```
![image](https://user-images.githubusercontent.com/116836378/214957586-8ac8aec9-6bd0-4abf-bbd8-52b7bde3a5e5.png)

**Comment by yann300** [comment]
this shouldn't happen anymore with the coming release. please try https://remix-beta.ethereum.org

**Comment by fahad-sajid** [comment]
> this shouldn't happen anymore with the coming release. please try https://remix-beta.ethereum.org

Thanks mate for the solution, now the while loop is working perfectly fine.
