### ISSUE TITLE
_this15.web3(...).eth.getExecutionResultFromSimulator  when Connected to Metamask and calling udapp,newtransaction

### ISSUE THREAD

**Issue by aelmanaa** [ethereum/remix-project#3332]
Hi,

When I run a transaction using a plugin. E.g.,

```javascript
    const transaction: RemixTx = {
      from: signerAccount,
      to: this.contractAddress,
      data: dataTrans,
      gasLimit: "500000",
      value: "0x00",
      useCall: false,
    };
const txReceipt = await this.call("udapp", "sendTransaction", transaction);
```

Error : ` _this15.web3(...).eth.getExecutionResultFromSimulator`

I noticed that this error occurs only when I'm connected to metamask.  The problem, in fact, is with this line: 

https://github.com/ethereum/remix-project/blob/3f8024aae33380fafe7a7a2db2e066fa0562d914/apps/remix-ide/src/blockchain/blockchain.js#L578

The function `getExecutionResultFromSimulator ` doesn't exist when you load your web3 object from metamask

**Comment by yann300** [comment]
thanks for creating the issue, that is fixed (and should be already in live)
