### ISSUE TITLE
When deploying contracts, why would you not store the contract addresses so that they are available after closing the explorer?

### ISSUE THREAD

**Issue by stebansaa** [ethereum/remix-project#3343]
It will make life so much easier if that after deploying a contract there is an option to save the deployed address. It feels like such a basic feature, that perhaps I feel I may be missing a reason for this not to be the default.

**Comment by yann300** [comment]
a recent conversion with @ioedeveloper make me think  that saving a deployed contract should be up to the the user. so instead of auto saving, we would add an action to do the operation.

**Comment by yann300** [comment]
This issue is about storing contract addresses for later use. Saving the VM state is done in an another issue:
https://github.com/ethereum/remix-project/issues/3382
