### ISSUE TITLE
Home tab Start Coding

### ISSUE THREAD

**Issue by LianaHus** [ethereum/remix-project#3357]
add Start Coding button to get started
create helloWorld in current ws

**Comment by ryestew** [comment]
helloWorld.sol file it should be placed in the contracts folder not in the root.

**Comment by ryestew** [comment]
In FF on a mac, the FE is not loading.  I'm getting this error:
<img width="1131" alt="image" src="https://github.com/ethereum/remix-project/assets/6050001/6ae9d38e-6e00-4cef-887b-402ce7f7667f">
