### ISSUE TITLE
Flattened files not compiling

### ISSUE THREAD

**Issue by n3me5is-git** [ethereum/remix-project#3361]
The old flattener plugin was working good, the new embedded flattener is not working, it produces a solidity file that does not compile.
In my case I have a project that uses openzeppelin dependencies (NFT contract), che original file compiles, but the flattened version not. 

It seems that the functions are in a wrong order, so the interfaces are not before the implementations and so on. So the compiler throws an error. I'm sure it worked in the past with the old flattener plugin because I deployed the same code in the past, flattened it and successfully compiled it inside Remix and in bscscan too.

How to reproduce: create a NFT contract using openzeppelin dependencies, for example "contract MyContract is ERC721, ERC721Enumerable, ERC2981, Ownable" compile it, flatten it and then try to compile the flattened version.

**Comment by Alucial** [comment]
i have the same issue after going live on eth mainnet.
Can we get a quick patch to the old flattener?

**Comment by Aniket-Engg** [comment]
@Alucial can you share exact contract to quickly reproduce this issue? And what error compiler shows?

**Comment by n3me5is-git** [comment]
Here is a demo code to reproduce it. Try to compile this code, it will compile without issues.
Then right click and Flatten it.
Then try co compile the flattened version.

```
// SPDX-License-Identifier: MIT
pragma solidity ^0.8.15;

import "@openzeppelin/contracts@4.7.1/access/Ownable.sol";
import "@openzeppelin/contracts@4.7.1/token/ERC721/ERC721.sol";
import "@openzeppelin/contracts@4.7.1/token/ERC721/extensions/ERC721Enumerable.sol";
import "@openzeppelin/contracts@4.7.1/token/common/ERC2981.sol";
import "@openzeppelin/contracts@4.7.1/utils/Strings.sol";


contract MyNFT is ERC721, ERC721Enumerable, ERC2981, Ownable {

    using Strings for uint256;

    constructor() ERC721("MyNFT", "NFT") { }
    
    function _beforeTokenTransfer(address from, address to, uint256 tokenId) internal override(ERC721, ERC721Enumerable)
    {
        // DO SOMETHING
        super._beforeTokenTransfer(from, to, tokenId);
    }

    function _burn(uint256 tokenId) internal override(ERC721) {
        super._burn(tokenId);
    }

    function supportsInterface(bytes4 interfaceId) public view override(ERC721, ERC721Enumerable, ERC2981)
        returns (bool)
    {
        return super.supportsInterface(interfaceId);
    }

    // DO OTHER STUFF

}
```

The error when trying to compile the flattened version is:

```
TypeError: Definition of base has to precede definition of derived contract
--> Test.sol_flattened.sol:18:23:
|
18 | interface IERC2981 is IERC165 {
| ^^^^^^^
```

Basically the output flattened file is generated placing the input files in the wrong order, so the compilation is filing. And I suppose it will fail also when trying to verify the contract on the explorer.

Same code (more or less) deployed some months ago using the old plugin without issues. 

A minor improvement to do: add in the flattened file the same SPDX used in the file you are flattening.

**Comment by n3me5is-git** [comment]
I was able to use the old Flattener plugin using "Connect to local plugin" and using the following address: https://ipfs.io/ipfs/QmTX5ktywUaHSiEzdxf91C5gpE2MShpD1KxNmCd3Dzy1pR/
Reference: https://github.com/bunsenstraat/flattener/issues/1

This can be a temporary fix to generate flattened files

**Comment by joeizang** [comment]
@n3me5is-git. We are working on a fix. Very well done on the temporary fix. But we have found the issue and it will be in our next release. Apologies for all the trouble caused.

**Comment by Dark-Viper** [comment]
> The old flattener plugin was working good, the new embedded flattener is not working, it produces a solidity file that does not compile. In my case I have a project that uses openzeppelin dependencies (NFT contract), che original file compiles, but the flattened version not.
> 
> It seems that the functions are in a wrong order, so the interfaces are not before the implementations and so on. So the compiler throws an error. I'm sure it worked in the past with the old flattener plugin because I deployed the same code in the past, flattened it and successfully compiled it inside Remix and in bscscan too.
> 
> How to reproduce: create a NFT contract using openzeppelin dependencies, for example "contract MyContract is ERC721, ERC721Enumerable, ERC2981, Ownable" compile it, flatten it and then try to compile the flattened version.

i have the same issue. Wait do you think that's why they pulled the flattener. it was there like a minute ago, and viola it wasn't. Thanks for this complaint

**Comment by Aniket-Engg** [comment]
@n3me5is-git @Alucial @Dark-Viper Can you please check if it is working fine on http://remix-alpha.ethereum.org/ ?

**Comment by Dark-Viper** [comment]
> @n3me5is-git @Alucial @Dark-Viper Can you please check if it is working fine on http://remix-alpha.ethereum.org/ ?

it works! Great job Aniket! 👍

**Comment by Alucial** [comment]
Sorry I just saw this email.

I’ll send it over shortly.

I fixed it with another flattener
sol-merge 

And i think it was cos my contract compiled on solidity only on 0.8.17

**Comment by Aniket-Engg** [comment]
Okay. This is fixed and live now. So closing this
