### ISSUE TITLE
remix-ide/readme Documentation specifies incorrect (and non-functional) way to install remix-ide

### ISSUE THREAD

**Issue by intmainvoid** [ethereum/remix-project#337]
[The documentation](https://github.com/ethereum/remix-ide) currently states:

```
Install npm and node.js (see https://docs.npmjs.com/getting-started/installing-node), then do:

Remix-ide has been published as an npm module:

npm install remix-ide -g
remix-ide
```

This leads folks to believe that the correct way to install `remix-ide` is via npm. According to https://github.com/ethereum/remix-ide/issues/2970, this is no longer the case.

The documentation should be updated to specify the correct (ie. non-deprecated) way to install remix-ide.

**Comment by LianaHus** [comment]
Hi. [Here](https://github.com/ethereum/remix-project) is the new readme. We moved all remix projects to one monorepo.
@ryestew I guess we should update the old readme

**Comment by ryestew** [comment]
This is to update the readme of the remix-ide repo.  Though this repo's readme now has a warning on it that it has moved to remix-project.  But we should probably update the remix-ide/readme.md with the correct info or take down the incorrect info.
