### ISSUE TITLE
Cann't load compiler

### ISSUE THREAD

**Issue by basdevelop** [ethereum/remix-project#340]
Cannot load compiler version list. It might have been blocked by an advertisement blocker. Please try deactivating any of them from this page and reload. Error: SyntaxError: Unexpected end of JSON input

**Comment by LianaHus** [comment]
hi @basdevelop, I assume this issue was temporary, can you confirm it works well now?

**Comment by basdevelop** [comment]
It's ok now, maybe that's because of  the bad internet connection, sorry to bother you .
