### ISSUE TITLE
Deploy & Run - Custom fork - Remix VM erroring on deployment

### ISSUE THREAD

**Issue by ryestew** [ethereum/remix-project#3409]
To duplicate:
1. In the Environment section choose Remix VM custom fork
2. In the modal's Node URL, input: https://bsc-dataseed1.binance.org  (or any other you'd like- chainlist.org will help) and the same problems happens if you to fork goerli: https://goerli.blockpi.network/v1/rpc/public  and leave the rest of the select boxes to their defaults.
4. Hit Connect & the chain will get forked and the accounts will get populated
5. Then deploy to that forked chain (or any other) and you'll see:

<img width="651" alt="image" src="https://user-images.githubusercontent.com/6050001/220480555-e1d38bbe-692a-4fca-8d02-3e21e7e9671e.png">

Maybe the default should be Merge and not Chainstart.
Similarly:
If you choose Remix VM custom fork and use goerli: https://goerli.blockpi.network/v1/rpc/public and use the Merge as the flavor of VM and then deploy, you'll get this error because that 1st account had 0ETH in it:

```
creation of Owner errored: sender doesn't have enough funds to send tx. The upfront cost is: 3000000 and the sender's account (0x5b38da6a701c568545dcfcb03fcb875f56beddc4) only has: 0 (vm hf=merge -> block number=0 hash=0x2762f1acf3de924199ee33dd0ec1a4de808c4e6ae566cd0a7fcefc01b3dfc5d1 hf=merge baseFeePerGas=1 txs=1 uncles=0 -> tx type=2 hash=0x14fee5e7be51327b9dc3fdeea33b7a4b0fb7b3cd1a70b6a253ed4641bdc675d8 nonce=356 value=0 signed=true hf=merge maxFeePerGas=1 maxPriorityFeePerGas=1)
```

**Comment by yann300** [comment]
> nd leave the rest of the select boxes to their defaults.

the EVM box has to be the one that fit with the network targeted by the URL.
we could by default set it to "merge"

**Comment by ryestew** [comment]
I just came to the same conclusion.  Set default to Merge would be a good idea.
