### ISSUE TITLE
Remix use all of my CPU

### ISSUE THREAD

**Issue by VieYang** [ethereum/remix-project#341]
When I visit https://remix.ethereum.org/, after working for a while,  It use all of my CPU.

At this time, when I try to close the tab, ohhhhhh, Chrome stuck.

```
OS: windows 10
Browser:  Chrome 84.0.4147.105 (64)
CPU:  Intel Core i7
RAM: 16GB
```

**Comment by LianaHus** [comment]
hi. could you please add more details? what exactly do you do in remix when this happens?

**Comment by VieYang** [comment]
Just open and wait, but I can't reproduce  it now.

@sinsinpurin Can you reproduce this problem?

**Comment by sinsinpurin** [comment]
It occurred when opening many chrome tabs and standing for time

**Comment by yann300** [comment]
@VieYang @sinsinpurin 
could you please verify you are still experiencing this issue?

**Comment by VieYang** [comment]
not now, close this comment. thank you.

**Comment by bokkypoobah** [comment]
Been monitoring Chromium memory usage for the last 10 hours and there has been no issues. Thx for fixing!
