### ISSUE TITLE
Delete All Workspaces modal

### ISSUE THREAD

**Issue by ryestew** [ethereum/remix-project#3419]
On the Delete All Workspaces modal - it currently looks like this:
<img width="498" alt="image" src="https://user-images.githubusercontent.com/6050001/220674831-3b772f57-53b9-4c3d-9d7c-c82d3ca4201d.png">

1. It needs a button to cancel.  The text on the button should be "Cancel the delete"  or something as explicit as that.
2. The text should be altered slightly.  There should be a line break between the 2 sentences.  And the second sentence should be:
Deleted workspaces can not be restored.

or 

Once a workspace is deleted it cannot be restored.

**Comment by LianaHus** [comment]
1. is a duplicate. see #3417
2. Will update for this release
