### ISSUE TITLE
provider plugins are visible in plugin manager

### ISSUE THREAD

**Issue by Aniket-Engg** [ethereum/remix-project#3426]
![Screenshot 2023-02-23 at 12 21 03 PM](https://user-images.githubusercontent.com/30843294/220837934-c9ee388f-f23a-4799-b108-c5ae6ccbbe5f.png)

I think they should not be visible in plugins list

**Comment by yann300** [comment]
This should already be fixed

**Comment by Aniket-Engg** [comment]
it is
