### ISSUE TITLE
Social Icons not responsive

### ISSUE THREAD

**Issue by uday03meh** [ethereum/remix-project#3443]
Hi, I was testing the beta version for Remix IDE and it seems that the social icons are not responsive on smaller screen sizes

![image](https://user-images.githubusercontent.com/59679281/221419647-2f6d0878-0943-46ee-b9f9-32ef37921ad9.png)

I can work on it and fix this issue, please assign it to me.

**Comment by Aniket6990** [comment]
I'm also facing same issue.
