### ISSUE TITLE
Remix 0.30 and 0.31 breaks fresh ERC20 workspace

### ISSUE THREAD

**Issue by kvutien** [ethereum/remix-project#3457]
Steps to produce issue:
- go to Workspace and create fresh ERC20 workspace (Mintable, Burnable)
- go to Solidity compiler and compile successfully `MyToken.sol` to populate the folder `.deps` with `@openzeppelin`
- go to Solidity compiler and compile `MyToken_Test.sol` 

Expected result:
- compile successful
- it was the case in Remix 0.29

Actual result:
- parser error: `ERC20.sol not found` in `MyToken.sol` and several similar.

Importance:
- Major for my students. They can't complete their assignment. Any work around please?

**Comment by ryestew** [comment]
Thanks for reporting this.  I am trying to recreate the problem, but it is working for me - on both Firefox & Chrome.
I see the erc20 in the file explorer:
![image](https://user-images.githubusercontent.com/6050001/221921421-de2eebdd-702a-4274-8a2a-7f19862282fd.png)

Are you seeing this file in the .deps folder?

**Comment by kvutien** [comment]
@ryestew Thank you for having checked and for your feedback.

Yes I also see the files :-) and also does the parser of `MyToken.sol`. It compiled perfectly well.

It's the parser of `MyToken_Test.sol` that complaints that it doesn't see them when I compile this contract, saying it's a `deferred import` not found. BTW, I tried changing the version of the Solidity compiler but I got the same error message.

It happened in Safari 16.3 on a M1 MacBook Pro running macOS Ventura 13.2.1, and in Firefox 109.0.1 on a MacBook Pro Intel running macOS Mojave 10.14.6.

**Comment by kvutien** [comment]
This is a question I haven't found on Stack Exchange: 

_is there any way to force the Remix IDE to load a specific version, 0.29.6 for example?_ 
preferably not using the desktop version. It's for a training where no previous installation is foreseen.

it could be a workaround for the current versions 0.30 and 0.31 where the Solidity parser chokes on `MyToken_Test.sol`. It complaints that it can't find a `deferred import` in `MyToken.sol`, although the latter compiles perfectly and finds the imported `@openzeppelin` files.

**Comment by ryestew** [comment]
Thanks for updating the issue.  Unfortunately there isn't a way to target a specific release.  
Also, please not use Safari or Edge with Remix - they are supported.

Could you check Chrome or Brave for this issue?  I can replicate your issue in FireFox but it is working fine (for me) in Chrome.

**Comment by ryestew** [comment]
@Aniket-Engg - this is an issue with FireFox when compiling `MyToken_Test.sol` - see above for more details.

**Comment by kvutien** [comment]
thanks @ryestew .

You might be interested to know that I have also the same bug for Remix 0.31.2, in Chrome Version 111.0.5563.64 (Official Build) (arm64), macOS 13.2.1
![99-Bug also in Chrome](https://user-images.githubusercontent.com/32614226/223693553-b5448115-70b9-4621-8071-cdb569bf08e1.jpg)

I believe that Brave has the same rendering engine as Chrome, so the bug is likely to hold also there? Anyhow, now we have this bug in Safari

**Comment by kvutien** [comment]
Cool. Thanks.

**Comment by kvutien** [comment]
You might be interested to know that I tried on the current Remix 0.32.1. with the latest Chrome on macOS Venture 13.2.1, MacBook Pro M1.
The file `MyToken_test.sol` still has the same 4 parser error messages.

**Comment by yann300** [comment]
yes it hasn't been released, yet. Please try with https://remix-alpha.ethereum.org

**Comment by kvutien** [comment]
I tried the alpha version and it works.
Folks, don't blush but indeed you are wonderful 👏
Now I wait for the public version.

**Comment by kvutien** [comment]
The new version 0.32.0 made the issue disappear.
Folks, you are wonderful.
-- 
There is still a warning in `remix_accounts.sol`, but it's only a warning and probably you are aware of it?
<img width="615" alt="image" src="https://user-images.githubusercontent.com/32614226/229611538-3427da15-b227-4175-9fe4-e27f093d43d7.png">
I'll restart doing my tutorial how to use Remix for humanitarians. Thanks.

**Comment by yann300** [comment]
> I'll restart doing my tutorial how to use Remix for humanitarians. Thanks.

sounds interesting, can you expand a bit what  you are doing? feel free to drop a mail at remix@ethereum.org

**Comment by kvutien** [comment]
Hello yann300,

Very kind of you, to be interested in Machu Picchu.

The white paper of Machu Picchu is here. https://github.com/kvutien/Project-Machu_Picchu_White_Paper_Tutorial2023

As you can observe there,  the white paper's companion is a Solidity coding tutorial how to get one's feet wet, using Remix. 

The tutorial first stage explains the Remix' default workspace.
I'm preparing the second stage, using the ERC20 workspace, and was blocked there because of the bug in the test folder. Now I'm resuming.
The 3rd stage will be using ERC721.
Then I'll add Metamask to Remix, and maybe use Polygon Mumbai.

It would be lovely when you have ready a workspace using ERC4337. This will ease onboarding the persons-in-need.

Best.
-- 
Vu Tien Khang 
Machu Picchu
https://www.linkedin.com/in/kvutien/
