### ISSUE TITLE
Path in remixd

### ISSUE THREAD

**Issue by bunsenstraat** [ethereum/remix-project#3460]
On electron remixd spawn doesn't have the right path environment to execute commands like npx.  Basically process.env doesn't have the default paths when electron is executed as a standalone GUI. This is due to the shell it inherits from. It can be fixed in several ways. Another option can also be to let the user provide a .env file in the workspace if the path can't be found.

**Comment by yann300** [comment]
in which case do you need remixd to execute `npx`?

**Comment by yann300** [comment]
what's the bug that this issue reveal?

**Comment by bunsenstraat** [comment]
https://github.com/ethereum/remix-project/blob/42872eb3c2109d327377758c5706c22b105d705c/libs/remixd/src/services/hardhatClient.ts#L57

When you run compile with hardhat compile enabled in remix desktop it fails, npx is not found. 
The default path it sees is: "PATH":"/usr/bin:/bin:/usr/sbin:/sbin"
Npx could be in usr/local/bin or in homebrew bins on mac.
