### ISSUE TITLE
Issues connecting Coinbase Wallet with Injected Provider

### ISSUE THREAD

**Issue by taycaldwell** [ethereum/remix-project#3461]
When attempting to connect using the Injected Provider option for Coinbase Wallet:

1. Multiple connect confirmation windows pop-up.
2. The connected network is not detected, despite connecting to the dapp.

**Comment by taycaldwell** [comment]
@yann300 @bunsenstraat Here is the behavior I'm seeing.

https://user-images.githubusercontent.com/3264051/222920568-bc78164c-d2fc-401b-a0e7-ad3f9fec407d.mov

**Comment by bunsenstraat** [comment]
thanks for the report!
