### ISSUE TITLE
default icon for plugins without a logo

### ISSUE THREAD

**Issue by LianaHus** [ethereum/remix-project#3466]
![Screenshot from 2023-02-28 13-13-04](https://user-images.githubusercontent.com/9685356/222129005-31665ac7-ab7e-4849-a9ea-394ee346768c.png)

**Comment by ArslanYM** [comment]
Can you explain the bug and how we can fix it ?

**Comment by ArslanYM** [comment]
On it

**Comment by Aniket-Engg** [comment]
fixed by #4324
