### ISSUE TITLE
copy to clipboard copy wrong address

### ISSUE THREAD

**Issue by yann300** [ethereum/remix-project#3512]
- switch to injected
 - "copy to clipboard" the account address in remix, this is the right one
 - select another account in metamask
 - the account is changed in the dropdown list
 - click on "copy to clipboard", the copied account is still the previous one

**Comment by joeizang** [comment]
![replicated bug](https://user-images.githubusercontent.com/4255962/226358871-155c3ce1-abf2-43af-a177-ac17efa326e8.png)
I was able to replicate the bug following @yann300 instructions.

**Comment by Aniket-Engg** [comment]
I could not reproduce it

**Comment by LianaHus** [comment]
I'm adding this to this release, but feel free to move it to the next one once it is created.

**Comment by Aniket-Engg** [comment]
@LianaHus are you able to reproduce it?
