### ISSUE TITLE
Deploy iframe plugins with CI etc

### ISSUE THREAD

**Issue by bunsenstraat** [ethereum/remix-project#3534]
In order to deploy 'external' iframe plugins from the mono-repo & CI and have alpha/beta versions:

1 add _optional_ fields to the plugin directory profile: 'alpha', 'beta' that contain urls to the alpha/beta deploys ( ipfs or otherwise )
2 CI runs a deploy plugin script from a matrix ['etherscan', 'ethdoc' ] based on branch ( alpha, beta, master )
3 this script will:
- take the profile.json which is in the apps/ethdoc etc if it exists, otherwise, nothing happens
- upload a new build to IPFS or otherwise
- compare the hash to the one in the public directory
- if it changed, update the plugin directory with a PR containing the new profile
- the PR then needs to be approved or we force push ( optional )

4. IDE running on alpha/beta will load the alpha/beta versions if they are available, if not it loads the default

There is a script already in the plugin directory which can be adopted to do this.

**Comment by yann300** [comment]
that sounds about right!
