### ISSUE TITLE
Tool tips on file name not needed

### ISSUE THREAD

**Issue by ryestew** [ethereum/remix-project#3539]
- [ ] in the FE: The tooltips that show a filenames name are "overly" redundant:
<img width="185" alt="image" src="https://user-images.githubusercontent.com/6050001/226630480-9936d764-99a6-4d3d-84cc-9dedb59ccd09.png">

- [x] In the Plugin Manager - the documentation icon is helpful for the tooltip - but the activate button does not need a tooltip. (it doesn't hurt - but it seems a bit too much).

**Comment by LianaHus** [comment]
1. this is removed but the reason we had it it was useful for long file names.
2. it says 'activate _plugin name_' . I think we can keep it.

**Comment by LianaHus** [comment]
1st will be fixed here https://github.com/ethereum/remix-project/issues/4046
