### ISSUE TITLE
UML Download is squished

### ISSUE THREAD

**Issue by ryestew** [ethereum/remix-project#3541]
This is the download from this PR: https://github.com/ethereum/remix-project/pull/3395

The aspect ratio gets squished in the download:
<img width="880" alt="image" src="https://user-images.githubusercontent.com/6050001/226700402-d5eb090f-33ea-4a48-921e-2b680be103a5.png">

I tried it with and ERC20 contract downloading the PDF.  The PNG file is fine.

**Comment by joeizang** [comment]
Tested this on my system and couldn't replicate it @ryestew on alpha. was this bug seen on localhost or another environment?
