### ISSUE TITLE
Free Functions right click menu item(s)

### ISSUE THREAD

**Issue by ryestew** [ethereum/remix-project#3550]
- [ ] when you right click on the word "function" in a free function, you get the menu items about running the function, but if right clicked on the **name of the function** before trying to click on the word "function", the menu item "Run a free function... " does not always come up.  If you wait a few seconds before right clicking on the name of the function, it does come up.  If you right click on other code inside the function, the "Run" menu items don't always come up.
- [x] There are 2 menu items and there should be only one:

<img width="436" alt="image" src="https://user-images.githubusercontent.com/6050001/227316951-c78ca2c2-3e78-4fd2-b176-e40e471f7c12.png">

**Comment by yann300** [comment]
> when you right click on the word "function" in a free function, you get the menu items about running the function, but if right clicked on the name of the function before trying to click on the word "function"

the main issue here is that in order to use that feature, the code needs to be parsed, which take a bit of time... knowing that could you retry to reproduce it?
