### ISSUE TITLE
Error on Fix generating unit-tests accounts 

### ISSUE THREAD

**Issue by ryestew** [ethereum/remix-project#3567]
When testing https://github.com/ethereum/remix-project/pull/3508 
I sometimes get this error:
<img width="1046" alt="image" src="https://user-images.githubusercontent.com/6050001/228127085-a1916186-6e7b-48b0-b198-13b1b932ac0f.png">

**Comment by yann300** [comment]
when the test plugin loads, it creates the `remix_accounts.sol` but at this point the udapp isn't properly activated so it can't retrieve the list of accounts. But when the test run it will provide the right account list.

**Comment by yann300** [comment]
note that this isn't an error but a warning
