### ISSUE TITLE
Error "transact to Contract.function errored: NotFound" when using blockhash

### ISSUE THREAD

**Issue by niccolopetti** [ethereum/remix-project#3588]
Here is a minimal code to reproduce the error:

```
pragma solidity ^0.8.17;

contract A{

        function foo() public view returns(bytes32){

        return blockhash(block.number - block.basefee);
    }

}
```

calling function foo from remix gives
```
call to A.foo
call to A.foo errored: NotFound
```

**Comment by Aniket-Engg** [comment]
![Screenshot 2023-04-03 at 7 37 29 PM](https://user-images.githubusercontent.com/30843294/229534147-936e8e07-5ee4-4a2b-b700-4f04c0ff5e1b.png)

This works fine for me.

**Comment by niccolopetti** [comment]
Can you try deploying multiple instances and trying interacting again?

![image](https://user-images.githubusercontent.com/22686876/229578558-3c7370fc-aa22-4517-9830-d993cfaaca28.png)

I just tried deploying again and at first it worked, then deploying another instance and calling the function on the new instance reproduced the issue for me, 
Ps: I'm deploying to Remix VM (Merge) chain in case it matters for reproducing the error

**Comment by Aniket-Engg** [comment]
Oh I see. I can reproduce it with second instance.
