### ISSUE TITLE
Etherscan Plugin Improvement and fixes

### ISSUE THREAD

**Issue by Aniket-Engg** [ethereum/remix-project#3597]
As per current status:
- [x] Nothing happens on clicking icons if no API key provided. Actually that is a feature but user has no idea what to do next.
- [x] After providing API key, clicking on Save, no message appears.
- [x] No check on API key length

**Home Tab:**
- [x] Form validation improvement, unnecessary cross icon
- [x] Show constructor arguments field conditionally if required
- [x] Show error in red. 
- [x] Show selected network in the plugin itself in read-only text

**Receipts:**
- [x] Requests seems to pending in queue forever

**Settings:**
- [x] Show API key in dots

**Comment by yann300** [comment]
- Unable to verify contracts which has openzeppelin imports.
 - Unable to verify contracts that uses proxy.

**Comment by LianaHus** [comment]
- [ ] titles
- [ ] font awsome icons instead of svg's

**Comment by Aniket-Engg** [comment]
- [ ] Add a user-friendly way for encoded constructor arguments
