### ISSUE TITLE
Display a warning in udapp that the evmversion should match the current network fork.

### ISSUE THREAD

**Issue by yann300** [ethereum/remix-project#3628]
The warning should be displayed:
 - when the current network isn't "1" (mainnet)

The warning should state something like:
"Please make sure that the current network you deploy to is compatible with the evm version {evm version} . Otherwise any deployment will fail."

**Comment by LianaHus** [comment]
I'm opening the issue to improve the UI

Working version:
![Screenshot from 2023-06-20 13-14-08](https://github.com/ethereum/remix-project/assets/9685356/80745423-7db6-46e3-b3ac-942373e28603)

@aniket suggested trying shorter names. To be discussed in UX meeting

**Comment by Aniket-Engg** [comment]
closed by #3895
