### ISSUE TITLE
Remix-alpha. udapp.sendTransaction. Uncaught Error: The data field must be HEX encoded data.

### ISSUE THREAD

**Issue by loredanacirstea** [ethereum/remix-project#363]
On Remix-alpha: since this morning I cannot send transactions through `remixclient.udapp.sendTransaction` for “Injected Web3” and “Web3 Provider” - fails with `The data field must be HEX encoded data.`, even though the data is correctly hex encoded.
Sending the same transaction on the Javascript VM works.

<img width="1274" alt="Screen Shot 2020-08-18 at 11 09 04 AM" src="https://user-images.githubusercontent.com/4785356/90488250-4d5a2300-e144-11ea-868f-0cd619dca229.png">

**Comment by LianaHus** [comment]
https://github.com/ethereum/remix-project/issues/364

**Comment by yann300** [comment]
@loredanacirstea could you post here the transaction you are trying to send? thanks

**Comment by loredanacirstea** [comment]
The "works on JS VM" was a red herring. Indeed, the bytecode was malformed:
`610188600f600039610188600000f360c0604052600c36610145565b3660008237601b610100610145565b816020820152600060408201528060605260326047565b61010081015150610120810151505050610188565b60605160208101516040820151600051600a8111156069578060005260206000f35b6001810160005250607982610158565b6003608384610169565b60808601528060a08601528081141560c557609d8261017a565b60ab60206001830102610145565b8181528160c0880152600060e08801528061010088015250505b60cf610100610145565b9150848252600884016020830152826040830152816060528060a06060515101511494505050505080156101065780506101066047565b805050606051805161010082015150610120820151508060605260006000925050816101008201528161012082015250505b565b600060405190505b90565b600060405190508181016040525b919050565b6000815160e061____90505b919050565b6000815160c061____90505b919050565b6000603f821690505b91905056`.

So, @LianaHus is right to link https://github.com/ethereum/remix-project/issues/364. 

I should have checked, sorry! Closing both of them.
