### ISSUE TITLE
Matomo on FE context menu cleanup

### ISSUE THREAD

**Issue by ryestew** [ethereum/remix-project#3633]
General comment
So when making a new name  for the context menu or cleaning up a name in the context menu, how does this affect tracking the data.  Of course missing a month of data with the name change is not a big deal.

Generate UML
The event name solidityumlgen/generateCustomAction should be solidityumlgen (without the /generateCustomAction

Flattener
There are 2 event names (the 4th parameter in the _paq object) for the flattener:
contractflattener/flattenAContract  contractflattener
These need to be cleaned up/ organized so there is only 1 - or I just need to know which is the one I should now be monitoring.

**Comment by yann300** [comment]
we need to make sure we have all the info to reconstruct the matomo history.
