### ISSUE TITLE
Matomo bug: Workspace in localstorage not found: code-sample

### ISSUE THREAD

**Issue by ryestew** [ethereum/remix-project#3635]
This looks like it is catching a bug in the code.  Please investigate.

you can find this in Matomo: events / Event Names

<img width="659" alt="image" src="https://user-images.githubusercontent.com/6050001/232824865-afc66ca2-b678-498b-9cfa-642a721e253b.png">

**Comment by bunsenstraat** [comment]
by the item I mean the name of 'current workspace' which is stored in localstorage and then loaded on boot.

**Comment by ryestew** [comment]
There is no work to be done on this issue.  @bunsenstraat - your last comment mean that the user deleted the workspace and then reloaded?  Or more generally - whatever the reason, the workspace cannot be found.  What would be the user's behavior that would trigger this?

**Comment by bunsenstraat** [comment]
well most likely the browser reset the indexeddb. it happens and is completely unpredictable, mostly due to lack of diskspace or them cleaning up.
