### ISSUE TITLE
How can i input  a string of JSON in remix

### ISSUE THREAD

**Issue by BaZahei** [ethereum/remix-project#3655]
In my project, I need to send a JSON string to the contract, but remix doesn't seem to recognize double quotes
![image](https://user-images.githubusercontent.com/29537332/234520572-5b05ac4f-1231-4581-8112-c7fffd78a402.png)

I got the error

Error encoding arguments: Error: types/values length mismatch (count={"types":3,"values":6}, value={"types":["address","string","string"],"values":["0x5B38Da6a701c568545dCfcB03FcB875f56beddC4","”{",":{",":","}}“","1"]}, code=INVALID_ARGUMENT, version=abi/5.5.0

**Comment by BaZahei** [comment]
update error

Error encoding arguments: Error: types/values length mismatch (count={"types":3,"values":7}, value={"types":["address","string","string"],"values":["0x5B38Da6a701c568545dCfcB03FcB875f56beddC4","","add","delta","1","","1"]}, code=INVALID_ARGUMENT, version=abi/5.5.0)

**Comment by Aniket-Engg** [comment]
Use it like `"{'add':{'delta':'1'}}"`

**Comment by Aniket-Engg** [comment]
Closing it. Feel free to reopen if issue persists.
