### ISSUE TITLE
Matomo: Slither Static Analysis

### ISSUE THREAD

**Issue by ryestew** [ethereum/remix-project#3670]
this line:
 _paq.push(['trackEvent', 'solidityStaticAnalyzer', 'analyze', 'slitherAnalyzer'])
does not seem to be tracking any events.

There should be some usage of slither.

**Comment by yann300** [comment]
I see: 

![remix](https://user-images.githubusercontent.com/6940742/235876918-dc5e183a-9f93-476e-9c7d-28b26268769b.png)
