### ISSUE TITLE
No warning in terminal when an bytes32 input is the wrong length

### ISSUE THREAD

**Issue by ryestew** [ethereum/remix-project#3684]
When testing https://github.com/ethereum/remix-project/pull/3650
I input a bytes32 of the wrong length and only way I found that there was a problem with my input was by going to the console to see the error.  This error should show in the terminal.

**Comment by drafish** [comment]
It's not just bytes32. You can try a function with two parameters, and input one parameters, you will find the same issue. 

https://github.com/ethereum/remix-project/pull/3650/files#diff-885bce4d314b6b7451fb4116970c82e7ec325db5ec23d7b2beab85e69dc3c530

https://github.com/ethereum/remix-project/pull/3650/files#diff-a2d8c5d26e33172b42d484368629a7b5e71d0507a238cce20e0f7ee86a4bd6d1R68

Check these two links. That's the code that cause this issue. The `encodeParams` was converted to `Promise`, and the rejected error is not be catched.

I fixed this issue in brochain ide. I will submit a pr for remix.

**Comment by Aniket-Engg** [comment]
fixed by #3912
