### ISSUE TITLE
Network Error

### ISSUE THREAD

**Issue by waiinu8798** [ethereum/remix-project#3686]
When using ETHERSCAN - CONTRACT VERIFICATION Plugin and trying to verify on Arbitrum

**Comment by ramagumilar** [comment]
can use all networks during transactions but the results are pending and when selecting the network that has been determined the results are successful, so for this you need to connect and sign in to a wallet/address and when the web is closed and a few moments later it is opened and the connection goes straight to when the wallet/address is directly connected to the wallet/address that was first connected and has signed in to the wallet and when different networks can change the network automatically
