### ISSUE TITLE
Wallet connect environment cannot detect 43113 Fuji chain after switching 

### ISSUE THREAD

**Issue by aboklag** [ethereum/remix-project#3692]
![image](https://user-images.githubusercontent.com/100861811/236794647-a61eb163-c7e5-4c31-8b80-5eb7352bccd4.png)
1 I connect using wc
2 switch to fuji in iphone metamask application

**Comment by ioedeveloper** [comment]
@aboklag Fuji chain is not supported on remix-walletconnect plugin. Here is a list of supported networks: arbitrum, arbitrumGoerli, mainnet, polygon, polygonMumbai, optimism, optimismGoerli, goerli and sepolia. I will close this issue if there are no issues detected using the supported networks.

**Comment by pulokpanditblock8** [comment]
`Here is a list of supported networks: arbitrum, arbitrumGoerli, mainnet, polygon, polygonMumbai, optimism, optimismGoerli, goerli and sepolia.`

What is the procedure to add more to this list?
