### ISSUE TITLE
WalletConnect is not updating Deploy & Run

### ISSUE THREAD

**Issue by ryestew** [ethereum/remix-project#3705]
Even though this was tested - I am now seeing a problem - walletConnect on my phone and in the plugin is not that same as what is showing in Deploy&Run.

<img width="1136" alt="image" src="https://github.com/ethereum/remix-project/assets/6050001/6843db72-3c9e-4f21-bf73-6f0fe9a4cdc2">

but after I change the network on the phone a few times, it syncs.

**Comment by yann300** [comment]
you mean the balance isn't the same? I think the balance get updated every 20s , so this might take time.

**Comment by ryestew** [comment]
not the balance - but that WalletConnect is on goerli and Deploy & Run Environment shows Mainnet
