### ISSUE TITLE
FE and Workspace menu UI Improvements from Q1 User Interviews/Testing

### ISSUE THREAD

**Issue by vermouth22** [ethereum/remix-project#3714]
- [x] Move Hamburger menu next to Workspaces title, either right or left. Users do not know it exists or is for Workspaces navigation. Plus icon can be removed as it is redundant.

- [ ]  Increase contrast on icons on vertical bar. Users cannot see they are navigable, thinking they are inactive because they are dark grey. Consider matching the color of Hamburger menu and titles. 

- [ ]  Either keep active icon white or consider using an "active" background that is darker than rollover state. Or, use both white icon as active AND add active background.

See attached comps for options on above points:
<img width="468" alt="Workspaces_hamburger_left_corner_live_icon_white" src="https://github.com/ethereum/remix-project/assets/35277634/25ee970d-1801-45fb-b2d1-5a2d9747b1dd">
<img width="468" alt="Workspaces_hamburger_right_active_icon_with_background copy" src="https://github.com/ethereum/remix-project/assets/35277634/2dde6379-9423-4227-aa27-fae0ab6d27be">

**Comment by yann300** [comment]
https://github.com/ethereum/remix-project/pull/3707 is fixing 1.

**Comment by LianaHus** [comment]
this need to discuss.

**Comment by LianaHus** [comment]
@vermouth22 closing this. If the current solution is not enough, please open a new discussion/issue.
