### ISSUE TITLE
source highlight of not active plugins should be removed

### ISSUE THREAD

**Issue by LianaHus** [ethereum/remix-project#372]
debugging -> solidity tab, editeng
the highlight should be removed if debugger is not in focus/active

**Comment by LianaHus** [comment]
discussed on standup: behavior for
1. for the plugins in sidePanel - remove when not active
2. for hidden plugins - later if needed
3. for mainPanel plugins - later if needed

**Comment by yann300** [comment]
fixed by https://github.com/ethereum/remix-project/pull/526
