### ISSUE TITLE
Custom error not working correctly.

### ISSUE THREAD

**Issue by amit-supraoracles** [ethereum/remix-project#3765]
Hello Members!

Custom Error is not working same as in VM and Testnet(Sepolia, Goerli..etc).
The caller will not get the reason behind why the function call is failing.

Following snippet works as expected in VM but when deployed in Sepolia...Does not provide which custom error was triggered...
```


// SPDX-License-Identifier: GPL-3.0
pragma solidity ^0.8.19;

contract Test {

    error InvalidAddressError();
    error InvalidAddressWithParamError(address _addr);
    
    function checkCustom() public pure returns (bool){
        address _input = address(0); 
        if (_input == address(0)) revert InvalidAddressError();
        return true;
    }

    function checkRequire() public pure returns (bool){
        address _input = address(1);

        require(_input == address(0), "############ Address must be non zero");
        return true;
    }

    function checkCustomParametrised() public pure returns (bool){
        address _input = address(4);

        if (_input != address(0)) revert InvalidAddressWithParamError(_input);
        return true;
    }
   
}
```

**Comment by Aniket-Engg** [comment]
I can reproduce this. 
With VM, it shows:
```
revert
	The transaction has been reverted to the initial state.
Error provided by the contract:
InvalidAddressWithParamError
Parameters:
{
 "_addr": {
  "value": "0x0000000000000000000000000000000000000004"
 }
}
Debug the transaction to get more information.
```

and with Sepolia:
```
call to Test.checkCustomParametrised errored: Returned error: {"jsonrpc":"2.0","error":"execution reverted","id":3144465169327109}
```

**Comment by 0xV4L3NT1N3** [comment]
Bumping this, Etherscan supports custom errors for verified contracts on mainnet + testnets

https://twitter.com/etherscan/status/1452955443991494661

**Comment by 0xV4L3NT1N3** [comment]
@Aniket-Engg could this be due to checking for custom errors using `checkVMError` only on VM simulations and not on live networks ?

https://github.com/ethereum/remix-project/blob/9d466a19e18736158c54eecf03a9c76ccf493e5b/apps/remix-ide/src/blockchain/blockchain.tsx#L913C18-L913C18
