### ISSUE TITLE
function name got sliced in Udapp

### ISSUE THREAD

**Issue by Aniket-Engg** [ethereum/remix-project#3767]
![Screenshot 2023-06-07 at 1 24 59 PM](https://github.com/ethereum/remix-project/assets/30843294/8e30ccfc-8999-4ab2-9134-45640838b46c)

**Comment by joeizang** [comment]
I think the name of the functions are longer than the button allows for. Maybe we use an ellipsis and show the full button/function name in a tooltip?

**Comment by Aniket-Engg** [comment]
Full name is already visible on tooltip. But having a sliced string on UI doesn't look right to me.

**Comment by himanshupal** [comment]
Hi, I made a few changes locally for this, initially it looks the same, but on expanding the sidebar it expands to show full function name now, lmk if it looks okay (SS attached below)

---

![image](https://github.com/ethereum/remix-project/assets/40417771/81e32279-cb04-4df0-a116-13a0aa3f4057)
![image](https://github.com/ethereum/remix-project/assets/40417771/57ea3864-6e89-4e41-9a63-20fd197a9fa3)

**Comment by ranjansmygit** [comment]
needful could be done at 
libs/remix-ui/run-tab/src/lib/css/run-tab.css
