### ISSUE TITLE
SUT Checkboxes should have custom style

### ISSUE THREAD

**Issue by LianaHus** [ethereum/remix-project#3790]

**Comment by AnuragNishad12** [comment]
hey @LianaHus can u tell me more about this issue?

**Comment by Aniket-Engg** [comment]
@LianaHus Can you add more details about implementation?

**Comment by LianaHus** [comment]
they should have the same style as "listen on all transactions"'s checkbox on terminal title bar

![Screenshot from 2023-08-29 13-17-29](https://github.com/ethereum/remix-project/assets/9685356/206a04d0-c817-4177-a1bc-7c0f84f2d9be)

|
 V

![Screenshot from 2023-08-29 13-17-05](https://github.com/ethereum/remix-project/assets/9685356/f6bb9a1b-da7d-4b3f-85a4-62bd0a17b13b)
