### ISSUE TITLE
error on new workspace creation (alpha)

### ISSUE THREAD

**Issue by ryestew** [ethereum/remix-project#3792]
I get this modal when there is a new workspace:
<img width="496" alt="image" src="https://github.com/ethereum/remix-project/assets/6050001/dfff7c69-8ada-422e-b51f-64253283bece">

**Comment by yann300** [comment]
please try refresing the cache, or clear the cache, is this happening in incognitto mode?

**Comment by ryestew** [comment]
its not happening in incognito mode.
its not happening in FF
its not happening when I open another window in Chrome with Remix

So this issue is something to watch it could be related to the issue: 
https://github.com/ethereum/remix-project/issues/3793
Both were happening on the same browser window.

**Comment by yann300** [comment]
ok, if you don't mind I 'll close, but reopen if think it's better.
