### ISSUE TITLE
occasionally cannot access address in remix vm (on alpha)

### ISSUE THREAD

**Issue by ryestew** [ethereum/remix-project#3793]
Refreshing fixes this but still
<img width="304" alt="image" src="https://github.com/ethereum/remix-project/assets/6050001/cca2a9ea-a85f-481b-928d-ef22cbec473f">

**Comment by yann300** [comment]
when you've got that issue again, please check if there are any error in the javascript console.

**Comment by yann300** [comment]
close cause unable to reproduce, please reopen it if necessary
