### ISSUE TITLE
Etherscan plugin has a confusing workflow for Proxy contracts

### ISSUE THREAD

**Issue by ryestew** [ethereum/remix-project#3797]
The etherscan plugin has this info modal pop up when hovering over the i icon.

<img width="323" alt="image" src="https://github.com/ethereum/remix-project/assets/6050001/2e0469ff-955d-45e1-bc03-88cb1ec855e6">

In the proxy contract - at least in our docs, the implementation contract refers to contract that imports the eip 1967 - like the first contract below:

<img width="295" alt="image" src="https://github.com/ethereum/remix-project/assets/6050001/ea674a22-94d1-4ecb-bb28-d481be89f02c">

and the second is the proxy contract.

So the interface looks like it is for verifying both at the same time - but the i icon info reads like you need to verify that one before the proxy - but its not clear how to verify that first.   Or maybe I am getting confused by the It's a proxy contract checkbox.  Because the impementation is not the proxy contract - its the implementation - so it would get verified just like any other contract.

## Process problem
So now that I have verfied the implementation  - like any other "normal contract" I then go to verify the proxy.  So I need to cut the contract's address out of the address box and paste it into the implementation box.
From this:

<img width="323" alt="image" src="https://github.com/ethereum/remix-project/assets/6050001/8a5e894c-923f-48eb-8c50-e2f012a16bf1">

to this:
<img width="310" alt="image" src="https://github.com/ethereum/remix-project/assets/6050001/260dce7b-4357-4ced-9906-0bb3e2a5eac2">

and it worked!  ... I think.

### Did it work?
I have to know that I can go to the receipts page.  When I do I see this:
<img width="433" alt="image" src="https://github.com/ethereum/remix-project/assets/6050001/681ffe9c-c90a-4013-b4e2-ab77d29a49ec">

So all is well - as long as I know that treat the implemenation contract like any other.  I was so excited to use the new proxy feature that it was very hard to convince myself that the 2 don't get verified at once.  And I had to read the Remix docs on Proxy contracts to double check.

I will update this issue possibly with an updated tooltip.

- [ ] the tooltip, "Click to proceed" is not needed and only adds noise to the page.

**Comment by Aniket-Engg** [comment]
@ryestew Yes, at the end you concluded it almost right. We can discuss the improvements in the flow as we need to add documentation for this too on Remix docs. May be we should link the docs for proxy contract verification in the Etherscan plugin too.

**Comment by Aniket-Engg** [comment]
@ryestew Can this be closed now?
