### ISSUE TITLE
Etherscan verifying on Mumbai - Polygon doesn't work

### ISSUE THREAD

**Issue by ryestew** [ethereum/remix-project#3812]
On the polygon version of ETherscan, there is no place to login to get the API key - so when I try to verify a contract on Mumbai, I get an error that says invalid API key.   I am not sure if there is a single API key for all of the Etherscan or whateverscan world - or if there is a different API key for each network.  But if there is, I don't know how to get the key - on this site: https://mumbai.polygonscan.com/

<img width="321" alt="image" src="https://github.com/ethereum/remix-project/assets/6050001/33335a7b-1e6b-4d01-ab5a-d3c13f96e230">

**Comment by Aniket-Engg** [comment]
@ryestew As mentioned in different explorer's verify contract API doc https://docs.polygonscan.com/v/mumbai-polygonscan/api-endpoints/contracts#verify-source-code , API key is individual to one explorer.

For this particular polygonscan, I agree that API key creation link is broken.

**Comment by yann300** [comment]
> API key is individual to one explorer.

If you don't want to always update the api key in the UI, you can directly verify using the script.

**Comment by yann300** [comment]
I think the main issue is that the api key generation in Mumbai isn't working right?

**Comment by yann300** [comment]
i close, please reopen if there's something else?

**Comment by ryestew** [comment]
The issue is that in all these other chains, there is no login and so there is no API key to input into the EtherScan plugin
This binance chain has the standard navigation on etherscan (standard without a place to login)
<img width="1409" alt="image" src="https://github.com/ethereum/remix-project/assets/6050001/69878533-d921-4135-9edd-9790ca878823">

**Comment by ryestew** [comment]
I just tried on Optimism Goerli and I get 
<img width="295" alt="image" src="https://github.com/ethereum/remix-project/assets/6050001/0436733e-a5ed-4f6f-bd53-b7bbf74fcb93">

**Comment by ryestew** [comment]
When verifying on Optimism, you need to have a different API key than when verifying on mainnet or ethereum testnets.
