### ISSUE TITLE
Etherscan issues part 2

### ISSUE THREAD

**Issue by LianaHus** [ethereum/remix-project#3813]
part 1 is here https://github.com/ethereum/remix-project/issues/3597

- [ ] To keep this consistency with other parts of the ide we need to use in-place value verification(for example 'required' error msg if the address is empty) instead of toasters ( we are minimizing the usage of toasters through the app.)
- [x] When VM is selected in D&R we need to disable the Verify button and the label should be 'VM - not supported" in the env field
- [x] The active icon from the header menu of the plugin should be brighter.

**Comment by ryestew** [comment]
There is the api key input in the plugin and also in the settings panel.  When is the one in the settings panel used?
