### ISSUE TITLE
Sol2Uml styling improvements

### ISSUE THREAD

**Issue by joeizang** [ethereum/remix-project#3832]
The current setup for styling generated uml diagrams is dependent on a hand rolled mapping of values from the css file of every theme in the ide. To improve this so it picks values dynamically from set themes some changes are required.

- [x] ThemeModule plugin should push a payload along with the theme changed event.
- [x] Look into how best to have a global config of current themes and their values  so that plugins can access them
- [x] Use css variables dynamically as values for the uml diagram

**Comment by fwx5618177** [comment]
Has it closed?
