### ISSUE TITLE
Etherscan Proxy Contract Verification Issues

### ISSUE THREAD

**Issue by ioedeveloper** [ethereum/remix-project#3834]
- [x] Proxy verification instruction is not visible
- [x] Initialize args are not updated and shown like we have for constructor args
- [x] Generate Verification Scripts fails to generate script with the error shown below
<img width="503" alt="Screenshot 2023-06-20 at 14 18 08" src="https://github.com/ethereum/remix-project/assets/23282059/d13ae757-7e0c-4fbf-a77b-cdfb72e501ee">

- [ ] Constructor args are not auto-updated after compilation

**Comment by ryestew** [comment]
The warning should be something like:
Before verifying the proxy, the implementation contract must be verified.
