### ISSUE TITLE
Getting "Error from IDE 401 unathorized" while using Dgit

### ISSUE THREAD

**Issue by therevealer** [ethereum/remix-project#3864]
My Github API tokens is set and my remote URL is also set But i can't push to my Github Repository

**Comment by bunsenstraat** [comment]
Can you verify your credentials have the correct permissions?

**Comment by bunsenstraat** [comment]
![Screenshot 2023-06-29 at 10 18 12](https://github.com/ethereum/remix-project/assets/2787300/b6974123-2ba2-406d-b3ef-200c6fca9e95)
![Screenshot 2023-06-29 at 10 18 02](https://github.com/ethereum/remix-project/assets/2787300/d7d71f04-d2aa-4dc6-b682-0e73e54058cd)

**Comment by bunsenstraat** [comment]
and did you clone your repo?

**Comment by therevealer** [comment]
I accidentally pushed my API key to github, and it was rendered invalid by github.
I created a new one now...it is working.

**Comment by bunsenstraat** [comment]
Great!!
