### ISSUE TITLE
Invalid Tuple Value

### ISSUE THREAD

**Issue by quirp** [ethereum/remix-project#3866]
### Description
No change in input for struct parameter, yet a function with an extra parameter will state there is an encoding error for tuple type.

```
pragma solidity ^0.8.9;

contract StructInputError{
    struct A{
        address user;
        uint256 a;
    }
    function noError(A memory _a) external {
    }
    function error(A memory _a, uint256 _b) external {
    }
}


```
Input Parameters : 
    _a   = [ 0xeb3dfde2db8e7fef92cff3baafa0dc3f8d997beb, 3294 ] ,
    _b    = 39

Successful transaction  for _noError_ function.
Error on transacting the _error_ function with above input,

transact to StructInputError.error errored: Error encoding arguments: Error: invalid tuple value (argument="tuple", value="[0xeb3dfde2db8e7fef92cff3baafa0dc3f8d997beb,3294]", code=INVALID_ARGUMENT, version=abi/5.7.0)

**Comment by Aniket-Engg** [comment]
![Uploading Screenshot 2023-06-29 at 1.50.38 PM.png…]()

It works fine for me. Can you add more details to reproduce? @quirp

**Comment by quirp** [comment]
Using Remix VM (Shanghai). 
No advanced compilation configuration.

Replicated the same behavior on an Incognito Mode instance on Brave browser.

**Comment by quirp** [comment]
![Screenshot from 2023-06-29 02-34-21](https://github.com/ethereum/remix-project/assets/28508472/ffde04c0-f779-417a-b49f-5bb97fabe425)
