### ISSUE TITLE
Vyper refactor

### ISSUE THREAD

**Issue by PatrickAlphaC** [ethereum/remix-project#3870]
I'd like to propose a vyper refactor, so that the vyper plugin has 1st priority support the same way solidity does. Vyper is a fantastic python based language which often performs better than solidity due to it's use of [static memory allocation](https://www.youtube.com/watch?v=sbc74oU94FM).

I am willing to help sponsor this issue. The plugin should be able to:

1. Support multiple Vyper versions (like solidity)
2. Have a giant compile button (like solidity)
3. Remove the local vs remote compiler option so it's intuitive for people to use (like solidity)

**Comment by joeizang** [comment]
@ryestew should we close this based on the current state of vyper?
