### ISSUE TITLE
Remove caret in FE

### ISSUE THREAD

**Issue by ryestew** [ethereum/remix-project#3881]
![image](https://github.com/ethereum/remix-project/assets/6050001/f02b4401-cbb7-4af2-9726-8982f51ac8ba)

**Comment by Rana-Paul** [comment]
I want to work on that issue.  I already solved it

**Comment by Rana-Paul** [comment]
It looks like this
![Screenshot](https://github.com/ethereum/remix-project/assets/72220579/ca4eff04-3853-4532-8905-8a776c04f807)

**Comment by LianaHus** [comment]
done
