### ISSUE TITLE
more columns should be added in terminal logs, such as contractAddress, blockNumber, blockHash

### ISSUE THREAD

**Issue by drafish** [ethereum/remix-project#3890]
We want to see `contractAddress, blockNumber, blockHash` in brochain ide. Remix does not show these three columns in terminal logs. So we add them like this.
![image](https://github.com/ethereum/remix-project/assets/18543527/a2e87b52-4a75-4b11-950c-6db9571858a8)
![image](https://github.com/ethereum/remix-project/assets/18543527/e97b51a6-a24e-4522-bbe7-dbddfb36703c)

I suppose remix want to show contractAddress, it just get the property from the wrong object. Check the code below. It should be `receipt`, not `tx`.
https://github.com/ethereum/remix-project/blob/master/libs/remix-ui/terminal/src/lib/components/RenderKnownTransactions.tsx#L43

And forget about `regionId`, it's just a special column that only exist in brochain.

I can submit a pr, if your team like my proposal.

**Comment by Aniket-Engg** [comment]
fixed by #3896
