### ISSUE TITLE
Create Feature panel for survey

### ISSUE THREAD

**Issue by vermouth22** [ethereum/remix-project#3929]
We could replace the "Jump into Web3" panel keeping the image that's already there, but replacing text with:

🎧Remixers... Have a spare moment? Please help us improve your Remix UX with this one-minute survey.

Survey Link:
https://us8.list-manage.com/survey?u=5a84beb6d688fe180c0da482a&id=1148d10f8c

**Comment by AnuragNishad12** [comment]
hey @LianaHus I'm getting this error 
![image](https://github.com/ethereum/remix-project/assets/124987038/01371928-c104-4dd5-8b9b-93cd1cee0d68)
How should i solve this 
I get this error all over in my github repository

**Comment by LianaHus** [comment]
> hey @LianaHus I'm getting this error ![image](https://user-images.githubusercontent.com/124987038/254513585-01371928-c104-4dd5-8b9b-93cd1cee0d68.png) How should i solve this I get this error all over in my github repository

@bunsenstraat is this coming from dgit?

**Comment by LianaHus** [comment]
also we need a modal for limited time to ask main questions of survey

**Comment by LianaHus** [comment]
this is all done or not relevant.

@bunsenstraat could you please open an issue for the comment above if it is still relevant?
