### ISSUE TITLE
Can we get the trace of a reverted transaction?

### ISSUE THREAD

**Issue by Billy1900** [ethereum/remix-project#3934]
I have a function which I plan to revert, since the REVERT instruction provides a way to stop execution and revert state changes, without consuming all provided gas and with the ability to return a reason. At the same time, I want to get the trace of the transaction, can we do that using geth? I have tried to use hardhat/truffle/ganachi, but it does not work (it seems like the framework refuses to send the reverted transaction, but we can forcefully do it on remix IDE).

```
function attack1_int_overflow() public {
      multiVulnToken.transferProxy(
          address(this),
          attacker1Address,
          uint256(2 ** 255 + 1),
          uint256(2 ** 255)
      );
      revert();
  }
```

**Comment by Aniket-Engg** [comment]
Have you tried  debugger plugin of Remix IDE?

**Comment by Aniket-Engg** [comment]
I think you can send a transaction like that on Remix. Have you tried?

**Comment by Billy1900** [comment]
> I think you can send a transaction like that on Remix. Have you tried?

What do you mean, send a transaction like that on Remix? using js script?

**Comment by Billy1900** [comment]
We could refer here: https://github.com/ethereum/go-ethereum/issues/27749
