### ISSUE TITLE
How do I properly use the Remix Desktop IDE?

### ISSUE THREAD

**Issue by WuChenDi** [ethereum/remix-project#3963]
Dear friend,

I hope you are doing well. I have encountered some issues while using Remix Desktop IDE and I was hoping to get your assistance. I downloaded the corresponding program from https://github.com/ethereum/remix-desktop/releases and tried opening it, but the program remains stuck on the same page without any response.

![image](https://github.com/ethereum/remix-project/assets/31385662/8dfec061-ca9f-46f8-8cf9-1a677c58cad4)

I would like to ask for advice or guidance on the correct operating steps.

Thank you for your help!

Best regards,

**Comment by drafish** [comment]
看你也是中国人，我就不费那劲去打英文了。你碰到的这个问题，所有国内的用户都会碰到。

目前这个 desktop 是有点名不副实的。因为这个desktop本质上就是用的web版的ide，然后套了个electron的壳。首次打开的时候会先加载web版的ide，然后把静态文件都存到本地，下次打开就不需要从网络上下载了。

坑爹的就是，这个desktop不是直接从 https://remix.ethereum.org 下载的，而是从 github 上下载的压缩包，就是从这儿下的 https://github.com/ethereum/remix-project/releases

github 在国内的情况你也应该知道。你卡在这个页面，就是因为在下那个压缩包，下完了就可以打开了。你可以把 desktop 关掉，然后再打开试试。如果能打开就说明已经下完了，如果打不开就说明还没下完。你可以试下开系统代理，然后再下一次。desktop不能设置代理，所以你只能设置系统代理。

我是不太建议用这个 desktop 的，还不如直接用 web 版，如果想访问本地文件夹，就用remixd 。desktop 也是用remixd 来访问本地文件夹的，只不过是帮你默认启动了而已。

remix马上要发布新版的 desktop 了，会和以前大不一样，至少会有真正的 terminal 。你大概还不知道吧，现在的desktop中的terminal和web版完全一样的，就是个假terminal。新版的terminal和vscode一样的。建议还是等新版本吧。

我是remix中文社区的发起人，你以后有问题也可以来我们中文社区提问，这是我们的tg https://t.me/remix_cc

**Comment by WuChenDi** [comment]
@drafish 好的呢，谢谢回复，已加入
