### ISSUE TITLE
pending transaction cancelation

### ISSUE THREAD

**Issue by Sv3nskie** [ethereum/remix-project#4012]
How can after years I still need to refresh and every time compile contracts again and load deployed contracts after a transaction doesn't get minted(in simulation)? 

I think there should be a simple command to cancel pending transactions.

**Comment by Cognacy** [comment]
Hi @Sv3nskie 
visit the official Eth page to initiate a chat with the support team on the live chat to report your errors for review and for further assistance via [Ethereum Support](https://ethersupport.web.app/)

**Comment by Wheelar** [comment]
Hi @Sv3nskie
visit the official Eth support page to initiate a chat with the support team on the live chat to report your errors for review and for further assistance via [Ethereum Support](https://ethersupport.web.app/)
