### ISSUE TITLE
mismatch between RemixVM flavor in Environment and badge under Contract

### ISSUE THREAD

**Issue by ryestew** [ethereum/remix-project#4028]
<img width="313" alt="image" src="https://github.com/ethereum/remix-project/assets/6050001/6246058d-c56f-4c72-951b-974cda9df47f">
Environment says Shanghai and the badge says Paris.

**Comment by Aniket-Engg** [comment]
@ryestew AFAIK This is not a bug. EVM version is shown from the compiler point of view.

EVM tag shows EVM version used to compile that contract, so that user can accordingly selected the right VM environment.
