### ISSUE TITLE
Remix Desktop: Use offline solidity compilers, plugins resources using for example IPFS

### ISSUE THREAD

**Issue by LianaHus** [ethereum/remix-project#403]
Use offline solidity compilers, plugins resources using for example IPFS

**Comment by yann300** [comment]
- theme
 - local icons instead of font-awesome (?)
 - solidity compiler
 - connect to IPFS node for plugins

**Comment by yann300** [comment]
depend on https://github.com/ethereum/remix-desktop/pull/25
