### ISSUE TITLE
Move to Web3js version 4

### ISSUE THREAD

**Issue by avkos** [ethereum/remix-project#4051]
Web3js released version 4 (fully on the TypeScript)

It will be great to move on to the new version.

I've already started to do this. Here is [PR](https://github.com/ethereum/remix-project/pull/3951) 

I've finished integrating the latest version of wev3js@4x into remix-libs and tests passed. But I still have problems with some browser tests. As the project is huge and complex it would be better if someone familiar with all relations and connections inside the project would finish integration by fixing browser tests. From my side, I will provide any help you need from my knowledge of web3js@4.x library.

Here is a list of errors in a browser tests:
1. [remix-ide-browser-chrome-0-10-browser_test.sh](https://app.circleci.com/pipelines/github/ethereum/remix-project/16325/workflows/cbcb59c2-b37f-454c-8b2d-f1ae0fa22eed/jobs/185482)
```ts
Timed out while waiting for element <*[data-id="universalDappUiContractActionWrapper"]> to be present for 60000 milliseconds. - expected "found" but got: "not found" (60210ms)
```

2. [remix-ide-browser-chrome-1-10-browser_test.sh](https://app.circleci.com/pipelines/github/ethereum/remix-project/16325/workflows/cbcb59c2-b37f-454c-8b2d-f1ae0fa22eed/jobs/185495)
```ts
Timed out while waiting for element <[data-id="universalDappUiTitleExpander0"]> to be present for 10000 milliseconds. - expected "found" but got: "not found" (10232ms)
```

3. [remix-ide-browser-chrome-3-10-browser_test.sh](https://app.circleci.com/pipelines/github/ethereum/remix-project/16325/workflows/cbcb59c2-b37f-454c-8b2d-f1ae0fa22eed/jobs/185501)
```ts
Timed out while waiting for element <*[data-shared="universalDappUiInstance"]> to be present for 10000 milliseconds. - expected "found" but got: "not found" (10249ms)
```

4. [remix-ide-browser-chrome-4-10-browser_test.sh](https://app.circleci.com/pipelines/github/ethereum/remix-project/16325/workflows/cbcb59c2-b37f-454c-8b2d-f1ae0fa22eed/jobs/185497)
```ts
Expected element <*[data-id="terminalJournal"]> text to contain: "Unlock time should be in the future" in 60000ms - expected "contain 'Unlock time should be in the future'" but got: " Welcome to Remix 0.36.0-dev 
```
5. [remix-ide-browser-chrome-5-10-browser_test.sh
](https://app.circleci.com/pipelines/github/ethereum/remix-project/16325/workflows/cbcb59c2-b37f-454c-8b2d-f1ae0fa22eed/jobs/185492)
```ts
Timed out while waiting for element <*[data-id="signMessageTextarea"]> to be present for 120000 milliseconds. - expected "visible" but got: "not found" (120431ms)
```
6. [remix-ide-browser-chrome-6-10-browser_test.sh](https://app.circleci.com/pipelines/github/ethereum/remix-project/16325/workflows/cbcb59c2-b37f-454c-8b2d-f1ae0fa22eed/jobs/185502)
```ts
Timed out while waiting for element <*[data-id="testTabSolidityUnitTestsOutputheader"]> to be present for 120000 milliseconds. - expected "visible" but got: "not found" (120500ms)
```
7. [remix-ide-browser-chrome-7-10-browser_test.sh](https://app.circleci.com/pipelines/github/ethereum/remix-project/16325/workflows/cbcb59c2-b37f-454c-8b2d-f1ae0fa22eed/jobs/185486)
```ts
 Failed [fail]: (TimeoutError: An error occurred while running .waitForElementContainsText() command on *[data-id="terminalJournal"] after 120000 milliseconds. expected: test running free function - got: Waiting Promise
```
8. [remix-ide-browser-chrome-8-10-browser_test.sh](https://app.circleci.com/pipelines/github/ethereum/remix-project/16325/workflows/cbcb59c2-b37f-454c-8b2d-f1ae0fa22eed/jobs/185488)
```ts
Timed out while waiting for element <*[data-id="universalDappUiContractActionWrapper"]> to be present for 60000 milliseconds. - expected "found" but got: "not found" (60294ms)
```
9. [remix-ide-browser-firefox-0-10-browser_test.sh](https://app.circleci.com/pipelines/github/ethereum/remix-project/16325/workflows/cbcb59c2-b37f-454c-8b2d-f1ae0fa22eed/jobs/185499)
```ts
Timed out while waiting for element <*[data-id="universalDappUiContractActionWrapper"]> to be present for 60000 milliseconds. - expected "found" but got: "not found" (60226ms)
```
10. [remix-ide-browser-firefox-1-10-browser_test.sh](https://app.circleci.com/pipelines/github/ethereum/remix-project/16325/workflows/cbcb59c2-b37f-454c-8b2d-f1ae0fa22eed/jobs/185487)
```ts
 Response 500 POST /wd/hub/session/85768bcf-2baa-4478-919a-7bc4c92349d8/elements (1983ms)
 NoSuchElementError
 An element could not be located on the page using the given search parameters.
```
11. [remix-ide-browser-firefox-3-10-browser_test.sh](https://app.circleci.com/pipelines/github/ethereum/remix-project/16325/workflows/cbcb59c2-b37f-454c-8b2d-f1ae0fa22eed/jobs/185503)
```ts
Timed out while waiting for element <*[data-shared="universalDappUiInstance"]> to be present for 10000 milliseconds. - expected "found" but got: "not found" (10124ms)
```
12. [remix-ide-browser-firefox-4-10-browser_test.sh](https://app.circleci.com/pipelines/github/ethereum/remix-project/16325/workflows/cbcb59c2-b37f-454c-8b2d-f1ae0fa22eed/jobs/185489)
```ts
 Expected element <*[data-id="terminalJournal"]> text to contain: "Unlock time should be in the future" in 60000ms - expected "contain 'Unlock time should be in the future'" but got: " Welcome to Remix 0.36.0-dev 
```
13. [remix-ide-browser-firefox-5-10-browser_test.sh
](https://app.circleci.com/pipelines/github/ethereum/remix-project/16325/workflows/cbcb59c2-b37f-454c-8b2d-f1ae0fa22eed/jobs/185491)
```ts
Timed out while waiting for element <*[data-id="signMessageTextarea"]> to be present for 120000 milliseconds. - expected "visible" but got: "not found" (120389ms)
```
14. [remix-ide-browser-firefox-6-10-browser_test.sh](https://app.circleci.com/pipelines/github/ethereum/remix-project/16325/workflows/cbcb59c2-b37f-454c-8b2d-f1ae0fa22eed/jobs/185485)
```ts
 Timed out while waiting for element <*[data-id="testTabSolidityUnitTestsOutputheader"]> to be present for 120000 milliseconds. - expected "visible" but got: "not found" (120091ms)
```
15. [remix-ide-browser-firefox-7-10-browser_test.sh](https://app.circleci.com/pipelines/github/ethereum/remix-project/16325/workflows/cbcb59c2-b37f-454c-8b2d-f1ae0fa22eed/jobs/185498)
```ts
 NoSuchElementError
 An element could not be located on the page using the given search parameters.
```
16. [remix-ide-browser-firefox-8-10-browser_test.sh](https://app.circleci.com/pipelines/github/ethereum/remix-project/16325/workflows/cbcb59c2-b37f-454c-8b2d-f1ae0fa22eed/jobs/185496)
```ts
Timed out while waiting for element <*[data-id="universalDappUiContractActionWrapper"]> to be present for 60000 milliseconds. - expected "found" but got: "not found" (60207ms)
```
17. [test-plugin-plugin_api](https://app.circleci.com/pipelines/github/ethereum/remix-project/16325/workflows/cbcb59c2-b37f-454c-8b2d-f1ae0fa22eed/jobs/185490)
```ts
Failed [ok]: (Returned value from call does not match expected value.) - expected "true" but got: "false" (9ms)
```

**Comment by yann300** [comment]
done by

https://github.com/ethereum/remix-project/pull/3951
https://github.com/ethereum/remix-project/pull/4108
https://github.com/ethereum/remix-project/pull/4166
https://github.com/ethereum/remix-project/pull/4194
