### ISSUE TITLE
Workspace Management

### ISSUE THREAD

**Issue by yann300** [ethereum/remix-project#406]
Loading and accessing a file can be sometime tricky, they are all loaded at the root and it often happens that the browser explorer is flooded with old files.
After some discussions here are some proposition to improve that.
This changes will serve as a playground for us to figure out the best way for handling that:

 - Workspace creation (a workspace will basically be a folder under `browser`).
     - As we already have current a workspace for the remix-tests, we could reuse that property. Perhaps other workspace can be grayed out or even hidden.
     - As for Solidity import, the workspace should be considered as root folder. This is important to remember.

 - Import Workspace template (This part can be developed under an external plugin) 
     - Loading specific project code. e.g OpenZeppelin ERC, multisig, ...
     - With all required files (deploy.js, remix-tests files, ...)

**Comment by yann300** [comment]
some more specs:
```
import "github url";  // <= OK (that should load the github files in the current workspace (leads to code duplication)
import "../workspace1/Untitled.sol"; // <= wrong
import "browser/workspace2/hello.sol"; // <= wrong
import "localhost/something"; // <= maybe OK (it should not be possible to name a workspace "localhost")
import "./hello.sol"; // <=  OK
```

**Comment by ioedeveloper** [comment]
- Decide on how test files will be generated and loaded in the Solidity Unit Testing plugin.
    - Workspace dependent (i.e can only generate and select files loaded in the current workspace).
    - Workspace independent (i.e can generate and select files from any workspace, including remixd).
- Save/Load preset settings based on selected workspace.
    - Themes.
    - Plugins list.
    - Layout adjustments.

**Comment by Aniket-Engg** [comment]
We can have a config file dedicated to a workspace: https://github.com/ethereum/remix-project/issues/674

**Comment by yann300** [comment]
Some more proposals we should discuss, that will address basic issues:

 - [ ] one current flaw is that it's currently impossible to easily restart a project from scratch. We should have a way to save/open/create/close/delete workspaces.
 - [ ] some folders like `github`, `ipfs`, ... are not really part of a workspace but are dependencies, This should be shown in the UI (with a different colors in the folder icon, and also with a `.` preceding the folder name).
 - [ ] It is currently very confusing to work with `browser` and `localhost`, mainly because the path `browser` and `localhost` get included in the compilation result, which should not be the case (e.g compilation never contains absolute path).
 A solution for that would be to either only allow browser or localhost to be open at a time. or too make sure both root folder can't be seen each other. 
Here's how vscode handles it https://code.visualstudio.com/docs/editor/multi-root-workspaces

**Comment by yann300** [comment]
@ioedeveloper 's proposal:
- [ ] put all the dependencies under a single folder (i.e instead of having github, ipfs folder, we'd have `.deps/github`, `.deps/ipfs`

**Comment by yann300** [comment]
@bunsenstraat 's proposal:
 - we keep the entire filesystem as `browser`.
 - user create an empty workspace, they can add folders to it.
 - in the UI, close to the file explorer : `create workspace`, `open workspace`, `add folder to workspace`

**Comment by LianaHus** [comment]
#1102

**Comment by LianaHus** [comment]
> * Decide on how test files will be generated and loaded in the Solidity Unit Testing plugin.
>   
>   * Workspace dependent (i.e can only generate and select files loaded in the current workspace).
>   * Workspace independent (i.e can generate and select files from any workspace, including remixd).
> * Save/Load preset settings based on selected workspace.
>   
>   * Themes.
>   * Plugins list.
>   * Layout adjustments.
>   * e.t.c.

* first part is done in a 'dependent' way
* for the second part @Aniket-Engg has created the config file description. Could you link it to the Issue please, Aniket?
