### ISSUE TITLE
Why I'm Getting the Gas estimation failed error 

### ISSUE THREAD

**Issue by AnuragNishad12** [ethereum/remix-project#4071]
When I connect My ganache with remix IDE and deploy the contract Then I gets this error 
<img width="403" alt="image" src="https://github.com/ethereum/remix-project/assets/124987038/90c4531c-2981-4750-bf34-c94236e68ba4">

**Comment by yann300** [comment]
Are you using ganache UI, please check they are supporting the latest fork.
I am sure Ganache cli is, but not sure about the UI version.
Also please post the soliditi code so we can try to reproduce.
