### ISSUE TITLE
erc autocomplete can't highlight any erc but the 1st.

### ISSUE THREAD

**Issue by ryestew** [ethereum/remix-project#4206]
When you type erc, you get the huge list of ERCs and the 1st (1155) is highlighted and has a little descriptor.  The rest can be selected but not highlighted so no descriptor can be seen.

<img width="273" alt="image" src="https://github.com/ethereum/remix-project/assets/6050001/4b5f3aeb-503a-489f-8c31-c3dfedd1525b">

**Comment by Aniket-Engg** [comment]
To go to other options in list, you need to use arrow keys from keyboard. Auto complete in editor also works in same way.

**Comment by Aniket-Engg** [comment]
@ryestew Can this be closed?
