### ISSUE TITLE
Can't deploy to mainnet - error: " Max transaction fee: Please fix this issue before sending any transaction. toBN is not defined "

### ISSUE THREAD

**Issue by thomascvan** [ethereum/remix-project#4207]
gas fees can't be calculated when trying to deploy any contracts to ETH mainnet.  

See reddit thread below:
https://www.reddit.com/r/ethdev/comments/17q37sh/having_issue_with_remix_ide_deploying_contract/

**Comment by yann300** [comment]
this is fixed and deployed, thanks for the report.

**Comment by Yammawa** [comment]
Can I deploy now

**Comment by kvvntran** [comment]
Can deploy now, thank you very much. @yann300 and @thomascvan

**Comment by thomascvan** [comment]
Thanks! worked for me as well
