### ISSUE TITLE
Can't create contract on eth main-net.

### ISSUE THREAD

**Issue by byteamaze** [ethereum/remix-project#4212]
![20231108180046](https://github.com/ethereum/remix-project/assets/42631111/af5ce9e5-56f5-417a-9f8d-75442603d593)

version: 0.37.1

**Comment by yann300** [comment]
0.37.2 is deployed and should work better.
Please if you see the issue again, could you add more information like about the network, the type of connection (injected provider, external, ...)
thanks!

**Comment by byteamaze** [comment]
Can popup the approve page, but what the hell? The gas is too high...
![20231108180046](https://github.com/ethereum/remix-project/assets/42631111/7ac68dd1-f53a-4e8d-a7df-7fa19724e413)

**Comment by yann300** [comment]
A fix has been deployed

**Comment by byteamaze** [comment]
> A fix has been deployed

Thank you, man. It works now. Have a nice day!
