### ISSUE TITLE
creation of Owner errored: Error occured: Transaction has been reverted by the EVM.

### ISSUE THREAD

**Issue by aqeelVaival** [ethereum/remix-project#4213]
None of the contracts have been deploying, each time before Metamask popup it states error "Transaction has been reverted by the EVM."...Only happening with metamask injection with specific chains....Like 
Elysium Mainnet
chainID 1339
rpc   1.  https://rpc.elysiumchain.tech/
         2. https://rpc.elysiumchain.us/
         
         
         seems from 0.37.0 changes, **Update web3js 4 With Injected provider** has been the caused.

**Comment by Aniket-Engg** [comment]
@aqeelVaival Can you check if it is fixed with v0.37.3 ?

**Comment by aqeelVaival** [comment]
Right now , I am not facing reverted by EVM error, end even Metamask Popped up as well with elysium chain..Even txn proceeded as well but its reverting each time

https://blockscout.elysiumchain.tech/address/0xA5d638Df5A92231bb1AB4E951817D6ff54e006Ad
https://blockscout.elysiumchain.tech/address/0x218A866dbdCe8da777102221B6eC1404bF25D98F

**Comment by aqeelVaival** [comment]
Issue seems to be with fee dealing in remix, because i executed  deployment txn with max gas and its still reverted back

**Comment by aqeelVaival** [comment]
Please let us know when you resolved this issue..Further we can provide the test funds as well if you want to test it with any sample contracts
Elysium Mainnet
chainID 1339
rpc 1. https://rpc.elysiumchain.tech/
2. https://rpc.elysiumchain.us/

**Comment by aqeelVaival** [comment]
I just want to notify here that we are able to deploy contracts now..

**Comment by aqeelVaival** [comment]
> Right now , I am not facing reverted by EVM error, end even Metamask Popped up as well with elysium chain..Even txn proceeded as well but its reverting each time
> 
> https://blockscout.elysiumchain.tech/address/0xA5d638Df5A92231bb1AB4E951817D6ff54e006Ad https://blockscout.elysiumchain.tech/address/0x218A866dbdCe8da777102221B6eC1404bF25D98F

https://blockscout.elysiumchain.tech/address/0x6a3dbb8A63fF98487627C09659C87D9038450e1f
Again facing same issue, Can anybody here to help?

**Comment by aqeelVaival** [comment]
@Aniket-Engg @joeizang 

<img width="1920" alt="Screenshot 2023-11-13 at 2 32 29 PM" src="https://github.com/ethereum/remix-project/assets/123551683/63fe2eaf-31a3-46fe-bdda-ef79eefec1e2">
<img width="1920" alt="Screenshot 2023-11-13 at 2 34 28 PM" src="https://github.com/ethereum/remix-project/assets/123551683/7a7b1918-2bc0-4f50-8133-1cd017fad68b">

Here you can check reverted txn on remix with MM injection, but still its loaded at side bar....Also tried with sample contract of owner, but it also has the same issue

**Comment by aqeelVaival** [comment]
Unable to call any write function , all read are working fine for the loaded contract....Also as mentioned earlier unable to have any contract deployment.....So any operation which includes interaction of gas fee fails every time.

**Comment by Aniket-Engg** [comment]
Hello @aqeelVaival are things fine now?
