### ISSUE TITLE
When reporting an error, the error message remains unspecified.

### ISSUE THREAD

**Issue by justletmeopenticket** [ethereum/remix-project#4225]
I get a prompt:

"Gas estimation errored with the following message (see below). The transaction execution will likely fail. Do you want to force sending?
Error happened while trying to execute a function inside a smart contract"

the only problem is the lack of following message. 

Doesnt matter if it is a message in require statement, or custom error (error statement).

type of connection: injected provider

network: bsc mainnet (56), forked bsc (31337).

to pre-empt the question this setup has worked through many consequent updates of remix version up until yesterday (0.37), when problems with "transaction being reverted by the EVM" started popping up on certain number of networks (bsc was one of the affected). 

Now  transactions make it to the EVM (thanks for quick fix), but the lack of possibility to see the error message (thus placement), makes working with larger codes nigh impossible.

**Comment by Aniket-Engg** [comment]
@justletmeopenticket can you check if it is fixed now on v0.37.3 ?
