### ISSUE TITLE
V5 ERC1967 Proxy is unverifiable

### ISSUE THREAD

**Issue by coffeexcoin** [ethereum/remix-project#4257]
It seems that V5 ERC1967 Proxies are not verifiable on etherscan. Can you please provide the exact commit of the OZ repo and compiler settings that were used to create the deployment bytecode here:
https://github.com/ethereum/remix-project/blob/master/libs/remix-core-plugin/src/lib/constants/uups.ts#L7

When I use the tagged v5.0.0 OZ library and solc 0.8.21 with optimizations disabled and `evmversion: shanghai` I get very similar bytecode but not an exact match:

Compiled:
`0x6080604052600a600c565b005b60186014601a565b6026565b565b5f60216044565b905090565b365f80375f80365f845af43d5f803e805f81146040573d5ff35b3d5ffd5b5f606e7f360894a13ba1a3210667c828492db98dca3e2076cc3735a920a3ca505d382bbc5f1b6095565b5f015f9054906101000a900473ffffffffffffffffffffffffffffffffffffffff16905090565b5f81905091905056fea264697066735822122046ee58456b643d19a1393779370697741c61dbdded8b4d2536d03192335bf59f64736f6c63430008150033`

Deployed/Remix:
`0x6080604052600a600c565b005b60186014601a565b6026565b565b5f60216044565b905090565b365f80375f80365f845af43d5f803e805f81146040573d5ff35b3d5ffd5b5f606e7f360894a13ba1a3210667c828492db98dca3e2076cc3735a920a3ca505d382bbc5f1b6095565b5f015f9054906101000a900473ffffffffffffffffffffffffffffffffffffffff16905090565b5f81905091905056fea26469706673582212202e577dc05daa509bce6e6a86e29397d40b31118aea9fcd0aa88768ad25c610f964736f6c63430008150033`

**Comment by ioedeveloper** [comment]
@coffeexcoin Here is the compiler settings for the v5.0.0 proxy contract.
`Contract Code`: https://github.com/OpenZeppelin/openzeppelin-contracts/blob/v5.0.0/contracts/proxy/ERC1967/ERC1967Proxy.sol
`Compiler Version`: soljson-v0.8.21+commit.d9974bed.js
`Language`: Solidity
`Optimize`: false
`Runs`: 0
`Evm Version`: default

**Comment by coffeexcoin** [comment]
Thanks @ioedeveloper

Are you able to provide a standard json input file that matches the bytecode in the remix repository? Despite my best efforts, I have not been able to duplicate the exact bytecode stored in the remix deployment code.

Here's a remix gist referencing that specific tag from `OpenZeppelin/openzeppelin-contracts` - as you can see the ERC1967Proxy.sol file is compiling to slightly different bytecode than what remix has.

https://gist.github.com/coffeexcoin/8e56c72fdc1d3af809d8107c615daf6b

**Comment by coffeexcoin** [comment]
Was able to verify with this standard json even though the contract metadata portion of the bytecode is not an exact match (thanks @0xth0mas) 

https://gist.github.com/coffeexcoin/1b5b7b7ce14d1c862c60fbc592d08cb2

**Comment by ioedeveloper** [comment]
> Thanks @ioedeveloper
> 
> Are you able to provide a standard json input file that matches the bytecode in the remix repository? Despite my best efforts, I have not been able to duplicate the exact bytecode stored in the remix deployment code.
> 
> Here's a remix gist referencing that specific tag from `OpenZeppelin/openzeppelin-contracts` - as you can see the ERC1967Proxy.sol file is compiling to slightly different bytecode than what remix has.
> 
> https://gist.github.com/coffeexcoin/8e56c72fdc1d3af809d8107c615daf6b

I think your contract code has a slight difference.

Use this contract code instead.
```
// SPDX-License-Identifier: MIT
// OpenZeppelin Contracts (last updated v5.0.0) (proxy/ERC1967/ERC1967Proxy.sol)

pragma solidity ^0.8.21;

import "https://github.com/OpenZeppelin/openzeppelin-contracts/blob/v5.0.0/contracts/proxy/ERC1967/ERC1967Proxy.sol";
```
