### ISSUE TITLE
Flow suggestion for docgen for .md files

### ISSUE THREAD

**Issue by Aniket-Engg** [ethereum/remix-project#4326]
Current Flow:

One clicks on a .md file, it loads file with docgen viewer with an EDIT button. If user wants to make changes on the file, can click on EDIT button and new tab in editor opened with raw content.

Suggested Flow:

One clicks on .md file, file with raw content opens. User can make changes to the file if required and can click on green play button in editor to have the preview. Preview will be loaded with EDIT button.

**Comment by yann300** [comment]
loading the preview first was actually intended..
When one loads a README.md, it's first to read the file, not to edit it.
Having a split screen were you can choose to see the edit or the preview would be the best.
