### ISSUE TITLE
how to save files in remix?

### ISSUE THREAD

**Issue by cell0901** [ethereum/remix-project#4366]
how to save the files i work with in remix ?? i know it saves on browser storage but what if i want to save it?
Or how can i setup this environment locally on my machine with vs code

**Comment by Aniket-Engg** [comment]
@cell0901 See: https://remix-ide.readthedocs.io/en/latest/file_explorer.html#backup
https://remix-ide.readthedocs.io/en/latest/remixd.html 

For more queries, please join our discord: https://discord.gg/mh9hFCKkEq
