### ISSUE TITLE
[Bug] Contract deployment failing while using injected provider - metamask as environment

### ISSUE THREAD

**Issue by CahidArda** [ethereum/remix-project#4376]
I am trying to deploy my contract on bloxberg testnet. I have written the contract on remix ide and built it. Now, I want to deploy it. I choose "Injected Provider - Metamask" and connect to my account. Next, I deploy the contract.

I keep getting the following error:

```
creation of HelloWorld pending...
creation of HelloWorld errored: Error occured: Invalid params: unknown field `type`, expected one of `from`, `to`, `gasPrice`, `gas`, `value`, `data`, `nonce`..

Invalid params: unknown field `type`, expected one of `from`, `to`, `gasPrice`, `gas`, `value`, `data`, `nonce`.
```

I have also tried to deploy a "HelloWorld" contract to make sure that the error is not caused by my contract. This attempt also failed, therefore I believe the issue is not related to my contract.

I have seen the issue #1282 and I wonder if there is a similar problem here. I also found [this section of code](https://github.com/ethereum/remix-project/blob/6bdf4b8864d8821592af7c57017fcaafb55bd3df/libs/remix-lib/src/execution/txRunnerWeb3.ts#L22) from the repository which looks like it is related to this but it's a code which is 2 years old and I am not sure if that could be the issue.

Metamask version: 11.7.2
I am using remix-ide on https://remix.ethereum.org/

**Comment by Alputer** [comment]
I also get the same error.

**Comment by Aniket-Engg** [comment]
@CahidArda Have you tried deployment to any other testnet through Metamask?

**Comment by CahidArda** [comment]
I tried avalanche testnet and I was able to deploy it. I guess this only happens with the bloxberg testnet.
