### ISSUE TITLE
Live web-version has stale JS code and previously fixed bugs

### ISSUE THREAD

**Issue by lebedev** [ethereum/remix-project#4435]
Hi!

There's a bug that can be reproduced in live web-version, but can't be reproduced locally.

Steps to reproduce:
1. Go to https://remix.ethereum.org
2. Select any deployable contract.
3. Set transaction value to `1` (any unit is fine).
4. Press the contract Deploy button (any outcome is fine).
5. Try to set transaction value to `1` again.

Expected result: the value changes.
Actual result: the value stays 0 as long as you don't try other digits.

This bug was fixed in commit https://github.com/ethereum/remix-project/commit/7c5c00687c73dbc369cfc2f04e24df3cff63712c (no bug in this commit, but described buggy behavior presents if built from the previous commit), but it looks like it wasn't deployed to https://remix.ethereum.org?

Other signs of stale code I noticed:
* `react-dom` version on https://remix.ethereum.org is 17 (can be checked with React developer tools), however it's 18 in the repo.
* there's commit https://github.com/ethereum/remix-project/commit/4fb76840c43c4a1d09485dfd08ff620a1ed3fc76 in master branch, which deleted `validateInputKey` function, which isn't in the repo for several weeks, but this function can be found in currently deployed file https://remix.ethereum.org/162.0.40.0.1704877784384.js

**Comment by Aniket-Engg** [comment]
@lebedev This must have been fixed with our latest release. Can you please check?

**Comment by lebedev** [comment]
@Aniket-Engg this bug is indeed fixed in live version of Remix. Thanks!
