### ISSUE TITLE
EIP-7569 `Remix VM (Decun)` Fork Upgrade Solidity Compiler Not Supported

### ISSUE THREAD

**Issue by MarcusWentz** [ethereum/remix-project#4474]
Goerli has upgraded to Decun fork:
https://twitter.com/protolambda/status/1747528819353796826

When will Decun be supported in Solidity in Remix IDE to test contracts on Goerli with Decun support?
https://eips.ethereum.org/EIPS/eip-7569

Solidity variable documentation covering Decun opcodes:
https://docs.soliditylang.org/en/latest/units-and-global-variables.html#block-and-transaction-properties

**Comment by Aniket-Engg** [comment]
Looks like it is planned for next Solidity release: https://github.com/ethereum/solidity/issues/14739
