### ISSUE TITLE
Returned error: The method "debug_traceTransaction" does not exist / is not available.

### ISSUE THREAD

**Issue by frankli-dev** [ethereum/remix-project#4478]
I am working on my local network (substrate) and added tracing capability.
I deployed smart contract through Remix (through injected provider metamask) and get the transaction id.

I can successfully debug transaction by calling `debug_traceTransaction` rpc manually like the following screenshot.
<img width="1090" alt="Screenshot 2024-01-19 at 8 53 25 AM" src="https://github.com/ethereum/remix-project/assets/51565705/9669aab3-17fd-423a-a5a1-bdb2a9f7f4f8">

But the remix does not recognize it. I'm not sure why Remix UI can't call the rpc that I can manually run.
<img width="574" alt="Screenshot 2024-01-19 at 8 53 43 AM" src="https://github.com/ethereum/remix-project/assets/51565705/d4917bcc-cc03-4725-8e71-500cbd3d056c">

Please help me

**Comment by Aniket-Engg** [comment]
cc: @yann300

**Comment by yann300** [comment]
@frankli-dev when you start debugging, are you still using `injected provider`? could you try to directly connect to that node use `external provider`?

**Comment by georgi-l95** [comment]
Hey @frankli-dev I have the same problem, but this is not Remix limitation, it's MetaMask.
Here is the issue in their repo https://github.com/MetaMask/metamask-extension/issues/21611
Drop a comment, if you can to get the snow ball rolling.
