### ISSUE TITLE
Template explorer

### ISSUE THREAD

**Issue by LianaHus** [ethereum/remix-project#4482]
### Template explorer

Mainview plugin.
It should have three main sections: **Solidity**, **Vyper**, and **Circum**.
Each template is a card with tags—examples of tags are **ERC20**, **UNISWAP**, **OpenZeppelin**, and **Multisig**.
Each card will have a create button and be expandable by clicking on it. The expanded row at the bottom will contain more info and the create button.
Search the filter at the top, with checkboxes to filter by tags.

**Open question: should we have checkboxes to choose different options or put all possible combinations as separate cards.**

**Comment by Aniket-Engg** [comment]
closed by https://github.com/ethereum/remix-project/pull/4772
