### ISSUE TITLE
Wrong address copying to clipboard at "External Http Provider" environment option

### ISSUE THREAD

**Issue by EthanBlockson** [ethereum/remix-project#4513]
I know the cases where I had to wait a little bit, so UI change the addresses of chosen env.

But here is 100% bug.

Steps to reproduce:

1) Choose **Remix VM (Shanghai)**
2) Run `npx hardhat node` on local machine
3) Switch env to **Custom - External Http Provider**
4) Now **copy account to clipboard** in Remix or **try to call contracts**

No matter how long you wait, it will copy the prev address from local Remix VM env.

_Its a minor but took near 20 minutes to figure out, in dev process where you deal with hundred of addresses — was hard to identify the problem._

**Comment by Aniket-Engg** [comment]
I can reproduce it. It preserves previous address to copy. Works fine for all addresses, once we select any other address from dropdown
