### ISSUE TITLE
UI bug on saved contracts warning & Saved Contracts title

### ISSUE THREAD

**Issue by ryestew** [ethereum/remix-project#4582]
- [ ] When you save a contract, it goes to the Saved Contract section.  And if there are no other contracts in the Deployed Contracts section then the warning comes up that says:
<img width="300" alt="image" src="https://github.com/ethereum/remix-project/assets/6050001/af7ea770-45f8-4362-921f-134d4bea498c">

But I do have a contract to interact with - I just deployed it and saved it.

- [ ] Also Saved Contracts are Deployed Contracts - so we need to do a bit of renaming.  
I was thinking of Freshly Deployed Contracts - but this isn't right.  I'll put some ideas here later.

- [ ] when you change to the RemixVM and then switch back to injected provider, the saved contracts do not reappear -unless you refresh Remix.

**Comment by Aniket-Engg** [comment]
@ryestew I cannot reproduce 3rd point. Its working fine for me.

**Comment by Aniket-Engg** [comment]
For second point, may be we can categorize as pinned and unpinned contracts

**Comment by Aniket-Engg** [comment]
fixed by https://github.com/ethereum/remix-project/pull/4600
