### ISSUE TITLE
indents in the FE seem frugal

### ISSUE THREAD

**Issue by ryestew** [ethereum/remix-project#4583]
I loaded the Sindri scripts.  It was a bit hard to tell when the files in the Sindri folder stopped and the files in the containing folder continue.  If the indents were a bit larger, then the folder hierarchy would be more clear.
<img width="250" alt="image" src="https://github.com/ethereum/remix-project/assets/6050001/6d78ea4e-98c2-4f28-8827-1a19bb7e40b6">

**Comment by yann300** [comment]
@joeizang very relevant ^

**Comment by joeizang** [comment]
Will take a look at this @ryestew @yann300
