### ISSUE TITLE
Abi Code Not Showing in Remix

### ISSUE THREAD

**Issue by mahatotarit** [ethereum/remix-project#4597]
## **Abi Code Not Showing in Remix**

**There's an issue in Remix where, after compiling a contract file, clicking the "ABI Copy" button doesn't copy the ABI code correctly. Instead, it seems to copy null values, and the ABI isn't displayed. This makes it hard to interact with contracts in Remix. We need help fixing this problem so developers can smoothly work with their contracts. Any assistance in resolving this issue would be highly valued. Thank you.**

![final](https://github.com/ethereum/remix-project/assets/122891749/a2640b90-8209-4cee-a48f-74aec73cbdad)

_Encountering a problem where, upon compiling the contract file in Remix IDE and attempting to copy the ABI code using the designated button, it appears to be copying null values instead. Consequently, the ABI is not being displayed as expected, hindering the interaction between the smart contracts and frontend interfaces. This issue disrupts the development process and requires immediate attention to ensure seamless contract interaction within the Remix environment. Your insights and contributions toward resolving this matter are greatly appreciated._

**Comment by Aniket-Engg** [comment]
@mahatotarit This seems working fine for me. Is it happening in some specific case?

**Comment by mahatotarit** [comment]
Okay, I understand.
