### ISSUE TITLE
CONTRACT VERIFICATION - ETHERSCAN: Plugin activation fails

### ISSUE THREAD

**Issue by karwen73** [ethereum/remix-project#4606]
The plugin cannot be activated correctly.
If you click on the **activate** bottun, the plugin appears in the sidebar. I fyou click on the sidebar button the plugin remains empty.

<img width="281" alt="image" src="https://github.com/ethereum/remix-project/assets/162475611/a987db69-f753-4dc3-8b28-6ef1ae504120">

**Comment by karwen73** [comment]
This appeared right now after trying to activate plugin.

**Comment by Aniket-Engg** [comment]
It goes fine for me. Can you share the OS and browser?

**Comment by karwen73** [comment]
Win 11 Prof.
Chrome
Both up to date

**Comment by karwen73** [comment]
Sourcify Activation Plugin goes fine for me as well. Only etherscan doesn't work.

**Comment by karwen73** [comment]
![image](https://github.com/ethereum/remix-project/assets/162475611/a1fe86f9-b3dc-4341-889c-22b1b8532dc6)

Right now after clearing browser cache.

**Comment by joeizang** [comment]
Hi @karwen73, I tried activating the Etherscan plugin and it was fine. Sorcify also was fine. What other browsers did you try?

**Comment by karwen73** [comment]
Hi there,

I tried Chrome, Firefox and Edge so far. Always the same result - Sorcify works fine, Ethersacan doesn't :(

**Comment by joeizang** [comment]
Can you confirm if you have a browser plugin that could be causing your issue? I have a few plugins but mine works fine.
But from your console error, I would like to ask if your internet connection is stable?
