### ISSUE TITLE
Unpinned contract message needs to be updated on VM

### ISSUE THREAD

**Issue by ryestew** [ethereum/remix-project#4620]
If the pinning can only be used on a public network with Injected Provider, then this message is not correct when connected to the VM

<img width="306" alt="image" src="https://github.com/ethereum/remix-project/assets/6050001/6b78d773-a02b-4f2a-b167-0629a9ee70ff">

When connected to the VM, it should be the old message of
You have no deployed contracts to interact with.

**Comment by Aniket-Engg** [comment]
We will add the pinned contracts for VM in next release.
