### ISSUE TITLE
v0.45.0 stuck at hard refresh error

### ISSUE THREAD

**Issue by EVMlord** [ethereum/remix-project#4641]
Unable to access the UI, keep getting the error message below:

`An unknown error has occurred while loading the application.
Doing a hard refresh might fix this issue:
Windows:
- Chrome: CTRL + F5 or CTRL + Reload Button
- Firefox: CTRL + SHIFT + R or CTRL + F5
MacOS:
- Chrome & FireFox: CMD + SHIFT + R or SHIFT + Reload Button
Linux:
- Chrome & FireFox: CTRL + SHIFT + R`

Already hard refreshed a couple of times without anything changing.

**Comment by Aniket-Engg** [comment]
@EVMlord do you still face the same issue?

**Comment by EVMlord** [comment]
> @EVMlord do you still face the same issue?

Solved, thank you!

**Comment by EVMlord** [comment]
Solved, thank you!

**Comment by 0xelilee** [comment]
I encountered the same problem, how did you solve

> Solved, thank you!

I encountered the same problem, how did you solve

**Comment by shilohma** [comment]
I encountered the same problem, how did you solve

**Comment by emmatheo** [comment]
how did you slove it

**Comment by Aniket-Engg** [comment]
@0xelilee @shilohma @emmatheo Can you share error screen? 

Would you like to create a new issue with details to reproduce?

**Comment by emmatheo** [comment]
<img width="361" alt="remix issue" src="https://github.com/ethereum/remix-project/assets/79262041/ef3bab4d-4748-45a8-9dee-9b25b0390b78">
   
 this is the errror meassage

**Comment by emmatheo** [comment]
No , no error on my broswer

**Comment by npxpath** [comment]
> I encountered the same problem, how did you solve

hello pls i am also encountering same issue pls how did you solve
