### ISSUE TITLE
NPM Module to manage Solidity AST 

### ISSUE THREAD

**Issue by Aniket-Engg** [ethereum/remix-project#467]
**Objective:** 
To develop and maintain of an NPM module to manage the fields of AST which can/should work as types configuration

**Benefits:**
1. To manage AST types at single place and make updates with Solidity upcoming releases.
2. Can be used across all remix libs wherever required
3. Better from documentation point of view
4. Can be helpful to people out there

cc: @yann300

**Comment by chriseth** [comment]
What exactly do you have in mind here? We have been thinking about an official AST definition for a long time but could not find a good structure yet. If it is not an NPM module but rather a single structured document, we could integrate that into the compiler and use tests to see that it is always up to date.

**Comment by Aniket-Engg** [comment]
We currently use AST in different libs. With various releases, fields are updated in AST node types. So main purpose here is to maintain AST at one place and use everywhere else. With that thought, for now we were considering to develop an NPM package with AST nodes type configuration. 

Can you elaborate your thoughts with 'single structured document'?

**Comment by chriseth** [comment]
Can you provide a pointer to how you do it currently?
I was thinking about a document of the form
```
ModifierDefinition:
  name: string
  documentation: Documentation
  visibility: string
  parameters: Parameterlist
```
So something between a TypeScript type definition and Yaml. Maybe we can also add some documentation.

**Comment by Aniket-Engg** [comment]
Currently we are using these type definitions: https://github.com/ethereum/remix-project/blob/master/libs/remix-analyzer/src/types.ts#L125

I got your point. Seems we are on almost same page, just need to decide the way to maintain it

**Comment by Aniket-Engg** [comment]
What if we define it in YAML and then use a js-yaml parser?

**Comment by Aniket-Engg** [comment]
Comment from @chriseth :
"defining it in yaml sounds good!
can you come up with a schema for it?
Another solution would be to use json-schema
json-schema is rather verbose, but if we use that, we can use a regular json-schema-validator to validate all the ASTs output in our tests"

**Comment by chriseth** [comment]
By the way, do you know about this one: https://github.com/OpenZeppelin/solidity-ast/ ?

**Comment by Aniket-Engg** [comment]
> By the way, do you know about this one: https://github.com/OpenZeppelin/solidity-ast/ ?

Seems this is doing exactly what we were planning of

**Comment by Aniket-Engg** [comment]
This is no more a plan as of now. So closing this.
