### ISSUE TITLE
AI solcoder integration 

### ISSUE THREAD

**Issue by yann300** [ethereum/remix-project#4676]
Remaining to do:
 - [x] code review https://github.com/ethereum/remix-project/pull/4554
 - [x] adding internal documentation (deployments , etc..)
 - [x] getting a status page online (that shows response time and up/down status). https://status.remixproject.org/
 - [x] adding remix ide documentation @ryestew

**Comment by STetsing** [comment]
Additional deployment documentation can be found [here](https://docs.google.com/document/d/17gLr_q5jDC_8sMZazFzAWtGYw29fI8U8ZDcxoJcV2ac/edit?usp=sharing)
