### ISSUE TITLE
Solidity compiler not loading on Remix IDE

### ISSUE THREAD

**Issue by livinalt** [ethereum/remix-project#4687]
## Issue

Onstart, Remix IDE automatically loads different compiler versions but for over 10 hrs, I couldn't get Remix to load compiler versions for my project. Wondering what the issue is. Below is an attached screenshot

![Screenshot (279)](https://github.com/ethereum/remix-project/assets/15064313/48678ba9-2ff5-43b0-8873-61d0ee7dcea5)

**Comment by LianaHus** [comment]
are you sure you don't have any connection issues? if you still have this issue could you please tell us what kind of errors do you see in browser debugger?

**Comment by LianaHus** [comment]
https://github.com/ethereum/remix-project/issues/4727
