### ISSUE TITLE
Account list is empty while connecting to localhost via Remixd

### ISSUE THREAD

**Issue by GarenWoo** [ethereum/remix-project#4692]
After I connected the environment of Remix to localhost, the account list was empty. It showed that the list was loading.
Though I waited several hours or tried the same operation many times, the account list was still empty(the default accounts are not available).

Therefore, I initially judge that Cancun EVM does not fit well with the original core functions of Remix.

**Comment by shestakoven** [comment]
@GarenWoo  Remove .states folder and recompile a contract. Works for me
