### ISSUE TITLE
Remix Can't Deploy Contracts Past Cancun Upgrade

### ISSUE THREAD

**Issue by Grimxjoke** [ethereum/remix-project#4748]
Since the new Cancun upgrade.
I often have issue to deploy some lower version of Solidity.
_There's no issues with the Compiler._

Under the **Contract** list, it ask me to connect to the corresponding VM on top. 
Once I'm done with that, It's Loading for "List of Accounts" **forever**.

It does work sometime, after reloading couple time or changing to another Solidity version. <br>
![Remix-Issue](https://github.com/ethereum/remix-project/assets/91224700/76efbdf3-9b3c-4209-9644-6788d7cd33cb)

**Comment by vishwajeeta** [comment]
You can use test-net using Metamask wallet.
YouTube has many videos related to it

**Comment by Grimxjoke** [comment]
Yes I know but not convenient, Metamask got a very bad UX, need to fund with Faucet and limited amount, wait for tx to get validated ...
I usually test with forge chisel as it's working great (most of the time). 
But sometime I still come back to remix for some basic Solidity functionalities quickly.

**Comment by Aniket-Engg** [comment]
@Grimxjoke Can you try to change your workspace and reload Remix and see if accounts are loading fine?

**Comment by spaceh3ad** [comment]
any update on that? I have same issue

**Comment by Aniket-Engg** [comment]
> @Grimxjoke Can you try to change your workspace and reload Remix and see if accounts are loading fine?

@spaceh3ad can you try this and share if it is fixed?

**Comment by YoungTeam** [comment]
I just deleted the '.state' folder and it worked. You can try it too
