### ISSUE TITLE
Show info about usage of compiler older that 0.4.12

### ISSUE THREAD

**Issue by Aniket-Engg** [ethereum/remix-project#475]
After https://github.com/ethereum/remix-project/pull/472 , legacyAST will not be used in remix. Latest AST will be only supported.

As latest AST is not exported for compiler version older than 0.4.12, some things may not work perfect in such case. Inform users about this, better to be specific while old compilers are used.

**Comment by yann300** [comment]
Should probably disable the modules that are not working with solidity < 0.4.12

**Comment by Aniket-Engg** [comment]
We ensure that compilation, deployment and debugging works without any error if not with all features.

For Solidity Static Analysis, we use AST to run the analysis. So for versions older than 0.4.12, it will not be possible to support them and similar for Solidity Unit testing.

**Comment by Aniket-Engg** [comment]
Just to add, in Solidity [0.8.0](https://github.com/ethereum/solidity/releases/tag/v0.8.0) , it states: `Standard JSON: Remove the legacyAST option.`
