### ISSUE TITLE
Too many AI's at top of Remix editor

### ISSUE THREAD

**Issue by ryestew** [ethereum/remix-project#4764]
There are 3 icons at the top of Remix Editor:
![image](https://github.com/ethereum/remix-project/assets/6050001/b2309ed5-00fa-497d-b8aa-0c3f497bf9ef)

From the UX meeting 17 April, we decided that

- [ ]  the docs could be removed and placed in the console as a link on a line after "Solidity copilot not activated!"
- [ ] the robot icon doesn't need the AI text.
- [ ] the switch can stay the way it is.

Not discuss 17 April
the rollovers when there is no file selected:

![image](https://github.com/ethereum/remix-project/assets/6050001/7ec05d5b-bf06-4609-8842-757bfdb28d4f)

"To use Explain a Contract, choose a .sol file"

@LianaHus - I assigned this to you just so you could review this issue.  Probably @STetsing should make the update.

**Comment by STetsing** [comment]
@LianaHus @ryestew We can opt to fully remove the AI text by the next release, as many users out there already know what it is.

**Comment by LianaHus** [comment]
I suggest removing the doc button. we can group them and extract the AI icon to the top level and make it a link to the documentation. 
![Screenshot from 2024-04-25 13-59-32](https://github.com/ethereum/remix-project/assets/9685356/c9bf598d-30f7-4323-a591-cf18b5e0b211)

**Comment by LianaHus** [comment]
- Remove green from play
- Remove AI postfixes everywhere
- Remove docs. put them in settings. or where we print info about solgpd about AI in terminal
- Robot comes first then switch
