### ISSUE TITLE
I can't run script in terminal

### ISSUE THREAD

**Issue by drafish** [ethereum/remix-project#4784]
![image](https://github.com/ethereum/remix-project/assets/18543527/d6293eaf-64d2-41d1-b779-1658d83bc67e)

I'm trying to convert a string to hex, and I keep getting this error -- `scriptRunner plugin is already rendered`

I don't understand. Am I using it correctly?

**Comment by Aniket-Engg** [comment]
May be just reload the IDE, it should be working fine. It sometimes happen when you make another call before previous one is completed

**Comment by drafish** [comment]
Thanks! It works! @Aniket-Engg
