### ISSUE TITLE
scrollbar style is not right 

### ISSUE THREAD

**Issue by drafish** [ethereum/remix-project#4815]
![image](https://github.com/ethereum/remix-project/assets/18543527/7db91731-ecfe-4217-aa4f-16838d4b8cf0)

This issue not just happen in my mirror site, but also in the official site.

I think it is caused by `scrollbar-width: thin;`. It go back to normal when I remove this style.

Check the code here -- https://github.com/ethereum/remix-project/blob/master/libs/remix-ui/grid-view/src/lib/remix-ui-grid-section.css#L24

@LianaHus

**Comment by Nishant891** [comment]
Hey which browser are you using, scrollbar-width property is not supported on safari and web view. 
Here is a reference https://developer.mozilla.org/en-US/docs/Web/CSS/scrollbar-width#browser_compatibility scroll to Browser compatibility section.

**Comment by Nishant891** [comment]
I have checked in all browsers chrome, safari, opera, brave removing scrollbar-width: thin; makes the scrollbar's visibility better. Looks like the property sets the scrollbar to default and overwrites all the styles added
Before - ![Screenshot 2024-06-07 141700](https://github.com/ethereum/remix-project/assets/109356848/6778ff37-388f-43c6-bd81-24a64cc59354)
.
After removing - ![Screenshot 2024-06-07 141631](https://github.com/ethereum/remix-project/assets/109356848/b57ccd54-a993-4c22-a97f-2422f0c25652)

**Comment by drafish** [comment]
I'm using chrome. It's nice to have you checking all other browsers. Good job! @Nishant891
