### ISSUE TITLE
side-panel improvements

### ISSUE THREAD

**Issue by LianaHus** [ethereum/remix-project#4824]
If we move the side panel to the right, the vertical icon should be highlighted somehow because it would be 'focused' always but will not look focused ( no blue border, no bright color)
My suggestion would be

- To make it look disabled (dark color)
- right click would still work
- improved tooltip
- left click will highlight for a second the title of side panel in right part as we currently do with verticaliconpanels icons on plugin activation

**Comment by ioedeveloper** [comment]
We also agreed to have the blue left border appear on the right of the vertical icons panel for the plugins that are pinned to the right.

**Comment by ioedeveloper** [comment]
>     * improved tooltip
> 
>     * left click will highlight for a second the title of side panel in right part as we currently do with verticaliconpanels icons on plugin activation

@LianaHus What should be written as an improved tooltip?
