### ISSUE TITLE
Which URL to use for the remix desktop client?

### ISSUE THREAD

**Issue by jasonhuan** [ethereum/remix-project#483]
Hi,

I'm using the Remix desktop client for MacOS, and when I try to connect remixd to it, I don't know what URL to use for the --remix-ide flag. Is it possible to connect remixd to the desktop client? I ask this since the "open folder" option on the desktop client doesn't allow me to import a high-level directory, only individual files.

**Comment by yann300** [comment]
we should probably add `Open Folder` in the homepage for more clarity.
closing for the moment and cc @LianaHus
