### ISSUE TITLE
Injected Provider account doesn't load into Remix

### ISSUE THREAD

**Issue by livinalt** [ethereum/remix-project#4838]
I have tried several to deploy contracts in the last 24 hours by injecting my accounts using Metamask, however, it has proved very frustrating. Though I can use the VMs on Remix, using the inject provider doesn't seem to work.

**Comment by Aniket-Engg** [comment]
@livinalt can you share error screenshot?

**Comment by livinalt** [comment]
Sure, here is a screenshot of it @Aniket-Engg 

![Screenshot (337)](https://github.com/ethereum/remix-project/assets/15064313/6fa6a68e-75c9-4b7c-b73e-78c4dbd24e22)

**Comment by Giulianomlodi** [comment]
Same issue here

**Comment by livinalt** [comment]
I think I have found a solution. 
Sometimes conflicts arise when you have multiple wallets extensions. So I disabled the other wallet extensions leaving only metamask and it worked. Try disabling also @Giulianomlodi

**Comment by fanismahmalat** [comment]
> I think I have found a solution. Sometimes conflicts arise when you have multiple wallets extensions. So I disabled the other wallet extensions leaving only metamask and it worked. Try disabling also [@Giulianomlodi](https://github.com/Giulianomlodi)

thank you, that worked!
