### ISSUE TITLE
Update Solidity Scan Modal text

### ISSUE THREAD

**Issue by ryestew** [ethereum/remix-project#4882]
The current text needs editing:
To scan the contract for vulnerabilities & possible risks, smart contract code will be shared to third-party SolidityScan.

What are you informing the user? Is it that we are sharing your code?  Or what Solidity Scan does?  
If sharing, I don't think the word share is the right. Its more we are sending it Solidity Scan. 
Does it need to be vulnerabilities and risk.  Is just vulnerabilities is enough?  And if not then the word possible is not needed.

Choices:
A. To scan the contract for vulnerabilities and risks, the smart contract's code will be shared with SolidityScan, a  third-party.

B. Scanning this contract for vulnerabilities and risks, the smart contract code will be analyzed by SolidityScan, a  third-party provider.

C.  SolidityScan, a  third-party provider, will scan this contract for vulnerabilities and risks.

D.  SolidityScan, a  third-party provider, will scan this contract for vulnerabilities.

**Comment by vermouth22** [comment]
I suppose A is more of a formal "alert" style notice to the user. But, I would probably go with a hybrid to shorten the whole thing if the main intention is an "alert" to the user (which I think it is):

E. To scan the contract for risks and vulnerabilities, its code will be shared with SolidityScan, a third-party provider

**Comment by Aniket-Engg** [comment]
@ryestew @vermouth22 About the `possible` word before risks, idea is that sometimes warning are shown but they may not be critical.

I am ok with @vermouth22 E option as it is better to clarify the users that code will be shared.

**Comment by ompatil1357** [comment]
I suggest b. using  possible word is good but also we should see the consequence.  I am not slightly  ok with the words of @vermouth22 .
