### ISSUE TITLE
using remix-ide and remixd together

### ISSUE THREAD

**Issue by veich** [ethereum/remix-project#489]
This seems so basic that I can't believe I didn't find it in first 5 seconds of google search (let alone 20 minutes) :joy: 

Anyways, I'm using `remix-ide` locally and I want to access **and save** my local files.
I can load my local files into IDE but then they are on the `browser` file system and no changes are saved locally.

There is this magic command in the docs:
```
remixd -s <absolute-path-to-the-shared-folder> --remix-ide https://remix.ethereum.org
```
But when I try to do something like this it doesn't work:
```
remixd -s <absolute-path-to-the-shared-folder> --remix-ide http://localhost:8080
```

The issue seems so basic to me - like didn't anyone ever think it would be cool to use **everything** locally?
(maybe this is a dummy question but I decided to go with it) :joy: 

EDIT:
Almost forgot... this is the error:
```
Error: listen EADDRINUSE: address already in use 127.0.0.1:65520
```

**Comment by yann300** [comment]
@veich
were you able to make it work? I think this should be working now.
I m closing the issue, please reopen the issue if needed. you can also join https://gitter.im/ethereum/remix
thanks ;)
