### ISSUE TITLE
remixd can't be closed via ctrl +c

### ISSUE THREAD

**Issue by fritzschoff** [ethereum/remix-project#490]
Like it is common use case that you quite some task in your terminal with `ctrl + c`, but for remixd you only can't quit it by closing the terminal.

OS:
Pop_os
version: 20
gnome shell terminal

**Comment by riordant** [comment]
Same on macOS 10.15.7

**Comment by reginaliuyx** [comment]
Same on macOS 10.15.3

**Comment by Aniket-Engg** [comment]
@fritzschoff It should have been fixed now. Can you please re-check?

**Comment by fritzschoff** [comment]
sorry, not on that OS anymore

**Comment by Aniket-Engg** [comment]
Ok closing it. Please feel free to reopen in case issue persists.
