### ISSUE TITLE
IPFS Publish Failed - throws Infura error when trying to use alternative provider

### ISSUE THREAD

**Issue by dreadedhamish** [ethereum/remix-project#4913]
**Describe the bug**
I have entered details of my local IPFS node in the Remix settings tab.
When trying to submit to IPFS it throws the following error:

IPFS Publish Failed
Failed to publish metadata file and sources to ipfs, please check the ipfs gateways is available.
Error: HTTPError: project id required
,TypeError: Failed to fetch

**To Reproduce**
1. Go to Settings tab
2. Enter non-Infura node details, leave Project ID (Infura) and Project Secret (Infura) blank.
for me:
  IPFS HOST: 192.168.1.103
  IPFS PROTOCOL: HTTP
  IPFS PORT: 5002
3. Go to compiler tab
4. Click "Publish to IPFS" - throws error
5. go back to settings tab, enter dummy values in Project ID and  Project Secret
6. Go to compiler tab, Click "Publish to IPFS" - throws error

**Expected behavior**
A submission should ignore project ID and secret, and should submit to local node

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser: Brave
 - Version: [Version 1.64.122 Chromium: 123.0.6312.122 (Official Build) (x86_64)](https://brave.com/latest/)

**Comment by Aniket-Engg** [comment]
Hello @dreadedhamish Do you still face this issue?
