### ISSUE TITLE
Distribute a backdoor by package takeover in marketplace.

### ISSUE THREAD

**Issue by rex0x1b** [ethereum/remix-project#4914]
Since the package is not linked to the Marketplace, a malicious attacker could use the same package name to upload fake software (e.g., a backdoor). Users who install the VSCode extension through the official website https://remix-project.org/?lang=en may potentially put their wallet at risk and could also have their PC compromised, leading to the leakage of all personal information.

https://remix-project.org/?lang=en
<img width="1313" alt="image" src="https://github.com/ethereum/remix-project/assets/40204643/7e1440c8-50d9-4ff4-affc-e698712b6223">

https://marketplace.visualstudio.com/items?itemName=RemixProject.ethereum-remix
<img width="1447" alt="image" src="https://github.com/ethereum/remix-project/assets/40204643/f9ba7d59-7e42-4b67-bdc1-d706e6ae794b">

**Comment by BBongRu** [comment]
hello!

**Comment by LianaHus** [comment]
@rex0x1b thanks for the heads up. I fixed this and closing the issue
