### ISSUE TITLE
Undeclared EVM Logs aren't shown in receipt UI

### ISSUE THREAD

**Issue by 0xsanson** [ethereum/remix-project#4929]
**Describe the bug**
EVM logs that are emitted without declaring them, aren't shown in the transaction receipt.

It's possible to emit logs without declaring an interface in the following way:
```
contract Test {
    function test() external {
        assembly {
            log1(0x00, 0x00, 0xaa)
        }
    }
}
```
Running the above function works correctly but it won't show in the UI the log emitted (see screenshot below). However by copying-pasting the content in the photoshopped red circle, we can find the correct logs: 
```
[{"address":"0xc1159aa0089ad36c76595c795f1d281c263ec2c0","blockHash":"0x537ec7295212ca0b5072ca690ceea6f34f603759eb42b5b5e3aba5993fd31aa6","blockNumber":"0xd","data":"0x","logIndex":"0x0","removed":false,"topics":["0x00000000000000000000000000000000000000000000000000000000000000aa"],"transactionHash":"0xe2ae5fa32d2f7d3a07fe5d2f271bd8961a5119a969e3b1c6ab2ae4ea756bc56f","transactionIndex":"0x0"}]
```
![Unsaved Image 1](https://github.com/ethereum/remix-project/assets/86423699/5b417787-995b-466f-b1bc-abf93e0c2ced)

**To Reproduce**
1. Copy the contract above.
2. Compile and deploy, it doesn't matter the version or network.
3. Run the test function and look at the receipt in the terminal.

**Expected behavior**
I would expect to see under the `logs` section something like this:
```
[
	{
		"from": "0xc1159aa0089ad36c76595c795f1d281c263ec2c0",
		"topic": "0x00000000000000000000000000000000000000000000000000000000000000aa",
		"event": **unknown**,
		"args": {}
	}
]
```

**Comment by Aniket-Engg** [comment]
fixed by https://github.com/ethereum/remix-project/pull/4965
