### ISSUE TITLE
can't install remixd on macos

### ISSUE THREAD

**Issue by azmove** [ethereum/remix-project#493]
emixd
2143 timing stage:rollbackFailedOptional Completed in 0ms
2144 timing stage:runTopLevelLifecycles Completed in 112459ms
2145 verbose stack Error: ENOENT: no such file or directory, access '/usr/local/lib/node_modules/remixd'
2146 verbose cwd /Users/liquan
2147 verbose Darwin 18.7.0
2148 verbose argv "/usr/local/Cellar/node/12.10.0/bin/node" "/usr/local/bin/npm" "install" "-g" "remixd"
2149 verbose node v12.10.0
2150 verbose npm  v6.11.3
2151 error code ENOENT
2152 error syscall access
2153 error path /usr/local/lib/node_modules/remixd
2154 error errno -2
2155 error enoent ENOENT: no such file or directory, access '/usr/local/lib/node_modules/remixd'
2156 error enoent This is related to npm not being able to find a file.
2157 verbose exit [ -2, true ]

any one can help me fix this?

**Comment by devyeshtandon** [comment]
To anyone who visits this thread in future, try using `npm install -g @remix-project/remixd`. It resolved the issue for me

**Comment by Aniket-Engg** [comment]
Closing this. Feel free to reopen if issue persists
