### ISSUE TITLE
Connection error 400 Bad Request

### ISSUE THREAD

**Issue by krizka** [ethereum/remix-project#494]
I'm starting remixd with
`remixd -s . --remix-ide "http://remix.ethereum.org"`
And while connection from IDE I have 
```
Cannot connect to the remixd daemon.Please make sure you have the remixd running in the background.
```
and response from remixd is:
```
HTTP/1.1 400 Bad Request
Connection: close
X-WebSocket-Reject-Reason: URI malformed
```
Can't understand, what is malformed and where?

**Comment by Aniket-Engg** [comment]
@krizka Can this be closed?
