### ISSUE TITLE
Status bar covers the bottom or the right side plugin

### ISSUE THREAD

**Issue by ryestew** [ethereum/remix-project#4946]
**Describe the bug**
On the left side, the status bar is below LearnEth.  When I move it to the right side, it is over the bottom of LearnEth.

right side bad:
<img width="398" alt="image" src="https://github.com/ethereum/remix-project/assets/6050001/5cef6048-e8e5-48ec-891e-e7da0c268fc9">

left side expected look:
<img width="500" alt="image" src="https://github.com/ethereum/remix-project/assets/6050001/803f0da0-38db-44c0-acb8-268990afa9d5">

Is this a right panel problem or a status bar plugin.  If this is a status bar plugin, please reassign to Joseph.

**Comment by LianaHus** [comment]
This is side panel issue not status bar @ioedeveloper
