### ISSUE TITLE
How to make custom contract address?

### ISSUE THREAD

**Issue by erkanaas** [ethereum/remix-project#4951]
How can I create custom Contract addresses when deploying my contract in Remix? 
 
Example: How can I generate special addresses starting with numbers such as 0x420..., 0x5867...?
 
I couldn't find the custom address adding tab..

Regards

![tyt](https://github.com/ethereum/remix-project/assets/159719386/893b0e8e-7375-48f3-9818-cd6072c47f78)

**Comment by LITTLEFOLWOR** [comment]
To protect the safety of the blockchain, contract addresses are generated randomly, in my opinion, you can't specify the generated address. Or the safety of blockchain will be broken.
