### ISSUE TITLE
remix-ide used the local compilier failed.

### ISSUE THREAD

**Issue by YannickXiong** [ethereum/remix-project#498]
how does remix-ide could use the local compilier?

**Situation: **Because of some reason, I visit the online solc compilier (https://solc-bin.ethereum.org/bin) is really slowly.
Everytime I select a solidity version, more than hours to waiting the loading. So I wanted to use a local compilier with remix-ide.

**What had I done:** 
   1. downloaded solc-bin from: https://github.com/ethereum/solc-bin.git
   2. My remix-ide path is : /usr/local/lib/node_modules/remix-ide
      and the downloaded solc-bin path is: /usr/local/lib/node_modules/remix-ide/solc-bin
   3. I modified the remix-ide/build/app.js
      3.1: modified from : var url = 'https://ethereum.github.io/solc-bin/bin/soljson-' + versionString + '.js';
                     to: var url = 'http://localhost:8080/solc-bin/bin/list.json',
                      I alse visited 'http://localhost:8080/solc-bin/bin/list.json', it was OK, the list.json returns OK.

      3.2: modified from : baseurl: 'https://solc-bin.ethereum.org/bin'  
                    to : baseurl: 'http://localhost:8080/solc-bin/bin'

   4. restart remix-ide

**Question:** it did not work for me. So i really want to know how does remix-ide could use the local compilier?

**Comment by LianaHus** [comment]
you can specify your own path to load a compiler.
we have plans to use a local IPFS node for offline usage.
Please reopen this if you still have questions
