### ISSUE TITLE
Git plugin does not have enought padding in top section

### ISSUE THREAD

**Issue by ryestew** [ethereum/remix-project#4987]
**Describe the bug**
On uninitialized repos the padding is missing and the text is too large of the headline SETUP compared to the headline GIT (well now its DGIT but soon when a PR is merged it will be GIT).
<img width="313" alt="image" src="https://github.com/ethereum/remix-project/assets/6050001/d07ee9d4-d43b-4e41-957d-2e76f7648477">

**Comment by RaghavenderSingh** [comment]
@joeizang can i work on it
