### ISSUE TITLE
Add Keyboard Shortcut to perform Solidity Scan on an Compiled Code

### ISSUE THREAD

**Issue by shubhiscoding** [ethereum/remix-project#4993]
**Is your feature request related to a problem? Please describe.**
While writing a contract I'm able to compile it by pressing Ctrl + Shift + S, without opening the compile section, I don't want to open the compile the section to perform Solidity Scan too.

**Describe the solution you'd like**
Just like I can compile the code with keyboard shortcut, I'd like to perform Solidity Scan with a Keyboard shortcut after compiling the code

**Describe alternatives you've considered**
A keyboard shortcut would be nice, but May be a button here that appears after compilation to perform SolidityScan would work fine too.
![image](https://github.com/user-attachments/assets/34603cd9-3ed4-4449-97e4-31c0adeec429)

**Additional context**
N/A

**Comment by shubhiscoding** [comment]
I'd like to solve it too

**Comment by Aniket-Engg** [comment]
Hello @shubhiscoding , As per the team discussion, we decide not to add this as of now. so closing it.
