### ISSUE TITLE
servicesList[name][fn] is not a function

### ISSUE THREAD

**Issue by dmitry537** [ethereum/remix-project#501]
When I try to connect the browser and remixd, i have error:

`setup notifications for ****`
`Shared folder : *****`
`Wed Nov 28 2018 14:01:20 GMT+0300 (Belarus Standard Time) Remixd is listening on 127.0.0.1:65520`
`origin https://remix.ethereum.org`
`Wed Nov 28 2018 14:01:29 GMT+0300 (Belarus Standard Time) Connection accepted.`
`[ERR] Unexpected Error servicesList[name][fn] is not a function`

**Comment by Aniket-Engg** [comment]
This should be fixed now. Please reopen if issue persists.
