### ISSUE TITLE
Scam Alert text update suggestion

### ISSUE THREAD

**Issue by Aniket-Engg** [ethereum/remix-project#5015]
I would suggest minor updates

May be we should update it something like:
```
The only authentic URL of Remix IDE is remix.ethereum.org . Any other URL having similar visual appearance can lead to scams.
Beware of the videos promoting "liquidity front runner bots" :  know more
Click here for additional safety tips.
```

**Comment by ryestew** [comment]
**The current text:**
The only URL Remix uses is remix.ethereum.org
Beware of online videos promoting "liquidity front runner bots" :  [here](https://medium.com/remix-ide/remix-in-youtube-crypto-scams-71c338da32d)
Additional safety tips :  [here](https://remix-ide.readthedocs.io/en/latest/security.html)

**Aniket's proposed text**
The only authentic URL of Remix IDE is remix.ethereum.org . Any other URL having similar visual appearance can lead to scams.
Beware of the videos promoting "liquidity front runner bots" :  know more
Click here for additional safety tips.

**Rob's comment**
It looks like you are trying to explain why using remix.ethereum.org is important.  I think that users should already know the reasons why they should only use our URL.  Also I am concerned that too much text makes everything look too busy and makes everything less legible.  So I don't think we need to update that text.  Also, "know more" is not correct.  It could be "learn more"  or just "more" or "more info" or "click" or "see".  FYI "see" is the language used in libraries (brick and morter) and in bibliographies.  I would recommend a link that just has 1 word.
