### ISSUE TITLE
Status Bar suggestions

### ISSUE THREAD

**Issue by Aniket-Engg** [ethereum/remix-project#5021]
- Tooltips are not looking good with status bar. Should be avoided unless quite important
- The bulb icon for tips, can be yellow and/or glowing one
- Tip with 'Did you know?' is not looking perfect. Either we can make it 'Tip:' or 'Did you know:' and make it bold or completely remove the text, only keep bulb

**Comment by LianaHus** [comment]
- I'm afraid I don't agree with tooltips. They are necessary. maybe explain what exactly you don't like and we can improve
- this was discussed and also tested on ux call. If you like join any ux call we can discuss again.
- did you know is also a hashtag and used everywhere as it is. we can make it bold 

I'll push some updates
