### ISSUE TITLE
Windows 10 installation issue

### ISSUE THREAD

**Issue by amahfuda** [ethereum/remix-project#503]
Hello.
Can't install this on Windows 10 x64bit from some reason.
The error i get is - lerna ERR! npm ERR! Can't install C:\Users\amahfuda\AppData\Roaming\npm\node_modules\remixd\node_modules\web3\packages\web3-eth-iban: Missing package name

Details:
C:\Windows\System32>npm install -g remixd
C:\Users\amahfuda\AppData\Roaming\npm\remixd -> C:\Users\amahfuda\AppData\Roaming\npm\node_modules\remixd\bin\remixd

> websocket@1.0.25 install C:\Users\amahfuda\AppData\Roaming\npm\node_modules\remixd\node_modules\websocket
> (node-gyp rebuild 2> builderror.log) || (exit 0)

C:\Users\amahfuda\AppData\Roaming\npm\node_modules\remixd\node_modules\websocket>if not defined npm_config_node_gyp (node "C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js" rebuild )
Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.
  bufferutil.cc
  win_delay_load_hook.cc
     Creating library C:\Users\amahfuda\AppData\Roaming\npm\node_modules\remixd\node_modules\websocket\build\Release\bu
  fferutil.lib and object C:\Users\amahfuda\AppData\Roaming\npm\node_modules\remixd\node_modules\websocket\build\Releas
  e\bufferutil.exp
  Generating code
  Finished generating code
  bufferutil.vcxproj -> C:\Users\amahfuda\AppData\Roaming\npm\node_modules\remixd\node_modules\websocket\build\Release\
  \bufferutil.node
  bufferutil.vcxproj -> C:\Users\amahfuda\AppData\Roaming\npm\node_modules\remixd\node_modules\websocket\build\Release\
  bufferutil.pdb (Full PDB)
  validation.cc
  win_delay_load_hook.cc
     Creating library C:\Users\amahfuda\AppData\Roaming\npm\node_modules\remixd\node_modules\websocket\build\Release\va
  lidation.lib and object C:\Users\amahfuda\AppData\Roaming\npm\node_modules\remixd\node_modules\websocket\build\Releas
  e\validation.exp
  Generating code
  Finished generating code
  validation.vcxproj -> C:\Users\amahfuda\AppData\Roaming\npm\node_modules\remixd\node_modules\websocket\build\Release\
  \validation.node
  validation.vcxproj -> C:\Users\amahfuda\AppData\Roaming\npm\node_modules\remixd\node_modules\websocket\build\Release\
  validation.pdb (Full PDB)

> web3@1.0.0-beta.33 postinstall C:\Users\amahfuda\AppData\Roaming\npm\node_modules\remixd\node_modules\web3
> lerna bootstrap

lerna info version 2.9.0
lerna info Bootstrapping 20 packages
lerna info lifecycle preinstall
lerna info Installing external dependencies
lerna ERR! execute callback with error
lerna ERR! Error: Command failed: npm install
lerna ERR! npm ERR! Can't install C:\Users\amahfuda\AppData\Roaming\npm\node_modules\remixd\node_modules\web3\packages\web3-eth-iban: Missing package name
lerna ERR!
lerna ERR! npm ERR! A complete log of this run can be found in:
lerna ERR! npm ERR!     C:\Users\amahfuda\AppData\Roaming\npm-cache\_logs\2018-03-26T09_53_58_666Z-debug.log
lerna ERR!
lerna ERR!     at Promise.all.then.arr (C:\Users\amahfuda\AppData\Roaming\npm\node_modules\remixd\node_modules\execa\index.js:236:11)
lerna ERR!     at <anonymous>
lerna WARN complete Waiting for 3 child processes to exit. CTRL-C to exit immediately.
{ Error: Command failed: npm installdencies: WARN complete Waiting for 3 child processes to exit. CTRL-C to exit immedi
npm ERR! Can't install C:\Users\amahfuda\AppData\Roaming\npm\node_modules\remixd\node_modules\web3\packages\web3-eth-iban: Missing package name

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\amahfuda\AppData\Roaming\npm-cache\_logs\2018-03-26T09_53_58_666Z-debug.log

    at Promise.all.then.arr (C:\Users\amahfuda\AppData\Roaming\npm\node_modules\remixd\node_modules\execa\index.js:236:11)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
  code: 1,
  killed: false,
  stdout: '',
  stderr: 'npm ERR! Can\'t install C:\\Users\\amahfuda\\AppData\\Roaming\\npm\\node_modules\\remixd\\node_modules\\web3\\packages\\web3-eth-iban: Missing package name\n\nnpm ERR! A complete log of this run can be found in:\nnpm ERR!     C:\\Users\\amahfuda\\AppData\\Roaming\\npm-cache\\_logs\\2018-03-26T09_53_58_666Z-debug.log\n',
  failed: true,
  signal: null,
  cmd: 'npm install',
  timedOut: false,
  exitCode: 1 }
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.1.3 (node_modules\remixd\node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.1.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! web3@1.0.0-beta.33 postinstall: `lerna bootstrap`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the web3@1.0.0-beta.33 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\amahfuda\AppData\Roaming\npm-cache\_logs\2018-03-26T09_54_02_657Z-debug.log
[2018-03-26T09_53_58_666Z-debug.log](https://github.com/ethereum/remixd/files/1847307/2018-03-26T09_53_58_666Z-debug.log)

**Comment by Aniket-Engg** [comment]
Hello @amahfuda , This should be fixed now. Can you please check it with latest remixd v0.6.11 ?
