### ISSUE TITLE
Add Generate Proof Section To Circom GUI

### ISSUE THREAD

**Issue by ioedeveloper** [ethereum/remix-project#5035]
Mockup: https://www.notion.so/Wireframe-Circom-9506106a8d194f3ca36aa8be9bc651bc?pvs=4
Story: https://www.notion.so/Circom-GUI-workflow-9f566dbf998241a9aedde9da2e49ad6d?pvs=4

**Comment by horberlan** [comment]
I want to work on this issue, Can you please assign this to me? I cant access story link
