### ISSUE TITLE
install remixd failed, looks like some depandency not installable

### ISSUE THREAD

**Issue by evaon1017** [ethereum/remix-project#504]
this is a clean computer, win10 64bit, and after code on remix online ide, I want to do some source control, then I found remixd that can let remix access local file system.

but install is not easy, i am not familier with nodejs, so please someone help me findout why I can't install remixd.

ps. I tried install Python latest stable, not work...

please reference the 
[2018-03-24T09_16_49_512Z-debug.log](https://github.com/ethereum/remixd/files/1844222/2018-03-24T09_16_49_512Z-debug.log)

i found:
verbose stack Error: web3@1.0.0-beta.33 postinstall: `lerna bootstrap`

**Comment by Aniket-Engg** [comment]
Closing it. Please feel free to reopen if issue persists
