### ISSUE TITLE
Add Scroll to Remix verification

### ISSUE THREAD

**Issue by emilyJLin95** [ethereum/remix-project#5061]
**Is your feature request related to a problem? Please describe.**
Developers cannot verify contracts through Scroll

**Describe the solution you'd like**
I want to add Scroll to the list of networks

**Describe alternatives you've considered**
Directing devs to Foundry or Hardhat

**Additional context**
https://github.com/ethereum/remix-project/blob/master/apps/etherscan/src/app/utils/networks.ts

For testnet:
534351: https://api.scrollscan.com/api

For mainnet:
534352: https://api-sepolia.scrollscan.com/api

**Comment by Jagadeeshftw** [comment]
I want to work on this issue, Can you please assign this to me?

**Comment by Aniket-Engg** [comment]
@emilyJLin95 I think scroll is already in this list: https://github.com/ethereum/remix-project/blob/master/apps/etherscan/src/app/utils/networks.ts See line 20 & 42

**Comment by emilyJLin95** [comment]
Oh sorry I misread the file
Closing!
