### ISSUE TITLE
"Copy Bytecode" Button Not Working on Chrome

### ISSUE THREAD

**Issue by kaifirschau** [ethereum/remix-project#5071]
**Describe the bug**
When I click the "copy bytecode" button in the Remix IDE in Chrome, nothing happens. The "copy ABI" button, however, works fine. Same problems also in inkognito mode. However: in Firefox, all is working.

**To Reproduce**
Compile any contract and try to get the bytecode.

**Expected behavior**
I can get my bytecode :)

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser: Chrome
 - Version: 127.0.6533.89 (arm64)

**Comment by Aniket-Engg** [comment]
It seems working fine for me. Can you recheck and confirm?
