### ISSUE TITLE
UX: Pinned contracts view.

### ISSUE THREAD

**Issue by yann300** [ethereum/remix-project#5105]
This view takes too much space when there is no pinned contract.

**Comment by ryestew** [comment]
In Deploy & Run, if nothing is deployed, it currently shows this:
![image](https://github.com/user-attachments/assets/c3093e2f-ad40-4e59-b9ea-56d0e2c0b4e5)

and if something is deployed but not pinned it shows this:
![image](https://github.com/user-attachments/assets/506065c7-b970-4f76-ac0e-712b9d9ea09b)

I think we had the ...

**Comment by LianaHus** [comment]
I would suggest not to remove it completely. It is still informative. We could show the number of pinned/deployed contracts near each title(0 if nothing is to show). And add the message as a tooltip.

**Comment by Aniket-Engg** [comment]
We should discuss it in next UX meeting

**Comment by ryestew** [comment]
<img width="267" alt="image" src="https://github.com/user-attachments/assets/65749403-eef3-4c73-a597-bac7750ff463">

**Comment by ryestew** [comment]
Pinned:

Deployed/Unpinned:
No contracts have been pinned
No unpinned contracts
No contracts have been deployed

There are 2 sections 1. Pinned Contracts 2. Deployed Contracts
We could just say 
for **Pinned Contracts** (and include the network)(but we don't currently mention the workspace - but that's OK)
"No deployed contracts pinned to this Workspace & network"

for **Deployed Contracts** (unpinned is too awkward a work - so lets just leave it out)(unpin as a verb is awkward but makes sense.  Unpinned as an adjective takes to much thought to decipher) .

Either:
**No contracts here** or **Empty** or **None**

**Comment by ryestew** [comment]
plus @Aniket-Engg - Reduce padding and margins

**Comment by vermouth22** [comment]
Yes, I agree. 

Pinned Contracts
"No deployed contracts pinned to this Workspace and network"

Deployed Contracts
"No contracts here"

**Comment by Aniket-Engg** [comment]
@LianaHus Can you also share your views?

**Comment by LianaHus** [comment]
![Screenshot from 2024-09-05 10-06-00](https://github.com/user-attachments/assets/8e257253-bffb-4739-8dba-12d01730ecd2)
I'll put this here as well

**Comment by LianaHus** [comment]
![Deploy and Run (3)](https://github.com/user-attachments/assets/e5956c36-8865-4d4e-82a7-2c8877aad5d9)

**Comment by LianaHus** [comment]
![Deploy and Run (4)](https://github.com/user-attachments/assets/b2cfa31e-add6-44df-acb8-6ece6e9f34b7)

**Comment by LianaHus** [comment]
![Deploy and Run (5)](https://github.com/user-attachments/assets/9709ff87-c1b6-4153-8993-9924fe8bb44d)
