### ISSUE TITLE
Ballot contract bug

### ISSUE THREAD

**Issue by drortirosh** [ethereum/remix-project#5163]
**Describe the bug**
in the Ballot contract, a account can be locked out from voting - and lock other accounts too...
Say account A is registered, and calls "delegate" to account "B", which is not yet registered.
Now account "A" is marked as "voted", and account "B" has a weight increase ([here](https://github.com/ethereum/remix-project/blob/master/apps/remix-ide/contracts/ballot.sol#L92))
But account "B" can't register, since its current weight is not zero ([here](https://github.com/ethereum/remix-project/blob/master/apps/remix-ide/contracts/ballot.sol#L63)).. 
This way, both account "A" and account "B" are locked from voting..

The simplest fix is to require account-B to be already registered.
To allow delegating to unregistered account, need to add another flag, to separate "weight" from "registered"

**Comment by Aniket-Engg** [comment]
Ok, I see.

May be adding a under `delegate` can disallow delegation to unregistered addresses:
```
require(voters[to].weight != 0, "Delegated address should have the right to vote.");
```

**Comment by Aniket-Engg** [comment]
Anyway it was inspired from this contract in Solidity docs: https://docs.soliditylang.org/en/v0.8.27/solidity-by-example.html#voting

**Comment by Aniket-Engg** [comment]
As per the discussion with Solidity team, `// Voters cannot delegate to accounts that cannot vote.
        require(delegate_.weight >= 1);` is missing in our code
