### ISSUE TITLE
Deploy with proxy has stopped automatically deploying the proxy contract

### ISSUE THREAD

**Issue by hustynetwork** [ethereum/remix-project#5164]
**Describe the bug**
Deploy contract as proxy option is no longer deploying the 2nd contract automatically. There is no signing popup nor any pending log.

**To Reproduce**
1. basic deploy as proxy
2. first contract is deployed
3. proxy contract is not deployed (no popup for transaction signing)

**Comment by Aniket-Engg** [comment]
cc: @ioedeveloper
