### ISSUE TITLE
Accessing a already deployed contract with remixd in read-only mode

### ISSUE THREAD

**Issue by SvenMeyer** [ethereum/remix-project#5172]
I have a deployed contract (on Base Sepolia)
I want to connect Remix to that contract.
To provide remix with either the Solidity source code or the abi / json, I run remixd in a console in read-only mode (to secure my local filesystem).

However, although I tried all options the [At Address] button next to the inout field which I populated with the deployed address, is greyed-out.

1) As suggested by the opo up, I selected the abi json in the File Explorer and opened it in the editor, went back to the "Deploy & Run Transactions" tab, but [At Address] button is greyed-out

2) When I click the small 'sync' cirle next to the CONTRACT selector field (within "Deploy & Run Transactions" tab), I see all contract quickly showing up in the drop down selector, but at the end there is only one contract left to be selected, and its not the once I want.

3) I compiled the contract, some problem [At Address] button is greyed-out. It does not make a difference if I compile with hardhat or the internal compiler.

![image](https://github.com/user-attachments/assets/1163b6aa-7904-4d4b-8353-a9c3c75049d2)

**Comment by Aniket-Engg** [comment]
Hello @SvenMeyer , I can reproduce this. 

Can this try this: Compile a contract or select an abi file first then put the address in textbox. See if that enables the `At address` button
