### ISSUE TITLE
Matomo integration

### ISSUE THREAD

**Issue by yann300** [ethereum/remix-project#52]
This issue is for tracking Matomo integration

current TODOs

### For the next release (beginning April)

- we push the info that we are doing matomo integratio and ask for feedback + remix gitter channel

### Setup an instance of matomo/remix ( remix-beta.ethereum.org )

https://github.com/ethereum/devops/issues/369

### Basic implementation for warning the user could look like:

 - homepage : msg with the basic info, saying that it's opt in by default and obvious link to the settings to the opt out 

 - settings: specific information about what we are doing, with list of stuff we are analyzing, they can opt out easily

### item/action we put matomo in : 

 - how many active users do we have and some general statistics. initial PR https://github.com/ethereum/remix-project/issues/887

 - list of loaded plugins https://github.com/ethereum/remix-project/issues/881

 - using settings tab (themes, ... )  https://github.com/ethereum/remix-project/issues/879

 - how long they are using specific plugins https://github.com/ethereum/remix-project/issues/881

 - publish to IPFS (from run tab) https://github.com/ethereum/remix-project/issues/883

 - plugin documentation link https://github.com/ethereum/remix-project/issues/882

 - using mainnet / testnet and VM ? https://github.com/ethereum/remix-project/issues/884

 - run tab : using atAddress input / deploy https://github.com/ethereum/remix-project/issues/885

 - user flow ( which module in which order ) - create af file / compile it / deploy / at address / static analysis https://github.com/ethereum/remix-project/issues/886

- Content menu actions https://github.com/ethereum/remix-project/issues/1381

**Comment by LianaHus** [comment]
https://matomo.org/privacy-policy/ privacy policy template
