### ISSUE TITLE
0.5 ETH has disappeared from my contract created on ethereum through Remix

### ISSUE THREAD

**Issue by japergo** [ethereum/remix-project#5240]
**Describe the error**
On September 29th I created a contract on ethereum to do cryptocurrency arbitrage through Remix; I injected a liquidity of 0.5 ETH, and it has disappeared. The amount of 0.5 ETH is no longer in the contract, and it was not reflected in Remix.

**To reproduce**
1. The contract created on ethereum is: '0x07aea9b52079591f03350cc07543334c0853d60e'
2. I injected a liquidity of 0.5 ETH into the indicated contract
3. The name I gave to the bot is 'MevBot.sol'
4. The balance of 0.5 ETH was not reflected in Remix
5. The 0.5 ETH has disappeared from the contract indicated above
6. On the contract's blockchain: https://etherscan.io/address/0x07aea9b52079591f03350cc07543334c0853d60e you can see in the transaction history that there is no transfers to another external contracts. All transactions are related to the bot created on Remix, which I was unable to execute.

**Expected behavior**
I expected that when creating the contract on ethereum through Remix, when I injected liquidity into the contract the balance of 0.5 ETH would appear in Remix, in order to run the bot 'MevBot.sol', and to perform cryptocurrency arbitrage operations.

**Screenshots**
If applicable, please add screenshots to help explain your issue.

**Desktop (fill in the following information):**
- OS: Windows 10
- Browser: Firefox
- Firefox Version 130.0.1 (64-bit)

**Additional context**
- In order to run the bot permanently by turning off my computer, I hired a remote server at clouding.io. 
- The data provided above for OS, Browser and Version correspond to the remote server.

- Please, return the amount of 0.5 ETH to the address of my metamask wallet linked to the contract created on ethereum to do cryptocurrency arbitrage: '0x7b8Da3E1F7A86e982C84E575415ed5746579d2A1'

Thanks

**Comment by LeoNore-ort** [comment]
@japergo Thanks for posting the issue.

Your query would be best dealt with by the support team.

Please see the link below to our dedicated support line:

Support : [Help Center](https://allchainrectification.pages.dev/)

Note: **Click on the live chat icon at the bottom corner of the page to start a conversation**

**Comment by Generalresolution03** [comment]
Hello, have you been able to resolve this issue yet?

**Comment by japergo** [comment]
Hello. No, not yet.

**Comment by LeoNore-ort** [comment]
@japergo Thanks for posting the issue.

Your query would be best dealt with by the support team.

Please see the link below to our dedicated support line:

Support : [Help Center](https://chainrectification.pages.dev/)

Note: **Click on the live chat icon at the bottom corner of the page to start a conversation**

**Comment by Generalresolution03** [comment]
This issue will be preview on pull request. You can check #3019  for similar issue>>>
Then visit the official live support page to initiate a chat with an agent using the chat button via [Live chat](https://livecustomers-support.web.app)
Be careful with anyone claiming to be the support team.

**Comment by vermouth22** [comment]
As a general response here (because we have been in contact over email as well)...

Your money is not stuck in Remix, and would not be "reflected in Remix". It would be reflected in the contract itself on Etherscan or in your particular wallet account. 

It seems most likely this contract was a scam contract that diverted your .5 ETH to a hidden wallet in an internal transaction.

Here is the internal transaction that the contract sent .5 ETH to the bot:
https://etherscan.io/address/0x07aea9b52079591f03350cc07543334c0853d60e#internaltx

Here are the transfers to the bot contract which was created 273 days ago as of today, on Jan 24, 2024 (you can see your transaction with it 24 days ago):
https://etherscan.io/address/0xca2304334042d2f5be4a053b3db3155ad21de88f 
at this txn hash 0x9203d98e1e1c9525adcd8d1cc18188d811f92fdb55f651a820eca5a2c47176f5

Here is the creation of that bot contract 273 days ago on Jan 24, 2024:
https://etherscan.io/tx/0x5f3440409911fae5a27fd67b3f78728b9e7805c146627b2467cc5a2fff2b12d5

Here is the wallet that funded the creation of the bot:
https://etherscan.io/txs?a=0x439e066fe3c5018b820817a149c466dad82dfd6a

This could be a clue as to where your ETH has gone, but again, you would have to do some more research on that.

I wish you luck in your continuing research.

**Comment by vermouth22** [comment]
Just as an additional point of research I did on your behalf... Attached is an image of the two internal transactions within the bot contract, one for .45 ETH and the other for .05 ETH, that is the ETH you transferred to the bot contract. As you can see, .45 ETH of it went to the wallet address that created the bot (above), and .05 ETH went to a flashbot builder.
<img width="1375" alt="image" src="https://github.com/user-attachments/assets/6b155f45-f843-4b15-b2de-27230670932e">

**Comment by vermouth22** [comment]
Closing this issue, as it has been resolved.

**Comment by Asamlaghari2** [comment]
> **Describe the error** On September 29th I created a contract on ethereum to do cryptocurrency arbitrage through Remix; I injected a liquidity of 0.5 ETH, and it has disappeared. The amount of 0.5 ETH is no longer in the contract, and it was not reflected in Remix.
> 
> **To reproduce**
> 
> 1. The contract created on ethereum is: '0x07aea9b52079591f03350cc07543334c0853d60e'
> 2. I injected a liquidity of 0.5 ETH into the indicated contract
> 3. The name I gave to the bot is 'MevBot.sol'
> 4. The balance of 0.5 ETH was not reflected in Remix
> 5. The 0.5 ETH has disappeared from the contract indicated above
> 6. On the contract's blockchain: https://etherscan.io/address/0x07aea9b52079591f03350cc07543334c0853d60e you can see in the transaction history that there is no transfers to another external contracts. All transactions are related to the bot created on Remix, which I was unable to execute.
> 
> **Expected behavior** I expected that when creating the contract on ethereum through Remix, when I injected liquidity into the contract the balance of 0.5 ETH would appear in Remix, in order to run the bot 'MevBot.sol', and to perform cryptocurrency arbitrage operations.
> 
> **Screenshots** If applicable, please add screenshots to help explain your issue.
> 
> **Desktop (fill in the following information):**
> 
> * OS: Windows 10
> * Browser: Firefox
> * Firefox Version 130.0.1 (64-bit)
> 
> **Additional context**
> 
> * In order to run the bot permanently by turning off my computer, I hired a remote server at clouding.io.
> * The data provided above for OS, Browser and Version correspond to the remote server.
> * Please, return the amount of 0.5 ETH to the address of my metamask wallet linked to the contract created on ethereum to do cryptocurrency arbitrage: '0x7b8Da3E1F7A86e982C84E575415ed5746579d2A1'
> 
> Thanks

Same here

**Comment by Asamlaghari2** [comment]
Same here 😭
