### ISSUE TITLE
Create blank on hand burger menu bar bug

### ISSUE THREAD

**Issue by praisedisu** [ethereum/remix-project#5277]
**Describe the bug**
there is a bug whenever I create a blank on my hand burger menu the title doesn't save correctly rather it saves as blank - 1, blank - 2, ...

**To Reproduce**
1. Go to 'the hand burger menu'
2. Click on 'create blank'
3. Save new Blank
4. It saves as blank - 1, blank - 2, ...

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. Windows, Linux or MacOS]
 - Browser [e.g. chrome, firefox]

**Additional context**

```[tasklist]
### Tasks
```

**Comment by Aniket-Engg** [comment]
I can reproduce this.

**Comment by praisedisu** [comment]
I solved this bug, but tried creating a pull request, but it wasn't merged, I solved the issue on https://github.com/ethereum/remix-project/pull/5278#partial-pull-merging

**Comment by praisedisu** [comment]
-You can reproduce the error by going to the hand burger menu on the left top corner close to your workspaces
-click on create blank
-try inputting the name
-the name saves as blank - 1, blank -2, and so on,
I've fixed this error in my repo and I created a pull request, but it hasn't been merged
