### ISSUE TITLE
"Copy Bytecode" Button Not Working

### ISSUE THREAD

**Issue by geltonastech** [ethereum/remix-project#5316]
**Describe the bug**
after compiling. I click the 'Bytecode' button and is not working.. the ABI is working well. 

I have tried both chrome and firefox and still not working.. this using the Remix online IDE, with the desktop version the moment I click in the copy icon the page goes white..

I am working with MacOS with chrome V. 129.0.6668.101

**Comment by Aniket-Engg** [comment]
@geltonastech This seems working fine for me on online IDE. Can you share exact steps to reproduce?
