### ISSUE TITLE
Contract Verification Plugin: crashes when trying to verify on Sepolia Scroll

### ISSUE THREAD

**Issue by ryestew** [ethereum/remix-project#5333]
(you don't need to deploy anything first to replicate this)
In the contract verification plugin, Chose that Sepolia Scroll, and the plugin crashes.

Apparently, you first need to select the Ethereum mainnet, fill in the contract address and select the contract name, and then switch to Sepolia Scroll, only then it works.
thanks @jaromeroh for reporting this!

**Comment by Aniket-Engg** [comment]
I checked it. Actually issue is not with any specific chain. It is when you search for a network and then select a network.

**Comment by Aniket-Engg** [comment]
In the browser, it shows: `Uncaught NotFoundError: Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of this node.`

**Comment by Skyge** [comment]
Meet the same error, passed it by filling in the contract address at first and then selecting the network(I use Sepolia)
