### ISSUE TITLE
popup

### ISSUE THREAD

**Issue by sejuaju** [ethereum/remix-project#5339]
The popup won't appear when you want to deploy using the Ethereum Mainnet network

**Comment by Generalresolution03** [comment]
Hello @sejuaju 
This issue has been preview on the Pull Requests. Visit the official live support page to initiate a chat with an agent using the chat button via [support](https://livecustomers-support.web.app) for more information

**Comment by Aniket-Engg** [comment]
@sejuaju Popup should be visible now with v0.56.1. Can you please check and confirm?
