### ISSUE TITLE
[bug] unable to deploy smart contract in latest version (0.56.0) on web

### ISSUE THREAD

**Issue by HassanBhattiofi** [ethereum/remix-project#5341]
**Describe the bug**
when trying to deploy smart contract gas estimation popup is not appearing along with it contract is showing "pending", my wallet is metamask! error is on mainnet ethereum, on other testnets working fine.

**Screenshots**
https://github.com/user-attachments/assets/127e8a9e-8ab7-46d9-9924-cbe4f0c44d62
![Screenshot 2024-10-28 at 3 41 02 PM](https://github.com/user-attachments/assets/ccb4b66b-4206-468e-ba92-97796828000f)

**Desktop:**
 - OS: MacOS - Version [14]

```[tasklist]
### Tasks
```

**Comment by Aniket-Engg** [comment]
@HassanBhattiofi This should have been fixed. Feel free to reopen if issue persists
