### ISSUE TITLE
Log out from github

### ISSUE THREAD

**Issue by LianaHus** [ethereum/remix-project#5373]
after log in there is no way to log out. we should implement this

**Comment by dominikrudzki** [comment]
@LianaHus Isn't the "Disconnect" button in the Git tab from the sidebar meant for this purpose?
![image](https://github.com/user-attachments/assets/4c1e9b29-31b7-4e17-b950-ce6b97c4fe02)

**Comment by LianaHus** [comment]
yes but I'm talking about the login-logout from File Explorer
