### ISSUE TITLE
No compatible chain found for the selected EVM version. Consider opening an issue to update our internal store with your desired chainId.

### ISSUE THREAD

**Issue by DDev16** [ethereum/remix-project#5389]
**Describe the bug**
 i have been developing using UUPS upgradebale proxy pattern and mid upgrade remix got stuck. so i refrresehd the page and clear my activity on metmask. once i did this i then tried to interact with contracts and or upgrade my contracts and i get this error
 
 No compatible chain found for the selected EVM version.
Consider opening an issue to update our internal store with your desired chainId.

**To Reproduce**
1. Go to 'Injected provider with Metamask'
2. 'Chain ID 14'
3. compile contract
4. click deploy 

then this error

No compatible chain found for the selected EVM version.
Consider opening an issue to update our internal store with your desired chainId.

**Expected behavior**
i need to interact with Flare EVM as i have for 5 years not sure whats going on 

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [Windows 11]
 - Browser [edge]
 - Version [@latest]

**Additional context**

**Comment by DDev16** [comment]
https://remix.ethereum.org/#lang=en&optimize=true&runs=200&evmVersion=london&version=soljson-v0.8.26+commit.8a97fa7a.js heres my settings

**Comment by MDSL21** [comment]
Hi! I’m encountering a similar issue. I’m unable to interact with deployed functions on chain ID 97 (BSC testnet). Whenever I attempt to click on a public or simple external function, I receive the following error:

No compatible chain found for the selected EVM version.
Consider opening an issue to update our internal store with your desired chainId.

However, the issue disappears when I switch back to chain ID 56

<img width="619" alt="Screenshot 2024-11-07 at 9 58 48 PM" src="https://github.com/user-attachments/assets/4922c13d-ea7a-4dc6-a017-1c24298ea7b7">

**Comment by DDev16** [comment]
Yes I'm currently experiencing same issue, except for Chain id 14 (Flare) and chain 16 (Songbird)

if I switched to chain id 1 I have no issue and can interact with that network. Same for other EVM chains

I've been developing and working on UUPS Upgradeable contracts all day and all last night. this issue seemed to have happened mid day today while I was testing a contract. 

I've had to resort to interacting with the contracts and performing upgrades via hardhat, ethers, and node.js with scripts

which sucks as i used remix for mainly testing with ease. hopefully this issue gets resolved.. ive noticed they had a recent fail on their recent push maybe that has something to do with it

**Comment by supmisterkim** [comment]
Also happens with chain ID 8453 (Base)

**Comment by junnai09** [comment]
I am also experiencing this issue with Chain ID 8008135 (Fheni Helium)

**Comment by ntop001** [comment]
This is a weird problem, I have just deployed my contract few days ago, and the today, when I want to deploy a new one with another wallet, it's said: 
```
No compatible chain found for the selected EVM version.
Consider opening an issue to update our internal store with your desired chainId.
```
Honestly,I don't know what happened, just don't work anymore.

**Comment by aayush2870** [comment]
I am experiencing the same issue in Remix. When attempting to deploy a contract on the Amoy network (chain ID: 80002), I receive the following error message:

"No compatible chain found for the selected EVM version. Consider opening an issue to update our internal store with your desired chainId."

Despite this message, I was able to deploy the contract. However, none of the functions in the contract are working after deployment.

**Comment by giirafe** [comment]
Same issue on Amoy Network(Chain ID:80002). In my case I was trying to access deployed contract using 'At Address' and this error occured

**Comment by Caneryy** [comment]
I've been getting the same error since yesterday. Chain ID: 167009

**Comment by aiachain** [comment]
I've been getting the same error since today. Chain ID: 1319

**Comment by huahuahua1223** [comment]
I've been getting the same error since today. Chain ID: 1337

**Comment by RamirezXxX** [comment]
I have same error since today
No compatible chain found for the selected EVM version.

**Comment by devduru** [comment]
> Also happens with chain ID 8453 (Base)

yes just observed that now, any solution?

**Comment by lxh1121** [comment]
same problem ，bsc testnet chain ID 97。
<img width="605" alt="image" src="https://github.com/user-attachments/assets/aa9c757e-0e74-4b53-9b50-36e792d0c409">

**Comment by mehzee92** [comment]
Same issue for me on all chains i.e BSC, Bsc testnet, Sepolia etc

**Comment by fragtex-eth** [comment]
Same issue for me (ChainId: 1301)

**Comment by hoshi2237** [comment]
I encountered the same problem with Remix when I tried to deploy the contract on Ganache's local blockchain and received the message. However, trying to change the EVM version on Remix did not solve the problem. However, contract deployment can be carried out normally on Sepolia testnet.

**Comment by userInner** [comment]
我在使用FISCO-BCOS WEB3 RPC接口时，也报了相同错误，如下图
![image](https://github.com/user-attachments/assets/cbc66ebd-95cd-4f12-8a8d-e12a04773430)

**Comment by MDSL21** [comment]
> its fixed everyone

Great! Everything is normal here now.
