### ISSUE TITLE
Change EVM Chain map

### ISSUE THREAD

**Issue by ryestew** [ethereum/remix-project#5390]
**Describe the bug**
1. All chains should be able to deploy even if they are not on the map - so remove this error:
<img width="640" alt="image" src="https://github.com/user-attachments/assets/1938e36a-4ae3-47eb-b84c-2c68dcfaa0c1">

2. Assume all networks support the latest EVM unless they are in the map
3.  remove all chains but celo in the map - really celo mainnet. The rest of the chains we will put in the map as we get their input.

**To Reproduce**
4. Click on '....'
5. Scroll down to '....'
6. See error

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. Windows, Linux or MacOS]
 - Browser [e.g. chrome, firefox]

**Additional context**

**Comment by kirillpraded** [comment]
I also got this error when trying to connect Rabby Wallet using ApeChain. I need to deploy ASAP. Have you found solutions to this problem? @ryestew

**Comment by mengbin92** [comment]
I also got this error when trying to connect MetaMask Wallet using my own PoA chain. Have you found solutions to this problem? @ryestew

**Comment by joeizang** [comment]
There is a solution. A patch release will be out very soon

**Comment by DDev16** [comment]
Chain Id14 , 16 and 19 need fixed as well cannot interact through remix, have to interact via scripts

**Comment by DDev16** [comment]
> I also got this error when trying to connect Rabby Wallet using ApeChain. I need to deploy ASAP. Have you found solutions to this problem? @ryestew

solution is to write scripts and interact via ethers, hardhat, and node. js and javascript  for now

**Comment by ryestew** [comment]
@DDev16 - the patch release to fix this problem was done yesterday - this all should be working now.  If no please post here.

**Comment by mengbin92** [comment]
Remix v0.57.1 fix
