### ISSUE TITLE
Stagnant popup at Remix AI obstructs the view of some content

### ISSUE THREAD

**Issue by praisedisu** [ethereum/remix-project#5445]

**Comment by Aniket-Engg** [comment]
Popup can be minimized by double caret icon on left top.

**Comment by Aniket-Engg** [comment]
@praisedisu it is fixed by https://github.com/ethereum/remix-project/pull/5449

**Comment by praisedisu** [comment]
> @praisedisu it is fixed by #5449

alright, thanks for the fix
