### ISSUE TITLE
New Vyper UI is too noisy

### ISSUE THREAD

**Issue by ryestew** [ethereum/remix-project#5458]
The old Vyper UI was designed to be as close to the Solidity UI as possible. 
<img width="298" alt="image" src="https://github.com/user-attachments/assets/800b22e4-ea89-4206-8f94-a2525a8caa81">

Here is the new UI

<img width="315" alt="image" src="https://github.com/user-attachments/assets/69d54c4c-b575-4009-9984-535e3c0e561a">

At first I didn't see the logic - because I didn't really see the outline of the buttons.  
- The text in the buttons is too bright its better when its gray
- With the outline buttons - the text now looks like its floating all over the place
- The text Advanced Compiler Settings (which matched the Soldiity Compiler is now Configuration.  It should probably just be Compiler Settings.  But the size is too big and should be in gray- it is the most prominent thing on the panel.  It also doesn't seem to have much to do with the gray caret to its right - but it should.  Both should be in gray.

**Comment by LianaHus** [comment]
we are talking to remove the settings because it makes no sense. the rest I"ll adjust, I did;t check for dark theme, my bad
