### ISSUE TITLE
issue in running parent and child test file together

### ISSUE THREAD

**Issue by Aniket-Engg** [ethereum/remix-project#548]
If a (child) test file is generated from a (parent) test file and tests are run for both together, tests from parent test file appears twice without final result.

<img width="295" alt="testsIssue" src="https://user-images.githubusercontent.com/30843294/97994904-dad81580-1e0b-11eb-9ef1-f25e76f43f93.png">

cc: @LianaHus

**Comment by yann300** [comment]
This is what I got, could you details the step to reproduce (how to generate the files e.g - I used the action in the testing tab)
![remix](https://user-images.githubusercontent.com/6940742/98004173-e4538480-1def-11eb-95b6-f2a64d6c3a19.png)

**Comment by LianaHus** [comment]
you should generate a test file from test file. like that you have for example ballot_test.sol and ballot_test_test.sol

**Comment by yann300** [comment]
I believe this is what I did... As you can see the second test file imports the first one.

**Comment by yann300** [comment]
does this happen consistently?

**Comment by Aniket-Engg** [comment]
After analysing again, I think this is an issue in displaying result on UI.

**Comment by Aniket-Engg** [comment]
This is discussed with @LianaHus . This can not be reproduced anymore so closing this.
