### ISSUE TITLE
FE: issues with File Explorer

### ISSUE THREAD

**Issue by LianaHus** [ethereum/remix-project#55]
- [x] add *Create Folder* and *Create File* to the context menu of **Browser**
- [x] Check if file name already exists and use *createNonClashingNameWithPrefix()* of helper
- [x] check if folder name already exists and add a error or suggest versions
- [x] check if folder name is empty and add a error or suggest versions
- [x] *rename* of gist id folder should be prohibitted
- [x] *create folder* doesn't work when current folder is nested one(3rd level folder ex browser/a/b), openes *create file* modal instead
- [x] remove *create folder* from gist id menu
- [x] empty files name is not allowed
- [x] remove tabs when files removed
~~- [ ] allow to have a file and folder with same name~~
- [x] add path as a tooltip to the tabs
- [x] select the line on right click
- [x] Rename folder with content

**Comment by ioedeveloper** [comment]
The remix-ide fileSystem does not allow the existence of files and folders with the same name in the same location. So the option for file and folder with the same name has been crossed.
