### ISSUE TITLE
Debugger Config UI design needs a slight makeover

### ISSUE THREAD

**Issue by ryestew** [ethereum/remix-project#578]
The top and bottom margin of the Debugger config stuff needs an update.
The new Debugger Config currently looks like this:
<img width="421" alt="image" src="https://user-images.githubusercontent.com/6050001/99161420-24ecb100-26c0-11eb-9fe3-ff83e7010626.png">

It used to look like this:
![image](https://user-images.githubusercontent.com/6050001/99161274-af341580-26be-11eb-8e15-5dc5369728f0.png)

So now the hash of the txn is not the at the top of the screen - and the first thing people see is the Debugger Configuration stuff.  I'm not sure this should be at the top.  But let's leave it there for now.  But It seems not important enough to take up so much vertical height ( 2 lines for a single checkbox).

Here's a version with the spacing improved:
![image](https://user-images.githubusercontent.com/6050001/99161322-29649a00-26bf-11eb-9fd1-086bd934559d.png)

Here's a version with the config checkbox in a collapsed card:
![image](https://user-images.githubusercontent.com/6050001/99161340-6597fa80-26bf-11eb-91dd-360d43bd8ae2.png)

This puts everything on a single line and makes it fit in with the rest of the page.  Although maybe we should consider putting it lower down on on the module.

We need to update docs as well
(Liana)

**Comment by LianaHus** [comment]
to make things easier/clearer we can remove the label 'Debugger Configuration" and leave one line with checkbox only.
if later we add more configuration that can be restored(expandable for example as you're suggesting)
i don't see any other place to put this. somewhere at the end of the plugin will not work
