### ISSUE TITLE
Fetch imports automatically from `raw.githubusercontent.com` instead of `github.com`

### ISSUE THREAD

**Issue by edisinovcic** [ethereum/remix-project#579]
```
Unable to import "undefined": API rate limit exceeded for xx.xx.xx.xx. (But here's the good news: Authenticated requests get a higher rate limit. Check out the documentation for more details.)
```

Wrong import url basically. I was using:

```import 'https://github.com/OpenZeppelin/openzeppelin-contracts/tree/release-v3.2.0-solc-0.7/contracts/access/Ownable.sol';```
instead of
```import 'https://raw.githubusercontent.com/OpenZeppelin/openzeppelin-contracts/release-v3.2.0-solc-0.7/contracts/access/Ownable.sol';```

Would it make sense to signal this to user or automatically try to fetch from raw.githubusercontent.com?

**Comment by Aniket-Engg** [comment]
I think using replacing `tree` with `blob` in `https://github.com/OpenZeppelin/openzeppelin-contracts/blob/release-v3.2.0-solc-0.7/contracts/access/Ownable.sol` will also work fine
