### ISSUE TITLE
Beginner Developer

### ISSUE THREAD

**Issue by zaman10d** [ethereum/remix-project#585]
This is my false. we do something wrong. I Don't know this happen. so forget it about this pending. we need Robot to setup digital assets. Moving forward assets growing. Withdraw  on/off. TQ

**Comment by Aniket-Engg** [comment]
Closing as unclear.

**Comment by zaman10d** [comment]
No comment just keep moving forward assets account. Futures. Thanks you Bro/

**Comment by zaman10d** [comment]
Comment asset account moving growing futures. Some Withdraw Covid19 pandemic breaking down. Economy down. Money very urgent now. Lifes foods.
