### ISSUE TITLE
Improve Remix project template

### ISSUE THREAD

**Issue by yann300** [ethereum/remix-project#608]
For the moment a basic project includes example files and test files.
We should add to it JavaScript File (script file) for deploying / calling contract and a readme which explain how to use it.

**Comment by yann300** [comment]
@Aniket-Engg @ryestew please have a look to the branch `removeFiles`. Some logics and ideas from there could be reused..

**Comment by Aniket-Engg** [comment]
There were two proposals for it:
```
a) 
--src
   ----sol
   ----js
--test
   README.md

b)
--contracts
--scripts
--tests
    README.md
```

and `b` was preferred in internal team voting.
