### ISSUE TITLE
remixd modal instructions

### ISSUE THREAD

**Issue by ryestew** [ethereum/remix-project#635]
The instructions need to be edited.  
* Also does it need the --remix-ide in the command?
*  The command I used is simpler: remixd -s ./ https://remix.ethereum.org
* the modal is grabbing the entire URI - including the url params which makes it a bit confusing to read 

<img width="494" alt="image" src="https://user-images.githubusercontent.com/6050001/100288556-f040eb00-2f44-11eb-968b-9d7f0e7d731b.png">

Access your file system from Remix. Remixd the NPM module needs to be running in the background to use the Remixd plugin.  For more info please check the Remixd tutorial.

If you have looked at that tutorial and are just looking for the remixd command,
here it is:
remixd -s absolute-path-to-the-shared-folder --remix-ide your-remix-ide-URL-instance

A connection will start a session between http://remix-alpha.ethereum.org and your local file system ws://127.0.0.1:65520. 
To see that a connection has been made, check that there is a localhost section in the Files Explorer.

Please make sure your system is secured enough (port 65520 should not be opened nor forwarded).  
This feature is still in Alpha, so we recommend you to keep a copy of the shared folder.

**Comment by LianaHus** [comment]
@ryestew do you want to remove an alert for updating?

**Comment by LianaHus** [comment]
https://github.com/ethereum/remix-project/pull/1168 this part is already done
