### ISSUE TITLE
Undo change from SVG to WEBP

### ISSUE THREAD

**Issue by fulldecent** [ethereum/remix-project#645]
These commits are bad:

https://github.com/ethereum/remix-project/commit/7c539d8ed60bdc7bd766798e874243f68379f030
https://github.com/ethereum/remix-project/commit/f089853b9c0e94cacd30ee9219a8b1cfb68b26f7
https://github.com/ethereum/remix-project/commit/da5935441f05c088ba84c2fa8fbeff78b4051136

From @LianaHus @ioedeveloper 

---

They removed vector images in a format that works with all browsers and replaced it with a raster format that only works with some browsers.

Here is how remix currently loads on macOS Big Sur / Safari for me:

<img width="1504" alt="Screen Shot 2020-11-29 at 20 08 12" src="https://user-images.githubusercontent.com/382183/100558969-a9bdfa00-327e-11eb-87bc-471c2651a972.png">

---

Work plan

- [ ] Create SVG images by decoding the strings at data:image/svg
- [ ] s/.webp/.svg/c
- [ ] Delete those WEBP files

**Comment by GrandSchtroumpf** [comment]
@fulldecent thanks for keeping a positive discussion on github. We all try to do our best to improve devX.
These commits are not "bad", they **try** to provide a better experience for most developers. Some background:

webp is a great format [recommended to be use on the web](https://web.dev/serve-images-webp/). As it happens, **Safari and IE** don't support webp, and we didn't realized that as nobody in the team are using neither of them.

The right working plan would be to provide a fallback to svg or png for browser that doesn't support webp. Like that users using other browser than Safari or IE can enjoy the benefice of webp images.

**Comment by LianaHus** [comment]
https://www.macrumors.com/2020/06/22/webp-safari-14/

**Comment by fulldecent** [comment]
In general, SVG vector graphics are superior to bitmap graphics. They look great on every device/screen/resolution, they minimize file size and they are losslessly editable.

The only times to avoid SVG are:

 - Screenshots (too much detail)
 - Photography (too much detail)
 - Unimportant animations (because most people don't bother to animate SVGs)
 - Ridiculously high level of detail (e.g. a fractal rendered in full precision)

These are the reasons I recommend to revert to using SVG.

---

Human/voice note: The people mentioned above are good. And the commits were well intentioned. And they even made an improvement (refactoring image from inline to separate file). I am concerned only with the negative impact of the commit mentioned above.

**Comment by fulldecent** [comment]
@GrandSchtroumpf the article you cite https://web.dev/serve-images-webp/ does not match your summary "webp is a great format recommended to be use on the web" in this context.

That article (correctly) only recommends:

> WebP is an excellent replacement for JPEG, PNG, and GIF images

It does not recommend replacing SVGs with WebPs.

---

@LianaHus likewise, the article you cite https://www.macrumors.com/2020/06/22/webp-safari-14/ only compares:

>  It provides lossy and lossless compression with smaller file sizes as compared to JPEG and PNG files.

Likewise, no recommendation is made for replacing SVGs to be WebPs.

**Comment by LianaHus** [comment]
@fulldecent your problem should be solved now in remix-alpha can you confirm?
This PR was about moving from base64 to wepb. We don't have svgs of all icons we use and don't want to use external svgs for security reasons.
The article was about adding support to safari.

**Comment by fulldecent** [comment]
Looks good in Safari.

---

We **do** have SVGs of all of the icons except unitTesting.webp.

Proof: 

* Search https://github.com/ethereum/remix-project/commit/7c539d8ed60bdc7bd766798e874243f68379f030 for "image/" there are 10 results
* Search same page for "image/svg" there are 9 results
* That leaves on non-SVG file, it is this http://remix-alpha.ethereum.org/assets/img/localPlugin.webp

Here is the original artwork for localPlugin in SVG format https://github.com/ethereum/remix-project/commit/040876c03cfe7918ff2b4ccb7fc71bad7f76a076 

[Unknown.svg.zip](https://github.com/ethereum/remix-project/files/5667439/Unknown.svg.zip)

Attached above ^^

---

There is no security issue of using SVG files as images that are hosted in this repository.

Or if there is a security issue, then it is surely less that that of hosting HTML in this repository.
