### ISSUE TITLE
Update suggested command for running a local geth node

### ISSUE THREAD

**Issue by renaynay** [ethereum/remix-project#67]
The suggested command for running remix & a local geth test node is: 

```
geth --rpc --rpccorsdomain="http://remix.ethereum.org" --rpcapi web3,eth,debug,personal,net --vmdebug --datadir <path/to/local/folder/for/test/chain> --dev console
```

Some of these flags were recently deprecated, so this should be the new suggested command: 

```
geth --http --http.corsdomain="http://remix.ethereum.org" --http.api web3,eth,debug,personal,net --vmdebug --datadir <path/to/local/folder/for/test/chain> --dev console
```

![Screen Shot 2020-07-02 at 6 38 18 PM](https://user-images.githubusercontent.com/41963722/86387588-af91be00-bc93-11ea-8ab1-db48214cd256.png)

**Comment by renaynay** [comment]
Hey @LianaHus, we will be deprecating the `rpc` flags completely within a few months. I see this PR open #880 to change out the deprecated flags.

**Comment by Aniket-Engg** [comment]
#880 is merged, so closing it.
