### ISSUE TITLE
Allow gas profiler to activate debugger plugin

### ISSUE THREAD

**Issue by EdsonAlcala** [ethereum/remix-project#686]
Would it be possible to allow the gas profiler plugin to activate the debugger plugin?

So the gas profiler can activate the debugger like:

`await client.call("manager" as any, "activatePlugin", "debugger");`

**Comment by LianaHus** [comment]
yes, but why do you need to activate the debugger from gas profiler? would it be by default or after some user action?

**Comment by EdsonAlcala** [comment]
because the gas profiler requires traces (which gets from the debugger)

**Comment by FAvE01** [comment]
G

**Comment by Aniket-Engg** [comment]
Gas profile is no more a plugin, so closing this.
