### ISSUE TITLE
Cannot pass in address tuple as the parameter to a function

### ISSUE THREAD

**Issue by ldru** [ethereum/remix-project#696]
![image](https://user-images.githubusercontent.com/18008327/103099151-49856280-4648-11eb-8d25-a58b21e0b43e.png)
Prompting:
transact to FortSwapRouter.swapExactTokensForTokens errored: Error encoding arguments: Error: expected array value (argument=null, value="[0xa88C8923DD7af5d6E0f13BD08d2ea14cFF026e6E,0xDd7624e062Eac4Ba489A90a8Afd3669B45c76fE2]", code=INVALID_ARGUMENT, version=abi/5.0.7)

**Comment by Aniket-Engg** [comment]
Hi @ldru , you need to put quotes ("") around address values as `["0xa88C8923DD7af5d6E0f13BD08d2ea14cFF026e6E","0xDd7624e062Eac4Ba489A90a8Afd3669B45c76fE2"]`

**Comment by jacobmakarsky** [comment]
> Hi @ldru , you need to put quotes ("") around address values as `["0xa88C8923DD7af5d6E0f13BD08d2ea14cFF026e6E","0xDd7624e062Eac4Ba489A90a8Afd3669B45c76fE2"]`

Hello, I'm still getting this exact error, even with my array in the correct format. `["addr1","addr2","addr3","addr4"]`
