### ISSUE TITLE
Update UI of Settings module 

### ISSUE THREAD

**Issue by ryestew** [ethereum/remix-project#70]
Update to Ethworks Figma:
https://www.figma.com/file/giWj3yC998FcVDOqX8y3ia/Remix-Final?node-id=0%3A1

**Comment by yann300** [comment]
linked to https://github.com/ethereum/remix-project/issues/214

**Comment by LianaHus** [comment]
th input field for token pass needs to have a proper background color

**Comment by ryestew** [comment]
I believe this has been fixed.
