### ISSUE TITLE
Jump to error line does not work

### ISSUE THREAD

**Issue by decpr** [ethereum/remix-project#701]
Hello,
I am unsure if I am the first one who reports this and if yes, why, but I have an error.
In Compiler versions >= 0.8.0, the jump to a line when clicking the error or warning message doesn't work anymore.
It always jumps to the first line only.

**Comment by Aniket-Engg** [comment]
Hi @decpr , Thanks for raising it.

Can you try it once on remix-alpha.ethereum.org? it seems working fine there.

**Comment by decpr** [comment]
Hey @Aniket-Engg,
I have tested it on the alpha and it does not work there for me either.
I tried with Google Chrome and Firefox.
It's important to use the compiler version 0.8.0 (0.8.0+commit.c7dfd78e.js).
This error only occurs on that version, in versions 0.7.6 and below it works fine.
