### ISSUE TITLE
Allow plugins to set tabs as active

### ISSUE THREAD

**Issue by EdsonAlcala** [ethereum/remix-project#703]
The EthDoc plugin(which is located in the side panel) requires a second plugin (located in the main panel). 

When I activate the EthDoc plugin, I also activate the EthDoc Viewer. 

A good thing would be to allow plugins to set a tab as active. i.e When I click the EthDoc in the side panel, I want to set as active(in the main panel) the tab of the EthDoc viewer.

What do you guys think? Thanks

**Comment by yann300** [comment]
we need to define under which API this function can be added.

**Comment by LianaHus** [comment]
@yann300  side-panel could expose `focus` method of host plugins. we should add permissions as well

**Comment by bunsenstraat** [comment]
This specific question is also about the main panel.

**Comment by bunsenstraat** [comment]
https://github.com/ethereum/remix-project/pull/725 in progress
