### ISSUE TITLE
Allow Defi tutorials plugin to activate uma tutorials plugin

### ISSUE THREAD

**Issue by EdsonAlcala** [ethereum/remix-project#704]
The following pull requests are for 2 plugins: umaTutorials and defiTutorials.

- https://github.com/ethereum/remix-plugins-directory/pull/193/files

- https://github.com/ethereum/remix-plugins-directory/pull/194/files

Can we allow defiTutorials to activte the umaTutorials plugin?

Thanks

**Comment by LianaHus** [comment]
sure we can

**Comment by bunsenstraat** [comment]
https://github.com/ethereum/remix-project/pull/714 in progress

**Comment by bunsenstraat** [comment]
This is live and done. 
 * The caller can have 'canActivate' as a optional property in the plugin profile.
 * This is an array containing the 'name' property of the plugin it wants to call.
 * canActivate = ['plugin1-to-call','plugin2-to-call',....]
https://github.com/ethereum/remix-project/blob/a609efc312cf7073c39afc23a1e32c3b2dc8f864/apps/remix-ide/src/remixAppManager.js#L28
