### ISSUE TITLE
Allow plugins to collapse panels

### ISSUE THREAD

**Issue by EdsonAlcala** [ethereum/remix-project#705]
It would be nice to allow plugins to collapse the side panel and the network panel via API call. So the plugin can take the whole Remix screen space.

What do you think?

Thanks

**Comment by LianaHus** [comment]
nice idea, i think this is part of this one https://github.com/ethereum/remix-project/issues/29

**Comment by EdsonAlcala** [comment]
@LianaHus I realise there was already an issue for this https://github.com/ethereum/remix-project/issues/183

**Comment by LianaHus** [comment]
nice, closing this one :)
