### ISSUE TITLE
investigate possible problems with solc 0.8.0 

### ISSUE THREAD

**Issue by LianaHus** [ethereum/remix-project#717]
to me it takes very long to load it (using pragma)

**Comment by LianaHus** [comment]
https://github.com/ethereum/remix-project/issues/701

**Comment by Aniket-Engg** [comment]
Although https://github.com/ethereum/remix-project/issues/701 is resolved in https://github.com/ethereum/remix-project/pull/726  but it will be good if we use complete error object to parse the error

**Comment by yann300** [comment]
closing it @Aniket-Engg @LianaHus please reopen if needed
