### ISSUE TITLE
Memory leak

### ISSUE THREAD

**Issue by LianaHus** [ethereum/remix-project#72]
Firefox is hanging when autocompile is on and one edit the text in editor multiple times in a row a bit fast.
Debugger is causing same also in chrome

**Comment by yann300** [comment]
@VexyCats @AlphaSerpentis could you post here or send at remix@ethereum.org an example of contract that cause this issue. We are trying to address this.
Thanks

**Comment by AlphaSerpentis** [comment]
Hi @yann300. It didn't seem to matter which contracts ran. I can tell you however when it would occur.

When using Remix, it would certainly happen after using the testnet, for me, Ropsten. It doesn't seem to happen immediately, but with continuous use, at some point, there will be a surge in data write/read that seems unexplainable, and eventually locking the browser to no recovery. I'm not sure if this can be replicated for the local testing environment.

Here's a defunct example code I used back then nonetheless: https://github.com/Alpha-Serpentis-Developments/PawPoolsToken/blob/v0.0.3/PawPoolsToken.sol

**Comment by bokkypoobah** [comment]
There is a memory leak in Remix on Chromium, after compiling simple test contracts. This has been happening for several months with earlier releases of Chromium, and with the recent version of Chromium. On OS/X

**Comment by yann300** [comment]
partially linked to https://github.com/sourcifyeth/remix-sourcify/issues/39

**Comment by bokkypoobah** [comment]
> partially linked to [sourcifyeth/remix-sourcify#39](https://github.com/sourcifyeth/remix-sourcify/issues/39)

There seems to also be a memory leak in Remix Desktop. A workaround seems to be to switch off 'General' -> 'Generate contract metadata. Generate a JSON file in the contract folder. Allows to specify library addresses the contract depends on. If nothing is specified, Remix deploys libraries automatically.' Mentioning here as it could be related to this issue.

**Comment by yann300** [comment]
@bokkypoobah @AlphaSerpentis @VexyCats @LianaHus 
could you please verify you are still experiencing this issue?

**Comment by yann300** [comment]
closing as the duplicate as been closed already https://github.com/ethereum/remix-project/issues/341

please reopen if you still see the issue
