### ISSUE TITLE
Deleting request var in remix-plugin causes uncaught error blocking promise reject

### ISSUE THREAD

**Issue by bunsenstraat** [ethereum/remix-project#721]
https://github.com/ethereum/remix-plugin/blob/3dd57bf06671efcda825e9edbac0cf2899355302/packages/engine/core/src/lib/abstract.ts#L88

this.currentRequest is deleted before it is destructured and causes an uncaught error when the activate plugin is timed out.

**Comment by GrandSchtroumpf** [comment]
Whn should it be deleted then ?

**Comment by bunsenstraat** [comment]
Well, as reject doesn't stop the execution. We put it after the reject.
