### ISSUE TITLE
Remixd gives an error and quits

### ISSUE THREAD

**Issue by ryestew** [ethereum/remix-project#737]
Error: Your plugin client should have a method/attribut named "manager" as it is the name of another plugin. To prevent this set the option "customApi" to "null" in the client's options. For exemple: "const client = createClient(new PluginClient<any, any>({ customApi: null }))".

**Comment by bunsenstraat** [comment]
When is this happening?

**Comment by aspiers** [comment]
I see this too, with a fresh install of remixd, the first time I connect to it :-(

**Comment by aspiers** [comment]
Hmm, seems that I had an old `remixd` 0.2.4 installed alongside the new `@remix-project/remixd` - uninstalling that seems to have fixed it.
