### ISSUE TITLE
RegisterMenuItem / CustomAction

### ISSUE THREAD

**Issue by yann300** [ethereum/remix-project#761]
Following https://github.com/ethereum/remix-project/pull/752.

We need to continue to address stuff like:
 - [x] name of the plugin (fileExplorers with or without "s", or maybe this can be named "filePanel")
 - [x] making the api generic enough so we can apply it to the runtab, compiletab, other plugins..
 - [ ] would it be conceivable to preload custom action (before plugin is activated)

Please update the list with anything relevant

**Comment by bunsenstraat** [comment]
https://github.com/ethereum/remix-project/pull/1182
https://github.com/ethereum/remix-plugin/pull/368
