### ISSUE TITLE
using calldata causes remix debugger disappear

### ISSUE THREAD

**Issue by novaknole** [ethereum/remix-project#771]
It's super simple to reproduce this issue.  Let's take a look at the following:

```
pragma solidity ^0.7.4;

contract D {
    
    function test2(uint[1] calldata good) external {
        
        uint c = good[0];
    }
    
    
}
```

Now, `deploy` the contract. and call `test2` function, copy the transaction hash of it and put it in remix debugger. When you click `start debugging` , you will notice that the debugger will disappear completely and will stay disappeared until you refresh the page.

Any idea what could be wrong ?

**Comment by Aniket-Engg** [comment]
@novaknole Thanks for raising this. This is a known issue and tracked here: https://github.com/ethereum/remix-project/issues/481

**Comment by novaknole** [comment]
@Aniket-Engg  Thank you... hope it will be resolved soon.

**Comment by yann300** [comment]
fixed by https://github.com/ethereum/remix-project/pull/1179
currently deployed in remix-beta.ethereum.org
