### ISSUE TITLE
[ Feature Request ] Persist Deployed Contracts across Restarts

### ISSUE THREAD

**Issue by anudit** [ethereum/remix-project#78]
Would be it possible to persist the deployed contracts instances list while restarting Remix (closing and reopening the tab/browser)? or have a flag in General Settings to enable this if this is something not required as a default behavior in Remix.

**Comment by TbLtzk** [comment]
Yes, this would help a lot!

**Comment by Aniket-Engg** [comment]
This can be done now by pinning the contracts.
