### ISSUE TITLE
in case of array var the label and triangle are not alligned in debugger ui

### ISSUE THREAD

**Issue by LianaHus** [ethereum/remix-project#804]

**Comment by LianaHus** [comment]
![Screenshot from 2021-01-27 18-21-30](https://user-images.githubusercontent.com/9685356/106028870-c767de00-60cc-11eb-89d6-d57bd8e8019f.png)

**Comment by ryestew** [comment]
Here's another place where this happens:
<img width="640" alt="image" src="https://user-images.githubusercontent.com/6050001/106063011-91732b80-60c5-11eb-9116-213a0761c371.png">
