### ISSUE TITLE
Remixd points to the filesystem root instead of specified folder

### ISSUE THREAD

**Issue by ryestew** [ethereum/remix-project#808]

**Comment by ryestew** [comment]
I have put the absolute path to the folder I want to work in.  In the file explorer - the folders that lead to my desired working directory do not have names but have 2 dots :   ..
So its traversing the directory back to the root with the relative links to go one level above...or something like that.

**Comment by yann300** [comment]
This should be fixed after we've published remixd.
cc @ioedeveloper

**Comment by mounibec** [comment]
Just happened to me. It seems to be not fixed yet.

**Comment by ioedeveloper** [comment]
@mounibec Check https://github.com/ethereum/remix-project/issues/833
