### ISSUE TITLE
remixd console error

### ISSUE THREAD

**Issue by ryestew** [ethereum/remix-project#823]
when I start remixd - I get this error in the console:
WebSocket connection to 'ws://127.0.0.1:65521/' failed: Error in connection establishment: net::ERR_CONNECTION_REFUSED
open @ vendor.js:15739
(anonymous) @ vendor.js:15734

Remixd does work though.

**Comment by gperezalba** [comment]
I have the same problem...I don't understand why the error shows `WebSocket connection to 'ws://127.0.0.1:65521/' failed` if remixd is running in port 65520. Is it right? it had been working for me for a long time.

**Comment by mellaught** [comment]
I have some problems! Win 10

**Comment by gperezalba** [comment]
@ryestew is there any way I can use a previous remix ide version son I can use it with remixd? I've tried running with docker or use desktop version but none of them worked for me. Thanks and hope you guys can fix that soon ;)

**Comment by yann300** [comment]
We are going to fix that soon, in the meantime, you could download the previous release : https://github.com/ethereum/remix-project/releases/tag/v0.10.7
the zip is attached

**Comment by yann300** [comment]
you can also access the previous version here https://ipfsgw.komputing.org/ipfs/QmZCogwZL3RpV6huuA4b57CxgHUGzRhTWR6cXDULabVuLz

**Comment by gperezalba** [comment]
With the one in ipfsgw.komputing.org I can connect remixd correctly. Thanks ;)

**Comment by gperezalba** [comment]
Hi @yann300
I'm having some problems again with this...the current version of remix.ethereum.org still has the same problem and the old version you gave me (https://ipfsgw.komputing.org/ipfs/QmZCogwZL3RpV6huuA4b57CxgHUGzRhTWR6cXDULabVuLz) has been working until today buy now Service is Unavailable...so again I cannot use remix ide :(

Hope you can help me again, thanks in advance
