### ISSUE TITLE
Remix server not launching at the specified directory

### ISSUE THREAD

**Issue by max-taylor** [ethereum/remix-project#833]
When running remixd -s <path_to_directory> the remix server always start from the root folder at /. 

Very recent issue, remix was working perfectly a few days ago, a recent patch must have broke this.

**Comment by xubowenshizi** [comment]
`npm uninstall -g remixd`
`npm install -g @remix-project/remixd --force`

**Comment by mariogutval** [comment]
I run both commands but still have the same issue. Any idea?

**Comment by ryestew** [comment]
@mariogutval - the update with the uninstall & install does not yet fix the problem on Windows machines.  We will be fixing this issue ASAP.  I assume you have a computer running Windows.  If not please let us know.

**Comment by mariogutval** [comment]
@ryestew yes, I am using Windows. Thank you for your answer!

**Comment by ryestew** [comment]
@mariogutval - we will post in twitter - @EthereumRemix and in the gitter/remix channel when the fix is done.  I'll also post it in this issue.

**Comment by max-taylor** [comment]
> `npm uninstall -g remixd`
> `npm install -g @remix-project/remixd --force`

Perfect fixed for me on a mac.

Thanks heaps for your help!

**Comment by ryestew** [comment]
For any windows users of Remixd - there has been a fix published to npm to fix the problem of incorrectly pointing to the root directory of your filesystem. To install the remixd fix:

First uninstall the old remixd with: **npm uninstall -g remixd**
Then install the new one: **npm install -g @remix-project/remixd**

**Comment by mariogutval** [comment]
@ryestew Solved! Thank you very much for your work!
