### ISSUE TITLE
UI Break on 0.10.8 on Windows

### ISSUE THREAD

**Issue by Gerald-Schinagl** [ethereum/remix-project#838]
After automatically beeing Updated to 0.10.8 on Windows locally the Remix-IDE is no longer usable - ist is only white and some icons, can not access anything now
![image](https://user-images.githubusercontent.com/78531255/106864281-ef0d0680-66c9-11eb-9582-fd363bf49a53.png)

**Comment by Gerald-Schinagl** [comment]
@LianaHus - looks the Update completely broke the UI and makes Remix not useable

**Comment by yann300** [comment]
@Gerald-Schinagl a fix has been deployed. This should be fixed, please get the latest version https://github.com/ethereum/remix-desktop/releases .
I am closing the issue but feel free to reopen if it is still not working.
