### ISSUE TITLE
remixd deactivate workflow

### ISSUE THREAD

**Issue by ryestew** [ethereum/remix-project#840]
When you **deactivate remixd** and refresh the browser - the plugin **still** loads and so the modal pops up asking you to start the script.  

The problem to put it more generally - is that when remixd dies - in my case if my computer goes to sleep often ( but not always) remixd dies.  And I get the modal message that remixd has stopped.  I never know if I need to refresh Remix or just restart remixd.  

Similarly remixd cannot be stopped in the shell script with cmd + c.

**Comment by ioedeveloper** [comment]
cmd + z stops the shell script.

**Comment by LianaHus** [comment]
https://github.com/ethereum/remix-project/issues/490
