### ISSUE TITLE
Static Analysis gives wrong source location

### ISSUE THREAD

**Issue by yann300** [ethereum/remix-project#846]
In order to reproduce:
compile `import "https://github.com/aave/protocol-v2/blob/ice/mainnet-deployment-03-12-2020/contracts/protocol/tokenization/StableDebtToken.sol";`

go to the static analyzer and click on some warning, highlight is in most case not relevant to the warning...

**Comment by Aniket-Engg** [comment]
There is a strange behaviour. If we save this file with the name `test.sol`, location seems working fine for the warning but issue can be reproduced with any other name. I tested it on remix live along with @bunsenstraat
