### ISSUE TITLE
Remix web UI connected to remixd shows contents of a root folder instead of the <shared folder> 

### ISSUE THREAD

**Issue by ethene** [ethereum/remix-project#853]
MacOS 10.15.7
npm@7.0.10
node v10.22.0
https://remix.ethereum.org/ on chrome 88.0.4324.146

steps:
1. remixd activated with a verified existing shared folder
`remixd -s <shared folder> --remix-ide https://remix.ethereum.org`

2. connecting remix web UI to remixd is showing the root volume instead of the selected shared folder
<img width="204" alt="Screenshot 2021-02-09 at 12 14 39" src="https://user-images.githubusercontent.com/57169/107306527-beb1d780-6ad0-11eb-8bc4-5e55cb7ae40a.png">

this has started happening just recently, there were no changes to remixd or scripts or anything else

**Comment by yann300** [comment]
This has been fixed , please update remixd:
```
npm uninstall -g remixd
npm install -g @remix-project/remixd
```
