### ISSUE TITLE
Remixd connects to the root folder -> Critical security issue

### ISSUE THREAD

**Issue by madjarevicn** [ethereum/remix-project#855]
**Problem:** 

While running remixd command to give permission to remix to access my local directory: 

`remixd -s /Users/nikolamadjarevic/Desktop/2key.network/contracts/contracts --remix-ide http://remix.ethereum.org` I see that now, even this command is given, remixd opens access to my whole harddrive.

![Screenshot 2021-02-09 at 11 20 49](https://user-images.githubusercontent.com/30060076/107349741-ddac6b80-6ac8-11eb-8e27-5b21a5b949dc.png)

When I connect using plugins in remix, this is the log I'm getting on the console: 
```
setup notifications for /Users/nikolamadjarevic/Desktop/2key.network/contracts/contracts
```

This is what remix loads: 
<img width="308" alt="Screenshot 2021-02-09 at 11 22 19" src="https://user-images.githubusercontent.com/30060076/107349916-15b3ae80-6ac9-11eb-98f3-1f0173d177bb.png">

### Reporting here 2 issues: 
- Remix behavior --> Can't load the directory I specified
- Remixd actually has access to the whole harddrive. 

**Env:** 
- Mac OS Big Sur
- Node: v10.23.0
- Npm: 6.14.8

**Comment by eiTanLaVi** [comment]
+1
Please resolve this ASAP, this is a MAJOR security issue

**Comment by yann300** [comment]
This has been fixed, please update remixd:
```
npm uninstall -g remixd
npm install -g @remix-project/remixd
```

**Comment by eiTanLaVi** [comment]
thanks, will try
