### ISSUE TITLE
create/save workspace

### ISSUE THREAD

**Issue by yann300** [ethereum/remix-project#857]
Add ability to save/open/create/close/delete a workspace. The content of a workspace will be put in the browser explorer.

**Comment by LianaHus** [comment]
1. first time opening: empty dropdown. After clicking default loads but also "undefined"
2. delete. message can be improved.
3. when I remove undefined the message to connect to localhost comes. i guess that was localhost workspace
4. when I do delete everything there is <localhost> workspace. i do cancel to connect and can't connect again. clicking is doing nothing
5.  when the name is long the icons have not enough space at the same line. we should discuss this. maybe worth to move them all to the new line
6. rename. why I can't have space? we allow that in file names
7. when no file/folder selected icons to addfile/folder etc don't work
8. after open file we should expand the tree to show the file

**Comment by yann300** [comment]
> rename. why I can't have space? we allow that in file names

**Comment by LianaHus** [comment]
> > rename. why I can't have space? we allow that in file names
> 
> I think that has changed @bunsenstraat @ioedeveloper

still valid on FE
