### ISSUE TITLE
profile.json new fields - issues_url, author_mail

### ISSUE THREAD

**Issue by yann300** [ethereum/remix-project#86]
In order to ensure that users will add issues in the right repository, we should probably add to the UI and to profile.json these 2 fields:
 - issues_url
 - link to the code (github, gitlab, ...)
 - author_mail
 - documentation

**Comment by LianaHus** [comment]
@yann300 is this still relevant with monorepo?

**Comment by yann300** [comment]
yes it aims to improve the plugin description we already have 
@ryestew

**Comment by yann300** [comment]
- [ ] analyze and decide the UI design @LianaHus @bunsenstraat 
 - [ ] add the properties, to the profiles.
