### ISSUE TITLE
Add 'muirGlacier' in the list of EVM version in solidity compiler

### ISSUE THREAD

**Issue by Aniket-Engg** [ethereum/remix-project#865]

**Comment by Patil2099** [comment]
hi @Aniket-Engg  I would love to help in solving this. Can you guide me a little more ?

**Comment by Aniket-Engg** [comment]
Hi @Patil2099 , In Solidity Compiler plugin, we show a dropdown to select EVM Version. It is missing this latest hardfork of Ethereum i.e. 'muirGlacier' . This should be added to that dropdown list.

Code for Remix native plugins is usually here: https://github.com/ethereum/remix-project/tree/master/apps/remix-ide/src/app/tabs

**Comment by Patil2099** [comment]
@Aniket-Engg  Can you please review my pr ?
