### ISSUE TITLE
Remixd always connecting to root of system

### ISSUE THREAD

**Issue by zaryab19aug** [ethereum/remix-project#889]
When we connect **Remix-IDE** with **remixd** it always connect to root of the system. I've tested it with older version **0.10.7** and it is working fine. On latest version locally compiled and on web interface it is not working. 

![image](https://user-images.githubusercontent.com/14287497/108034171-eec02400-7056-11eb-9dc8-2332b250caeb.png)

**Comment by ryestew** [comment]
There is a new version of Remixd with a new npm address: https://npmjs.com/package/@remix-project/remixd
Users need to:
1. uninstall the old one: npm uninstall -g remixd
2. install the new: npm install -g @remix-project/remixd

Please try this and please let us know if you still the same problem.

We reached out to users through twitter: @EthereumRemix , the gitter:ethereum/remix channel and in the Remix release notes on Medium.  Obviously, if you missed this, we need to add more channels to our communication.
  
Where would we have reached you with this info?

Thanks for reaching out to us and stay in touch.

**Comment by zaryab19aug** [comment]
Yes thanks this works fine.
