### ISSUE TITLE
Recorder Enhancement

### ISSUE THREAD

**Issue by ryestew** [ethereum/remix-project#89]
The recorder records exactly the transaction done, including the original bytecode which for our usecase it wasn’t what we expected.
    * we did a contract with 1 method ‘createProject’ and recorded it
    * we then added a second method ‘fundProject’
    * we replayed the recording, hoping this would save the trouble of having to redeploy and call createProject again
However it simply reuses/redoes the previous contract deployment that has old bytecode without the new method.

**Comment by yann300** [comment]
> However it simply reuses/redoes the previous contract deployment that has old bytecode without the new method.

If you didn't recompile, you 'll not get the new method.
what would you propose to do ? @ryestew

**Comment by ryestew** [comment]
figure out if we need to keep this open
