### ISSUE TITLE
Rename JavaScript VM to Remix VM

### ISSUE THREAD

**Issue by Aniket-Engg** [ethereum/remix-project#925]
cc: @yann300

**Comment by LianaHus** [comment]
I agreem this is more accurate name but we should think twice. user are used to it, all tutorials and videos using it etc.. Users can be confused

**Comment by Aniket-Engg** [comment]
May be for some releases we can put `Remix VM (JSVM)` and in the meantime we can spread words about it.

**Comment by Aniket-Engg** [comment]
closed by #2549
