### ISSUE TITLE
remixd: when switching between localhost & another workspace...

### ISSUE THREAD

**Issue by ryestew** [ethereum/remix-project#962]
When you leave localhost to see another workspace and then come back to localhost-  the modal appears again.  You just need to click connect to get back to localhost.  This issue is more of an annoyance than a bug.  

The connect modal shouldn't appear because the connection never broke - I think.

**Comment by yann300** [comment]
I think that when you switch to another workspace, remixd is actually deactivated, so that's the normal behavior at least.
If you want to keep the connection open, why not, but I don't think that's necessary..
