### ISSUE TITLE
switch from localhost to another workspace gives a console error

### ISSUE THREAD

**Issue by ryestew** [ethereum/remix-project#965]

**Comment by yann300** [comment]
can you paste that error?

**Comment by ryestew** [comment]
I believe this is the one I was getting:
<img width="691" alt="Screen Shot 2021-03-15 at 10 50 56 PM" src="https://user-images.githubusercontent.com/6050001/111248783-f71d6780-85e0-11eb-923e-75de30359136.png">

**Comment by ryestew** [comment]
when switching from remixd to a "real" workspace - I get this console error:
<img width="1082" alt="Screen Shot 2021-03-15 at 10 54 26 PM" src="https://user-images.githubusercontent.com/6050001/111249134-96daf580-85e1-11eb-9533-cebade35e580.png">
