### ISSUE TITLE
Blank name for files with the same name displayed in editor tabs.

### ISSUE THREAD

**Issue by ioedeveloper** [ethereum/remix-project#967]
<img width="654" alt="Screen Shot 2021-03-12 at 13 33 17" src="https://user-images.githubusercontent.com/23282059/110940868-dbdbff00-8337-11eb-9acd-aeb39ff88578.png">

**Comment by Aniket-Engg** [comment]
How is a blank file even created?

**Comment by bunsenstraat** [comment]
It's not blank files. It has to do with the tab titles.
