### ISSUE TITLE
Improve Error Messages

### ISSUE THREAD

**Issue by niccolopetti** [ethereum/remix-project#969]
Trying to compile a file on remix it wasn't compiling and the only output that I got was "compilation failed with one error",
to understand more on why it wasn't compiling I was forced to compile via truffle, that gave me information on why it wasn't compiling: 
```
CompileError: CompilerError: Stack too deep when compiling inline assembly: Variable headStart is 1 slot(s) too deep inside the stack.
```
It would be nice to provide this kind of information directly  on remixIDE.

**Comment by LianaHus** [comment]
@niccolopetti thanks for report.
Could you please give us an example code?

**Comment by niccolopetti** [comment]
@LianaHus you're welcome,
this example should reproduce the issue:

```
pragma solidity >=0.8.0 <0.9.0;

contract Example{

   function A (address payable a, address b, string memory c, uint d, uint e, uint f, uint g, uint h ,uint256 i,uint j, address payable k, address l) 
    public 
    {
        
        
    }
}
```
decreasing the number of parameters the code compiles correctly

**Comment by LianaHus** [comment]
you can add "pragma experimental ABIEncoderV2;" and enable optimization.

**Comment by yann300** [comment]
fixed by https://github.com/ethereum/remix-project/pull/948
